### ISSUE TITLE
[feature request] html导出时，配置自定义命令

### ISSUE THREAD

**Issue by owenstake** [obgnail/typora_plugin#105]
场景：html导出时，运行自定义命令
需求：在下拉框里 增加一个命令，免得手动输入。
原因：typora没有配置文件，安装后要UI配置一遍。UI操作很麻烦，难以自动化。
![image](https://github.com/obgnail/typora_plugin/assets/45960823/c3862755-37d1-4e38-a2d4-8be51c715f57)

**Comment by obgnail** [comment]
你好，今天我仔细研究了一下，这个需求应该就不做了。理由如下：

1. 功能点小且太细分了，经检查 Typora 是有记忆命令功能的，所以，这个功能仅用于刚新装 Typora 的时候
2. 需要修改内置的 js 文件，成本太高且没有通用性。

![Snipaste_2023-12-05_18-50-17](https://github.com/obgnail/typora_plugin/assets/48992887/f74c00d8-1048-4bc3-be1c-e7bcdc797be5)

---

如有其他需求、问题，麻烦另开 issue。
