### ISSUE TITLE
添加脚本后，运行Typora，左上角无法显示菜单功能，右上角不显示窗口最小化/最大化/关闭。如何解决or卸载脚本

### ISSUE THREAD

**Issue by Guohairui6** [obgnail/typora_plugin#107]
如题，
添加脚本后，运行Typora，左上角无法显示菜单功能，无法进行设置。右上角不显示窗口最小化/最大化/关闭，使用很不方便。
请问如何修复问题or回退回去。

**Comment by obgnail** [comment]
@Guohairui6  你好

1. 这个问题超出我想象的受人关注，遂在 1.2.4 版本做了调整，更新一下就行。
2. 如果你想关闭某个插件，可以正文区域鼠标右键->【启用插件】->【右键菜单】-> 【打开插件配置文件】，之后修改 settings.toml 文件即可。
