### ISSUE TITLE
关于默认只读模式的bug

### ISSUE THREAD

**Issue by loubth** [obgnail/typora_plugin#13]
首先感谢作者给typora这个软件增加了这么多有用的功能

特别是其中只读模式的功能一直是我想要加上的，因为这个能解决我误触给文件里增加了冗余文字的痛点

大佬我希望这个功能可以设置成打开新文件默认只读，我也尝试按您的思路修改脚本
把READ_ONLY_DEFAULT选项置为true但是并没有实现打开新文件默认只读的效果
![image](https://github.com/obgnail/typora_plugin/assets/33371020/781da732-54fc-41c3-bcc6-abf01622ae9d)
我又尝试修改File.unlock()附近的代码，但是打开新文件仍然是可修改的

请问大佬怎么才能实现这样的效果呢？

另外现有脚本有个bug就是，按下只读的快捷键后，图片左右还是可以键入文字

**Comment by obgnail** [comment]
@loubth 感谢反馈。

1.0.3 版本里两个问题都已经修复。你可以用用看，有问题麻烦帮忙反馈一下。

**Comment by loubth** [comment]
感谢作者大佬，上面提的bug经过验证已经改好了。发现一个新的bug，当在只读模式下在代码块区域输入若干中文此时确实没有显示，但是保持焦点不动切换为可编辑模式时，这些在只读模式下键入的中文就会全部出现在代码块区域

**Comment by obgnail** [comment]
@loubth 感谢反馈。真的不好意思。用的很细 👍

不负责任的讲，read_only 是 bug 最多的功能了。这个功能也是我的痛点，是我绞尽脑汁逆天而行，强行实现的。

我要吐了😢 我无法监控输入法啊😭 我现在的实现大概率方向不对，我看明天能不能重构一下。

**Comment by loubth** [comment]
发现个新bug，就是只读模式下，页内搜索和全局搜索框都不能进行增删了

**Comment by loubth** [comment]
大佬只读模式下 上下左右还有Home End PageUp PageDown等快捷键在失焦后都不能用了

**Comment by loubth** [comment]
作者大佬你好，修复的bug已验证

- 【在只读模式下键入的中文就会全部出现在代码块区域】：已验证。
- 【页内搜索和全局搜索框都不能进行增删了】：已验证。

如果有办法支持 Home End PageUp PageDown 等快捷键，做到像一个pdf阅读器一样的效果那将完美。：）

**Comment by obgnail** [comment]
@loubth 你好。

1.2.2 版本发布了。

对 read_only 做了一版修复，提高了效率而且理论上应该支持所有快捷键了。

有兴趣可以试用。

> 注：1.2.0 版本重构了，可能有些许 BUG，如果你发现了，麻烦提醒我。

**Comment by loubth** [comment]
作者你好，新版的已试用，发现一个bug就是只读模式下选中图片后乱按几下backspace还是可以删除图片

**Comment by obgnail** [comment]
@loubth 太强了，用的很细 👍 

1.2.4 版本已修复。这种情况应该不会再反复了。

> 原因：space、delete、backsapce、enter 在 Typora 的优先级比较高，绕过了 File.Lock 的限制。我现在学聪明了，在 read_only 模式下直接阻拦这四个按键。
