### ISSUE TITLE
新版本多标签页遮挡搜索框

### ISSUE THREAD

**Issue by Bronya-Rayi** [obgnail/typora_plugin#14]
ctrl + f 的搜索框会被多标签给遮挡
![image](https://github.com/obgnail/typora_plugin/assets/47048823/4aad4e5d-7e02-4278-9e4a-c2329cb4f2b2)
注意看那一细条，当时我找了好久，还以为是ctrl键坏了。。。
![image](https://github.com/obgnail/typora_plugin/assets/47048823/441c4bdb-c657-47eb-b6cd-c1d35f2379e3)

**Comment by obgnail** [comment]
感谢反馈，已修复。
