### ISSUE TITLE
用了该插件后，typora标题的序号不正常了

### ISSUE THREAD

**Issue by Dabai2007** [obgnail/typora_plugin#147]
一级标题不会自增序号，全部是1
![image](https://github.com/obgnail/typora_plugin/assets/133517982/1d3452eb-7729-4d3b-ada0-dbf8f4d85756)

排序编号是从二级标题开始，按照原来，二级标题的格式是 1.1 1.2 1.3......这样。现在是从二级标题开始编排的，如下图
![image](https://github.com/obgnail/typora_plugin/assets/133517982/fbc07848-f52d-42fe-80e9-5a061d613660)

然后到三级标题，就是接着有问题的二级标题来的，三级标题第一个标题编号是 1.1（正确的应该是1.1.1）
![image](https://github.com/obgnail/typora_plugin/assets/133517982/d9d6ccf7-0586-4f69-971e-aaccd24e4e52)

不知道是哪里的问题，麻烦大佬帮看看

**Comment by obgnail** [comment]
第一个问题我在 readme 里有说：

> 市面上常用的 [Markdown lint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) 和 [微软 Markdown 最佳实践](https://learn.microsoft.com/en-us/powershell/scripting/community/contributing/general-markdown?view=powershell-7.3) 和 [markdown 规范 MD025 号规则](http://xiangxing98.github.io/Markdownlint_Rules.html)，都指明：一篇文档应该 **有且仅有一个 h1**，甚至很多人提倡不使用 h1: [Avoid h1 headings](https://meta.stackexchange.com/questions/214427/is-using-heading-markdown-okay-in-answers)。故此插件从 h2 开始编号。

第二个问题，我没用过 markdown 的锚点，我明天学习下怎么用，再去兼容这个情况。

**Comment by obgnail** [comment]
@Dabai2007 第二个问题，麻烦能给个使用描点的示例么？

**Comment by obgnail** [comment]
@Dabai2007 

跨文件锚点问题解决了，麻烦更新验证一下。

**Comment by Dabai2007** [comment]
谢谢UP主，太牛了

**Comment by obgnail** [comment]
暂时关闭，如有其他问题，麻烦另提 issue
