### ISSUE TITLE
自定义插件没有显示，控制台报错  typora version 1.3.8

### ISSUE THREAD

**Issue by carve-myself** [obgnail/typora_plugin#150]
![image](https://github.com/obgnail/typora_plugin/assets/68720524/1d698c59-262a-445f-ba23-71e5b2207267)

配置图:
![image](https://github.com/obgnail/typora_plugin/assets/68720524/af464315-c19c-4a7e-b5d9-7d7c44b32712)

鼠标进入选择自定义插件,控制台报错: 
![image](https://github.com/obgnail/typora_plugin/assets/68720524/0e3ea46d-8727-47da-afd9-09062735aa9b)

**Comment by obgnail** [comment]
@carve-myself 
快速做了更新，有兴趣的话可以更新。

**Comment by carve-myself** [comment]
感谢大佬 可以了
