### ISSUE TITLE
插入看板 会覆盖我的剪切板?

### ISSUE THREAD

**Issue by carve-myself** [obgnail/typora_plugin#159]
插入看板 会覆盖我的剪切板? 导致我原来复制的内容不见了 变成了看板

**Comment by obgnail** [comment]
@carve-myself 

因为我偷懒了 😂 每次偷懒都会被用户正义执行 😂

我明天找机会处理一下

**Comment by carve-myself** [comment]
> @carve-myself
> 
> 因为我偷懒了😂栏偷懒都会被用户正义执行😂
> 
> 我明天找机会处理一下

好像是这个接口   editor.UserOp.pasteHandler(editor, content, true)

**Comment by obgnail** [comment]
@carve-myself 

你好，不好意思，前几天没有空处理。

当前版本已经修复此问题，麻烦更新一下。有问题可以在下面提出来。

**Comment by carve-myself** [comment]
> @carve-myself
> 
> 你好，不好意思，前几天没有空处理。
> 
> 当前版本已经修复此问题，麻烦更新一下。有问题可以在下面提出来。

可以了 感谢大佬修复😁
