### ISSUE TITLE
想请问大佬，选中的文本，在所有出现过的地方都高亮显示，这个好支持吗？感觉挺实用的

### ISSUE THREAD

**Issue by fiberCorpertor** [obgnail/typora_plugin#16]
![image](https://github.com/obgnail/typora_plugin/assets/15794108/2994c44d-52d8-4049-a257-1c09bfd29c3d)
类似这样的功能

**Comment by obgnail** [comment]
选中，然后 ctrl+F 就有了呀

**Comment by fiberCorpertor** [comment]
> 选中，然后 ctrl+F 就有了呀

嗯，这样也可以，主要是notepad++的这个双击选中高亮习惯了 ，先入为主了 (*￣︶￣)

**Comment by obgnail** [comment]
@fiberCorpertor 

嗯嗯，有什么其他需求可以再提一个 issue。

**Comment by obgnail** [comment]
@fiberCorpertor 

虽然没有实现双击选中高亮，但是我整个了类似的：多关键字高亮。

有兴趣可以用一下 :)
