### ISSUE TITLE
提个功能  支持一键上传所有图片

### ISSUE THREAD

**Issue by carve-myself** [obgnail/typora_plugin#167]
目前右键菜单只能选中图片一张一张上传  能否加个一键上传所有图片的功能项

**Comment by pro911** [comment]
建议,
ps. 借题主话题,完善下个人需求建议.
能否提供一个可以上传到github仓库,最好是可以支持私有仓库,配置秘钥的那种访问形式,这样可以放心的把一些比较敏感的截图暴露在公开仓库内.
2. md的文件同步到github仓库.

**Comment by Bronya-Rayi** [comment]
@carve-myself 
typora自带一键上传所有图片功能
![image](https://github.com/obgnail/typora_plugin/assets/47048823/3929cb14-8bb9-4acb-86ca-7fba9c76c326)

**Comment by carve-myself** [comment]
> @carve-myself typora自带一键上传所有图片功能 ![image](https://user-images.githubusercontent.com/47048823/275488191-3929cb14-8bb9-4acb-86ca-7fba9c76c326.png)

这个只是上传所有本地图片  网络图片没有

**Comment by carve-myself** [comment]
@Bronya-Rayi  这个只是上传所有本地图片 网络图片没有

**Comment by Bronya-Rayi** [comment]
可以用这个`复制所有图片到`，把所有网络图片下载到本地，然后再一键把本地图片全部上传
![image](https://github.com/obgnail/typora_plugin/assets/47048823/095caf26-b0f2-4af8-8ba5-5ebd76d97db7)

**Comment by obgnail** [comment]
@carve-myself @pro911 @Bronya-Rayi

鉴于大伙都有文件上传相关需求，我整了个新 repo：[typora_image_uploader](https://github.com/obgnail/typora_image_uploader)


后续图片上传相关功能都会在新仓库更新。

此 issue 关闭，后续处理请移步新仓库。
