### ISSUE TITLE
【feature request】简化typora中输入details标签

### ISSUE THREAD

**Issue by BrazilAmando** [obgnail/typora_plugin#170]
为便于阅读排版，日常笔记时会用到details标签功能（如下），总是靠敲代码还是有些不便，不知可否设计一种语法，可以在typora中简化输入实现相同功能？非常感谢！

`<details><summary>房产分类</summary><b>房产一般分为以下几类</b><ol>
    <li>普通住宅</li>
    <li>商铺</li>
    <li>写字楼</li>
    <li>...</li>
    </ol></b></details>`

![image](https://github.com/obgnail/typora_plugin/assets/125205627/9753c1b6-2a56-4aca-b68f-119f58d9c372)

**Comment by obgnail** [comment]
@BrazilAmando 

是想做一个快捷输入方式，直接插入标签吗？

**Comment by BrazilAmando** [comment]
就是类似于看板输入方式似的，用markdown语法就能输入，而不用每次输入html语法，太繁琐

**Comment by obgnail** [comment]
有个平替方案：使用代码块，语言使用markdown。之后使用 fence_enhance 插件的【折叠】功能。

本插件系统暂时不新增新的自定义语法。抱歉。

如有其他问题，麻烦另开 issue。
