### ISSUE TITLE
[suggestion]建议将一级标题（即文章标题）设置为默认居中显示

### ISSUE THREAD

**Issue by BrazilAmando** [obgnail/typora_plugin#171]
文章标题一般都是居中显示，建议考虑设置为默认值，我的实现方式是在auto_number.js文件中添加以下CSS代码
![image](https://github.com/obgnail/typora_plugin/assets/125205627/4b6ae36b-5eef-4d76-a012-a1b352a14f57)

**Comment by obgnail** [comment]
@BrazilAmando 

你好，感谢反馈。

这个需求听起来更像是应该交给 theme 来做。暂时就不做了。

**Comment by BrazilAmando** [comment]
这个思路可行，赞！谢谢
