### ISSUE TITLE
[suggestion] 使用以及重构方面的建议

### ISSUE THREAD

**Issue by yourests** [obgnail/typora_plugin#176]
1. 不要写死 /plugin 目录，因为我比较习惯把插件放到 /AppData/Roaming/Typora，但我发现只是修改 window.html 中的路径仍然会定位到 /resources/plugin。
2. 将 js 与 css 进行分离（style = () => {...} 部分），方便对部分样式进行扩展。
3. 章节折叠在 tab 切换之后会失效，scrollContent 的 scrollTop 也会发生错乱（等待 content 加载好再定位 scrollTop，我考虑的是通过 window.onload 或者 MutationObserver 可能实现？）。
4. 中英文混排优化影响到高亮的效果（==高亮== → == 高亮 ==）。

**Comment by carve-myself** [comment]
> 1. 不要写死 /plugin 目录，因为我比较习惯把插件放到 /AppData/Roaming/Typora，但我发现只是修改 window.html 中的路径仍然会定位到 /resources/plugin。
> 2. 将 js 与 css 进行分离（style = () => {...} 部分），方便对部分样式进行扩展。
> 3. 章节折叠在 tab 切换之后会失效，scrollContent 的 scrollTop 也会发生错乱（等待 content 加载好再定位 scrollTop，我考虑的是通过 window.onload 或者 MutationObserver 可能实现？）。
> 4. 中英文混排优化影响到高亮的效果（==高亮== → == 高亮 ==）。

第1条 你可以参考这个 弄成软链接 再typora://app/userData/~~~~~映射过去
https://github.com/typora-community-plugin/typora-community-plugin/blob/main/README.zh-CN.md

**Comment by obgnail** [comment]
@yourests 
你好，感谢反馈。

第三条【章节折叠在 tab 切换之后会失效】。这个问题在 1.4.0 做了修复。

**Comment by yourests** [comment]
> > 1. 不要写死 /plugin 目录，因为我比较习惯把插件放到 /AppData/Roaming/Typora，但我发现只是修改 window.html 中的路径仍然会定位到 /resources/plugin。
> > 2. 将 js 与 css 进行分离（style = () => {...} 部分），方便对部分样式进行扩展。
> > 3. 章节折叠在 tab 切换之后会失效，scrollContent 的 scrollTop 也会发生错乱（等待 content 加载好再定位 scrollTop，我考虑的是通过 window.onload 或者 MutationObserver 可能实现？）。
> > 4. 中英文混排优化影响到高亮的效果（==高亮== → == 高亮 ==）。
> 
> 第1条 你可以参考这个 弄成软链接 再typora://app/userData/~~~~~映射过去 https://github.com/typora-community-plugin/typora-community-plugin/blob/main/README.zh-CN.md

这个我试过的，引用是没问题的，但加载 `pluginFile` 的路径不对，由于 node 进程被 Electron 渲染进程调用，`global.dirname` 和 `global.__dirname` 分别指向 **/resources** 和 **/resources/electron.asar/renderer**，这个解决起来比较麻烦。

我的替换方案是通过 `document.currentScript.src` 或者 `type="module"` 作为 ES6 模块引入再通过 `import.meta.url` 获取当前模块路径，但这样 `reqnode` 会提示无法定位软链接，所以只能使用完整路径 `<script type="module" src="C:/Users/youre/AppData/Roaming/Typora/plugin/index.js"></script>`。

另外 `import.meta.url` 获得的路径会有 `file:///` 前缀需要截取掉 `const pluginFile = reqnode('path').join(import.meta.url.slice(8), "../global/core/plugin.js")`，否则 `reqnode` 引入时会报错，再作为参数传入 `new process().run(pluginFile)`。这样 `joinPath()` 就不拼接 `this.getDirname()` 了，`readToml()`, `stringifyToml()`, `updateSettings()` 去掉 `./plugin` 使用相对路径。

**Comment by yourests** [comment]
> @yourests 你好，感谢反馈。
> 
> 第三条【章节折叠在 tab 切换之后会失效】。这个问题在 1.4.0 做了修复。
> 
> window.onload 只会在打开 typora 时执行一次。【打开文件】只是在操作现有的 html。 MutationObserver 的话，我也不知道要监听什么呀，您有什么思路吗？
> 
> 我去看了一下 typora-community-plugin 的写法，别人是 setTimeout 硬等😂

我使用的是 1.3.21，我之后会重新下载试试😘
关于加载问题，我考虑的是类似 `nextTick` 的实现方案，监听 DOM 变化，content 每次变化调用一次 `callback` 异步更新 scrollTop，具体用法可以参照 https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver

**Comment by yourests** [comment]
> > @yourests 你好，感谢反馈。
> > 第三条【章节折叠在 tab 切换之后会失效】。这个问题在 1.4.0 做了修复。
> > window.onload 只会在打开 typora 时执行一次。【打开文件】只是在操作现有的 html。 MutationObserver 的话，我也不知道要监听什么呀，您有什么思路吗？
> > 我去看了一下 typora-community-plugin 的写法，别人是 setTimeout 硬等😂
> 
> 我使用的是 1.3.21，我之后会重新下载试试😘 关于加载问题，我考虑的是类似 `nextTick` 的实现方案，监听 DOM 变化，content 每次变化调用一次 `callback` 异步更新 scrollTop，具体用法可以参照 https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver

我重写了一下 `scrollContent`，感觉要好点。

```javascript
    scrollContent = activeTab => {
        if (!activeTab) return;
        const scrollTop = activeTab.scrollTop;
        if (scrollTop === 0) return;
        const plugin = this;
        this.switchToTab(activeTab).then(res => {
            const targetNode = document.getElementsByTagName('content')[0];
            // 观察器的配置（需要观察什么变动）
            const config = { attributes: true, childList: true, subtree: true };
            // 当观察到变动时执行的回调函数
            const callback = function (mutationsList, observer) {
                plugin.entities.content.scrollTop = scrollTop;
            }
            const observer = new MutationObserver(callback);
            observer.observe(targetNode, config)
        })
    }

    switchToTab = (activeTab) => {
        return new Promise((resolve, reject) => {
            const intervalId = setInterval(() => {
                const filePath = this.utils.getFilePath();
                if (filePath === activeTab.path) {
                    resolve();
                    clearInterval(intervalId);
                }
            }, 100);
        })
    }
```

**Comment by obgnail** [comment]
@yourests 

提问：

在 1.4.0 重构的时候，我给原来的代码加了一行：
```js
this.utils.publishEvent(this.utils.eventType.fileContentLoaded, filePath);
```
用来发布【加载完毕】事件

```js
    scrollContent = activeTab => {
        if (!activeTab) return;

        let count = 0;
        const stopCount = 3;
        const scrollTop = activeTab.scrollTop;
        const _timer = setInterval(() => {
            const filePath = this.utils.getFilePath();
            if (filePath === activeTab.path && this.entities.content.scrollTop !== scrollTop) {
                this.entities.content.scrollTop = scrollTop;
                count = 0;
            } else {
                count++;
            }
            if (count === stopCount) {
                clearInterval(_timer);
                this.utils.publishEvent(this.utils.eventType.fileContentLoaded, filePath);
            }
        }, this.config.LOOP_DETECT_INTERVAL);
    }
```

使用上述代码的话，该怎么加上这句呢？

**Comment by obgnail** [comment]
如果能监听 fileContentLoaded ，将给很多插件带来方便。

比如说上面讲的【章节折叠在 tab 切换时自动恢复】，我就是监听了 fileContentLoaded 事件
```js
    process = () => {
        // 切换标签前，记录折叠的heading
        this.utils.addEventListener(this.utils.eventType.beforeFileOpen, this.collect);
        // 文档加载完毕后，执行collapseHeading
        this.utils.addEventListener(this.utils.eventType.fileContentLoaded, this.collapseHeading);
    }
```

**Comment by yourests** [comment]
> @yourests
> 
> 提问：
> 
> 在 1.4.0 重构的时候，我给原来的代码加了一行：
> 
> ```js
> this.utils.publishEvent(this.utils.eventType.fileContentLoaded, filePath);
> ```
> 
> 用来发布【加载完毕】事件
> 
> ```js
>     scrollContent = activeTab => {
>         if (!activeTab) return;
> 
>         let count = 0;
>         const stopCount = 3;
>         const scrollTop = activeTab.scrollTop;
>         const _timer = setInterval(() => {
>             const filePath = this.utils.getFilePath();
>             if (filePath === activeTab.path && this.entities.content.scrollTop !== scrollTop) {
>                 this.entities.content.scrollTop = scrollTop;
>                 count = 0;
>             } else {
>                 count++;
>             }
>             if (count === stopCount) {
>                 clearInterval(_timer);
>                 this.utils.publishEvent(this.utils.eventType.fileContentLoaded, filePath);
>             }
>         }, this.config.LOOP_DETECT_INTERVAL);
>     }
> ```
> 
> 使用上述代码的话，该怎么加上这句呢？

你可以使用以下的写法
```javascript
    scrollContent = activeTab => {
        if (!activeTab) return;
        const scrollTop = activeTab.scrollTop;
        if (scrollTop === 0) return;
        const plugin = this;
        let observer = null;
        this.switchToTab(activeTab).then(res => {
            const targetNode = document.getElementsByTagName('content')[0];
            // 观察器的配置（需要观察什么变动）
            const config = { attributes: true, childList: true, subtree: true };
            // 当观察到变动时执行的回调函数
            const callback = function (mutationsList, observer) {
                plugin.entities.content.scrollTop = scrollTop;
            }
            observer = new MutationObserver(callback);
            observer.observe(targetNode, config);
        }).finally(() => {
            this.utils.publishEvent(this.utils.eventType.fileContentLoaded, activeTab.path);
            observer.disconnect();
        })
    }
```

**Comment by yourests** [comment]
> > @yourests
> > 提问：
> > 在 1.4.0 重构的时候，我给原来的代码加了一行：
> > ```js
> > this.utils.publishEvent(this.utils.eventType.fileContentLoaded, filePath);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用来发布【加载完毕】事件
> > ```js
> >     scrollContent = activeTab => {
> >         if (!activeTab) return;
> > 
> >         let count = 0;
> >         const stopCount = 3;
> >         const scrollTop = activeTab.scrollTop;
> >         const _timer = setInterval(() => {
> >             const filePath = this.utils.getFilePath();
> >             if (filePath === activeTab.path && this.entities.content.scrollTop !== scrollTop) {
> >                 this.entities.content.scrollTop = scrollTop;
> >                 count = 0;
> >             } else {
> >                 count++;
> >             }
> >             if (count === stopCount) {
> >                 clearInterval(_timer);
> >                 this.utils.publishEvent(this.utils.eventType.fileContentLoaded, filePath);
> >             }
> >         }, this.config.LOOP_DETECT_INTERVAL);
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用上述代码的话，该怎么加上这句呢？
> 
> 你可以使用以下的写法
> 
> ```js
>     scrollContent = activeTab => {
>         if (!activeTab) return;
>         const scrollTop = activeTab.scrollTop;
>         if (scrollTop === 0) return;
>         const plugin = this;
>         let observer = null;
>         this.switchToTab(activeTab).then(res => {
>             const targetNode = document.getElementsByTagName('content')[0];
>             // 观察器的配置（需要观察什么变动）
>             const config = { attributes: true, childList: true, subtree: true };
>             // 当观察到变动时执行的回调函数
>             const callback = function (mutationsList, observer) {
>                 plugin.entities.content.scrollTop = scrollTop;
>             }
>             observer = new MutationObserver(callback);
>             observer.observe(targetNode, config);
>         }).finally(() => {
>             this.utils.publishEvent(this.utils.eventType.fileContentLoaded, activeTab.path);
>             observer.disconnect();
>         })
>     }
> ```

我发现有个bug，写在 `finally()` 中的部分可能会先执行，导致观察者的回调函数执行之前停止观察，改成这样就没问题了。
```js
    scrollContent = activeTab => {
        if (!activeTab) return;
        const scrollTop = activeTab.scrollTop;
        if (scrollTop === 0) return;
        const plugin = this;
        let observer = null;
        let _timer = null;
        this.switchToTab(activeTab).then(res => {
            const targetNode = document.getElementById('write');
            // 观察器的配置（需要观察什么变动）
            const config = { attributes: true, childList: true, characterData: true, subtree: true };
            // 当观察到变动时执行的回调函数
            const callback = function (mutationsList, observer) {
                plugin.entities.content.scrollTop = scrollTop;
                // 观察者的回调函数频繁执行，做防抖处理
                clearTimeout(_timer);
                _timer = setTimeout(() => {
                    // 避免观察者的回调函数执行之前停止观察
                    // 停止观察时间间隔过短会造成无法滚动到上次的位置
                    // 停止观察时间间隔过长会造成滚动一段距离或点击大纲其他标题时回到之前的位置
                    observer.disconnect();
                    plugin.utils.publishEvent(plugin.utils.eventType.fileContentLoaded, activeTab.path);
                }, 1000)
            }
            observer = new MutationObserver(callback);
            observer.observe(targetNode, config)
        })
    }
```

**Comment by obgnail** [comment]
@yourests 感谢帮助。

试了一下，不太行。很奇怪，对于小文件总是会定位到文件首页。感觉原因是：固定的 1000ms 无法应对不同的文件打开时间。

**Comment by obgnail** [comment]
@yourests 

国庆有空，处理了第四点。添加了 ignore_words 参数。
有兴趣的话可以试用一下。

```toml
# 不希望拆分的单词
IGNORE_WORDS = ["=="]
```

**Comment by obgnail** [comment]
@yourests @carve-myself 

花了点时间，将 style 抽离成单独文件了。简单支持了类似于 jinja2 的模板方法
