### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by pro911** [obgnail/typora_plugin#177]
最新版本: tag:1.4.1
OS: Windows11 x64
fix:
1. 右键-开启和关闭`auto_number` 不生效,但配置设置stings.user 配置文件关闭可生效.
2. 只读模式`read_only` 开启后,无法唤醒全局检索.

feat:
1. 建议添加代码展开和收起的快捷键.

**Comment by obgnail** [comment]
两个问题都是 1.4.0 重构时带来的 bug。已经上到 master 了，晚上会上线 1.4.2。如果着急可以拉一下 master 代码。

**Comment by obgnail** [comment]
@pro911 

置于快捷键问题，我在想办法整一个快捷键系统，让每个功能都能支持快捷键，到时粒度应该会小到每个函数都能支持。

**Comment by obgnail** [comment]
@pro911 

1.4.2 已经上线，感兴趣的话可以更新：【右键菜单->启用插件->自定义插件->更新插件】
