### ISSUE TITLE
[feature] 未保存, 标签加 `*`

### ISSUE THREAD

**Issue by yiyungent** [obgnail/typora_plugin#183]
![image](https://github.com/obgnail/typora_plugin/assets/16939388/756d36e4-613e-40de-831f-10e2a7d3f4b1)

未保存时，建议在 `标签标题` 加 `*` ，如 `Typora` 默认行为，以便指示未保存状态

> PS: 话说能实现保存状态吗，发现每次 `启用插件->自动编号->禁用` 变成 `启用` 后，再次打开 `Typora` 又会重新进入 `禁用` 状态

**Comment by obgnail** [comment]
@yiyungent 

感谢反馈。

任何插件的任何功能都是可以 **通过修改配置文件** 永久打开/关闭的。

可以使用如下方式打开配置文件：
```
启用插件 -> 右键菜单 -> 打开插件配置文件
```

**Comment by yiyungent** [comment]
> @yiyungent
> 
> 感谢反馈。
> 
> 任何插件的任何功能都是可以 **通过修改配置文件** 永久打开/关闭的。
> 
> 可以使用如下方式打开配置文件：
> 
> ```
> 启用插件 -> 右键菜单 -> 打开插件配置文件
> ```

其实可以试试曲线救国，就如 `updater` 一样，去调 `exe` ，`exe` 保存到配置文件，不过确实对于开发来说麻烦了，也存在 `权限` 问题，^-^ ，就编辑配置文件也行

**Comment by obgnail** [comment]
@yiyungent  感谢反馈。

【在 标签标题 加 * 】，这个需求暂时就不搞了。不好意思。

原因：
1. 收益低：新版本的 Typora 会每隔几秒就保存一次文件，实现这个功能就显得没有啥意义。
2. 成本高：要想实现此功能有三种方法：
    1. 轮询当前文件是否处于编辑状态
    2. 监听用户每次输入，执行回调
    3. 装饰 Typora 用于【设置标题】的函数


这三种方案我嫌弃太【重】了。其中成本最低的是方法 3（可以看下面代码），但是它使用的 `JSBridge.invoke` 广泛运用于各个地方，我个人希望尽量避免装饰这种大函数。

---

如果您有兴趣实现，您可以修改 window_tab，这里给您一些关键代码：
```js
// 获取当前文件是否处于编辑状态（当然对于新版本的 Typora，返回值几乎永远都是 false）
File.isDocumentEdited() 

// Typora 是用此函数设置标题的 
// 可以通过装饰 JSBridge.invoke 函数实现
JSBridge.invoke("window.setTitle", t + "• - Typora")) : (i.text($.localize.getString("Untitled"))
JSBridge.invoke("window.setTitle", $.localize.getString("Untitled") + (File.changeCounter && !File.changeCounter.curState ? "• - Typora" : " - Typora")))
```

如果您有其他需求，可以提出来，我评估一下能不能做。

**Comment by yiyungent** [comment]
> @yiyungent 感谢反馈。
> 
> 【在 标签标题 加 * 】，这个需求暂时就不搞了。不好意思。
> 
> 原因：
> 
> 1. 收益低：新版本的 Typora 会每隔几秒就保存一次文件，实现这个功能就显得没有啥意义。
> 2. 成本高：要想实现此功能有三种方法：
>    
>    1. 轮询当前文件是否处于编辑状态
>    2. 监听用户每次输入，执行回调
>    3. 装饰 Typora 用于【设置标题】的函数
> 
> 这三种方案我嫌弃太【重】了。其中成本最低的是方法 3（可以看下面代码），但是它使用的 `JSBridge.invoke` 广泛运用于各个地方，我个人希望尽量避免装饰这种大函数。
> 
> 如果您有兴趣实现，您可以修改 window_tab，这里给您一些关键代码：
> 
> ```js
> // 获取当前文件是否处于编辑状态（当然对于新版本的 Typora，返回值几乎永远都是 false）
> File.isDocumentEdited() 
> 
> // Typora 是用此函数设置标题的 
> // 可以通过装饰 JSBridge.invoke 函数实现
> JSBridge.invoke("window.setTitle", t + "• - Typora")) : (i.text($.localize.getString("Untitled"))
> JSBridge.invoke("window.setTitle", $.localize.getString("Untitled") + (File.changeCounter && !File.changeCounter.curState ? "• - Typora" : " - Typora")))
> ```
> 
> 如果您有其他需求，可以提出来，我评估一下能不能做。

哦哦哦，没关系，已经很棒了，感谢！！！
