### ISSUE TITLE
中英文加空格的插件快捷键失效

### ISSUE THREAD

**Issue by aldol-reaction** [obgnail/typora_plugin#19]
目前其他功能都可以正常使用，这个功能 ctrl + shift + k 失效了，同时和 typora 自带的插入代码块快捷键冲突。我用 openark看了一下，这个快捷键我全局没有被占用。

**Comment by aldol-reaction** [comment]
用的是typora最新版本

**Comment by obgnail** [comment]
@aldol-reaction 你好，感谢反馈。

为了解决快捷键冲突的问题，我整了一个 right_click_menu.js 脚本，方便在右键菜单统一调用插件。
如果可以的话，帮忙试用一下此脚本，以验证是否为 md_padding.js 的 BUG。

如果还是不行，帮忙看一下控制台输出：
第一步：点击左上角【文件】，打开偏好设置。 或者快捷键 Ctrl+(逗号)
第二步：在通用中找到高级设置下的 "开启调试模式"
第三步：shift+F12，或者右键 -- 检查元素
第四步：选择第二个标签（Console 或者 控制台）

**Comment by aldol-reaction** [comment]
还是不行。
DevTools failed to load source map: Could not load content for typora://app/typemark/lib.asar/pdf/pdf-lib.min.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/underscore-node-f.cjs.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for file:///C:/Users/wsq/AppData/Local/Programs/Typora/resources/plugin/mermaid_replace/mermaid.min.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for typora://app/typemark/index.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/pad-markdown.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/parse.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/type-guards.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/char.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/inline-image.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/reference-image.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/alphabet-numeric.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/unicode-string.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/square-quoted.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/delimited.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/empasis.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/quoted.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/strong.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/strikethrough.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/document.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/compact.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/dfs.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/html-tag.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/punctuation.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/reference-link.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/reference-definition.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/inline-link.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/inline-code.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/math.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/block-code.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/blank.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/raw.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/ordered-list-item.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/unordered-list-item.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/stack.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/mask.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/parse-code.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/string.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/pad-markdown-options.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/pad-recursively.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for typora://app/typemark/pad-between-nodes.js.map: System error: net::ERR_FILE_NOT_FOUND
frame.js:25 presentedItemChanged, path is -1699136375
frame.js:25 presentedItemChanged ignored
DevTools failed to load source map: Could not load content for http://typora/appsrc/window/frame.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://typora/lib/codemirror/mode.min.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Comment by aldol-reaction** [comment]
另外建议右键菜单盘古之白可以改一下名字，有点不知所云。

**Comment by obgnail** [comment]
@aldol-reaction 

问题解决了，麻烦更新一下脚本文件。

原因：脚本核心逻辑没有问题。高版本 Typora 的 reloadContent 函数发生了变化，导致文件内容更新了，但是没有更新页面。

更新脚本前你可以试试：执行脚本后，切到其他文件，再切回来发现文件其实是被更新了的。

如果问题解决了，麻烦在这里回复提醒我一下。

**Comment by aldol-reaction** [comment]
@obgnail 很完美的解决了，感谢。
