### ISSUE TITLE
能否将用户及配置文件,去除发行版本.

### ISSUE THREAD

**Issue by pro911** [obgnail/typora_plugin#194]
问题:
1. 现在每次升级都是下载压缩包,然后覆盖plugin目录,这样同时将我的`settings.user.toml` 和 `custom_plugin.user.toml` 等配置都覆盖了, 这些文件能否做约定关系, 而不体现在发行版本当中, 这样我们可以自主创建和不创建.

**Comment by obgnail** [comment]
@pro911 
你好，感谢反馈。

是我没有说明白吗？不用手动升级呀。

我把【升级插件】做成了一个插件，所以正常的升级流程是：`常用插件 -> 自定义插件 -> 更新插件`（之前的是 `启用插件 -> 自定义插件 -> 更新插件`）。

如此，会自动下载安装包，并且自动保留用户的 settings.user.toml 和 custom_plugin.user.toml 和 用户写的自定义插件（我就是为了能支持自动升级才拆分出这两个文件的呀）

整个流程是一键完成的。

![Snipaste_2023-09-22_10-44-13](https://github.com/obgnail/typora_plugin/assets/48992887/d47a1d0b-ef75-421a-bcde-557ce922519a)

![Snipaste_2023-09-22_10-45-38](https://github.com/obgnail/typora_plugin/assets/48992887/f6363ed5-061e-486a-a933-3d1e2edecef1)

**Comment by pro911** [comment]
可能是我电脑配置没配置好,默认的配置无法使用报错.
报错截图:
![image](https://github.com/obgnail/typora_plugin/assets/28957658/a4d4e726-b6d3-45ca-bbf2-6096f667f985)

**Comment by obgnail** [comment]
@pro911 

看到你的图片，我猜到了原因了，应该是我自动升级脚本没有写好。不好意思。

> cd 后面的路径没有加引号导致的。

我晚上会上一个修复版本。之后应该不会出现此问题了，能支持一键化更新了。

**Comment by obgnail** [comment]
艹，低级失误 😂

**Comment by obgnail** [comment]
@pro911 

修复上了 1.4.8，能帮忙测试一下吗？应该没有问题了。

**Comment by obgnail** [comment]
如果可以的话，应该是你最后一次修改手动配置文件了 😂

**Comment by pro911** [comment]
fix:
1. 更新失败 好像是这个文件没了. `save_tabs.json`
```shell
注意: 请勿通过手动执行updater.exe更新插件

更新插件中，请稍等

[step 1] new updater
[step 2] check whether need update
[step 3] download latest version
[step 4] unzip file
[step 5] adjust files
panic: CreateFile D:\Program Files\Typora\resources\plugin\window_tab\save_tabs.json: The system cannot find the file specified.

goroutine 1 [running]:
main.main()
	D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:574 +0x21c
```

**Comment by obgnail** [comment]
唉，看来自动升级这个东西就没有人用过，从来没有人跟我反馈过这个问题。

你在 D:\Program Files\Typora\resources\plugin\window_tab 目录下创建一个空内容的 save_tabs.json，再重新运行一下插件，应该就可以了。

**Comment by pro911** [comment]
还有个小建议,不值当讲不当讲,  就是更新源建议新增gitee,这样不会vpn的小伙伴也可以更快速的更新.

**Comment by obgnail** [comment]
@pro911 

- 1.4.9 解决 save_tabs.json 的问题（很不好意思的说，这个 BUG 其实是 1.4.0 重构引入的），后续更新只要一键操作就行了。
- 感谢建议。我考虑一下。
- 最后想问一下，你觉得【自动更新插件】这个功能要不要做，还是说做成一个配置选项？大概就是每次打开 Typora 就自动检测，执行升级流程。有些用户也这样跟我建议。

![Snipaste_2023-09-22_14-11-26](https://github.com/obgnail/typora_plugin/assets/48992887/dbf18df4-b02f-41d7-be92-381712357ad5)

**Comment by pro911** [comment]
我觉着都可以,自动更新确实更加简单,做成配置项让用户可以关闭.  在保留手动更新保留就更完美了.自动更新毕竟会消耗一些时间,所以要看用户习惯.
1.4.9 测试过了 可以更新成功了.目前看可以满足升级了奈斯!

**Comment by obgnail** [comment]
@pro911 

我在 1.4.10 加了【自动静默更新】选项了。

默认会在打开 Typora 5 分钟后自动执行静默升级流程（自动升级时并不会弹窗回显当前进度）

```toml
[pluginUpdater.config]
# 打开Typora时自动静默升级（若为false，则start_update_interval配置失效）
auto_update = true
# 打开Typora多长时间后，开始执行升级流程（单位：ms）
start_update_interval = 300000 # (1000 * 60 * 5)
```
