### ISSUE TITLE
右侧滚轮在文章处于最开头的时候，一部分会被标签页挡住

### ISSUE THREAD

**Issue by aldol-reaction** [obgnail/typora_plugin#20]
希望可以优化一下。作者的插件很好，支持一下！

**Comment by aldol-reaction** [comment]
![](https://cdn.luogu.com.cn/upload/image_hosting/5r2ngox0.png)
大大什么时候可以优化一下，辛苦 @obgnail

**Comment by obgnail** [comment]
@aldol-reaction 

之前修复代码在 dev 里，现在已经合到 master 啦，顺便完善了拖拽排序的交互逻辑。更新一下就行。
> 注意：需要更换整个 plugin 文件。

有 bug 帮忙反馈一下。

**Comment by aldol-reaction** [comment]
已解决，感谢
