### ISSUE TITLE
【功能建议】是否可以增加采用markdown语法显示时间线的效果

### ISSUE THREAD

**Issue by BrazilAmando** [obgnail/typora_plugin#206]
mermaid中的时间线比较奇怪，是否可以参考layui或其他前端JS框架中常见的时间线样式，在插件中新增？通过简单的类似于看板的语法直接显示时间线
https://layui.dev/docs/2.8/timeline/
![image](https://github.com/obgnail/typora_plugin/assets/125205627/ca48d30e-6689-4b8a-b7f8-7dbc33d0f67a)

**Comment by obgnail** [comment]
@BrazilAmando 

新版本已经支持，麻烦试用一下。

不过这种自 high 的拓展语法应该只有我们两个人会用 😂

![timeline](https://github.com/obgnail/typora_plugin/assets/48992887/136f7c1d-f047-4298-adb3-b7ea0b509a32)

**Comment by BrazilAmando** [comment]
优秀👍
万事万物包含在时空内，用typora做笔记应该经常使用到时间线功能，特别是在商务场景。
线条核圆点颜色黑灰色有些单调，是否可更改为明亮些的，若能支持自定义颜色功能更好🤝

**Comment by obgnail** [comment]
@BrazilAmando 

添加了配置。

**Comment by BrazilAmando** [comment]
赞！
正好用来策划国庆安排，效果杠杠滴
