### ISSUE TITLE
[bug]“中英文混排优化”功能导致部分HTML开始标签及内容中出现空格

### ISSUE THREAD

**Issue by R3c0ger** [obgnail/typora_plugin#234]
经测试（测试范围为 [Typora学习索引——HTML篇](https://zhuanlan.zhihu.com/p/642771075) 中的HTML内容），在对文档使用“中英文混排优化”功能之后，会对如下标签造成不良（影响原来的表达效果）影响：

- `<kbd>`：表现为在标签内容两端添加空格，而这两个空格会表现出来，无论内容是中文还是英文；
- 对于在标签中有折行的HTML标签，会在多个位置添加空格，导致HTML失效。
  举例：优化前：
  ```html
  <figure class="clearfix" style="position: relative;"> 
    <img src="img/1" alt="左图" 
  style="box-sizing: border-box; float: left; width: 50%; padding-right: 4px;"/>
  </figure> 
  ```
  ![图片](https://github.com/obgnail/typora_plugin/assets/116271028/5800926b-43da-450c-b129-4e49d13a4b10)
  优化后：
  ```html
  <figure class="clearfix" style="position: relative;"> 
    < img src =" img/1 " alt =" 左图 " 
  style = "box-sizing: border-box; float: left; width: 50%; padding-right: 4px;"/>
  </figure> 
  ```
  ![图片](https://github.com/obgnail/typora_plugin/assets/116271028/1c4f1210-e3ed-4c39-8032-7cc7018096ad)

对于其他诸如 `<span>`、`<ruby>`、`<center>` 等标签，无论内容是什么语言，都会在内容两端也添加空格，不过对于最终的渲染效果无影响。

Typora 版本：v1.0.4

**Comment by R3c0ger** [comment]
除上述内容之外，在Typora文档里使用<style>标签，编写CSS时，下面的一些内容也会被分开：
- 伪类、伪元素的冒号和英文之间；
- !important的感叹号和英文之间；
- 属性选择器的中括号之前
![a](https://github.com/obgnail/typora_plugin/assets/116271028/dd246c32-bcec-4bcf-9473-9becb860162a)

**Comment by obgnail** [comment]
@R3c0ger 你好，感谢反馈。

不好意思，拖了这么久，主要是我想不到该怎么做了。先说结论，**暂时不会修复**。

原因：如果要修复这个问题，需要引入 html 的 AST 解析库，极大增加复杂度。

## !important 被拆开的问题

原因：**md_padding 只会保护 标签开始标志 `<` 和  标签结束标志 `>`  中间的文本，标签的 innerText 不受保护**。

md_padding 其实是没有 HTML 标签包裹概念的，它的实现方式是非常狡猾讨巧的，究极简单。其实就是把**同一行中** `<` 和 `>` 包裹的文本视为 html_tag，然后原封不动的返回而已。
```js
class HTMLTag {
    constructor(text) {
        this.children = [];
        this.kind = 64 /* HTMLTag */;
        this.text = text;
    }
    toMarkdown() {
        return `<${this.text}>`;   // this.text 的内容原封不动的返回
    }
}
```
所以 `<div>\nasdasd就是asdasd</div>`  这段文本的解析效果如下，你会发现 `\nasdasd就是asdasd` 是和 html 标签是平级的，并不是嵌套的

![Snipaste_2023-12-28_18-21-19](https://github.com/obgnail/typora_plugin/assets/48992887/38a1ea58-c09c-4577-881f-9bb86eb5eac3)

因为没有 `包裹` 的概念，所以 html 标签内部的 innerText 会被视为普通文本进行解析，所以就会出现 !important 被拆开的情况。

---

## img 被拆开的问题

原因：**标签开始标志 `<` 和  标签结束标志 `>` 必须在同一行**

因为是把**同一行中** `<` 和 `>` 包裹的文本视为 html_tag，所以下面的 html 是没有问题的：
```html
<img src="img/1" alt="左图" style="box-sizing: border-box; float: left; width: 50%; padding-right: 4px;"/>
```
但是如果把 img 标签拆开（就像你做的那样）：
```html
  <img src="img/1" alt="左图" 
style="box-sizing: border-box; float: left; width: 50%; padding-right: 4px;"/>
```
那么，就会彻底失效，将html文本作为普通文本解析。

---

## 这个问题严重吗？

回顾上面两个情况，其实就是两个问题：
1. html 标签的 `<` 和 `>` 必须在同一行出现。
2. html 标签的 innerText 会被当初普通文本处理。

这两个问题，对于我来说，是可以接受的，
- 问题1：用户稍微注意一下即可。
- 问题2：可以算是 md_padding 的特性。

比如说，本项目 readme 的 html 标签，因为 img 标签的 < 和 > 在同一行出现，所以 `img src="assets/typora_plugin.png" alt="typora_plugin" width="400" /` 这段内容是受到保护的
```html
<div align="center">
  <img src="assets/typora_plugin.png" alt="typora_plugin" width="400" />
</div>
```
比如说，text_stylize 插件，生成的 html 标签，< 和 > 也会在同一行出现
```html
 ada<span style="text-emphasis:filled red; vertical-align:super; text-decoration:overline;">sdasd</span>a
```

## 总结
1. 如果使用 html 标签，请保证标签开始标志 `<` 和  标签结束标志 `>` 在同一行
2. 如果希望保护 html 标签的 innerText，请使用代码块将其包裹

**Comment by obgnail** [comment]
@R3c0ger 

感谢反馈。此 issue 关闭，如有问题麻烦在下面留言，或者另开 issue。

**Comment by R3c0ger** [comment]
> @R3c0ger
> 
> 感谢反馈。此 issue 关闭，如有问题麻烦在下面留言，或者另开 issue。

也许...专门只对某一个段落块进行混排优化，这种功能实现起来是否具有可行性呢？

**Comment by R3c0ger** [comment]
> @R3c0ger
> 
> 已经实现仅在选区中生效。添加了 FORMAT_IN_SELECTION_ONLY 配置（默认为 false，需要手动开启此功能），你可以试试看，不过效果可能不太好。
> 
> ```toml
> [md_padding]
> # 仅在选区中生效：当框选文字时，调用此功能只会对当前框选的文字生效
> FORMAT_IN_SELECTION_ONLY = false
> ```

万分感谢，有机会会去尝试一下的，谢谢您
