### ISSUE TITLE
[window_tab]为何我的typora无法打开多标签？

### ISSUE THREAD

**Issue by echo0218** [obgnail/typora_plugin#239]
我的Typora Version1.2.5 X64版本，安装后无法打开多标签？仍是多窗口显示

**Comment by obgnail** [comment]
@echo0218 
你好，感谢反馈。能详细说明一下情况吗？

1. 是首次安装，并且没有修改任何配置，是吗？
2. 能提供一下截图吗？
3. 能不能帮忙看看控制台输出呢？
第一步：点击左上角【文件】，打开偏好设置。 或者快捷键 Ctrl+(逗号)
第二步：在通用中找到高级设置下的 "开启调试模式"，勾选上
第三步：shift+F12，或者右键 -- 检查元素
第四步：选择第二个标签（Console 或者 控制台）

**Comment by obgnail** [comment]
@echo0218 

你是怎么打开文件的？如果你是在资源管理器里双击打开多个文件，那确实是只能多窗口显示。
详见这个 issue [不从 typora 打开的文件还是单独窗口](https://github.com/obgnail/typora_plugin/issues/59)

**Comment by echo0218** [comment]
> @echo0218 你好，感谢反馈。能详细说明一下情况吗？
> 
>     1. 是首次安装，并且没有修改任何配置，是吗？
> 
>     2. 能提供一下截图吗？
> 
>     3. 能不能帮忙看看控制台输出呢？
>        第一步：点击左上角【文件】，打开偏好设置。 或者快捷键 Ctrl+(逗号)
>        第二步：在通用中找到高级设置下的 "开启调试模式"，勾选上
>        第三步：shift+F12，或者右键 -- 检查元素
>        第四步：选择第二个标签（Console 或者 控制台）



> @echo0218 你好，感谢反馈。能详细说明一下情况吗？
> 
>     1. 是首次安装，并且没有修改任何配置，是吗？
> 
>     2. 能提供一下截图吗？
> 
>     3. 能不能帮忙看看控制台输出呢？
>        第一步：点击左上角【文件】，打开偏好设置。 或者快捷键 Ctrl+(逗号)
>        第二步：在通用中找到高级设置下的 "开启调试模式"，勾选上
>        第三步：shift+F12，或者右键 -- 检查元素
>        第四步：选择第二个标签（Console 或者 控制台）

又认真测试了下，发现打开文件(Strl+O)和将markdown文件拖入typora窗口，都是以新窗口打开；只有快速打开(Strl+P)，能够以新标签页打开文件。所有截图见附件。
<img width="277" alt="Snipaste_2023-10-09_14-10-51" src="https://github.com/obgnail/typora_plugin/assets/11382853/7348286a-dcd3-4517-9da3-939b4d6439ee">
<img width="416" alt="Snipaste_2023-10-09_14-11-44" src="https://github.com/obgnail/typora_plugin/assets/11382853/ba873d0b-909b-43e1-bf25-2e200320d82f">

**Comment by obgnail** [comment]
@echo0218 你好，感谢反馈。

回复如下：
1. 要想做到【打开文件 (Strl+O) 和将 markdown 文件拖入 typora 窗口，以新标签页打开】，**从原理上就是做不到的** ，是字面意义的不可能，只能等待 Typora 官方支持。（不过我强烈怀疑官方永远都不会支持这个特性）
2. 大伙使用 Typora 一般都不会一个一个地去打开特定的文件。而是打开一个固定的文件夹。在文件夹下有你需要的一切文件。
具体到我的情况：创建一个 md 文件夹，把所有的文件分门别类放在不同的子文件里面，这样就可以管理所有的文件了。
![unnamed](https://github.com/obgnail/typora_plugin/assets/48992887/8988d324-4124-40d3-a756-67efe47823df)
3. 几乎市面上所有的笔记软件，都不支持在同一个窗口打开路径完全不同的文件，都是需要将这些文件放在同一个目录底下的。

**Comment by obgnail** [comment]
@echo0218 
此 issue 关闭，如果有其他问题，麻烦另开 issue
