### ISSUE TITLE
[bug]搜索好像只搜索了文件内容，不搜索文件名,应该是搜索关键词在文件名中的排在搜索结果权重高，排在最前面吧

### ISSUE THREAD

**Issue by heavenkiller2018** [obgnail/typora_plugin#25]
[bug]搜索好像只搜索了文件内容，不搜索文件名,应该是搜索关键词在文件名中的排在搜索结果权重高，排在最前面吧?

另外，直接从windows打开md文件时，能不能是以新tab页的形式，而不是新开一个typro窗口. 独立的typro窗口能合并一个已有的typro窗口去而成为其上的一个tab吗？

**Comment by obgnail** [comment]
@heavenkiller2018 你好，感谢反馈。

1. 这点我也考虑了。一来如果要搜索文件名，有自带的 ctrl+P 的功能，二来怕大伙疑惑。所以我把这个需求做成了配置选项 INCLUDE_FILE_PATH（将文件路径加入搜索内容），默认是 false。可以按需修改 search_multi.js 文件。
2. 这两个需求**从原理上就实现不了**。typora_plugin 本质是一个前端项目，Typora 并不支持插件功能。实际做法是通过各种绿皮手段（包括但不限于劫持、装饰、覆盖）强行实现功能。直接从 windows 打开 md 文件，合并窗口都是直接和后端交互，绕开了 typora_plugin。要想实现这两个功能，要么等待 Typora 官方支持，或者 Typora 官方提供插件系统。
3. 我过几天研究一下怎么在现有的窗口里打开不同目录的文件。实现类似于 vscode 的在同一个窗口打开不同目录 的功能。



![Snipaste_2023-07-25_11-39-43](https://github.com/obgnail/typora_plugin/assets/48992887/fdb804fb-7c30-4f23-ba59-73a3b7fc9f19)

**Comment by obgnail** [comment]
当然，我前面说的第二点，是针对高版本的 Typora。
对于低版本的 Typora，确实可以通过入侵劫持后端对象的方式实现这两个功能。

我暂时不会考虑这么实现，原因：
1. 局限性太大。仅限低版本（高版本修复了劫持后端对象的漏洞）
2. 影响面太大。需要修改 Typora 本身的 js 文件。
3. 不稳定。因为要修改自带的 js 文件，导致每当更新 Typora，此脚本都有可能会失效。

**Comment by heavenkiller2018** [comment]
多tab, 多关键词搜索的需求用户呼声这么高，typro是怎么能做到熟视无睹的呢? 真搞不懂当家人咋想的🤣🤣🤣

**Comment by obgnail** [comment]
@heavenkiller2018 

我把 INCLUDE_FILE_PATH 选项移动到 UI 层面了，有兴趣可以试试

![Snipaste_2023-07-30_15-01-59](https://github.com/obgnail/typora_plugin/assets/48992887/425e146b-e4b4-4546-972a-d53647667bea)
