### ISSUE TITLE
看到了个不错的浏览器插件  Markdown Web Clipper

### ISSUE THREAD

**Issue by carve-myself** [obgnail/typora_plugin#261]
是个挺不错的功能亮点，不知能不能集成到typora中，文章转markdown

https://chrome.google.com/webstore/detail/markdownload-markdown-web/pcmpcfapbekmbjjkdalcgopdkipoggdi

https://github.com/deathau/markdownload

**Comment by obgnail** [comment]
@carve-myself 

Typora 本身就支持这个功能呀。

鼠标拖选网页内容，ctrl+c，之后就在 Typora ctrl+v 就可以自动将网页转为 markdown 了。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦另开一个。
