### ISSUE TITLE
一个可行性讨论的想法[图片上传及回显]

### ISSUE THREAD

**Issue by pro911** [obgnail/typora_plugin#263]
需求: 图片上传及回显

描述: 
1. 想实现一个利用github作为图床的typora插件, 期望增加对github私有仓库的使用, 就是我只想上传到我的私有仓库,我只需要我的typora可以通过秘钥进行图片的回显. 上传应该是可以的,不知道回显能否可行.

**Comment by obgnail** [comment]
@pro911 

大伙都是怎么使用 github 作图床的呀？

要想及时回显，就必须上传，上传一张就 commit、push 一次？

**Comment by pro911** [comment]
目前用的`PicGO` 是上传一次push一次,但是私密性的图片,比如公司内部截图,需要将仓库设置成私有仓库,目前也可以push,但是无法实现在typora上回显, 想着是否可以配置自己的秘钥来实现图片的回显.

**Comment by obgnail** [comment]
@pro911 

鉴于大伙都有这个需求，我整了个新 repo：[typora_image_uploader](https://github.com/obgnail/typora_image_uploader)

目前仅支持公开的仓库。私密仓库我再研究一下。

后续图片上传相关功能都会在新仓库更新。

此 issue 关闭，后续处理请移步新仓库。
