### ISSUE TITLE
请问之后会出MacOS版吗？

### ISSUE THREAD

**Issue by zvm23** [obgnail/typora_plugin#273]
看到插件的功能真的挺全的～ 不知道之后会不会出MacOS版～

**Comment by obgnail** [comment]
@zvm23 

感谢反馈。我也想呀，不过我没有 Mac 😢

**Comment by zvm23** [comment]
> @zvm23
> 
> 感谢反馈。我也想呀，不过我没有 Mac 😢

好吧～ 希望以后能有机会看到吧～🥲
