### ISSUE TITLE
右键菜单自定义列表显示问题

### ISSUE THREAD

**Issue by mlhiter** [obgnail/typora_plugin#275]
![image](https://github.com/obgnail/typora_plugin/assets/100181513/470b843c-6a1b-4c4d-af48-8df636839312)
![image](https://github.com/obgnail/typora_plugin/assets/100181513/38b6894a-2512-4460-be0a-70713afc4dd1)

问题：如图，可以见得我自定义的命令列表会覆盖默认的命令列表的前三个，但是我想要的不是覆盖，而是删除所有默认的命令，只显示我自定义的命令列表

产生同样问题的还有【【自定义右键菜单】】
![image](https://github.com/obgnail/typora_plugin/assets/100181513/91ed876e-9e6a-40cc-a72c-923384eecfb1)
![image](https://github.com/obgnail/typora_plugin/assets/100181513/4176fe28-3e94-41a2-b171-6c227f72e7c4)

问题：依然是覆盖问题，我希望的是不需要显示默认的菜单内容，只留下我自定义的（因为显示太多了，非常不简洁）

目前我的解决方式就是修改setting.default.toml，但是每次更新都要修改一遍，很难受。

请问开发者大大可以修复一下嘛。

**Comment by obgnail** [comment]
@mlhiter 

fixed。代码在 [dev](https://github.com/obgnail/typora_plugin/commit/cd2c18dd5e846d394fb39a0e900cd5c651248643#diff-86c8ee8b9c010478e51b48e0307670ff1bc9fe83d016a31982eb4ee09a66c406)，晚上发版。

我原意是尽量保留 default.toml 的影响，竟然用户不喜欢，就改了吧（其实就改了一行代码）

> 另外，我看你的 user.toml 把 FIND_LOST_PLUGIN 置为 false，且【插件回收站】的 LIST 为空。既然如此，可以干脆删掉这个一级菜单了，仅保留【我的插件】，这样能更简洁一些。

![Snipaste_2023-10-22_12-45-11](https://github.com/obgnail/typora_plugin/assets/48992887/78df3e8d-ebbe-4a77-818e-afee90090bb6)

**Comment by mlhiter** [comment]
非常感谢，这个插件系统真心感觉用的很开心。（我这个懒狗原本是想试着完善一下的，但是看到了大大的项目感觉已经基本满足我需求了😍）
-----
关于你说的删除插件回收站这个菜单，刚发完issue我就发现了这个问题哈哈。

**Comment by R3c0ger** [comment]
前一阵子刚想提这个问题的，但是没来及（笑）

**Comment by obgnail** [comment]
@R3c0ger 有问题的话可以反馈呀，不过我这边比较忙，不保证能挤出时间处理就是了 :)
