### ISSUE TITLE
文件打开滑动全选

### ISSUE THREAD

**Issue by Kingwxl33** [obgnail/typora_plugin#277]
请问为什么某些md文件在打开时，鼠标滚轮稍微滑动就会将文件内容全部选中

**Comment by obgnail** [comment]
@Kingwxl33 

你好，感谢反馈。

我这边没有复现，也是第一次收到这种反馈，麻烦详细说明一下：
1. Typora 的版本
2. 是切换标签页的时候，还是打开 Typora 的时候？
3. 打开的是不是大文件？
4. 最好能说明一下复现步骤

**Comment by Kingwxl33** [comment]
你好

**Comment by Kingwxl33** [comment]
> @Kingwxl33
> 
> 你好，感谢反馈。
> 
> 我这边没有复现，也是第一次收到这种反馈，麻烦详细说明一下：
> 
> 1. Typora 的版本
> 2. 是切换标签页的时候，还是打开 Typora 的时候？
> 3. 打开的是不是大文件？
> 4. 最好能说明一下复现步骤



> @Kingwxl33
> 
> 你好，感谢反馈。
> 
> 我这边没有复现，也是第一次收到这种反馈，麻烦详细说明一下：
> 
> 1. Typora 的版本
> 2. 是切换标签页的时候，还是打开 Typora 的时候？
> 3. 打开的是不是大文件？
> 4. 最好能说明一下复现步骤

**Comment by Kingwxl33** [comment]
你好，版本为1.7.6。并不是切换标签页，是在资源管理器内直接点击md文件打开 Typora 的时候，还有Ctrl + O打开md文件时，鼠标滚轮稍微滑动就会将文件内容全部选中。文件并不大，最大的也仅仅20KB，里面插入的图片链接有几十个。
![截图](https://github.com/obgnail/typora_plugin/assets/125673931/8bdc8e66-acc4-4b3d-a0f6-4d6984818ac9)

**Comment by Kingwxl33** [comment]
> @Kingwxl33
> 
> 你好，感谢反馈。
> 
> 我这边没有复现，也是第一次收到这种反馈，麻烦详细说明一下：
> 
> 1. Typora 的版本
> 2. 是切换标签页的时候，还是打开 Typora 的时候？
> 3. 打开的是不是大文件？
> 4. 最好能说明一下复现步骤

你好，版本为1.7.6。并不是切换标签页，是在资源管理器内直接点击md文件打开 Typora 的时候，还有 Ctrl + O打开md文件时，鼠标滚轮稍微滑动就会将文件内容全部选中。文件并不大，最大的也仅仅20KB，里面插入的图片链接有几十个。
![截图](https://github.com/obgnail/typora_plugin/assets/125673931/bf14bb76-e7e2-4546-a909-fa7c2a884a61)

**Comment by obgnail** [comment]
@Kingwxl33 

你好，新版本已经修复，麻烦试用看看。

此单暂时关闭，如还有问题，麻烦在下面留言或者另开 issue。
