### ISSUE TITLE
【建议】是否有办法执行python或javascript脚本？

### ISSUE THREAD

**Issue by BrazilAmando** [obgnail/typora_plugin#289]
如果能在typora中书写代码，并且还可以执行代码，那就太酷了！最简单的，可以当个计算器用，不用离开typora另外计算了。

**Comment by Icarus-Alpha** [comment]
> 如果能在typora中书写代码，并且还可以执行代码，那就太酷了！最简单的，可以当个计算器用，不用离开typora另外计算了。

你是否再找 jupyter notebook？

**Comment by xiaogithubooo** [comment]
> 如果能在typora中书写代码，并且还可以执行代码，那就太酷了！最简单的，可以当个计算器用，不用离开typora另外计算了。

那样功能就太杂了...直接从编辑器变成编译器，不现实，转 `VSCode` 得了

**Comment by obgnail** [comment]
@BrazilAmando 

您好，感谢反馈。考虑了很久，决定还是暂时不实现此需求了，抱歉。原因如下：

1. Typora 的编辑能力很弱
2. Typora 不具备补全能力
3. 在文件中执行脚本，有一定的危险性

此 issue 关闭，如有其他问题，麻烦另开 issue。
