### ISSUE TITLE
我把自动编号改成false，每次更新还是会打开有办法改掉吗

### ISSUE THREAD

**Issue by ewfubwefwe** [obgnail/typora_plugin#295]
我把自动编号改成false，每次更新还是会打
![image](https://github.com/obgnail/typora_plugin/assets/91933542/63634201-afd1-4d02-9683-ed4864dc2fa1)
开有办法改掉吗

**Comment by obgnail** [comment]
@ewfubwefwe

你好。不能修改 settings.default.toml 文件。要修改 settings.user.toml 文件。

请阅读同目录下的【请读我.md】文件。


![Snipaste_2023-11-10_11-23-19](https://github.com/obgnail/typora_plugin/assets/48992887/8e5817db-44fa-4e3a-ab6c-492831f3768a)

![Snipaste_2023-11-10_11-28-12](https://github.com/obgnail/typora_plugin/assets/48992887/e19b45a9-c94f-4fdc-8025-9de4bad47cba)

**Comment by ewfubwefwe** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/91933542/afc31e8f-d157-4d2c-be8f-56614f400ac6)
这样就可以了把

**Comment by obgnail** [comment]
@ewfubwefwe 

是的。这样就永久关闭此插件了。你可以重启 Typora 验证一下。

**Comment by obgnail** [comment]
@ewfubwefwe 

此 issue 关闭，如有问题麻烦继续提问，或者另开 issue。
