### ISSUE TITLE
打开的文件过多时，我需要一个一个关，能增加一个一键关闭其他的按钮吗？

### ISSUE THREAD

**Issue by kakapreter** [obgnail/typora_plugin#296]

**Comment by obgnail** [comment]
@kakapreter 你好，感谢反馈

类似于 idea 这种？

![Snipaste_2023-11-11_15-02-30](https://github.com/obgnail/typora_plugin/assets/48992887/4873bcaa-902a-46cd-832b-d76d9b0aa497)

**Comment by kakapreter** [comment]
是

**Comment by kakapreter** [comment]
不过这个必须保留一个页面，不然就直接关闭了

**Comment by obgnail** [comment]
@kakapreter 

新版本已经添加了此功能，麻烦更新验证一下。

> 更新插件方式： 右键菜单 -> 常用插件 -> 自定义插件 -> 升级插件

默认添加的右键菜单如下，可以前往配置自定义：

```toml
# 在标签处，点击鼠标右键，弹出的右键菜单（若置为[]，则不使用此功能）
#   - closeOtherTabs:  删除其他标签
#   - closeLeftTabs:   删除左侧全部标签
#   - closeRightTabs:  删除右侧全部标签
#   - closeTab:        关闭标签
#   - copyPath:        复制文件路径
#   - showInFinder:    打开文件位置
#   - openInNewWindow: 新窗口打开
CONTEXT_MENU = ["closeTab", "closeOtherTabs", "closeLeftTabs", "closeRightTabs", "copyPath", "showInFinder", "openInNewWindow"]
```

![Snipaste_2023-11-12_00-31-31](https://github.com/obgnail/typora_plugin/assets/48992887/dcc9ec8b-d9e8-458e-8764-5bcdfcd644fd)

**Comment by kakapreter** [comment]
感谢楼主
