### ISSUE TITLE
【bug？】有时候看不到代码折叠按钮

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#297]
我设定了默认代码块折叠，出现了一些代码折叠了，但是无法展开的现象
![微信图片_20231111154013](https://github.com/obgnail/typora_plugin/assets/113878415/f54dd560-0d3e-47d9-a3cc-93e6852684f7)

**Comment by obgnail** [comment]
@xiaogithubooo 你好，感谢反馈。

算是 feather 吧，【总是折叠】功能并不会折叠 diagram。因为我也不知道图形该怎么折叠。

**Comment by obgnail** [comment]
实际上，图形的代码块并不会启用【fence_enhance】功能，原因：
一来会有遮挡，二来也没啥用，折叠代码总不能把图形也折叠/隐藏了吧。

**Comment by obgnail** [comment]
@xiaogithubooo 

额，我刚刚试了一下，是我理解错你的意思了。

确实是 BUG，我看看怎么修复

**Comment by xiaogithubooo** [comment]
但有时候对生成的思维导图不满意，需要做微调的时候有点难受😖，只能在一个文本行内用上下键挪动文本行来修改...

**Comment by obgnail** [comment]
@xiaogithubooo 

已修复。晚上发版，你可以等明天更新插件。

> 更新插件方式： 右键菜单 -> 常用插件 -> 自定义插件 -> 升级插件

**Comment by xiaogithubooo** [comment]
万分感谢！

**Comment by obgnail** [comment]
@xiaogithubooo 

新版本已经上线，麻烦测试一下。

**Comment by xiaogithubooo** [comment]
已经更新，感觉很好！
