### ISSUE TITLE
[小白]这种该如何更新呢

### ISSUE THREAD

**Issue by Arsiendle** [obgnail/typora_plugin#301]

**Comment by obgnail** [comment]
@Arsiendle 你好。

> 在正文区域鼠标右键，常用插件 -> 自定义插件 -> 升级插件

![Snipaste_2023-11-16_11-31-51](https://github.com/obgnail/typora_plugin/assets/48992887/12e6cd05-204d-431a-b52c-9b751b28fc5a)

之后会弹出对话框：

![Snipaste_2023-11-16_11-25-54](https://github.com/obgnail/typora_plugin/assets/48992887/4525032e-ce08-4598-b638-d0ef59261e00)

如果有代理，填入代理。如果没有代理，或者你所在地区能直连 github，清空输入框，点击确定即可

![Snipaste_2023-11-16_11-29-52](https://github.com/obgnail/typora_plugin/assets/48992887/5edb7498-39f6-4f0d-9a83-d5da13cd0eb4)

**Comment by obgnail** [comment]
如有问题请在下面留言

**Comment by obgnail** [comment]
@Arsiendle 你好，感谢反馈。

这个 [issue](https://github.com/obgnail/typora_plugin/issues/240) 的问题和你是一样的。

如果你的代理没有问题的话，就是网络异常导致的。

解决方案：
1. 换个更靠谱的代理。
2. 等待一段时间后重试。

**Comment by obgnail** [comment]
看起来步骤是没有问题的。

如果你的代理没有问题，麻烦等几分钟/小时再试一下（具体时间看网络情况）
如果你所在地区能直连 github，也可以试试：清空对话框的输入框，点击确定

**Comment by obgnail** [comment]
relax，现在是用网高峰，我这边偶尔也会出现这种情况

**Comment by obgnail** [comment]
@Arsiendle 情况如何？可以了吗？

**Comment by obgnail** [comment]
@Arsiendle  趁我现在有点时间，要不咱再试试？每次都这样蛮辛苦的

**Comment by 596142041** [comment]
这升级之后能否查看当前的插件的版本

**Comment by obgnail** [comment]
@596142041 

升级后，在 ./plugin/updater/ 目录下（就是你安装插件用到的 updater.exe 那个目录）有一个 version.json 文件。

这个文件记录了当前插件的版本信息。

内容大概如下：
```json
{"tag_name":"1.7.5","name":"1.7.5","body":"1. feat：【custom】插件：为所有自定义插件添加 order 选项，支持用户自定义排序。\r\n2. feat：【right_click_menu】插件：新增 HIDE_OTHER_OPTIONS 选项：移除右键菜单中除了插件以外的选项。\r\n3. chg：优化代码结构，优化配置说明，修改插件的默认排序。","zipball_url":"https://api.github.com/repos/obgnail/typora_plugin/zipball/1.7.5"}
```

**Comment by obgnail** [comment]
@596142041 

1. 无任何反应，是指连弹窗都没有吗？
2. 您是 Linux 系统吗？
3. 您的 Typora 版本？
4. 如果可以，能麻烦看一下控制台输出吗？

第一步：打开偏好设置。 或者快捷键 Ctrl+(逗号)
第二步：在通用中找到高级设置下的 “开启调试模式”，勾选上。
第三步：回到页面，然后 shift+F12，或者右键 – 检查元素
第四步：选择第二个标签（Console 或者 控制台）
第五步：复现您的问题

**Comment by 596142041** [comment]
> @596142041
> 
> 1. 无任何反应，是指连弹窗都没有吗？
> 2. 您是 Linux 系统吗？
> 3. 您的 Typora 版本？
> 4. 如果可以，能麻烦看一下控制台输出吗？
> 
> 第一步：打开偏好设置。 或者快捷键 Ctrl+(逗号) 第二步：在通用中找到高级设置下的 “开启调试模式”，勾选上。 第三步：回到页面，然后 shift+F12，或者右键 – 检查元素 第四步：选择第二个标签（Console 或者 控制台） 第五步：复现您的问题

\Program Files\Typora\resources\plugin\custom\plugins\pluginUpdater.js:41 Uncaught (in promise) Error: EPERM: operation not permitted, rename 'C:\Program Files\Typora\resources\plugin\updater\updater.exe' -> 'C:\Program Files\Typora\resources\plugin\updater\updater.exe'

**Comment by 596142041** [comment]
> @596142041
> 
> 你好，感谢反馈。
> 
> 由于 windows 的设计，放在 C:\Program Files 下的 exe 需要管理员权限才能执行。
> 
> 解决方案：手动执行命令。
> 
> 以管理员身份打开 cmd，输入以下命令：
> 
> ```
> C:
> cd "C:\Program Files\Typora\resources\plugin\updater"
> updater.exe --action=update --proxy=http://127.0.0.1:7890
> ```
> 
> proxy 改为你使用的代理
> 
> 因为是手动执行，后续的收尾也需要手动执行：
> 
> 执行成功后，updater 目录下会同时存在 updater1.7.6.exe 和 updater.exe：
> 
> 1. 删除 updater.exe
> 2. 将 updater1.7.6.exe 改名为 updater.exe

重新安装到其它的盘就可以了，谢谢！

**Comment by obgnail** [comment]
网络问题和磁盘问题已经脱离的插件的控制，此 issue 关闭，若还有问题，麻烦另开 issue。
