### ISSUE TITLE
自动编号的标题导出到Word中没有编号

### ISSUE THREAD

**Issue by styw1234** [obgnail/typora_plugin#302]
大佬，在Typora中自动编号的标题导出到Word中没有编号，这是怎么回事？怎么设置能够在导出的Word中有自动编号的标题
[20231117 0850 买鱼.docx](https://github.com/obgnail/typora_plugin/files/13385729/20231117.0850.docx)
[20231117 0850 买鱼.txt](https://github.com/obgnail/typora_plugin/files/13385730/20231117.0850.txt)

**Comment by obgnail** [comment]
@styw1234 你好，感谢反馈。

如果你仔细查看导出菜单，你会发现，`图像` 和 `Word(.docx)` 之间有一个横线。这代表了他们分属于两个不同的逻辑：
- 前者使用 内置代码 导出
- 后者使用通用的 pandoc 导出

**而我做的，只是修改了前者的逻辑。** 所以，导出为 Word 自然没有自动编号。

![Snipaste_2023-11-17_18-07-46](https://github.com/obgnail/typora_plugin/assets/48992887/5c6865ff-d9bd-4d6b-a103-7ecb2a40ccd2)

---

但是，这并不意味这不可以实现你的需求，但是需要你**学习 pandoc 如何使用**。

给一个最简单的配置，如下图，在自定义参数里加入 `--number-sections`，就可以实现自动编号了。

![Snipaste_2023-11-17_18-12-58](https://github.com/obgnail/typora_plugin/assets/48992887/5591ea21-63f6-4277-a916-a5760026392b)

但是这个方案有一个比较大的问题，它是从一级标题开始算起的，而我的插件是从第二级标题开始算起的。

---

我对 pandoc 也不熟，所以我帮你问了 gpt

![Snipaste_2023-11-17_18-28-08](https://github.com/obgnail/typora_plugin/assets/48992887/cffa837b-f029-46d1-9d7a-3a7ae3d24d72)

**Comment by obgnail** [comment]
参考:

- Typora 官方教程： https://support.typora.io/Export/#style-reference
- https://github.com/jgm/pandoc/issues/5071
- https://github.com/jgm/pandoc/issues/1413
- https://github.com/krissen/pandoc-extra/blob/master/templates/numbered-sections.docx

**Comment by obgnail** [comment]
@styw1234 

我看了一下你的文件，貌似你有使用一级标题的习惯，这样的话，在自定义参数里加入 --number-sections，就可以实现自动编号了。

![Snipaste_2023-11-17_18-12-58](https://github.com/obgnail/typora_plugin/assets/48992887/baebe2c6-eef6-4d47-938a-b24bfdb38f92)

**Comment by obgnail** [comment]
@styw1234 

已经给出解决方案，暂时关闭 issue。如有问题，麻烦另开 issue。
