### ISSUE TITLE
[功能建议]图片转base64

### ISSUE THREAD

**Issue by pengxiandyou** [obgnail/typora_plugin#311]
1. 在图片上右键，显示转base64，点击转换；
2. 空白处右键，显示全部图片转base64，点击转换。

原因：有时候不想在本地保存图片，又不想上传图床。
如果能添加，万分感谢。

**Comment by obgnail** [comment]
@pengxiandyou 你好，感谢反馈。

**这个功能确实是可以实现的。但是没有太大意义**。

因为 Typora 仅支持打开小于 2000000 byte (≈2M) 的文件。如果把图片塞入 md 文件，但凡多塞两张图片，就不能打开了。

![Snipaste_2023-11-23_20-34-55](https://github.com/obgnail/typora_plugin/assets/48992887/28e313f1-9b92-42bf-ae58-e0ddf212f1fa)

有个平台方案，使用【export_enhance】插件导出为 html，然后使用浏览器查看。

> 此插件的功能是：导出 html/pdf/png 时，将图片转为 base64（如果开启 DOWNLOAD_NETWORK_IMAGE 选项，还能自动下载网络图片并转为 base64）

**Comment by obgnail** [comment]
此 issue 关闭，如有疑问或其他问题，麻烦在下面回复或另开 issue。

**Comment by KellyEscobar** [comment]
插入的图片如果是 Webp 格式，base64 编码大小几十 KB 就足够。
所以，几十个图片占用也仅几百 KB，对于大量文档来説，几十个图片通常都是够用了。
尤其是关于一些 Readme 文档，需要的图片并不多，但是如果外挂图片和目录，对于管理来説，就增加了很多难度。
非常希望作者能增加这个功能。

**Comment by realSilasYang** [comment]
手动修改 Typora 的配置文件突破打开文件大小的限制：

1. 找到 Typora 安装目录下的 resources/appsrc/window/frame.js。
2. 搜索 MAX_FILE_SIZE: 2e6,。
3. 改成更大的值，比如 3e6（≈3 MB）或 5e6（≈5 MB）。
4. 保存并重启 Typora。

⚠️ 注意：文件越大，渲染性能会急剧下降，可能出现卡顿、内存占用过高等问题。

**Comment by realSilasYang** [comment]
> 插入的图片如果是 Webp 格式，base64 编码大小几十 KB 就足够。 所以，几十个图片占用也仅几百 KB，对于大量文档来説，几十个图片通常都是够用了。 尤其是关于一些 Readme 文档，需要的图片并不多，但是如果外挂图片和目录，对于管理来説，就增加了很多难度。 非常希望作者能增加这个功能。

同意。
如果担心影响文件大小或者性能，默认不启用此功能就好。
非常希望您能提供一个选项给有需要的同学。

**Comment by obgnail** [comment]
@pengxiandyou @KellyEscobar  @realSilasYang

我没想到有这么多人希望添加此功能。

需求已实现，代码在 master 分支中，等待周日发版。具体 commit 信息见上文。

---

插件【编辑工具】新增了两个功能【图片转 Base64 编码】【全部图片转 Base64 编码】

> 注意使用【图片转 Base64 编码】前，需要将鼠标定位到需要转化的图片上

- 鼠标定位到某个图片 -> 右键菜单 -> 常用插件 -> 编辑工具 -> 图片转 Base64 编码
- 右键菜单 -> 常用插件 -> 编辑工具 -> 全部图片转 Base64 编码

> 如果真的非常常用，你也可以为上述两个功能设置快捷键。

**Comment by realSilasYang** [comment]
> 我没想到有这么多人希望添加此功能。

因为图片另存到一个文件夹实在是太不优雅了😂

**Comment by obgnail** [comment]
@realSilasYang 

我认为 Base64 写入 md 是反人类的 😂

**Comment by obgnail** [comment]
BTW，我偷懒了，我没有去检测文件大小，不会阻止转化超大图片，也没有显式提出警告，风险全让用户自担了。

**Comment by realSilasYang** [comment]
> BTW，我偷懒了，我没有去检测文件大小，不会阻止转化超大图片，也没有显式提出警告，风险全让用户自担了。

那可不行🤯

**Comment by realSilasYang** [comment]
可不可以给一个这样的默认设置：粘贴到md文件的图片自动转webp，并转base64

**Comment by obgnail** [comment]
@realSilasYang 

功能是可以实现的。而且有两种方法。

## 方法一：使用 Typora Plugin 实现

幸运的是，Typora 自带图像处理库 JIMP。

https://github.com/obgnail/typora_plugin/blob/72282caf0817599abe391c890ebc044ac5ceeb68/plugin/global/core/utils/index.js#L112-L114

不幸的是 JIMP 默认不支持 webp 格式，需要引入三方库 [@jimp/wasm-webp](https://www.npmjs.com/package/@jimp/wasm-webp)

> 还有一个曲线救国方案： chromium 的 canvas 是支持导出为 webp 的。可以将 img 转为 canvas，再导出为 webp。考虑到使用 webp 一般是为了图片体积，这种方式生成的图片普遍偏大。

我很看重项目的性能和体积，因此我极力避免引入三方库，由于上述库是用 wasm 写的，体积有点大，而且本项目代码体积已经超过 10M 了，我应该不会实现此功能，抱歉。

> Typora Plugin 是支持用户自己写插件的，有兴趣自己实现的话可以参考 [readme](https://github.com/obgnail/typora_plugin/tree/master/plugin/custom)。有问题可以问，我帮忙回答。

核心代码类似于：

```js
import fs from 'fs/promises';
import { createJimp } from '@jimp/core';
import { defaultFormats, defaultPlugins } from 'jimp';
import webp from '@jimp/wasm-webp';

const Jimp = createJimp({
  formats: [...defaultFormats, webp],
  plugins: defaultPlugins,
});

async function getWebpBase64() {
  try {
    const image = await Jimp.read('input.jpg');
    const encoderOptions = { quality: 95 };
    const base64String = await image.getBase64Async('image/webp', encoderOptions);
    console.log('WebP Base64 编码:', base64String);
  } catch (error) {
    console.error('获取 Base64 编码时出错:', error);
  }
}
```

## 方法二：使用 Typora 官方的图像上传服务

这个实现就更简单了，我曾经写了一个 Typora 图片上传到 Github 作为图床的插件。只要将返回的 url 改成 base64 即可。使用 Node.js 实现的话上面代码简单改改就能用了， 20 行代码解决。

你可以参考一下：https://github.com/obgnail/typora_image_uploader

**Comment by realSilasYang** [comment]
感谢您用心详细回复！

**Comment by obgnail** [comment]
@realSilasYang 

我后面想了一下，使用 Canvas 或许是一个不错的方案。

Canvas 是 Chrome 背后的 C++ 引擎实现的，比起使用 JIMP 这种 Javascript 运行时应该效率还要更高。并且使用 Canvas 的话就无需导入库了。

**Comment by realSilasYang** [comment]
> [@realSilasYang](https://github.com/realSilasYang)
> 
> 我后面想了一下，使用 Canvas 或许是一个不错的方案。
> 
> Canvas 是 Chrome 背后的 C++ 引擎实现的，比起使用 JIMP 这种 Javascript 运行时应该效率还要更高。并且使用 Canvas 的话就无需导入库了。

那您现在会考虑实现了吗😙
