### ISSUE TITLE
关于文件大纲和目录大纲同时展示

### ISSUE THREAD

**Issue by YZZ321** [obgnail/typora_plugin#318]
有可以同时显示文件树和目录大纲的插件吗

**Comment by obgnail** [comment]
@YZZ321 你好，感谢反馈。

如果是树状的目录大纲，确实没有，需要开发。

如果可以接受思维导图形式的目录大纲，可以使用 `markmap` 插件，它可以以 弹窗、顶部、右侧 三种位置 显示目录大纲。

**Comment by obgnail** [comment]
@YZZ321 

如果是树状的目录大纲，那么您希望在哪个位置显示呢？比如说，弹窗、正文区域左侧 等等，我参考一下您的意见。

**Comment by YZZ321** [comment]
![WechatIMG12](https://github.com/obgnail/typora_plugin/assets/31879090/047f0c31-7cea-4cfc-9f7e-591ce145f5bb)
类似这样的

**Comment by YZZ321** [comment]
是一直显示的，不是弹窗，有个按钮，可以控制显示或者隐藏

**Comment by obgnail** [comment]
进度报告：新版本插件系统 新增了【toc】插件，实现了基本功能，但是尚未仔细打磨，暂时默认关闭。

**Comment by obgnail** [comment]
@YZZ321 

摸了几个月的鱼，今天终于下定决心做了 😂

新版本已经发布。麻烦升级到最新版本试用一下。

---

使用方法：
- 方式一：常用插件 -> 自定义插件 -> 大纲目录
- 方式二：右键点击侧边栏的【大纲】按钮

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
