### ISSUE TITLE
新版插件bug，打开笔记后在随机某一位置想输入，输入线会跳一下然后就没了

### ISSUE THREAD

**Issue by jingcaiwenshuai** [obgnail/typora_plugin#319]
我今天下午遇到的一个问题，打开笔记想在非尾部输入内容，点了之后输入线只跳一下，然后就没了，那么输入不了；删除插件后，恢复了正常，我还同时用了一个主题，不知道是插件原因还是插件与主题共用原因

**Comment by jingcaiwenshuai** [comment]
谢谢作者的付出，插件真的帮助了很多，感谢！！！

**Comment by obgnail** [comment]
@jingcaiwenshuai 你好，感谢反馈。

1. 出现频率高吗？
2. 删除插件前有尝试重启 Typora 吗？若有，效果如何？
3. Typora 版本？
4. 你打开的笔记文件大吗？

**Comment by obgnail** [comment]
@jingcaiwenshuai 

会不会是你不小心开启了【只读模式】插件，或者不小心键入了只读模式的快捷键？

**Comment by chenchunlai** [comment]
您好，开发者

我也遇到了类似的问题，无法编辑之前键入的文字或者代码

复现方式：
编辑一段文件，按快捷键 ctrl+k 插入代码框，随便写一点东西在代码行里，然后继续写下面的段落。此时去修改前面代码框里的内容，发现修改不了，也看不到光标，但长按左键，可以输入一些东西。

Q:出现频率高吗？
A:高

Q:删除插件前有尝试重启 Typora 吗？若有，效果如何？
A:未尝试，但上一个版本是正常的

Q:Typora 版本？
A:1.7.6

Q:你打开的笔记文件大吗？
A:不大，我是新建了一个Markdown文件

Q:是否开启【只读模式】插件，或者键入只读模式的快捷键
A:否

**Comment by jingcaiwenshuai** [comment]
基本同上楼，谢谢作者大佬！
1. 出现频率高吗？
很高，无法正常使用的那种
2. 删除插件前有尝试重启 Typora 吗？若有，效果如何？
有尝试重启，仍然相同；但是我卸载重装typora后(没安装插件)可以正常使用，安装您的旧版本插件也可以正常使用，就是可能存在插件自动更新或者其他涉及更新的问题，出现了此bug
3. Typora 版本？
卸载重装前是一个付费破解了的版本，重新安装的是付费前的一款老版本
4. 你打开的笔记文件大吗？
不大，试了好几个笔记文件，都有相同问题

**Comment by obgnail** [comment]
@jingcaiwenshuai @chenchunlai 

您上一个可用版本是多少？1.6.16?

**Comment by jingcaiwenshuai** [comment]
我使用的typora_plugin-1.5.15这个版本，且一直没手动更新过，可能存在自动更新？

**Comment by jingcaiwenshuai** [comment]
我卸载重装typora后，用typora_plugin-1.5.15版本插件没问问题，然后我手动更新后出现了之前的问题，然后再次删除plugin文件夹重装typora_plugin-1.5.15版本后，问题消失。以上都是下午4点左右遇到且尝试的解决办法。谢谢作者！

**Comment by obgnail** [comment]
@jingcaiwenshuai @chenchunlai 

如果可以的话，麻烦能删除 plugin 文件夹，更换为 [1.6.16 版本](https://github.com/obgnail/typora_plugin/releases/tag/1.6.16) ，我想缩小一下范围。看是不是  1.6.16 的问题

**Comment by jingcaiwenshuai** [comment]
@obgnail 测试了几个文件，1.16版本没问题，然后手动更新脚本后，出现了相同问题，所以可能是1.17版本的问题，插件存在自动更新是吧

**Comment by obgnail** [comment]
@jingcaiwenshuai 你好，确实是有自动更新，不过就像 readme 里说的，任何功能都是可以关闭的。

> 如何设置请看：[A/plugin/global/settings/](https://github.com/obgnail/typora_plugin/tree/master/plugin/global/settings)

我猜测应该是下面两个文件导致的，麻烦升级到 17 版本，然后直接移动下面两个文件到任意其他目录，应该就正常了。
- plugin/collapse_paragraph.js
- plugin/markmap/index.js

**Comment by obgnail** [comment]
@chenchunlai @jingcaiwenshuai 

可以的话，能麻烦看一下控制台输出吗：
第一步：点击左上角【文件】，打开偏好设置。 或者快捷键 Ctrl+(逗号)
第二步：在通用中找到高级设置下的 “开启调试模式”，勾选上。
第三步：回到页面，然后 shift+F12，或者右键 – 检查元素
第四步：选择第二个标签（Console 或者 控制台）
第五步：复现您的问题

**Comment by jingcaiwenshuai** [comment]
问题作者已解决！能力强，效率高，感谢！！！

**Comment by obgnail** [comment]
@chenchunlai @jingcaiwenshuai 

修复版本已经发布，麻烦更新到最新版本。

**Comment by obgnail** [comment]
@jingcaiwenshuai 

最后跟您说一下，如果您怀疑是插件的问题，想要禁用全部插件，可以直接将 plugin 目录移动到其他任意位置。
其他插件同理，您怀疑是什么插件有问题，只要将这个文件(夹)移动位置即可，不会对 Typora 原本功能有任何影响。

（比如说，我刚刚怀疑是 collapse_paragraph 插件有问题，将其移动位置，就算是禁用插件了）

**Comment by jingcaiwenshuai** [comment]
@obgnail 谢谢作者，这个道理明白，我先考虑是不是软件的问题，没有考虑到插件上来，所以重新安装了软件发现没问题，所以才继续安装插件，安装好后更新插件发现了相同问题，就怀疑是最新版插件的问题。总之，感谢作者，很强！！！

**Comment by obgnail** [comment]
这个 bug 主要是我半夜打码，神志不清，粘贴了一行无关代码导致的。

另：每个插件都有配置，您可以修改配置文件，使之更符合您的需求。

**Comment by jingcaiwenshuai** [comment]
谢谢作者！
