### ISSUE TITLE
开启插件使用鼠标文本光标定位困难

### ISSUE THREAD

**Issue by idzyr** [obgnail/typora_plugin#321]
**未开启插件；**
![未开插件](https://github.com/obgnail/typora_plugin/assets/38239519/4abbd74b-8608-4e25-a18a-c0cf05665cf2)
**开启插件；**
![开启插件](https://github.com/obgnail/typora_plugin/assets/38239519/89008bef-b33e-4fe6-af83-5b33bc753368)
**平台信息；**
- typora_plugin：1.6.17
- Typora版本：1.7.6
- Typora主题：GitHub
- 操作系统：Windows10

**Comment by obgnail** [comment]
1.6.18 版本已紧急修复

**Comment by idzyr** [comment]
> 1.6.18 版本已紧急修复

已下，已解决，感谢

**Comment by obgnail** [comment]
关闭此 issue，如有其他问题，麻烦另开 issue。
