### ISSUE TITLE
建议增加Typora文本拖动功能

### ISSUE THREAD

**Issue by styw1234** [obgnail/typora_plugin#325]
Typora内选中文字，不支持拖动功能。

比如选择2个单词，要从最后一行改到第一行，只能剪切+粘贴，不支持鼠标直接拖动。

建议作者增加一个支持鼠标拖动选中的单词，可以实现剪切+粘贴功能。
按住Ctrl按键进行拖动，可以实现复制+粘贴的功能。

**Comment by obgnail** [comment]
@styw1234 

你好，感谢反馈。

我研究了一下，决定暂时不考虑实现此功能，抱歉 😬

原因如下：
1. 成本高：需要将全部的文本标签添加 draggable 属性，十分影响性能。
2. 实现难度较大：md 同时支持普通文字、html标签、latex代码、代码块、math等等特性，每个都要单独实现
3. 影响文字框选：选中文字然后拖动，太容易误触
4. 不太实用

如果有其他需求，麻烦另开 issue。
