### ISSUE TITLE
思维导图无法使用

### ISSUE THREAD

**Issue by tianyunfari** [obgnail/typora_plugin#339]
大佬的插件很nice，但是我的版本好像有点低

![image](https://github.com/obgnail/typora_plugin/assets/39123237/ee3bc362-cf5a-4d0e-9c9c-53becbfd1d0c)

typora 版本0.9.86

**Comment by obgnail** [comment]
@tianyunfari 你好，感谢反馈。

我手上没有这么低的版本，能帮忙测试一下吗？

报错位置是：header.attributes.pattern。应该是 低版本Typora 的 header.attributes 没有 pattern 属性导致的
```js
    getToc = () => {
        const toc = File.editor.nodeMap.toc;
        const headers = [];
        if (toc) {
            for (const header of toc["headers"]) {
                if (header && header["attributes"]) {
                    // error: 空指针异常
                    headers.push(header.attributes.pattern.replace("{0}", header.attributes.text));  
                }
            }
            return headers.join("\n")
        }
    }
```

你能帮忙在控制台打印一下下面语句吗？
1. 首先切换到带有标题的文件
2. 执行下面语句
```
File.editor.nodeMap.toc.headers[0].attributes
File.editor.nodeMap.toc.headers
```

**Comment by obgnail** [comment]
主要是想看一下旧版本的 header.attributes 有什么属性

**Comment by tianyunfari** [comment]
> 主要是想看一下旧版本的 header.attributes 有什么属性
> 
> 附带一下最近版本的 attributes： ![Snipaste_2023-12-09_11-57-39](https://private-user-images.githubusercontent.com/48992887/289232197-25f761bd-bc98-4df0-b91e-037a2f9fb775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTg5MDIsIm5iZiI6MTcwMjA5ODYwMiwicGF0aCI6Ii80ODk5Mjg4Ny8yODkyMzIxOTctMjVmNzYxYmQtYmM5OC00ZGYwLWI5MWUtMDM3YTJmOWZiNzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA1MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YzViMWEyMWRmNjhlMTQ3MTAzN2E3NmY4NjYyYzg4ZWNmZTgxZTkzNjE2MmVkODhiZjJiYjE5MjA4ZDJiOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MUIec_AB1mgaD9qxrH3_xGLbnV25OAcPZkv-SHSPktY)

attributes:
after: n {cid: "n94", attributes: {…}, id: "n94", changed: {…}, TYPE: {…}, …}
ahead: undefined
align: undefined
alignText: undefined
alt: undefined
attachTo: m {blocks: f, allNodes: f, foot_list: n, link_list: n, toc: n}
attr: undefined
before: undefined
broadcast: false
checked: undefined
children: f {_set: Array(0), _map: Map(0)}
depth: 2
displayStyle: undefined
header: undefined
height: undefined
href: undefined
id: "n47"
in: m {blocks: f, allNodes: f, foot_list: n, link_list: n, toc: n}
isFixed: undefined
lang: undefined
marginLeft: undefined
marginRight: undefined
markindent: undefined
mathEqLabel: undefined
mathLabel: undefined
pattern: "## {0}"
patternEnd: undefined
prespace: undefined
ref: undefined
start: undefined
style: undefined
subindent: undefined
tagAfter: undefined
tagBefore: undefined
tail: undefined
text: "中心理解题"
title: undefined
type: "heading"
userIndent: undefined
userText: undefined
width: undefined

**Comment by obgnail** [comment]
@tianyunfari 

你好，感谢反馈。

我尝试做了一版修复，代码在 dev 分支。明天晚上发版。届时我会在下面留言，麻烦留意一下。

**Comment by obgnail** [comment]
@tianyunfari 

你好，新版本已经发布，麻烦更新测试一下。

此 issue 暂时关闭，如还有问题，麻烦继续在下面留言，或者另开 issue。

**Comment by tianyunfari** [comment]
> @tianyunfari
> 
> 你好，新版本已经发布，麻烦更新测试一下。
> 
> 此 issue 暂时关闭，如还有问题，麻烦继续在下面留言，或者另开 issue。

![image](https://github.com/obgnail/typora_plugin/assets/39123237/f02a5b42-48fb-4e85-bc94-270be5f6ab51)
还是不行

**Comment by tianyunfari** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/39123237/ccc8a8a8-2380-4116-bc69-db09c1fea875)

**Comment by obgnail** [comment]
@tianyunfari 

收到。这次是其他问题导致的，抱歉。

低版本 Typora 内置的 Node.js 版本太低，不支持新的语法糖 `a?.b` 导致的。

---

报错函数是：
```js
    lazyLoad = async () => {
        if (this.transformer && this.Markmap) return;

        // error
        const {markmapLib} = this.utils.requireFilePath("./plugin/markmap/resource/markmap-lib.js");
   }
```

而 markmap-lib.js 是我使用 esbuild 打包的，我后面学习一下怎么让 esbuild 兼容低版本的 node.js。

**Comment by obgnail** [comment]
您可以尝试在 控制台输入
```js
a = {};
a?.b;
```
应该也会报同样的错误

**Comment by tianyunfari** [comment]
> 您可以尝试在 控制台输入
> 
> ```js
> a = {};
> a?.b;
> ```
> 
> 应该也会报同样的错误

是会报错，我升级下我的typora版本吧，感谢大佬提供的开源插件
