### ISSUE TITLE
一键全文格式化代码

### ISSUE THREAD

**Issue by ljacksonl** [obgnail/typora_plugin#340]
一键全文格式化代码，对于已经存在的代码块，同时希望一键支持处理代码块的语言设置。

**Comment by obgnail** [comment]
@ljacksonl 你好，感谢反馈。

这两个需求，各有各的难处。

## 一键支持处理代码块的语言设置

这个插件我曾经做过一版，但是效果很差。给出一段代码，推测代码的语言其实是很难的，目前存在太多语法相似甚至相同的语言，比如 typescript、javascript、coffeescript 三者的代码可能完全相同。

我也找过 github 上高星的项目，但是效果都不理想。

一个最简单的例子，强如 vscode，作为代码编辑软件，它在推测代码语言这点也是经常出错。

而且有个很大的问题就是：vscode 错了就错了，用户手动调整就行。但是这个插件需要货真价实的写入文件，就很麻烦。

实际上，这个需求同样出现在 Typora 官方的 [issue](https://github.com/typora/typora-issues/issues/3661) 上，挂了 3 年多同样没有任何进展。

## 一键全文格式化代码

这个需求有个问题：

很多 md 编辑器，比如 Typora、obsidian 使用 codemirror 作为代码块编辑器。格式化代码这个功能，也是借助 codemirror 实现的。

但是 codemirror 本身是比较吃资源的，所以 Typora 是惰性加载代码块。也就是说，如果一个文件非常巨大，Typora 并不会一次性加载所有的代码块。

也就是说，如果实现了这个需求，就会出现一个问题：需要一次性将全部的代码块都加载出来，如果这个文件很大，这可能会导致 Typora 在 N 秒内失去响应，并且短时间内存飙升。


## 总结
1. 需求【一键支持处理代码块的语言设置】，**在找出合适的解决方案之前，应该不会做**。
2. 需求【一键全文格式化代码】，**会做，但是需要您提前知道风险**，同时我也会给这个功能添加风险提醒。

**Comment by ljacksonl** [comment]
@obgnail 期待大佬一键全文格式化代码的功能。

关于一键支持处理代码块的语言设置的想法，其实我的意思是，
![image](https://github.com/obgnail/typora_plugin/assets/32628669/f9dbf203-e612-4867-af94-5a8b25524c9f)
当代码块中的语言为空时，可以将md文件中所有代码块设置为我想要的代码语言，比如说变成这样

**Comment by obgnail** [comment]
@ljacksonl 

你好，【一键全文格式化代码】功能已经上线，

添加配置如下
```toml
[fence_enhance]
# 在右键菜单中启用危险的功能
#   危险功能：此功能会消耗巨量资源并导致Typora长时间（几秒到几十秒）失去响应
ENABLE_DANGEROUS_FEATURES = false
```

由于此功能有风险，所以默认关闭，需要您手动开启 ENABLE_DANGEROUS_FEATURES  选项。具体如何修改，请参考 [请读我](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md)

![Snipaste_2023-12-10_16-35-34](https://github.com/obgnail/typora_plugin/assets/48992887/e023a2fe-0904-4fe4-8367-42c440cdaf92)

**Comment by obgnail** [comment]
此需求关闭，另一个需求请看 [关联issue](https://github.com/obgnail/typora_plugin/issues/342)

如有其他问题，麻烦继续在下面留言，或者另开 issue

**Comment by ljacksonl** [comment]
666，大佬牛逼，一键三连了

**Comment by obgnail** [comment]
@ljacksonl 

其实我只是批量调用 Typora 自带的功能而已，况且 Typora 自带的调整缩进的能力很弱鸡，不要抱太大期待

**Comment by ljacksonl** [comment]
@obgnail 刚试了下效果，确实有点弱鸡。

**Comment by obgnail** [comment]
@ljacksonl 

实际上，typora 实现的只是 indent 功能，而你要的是 format 功能。

其实你可以搜一下 codemirror 的 formatter 包，每个语言都有一个 1-2M 的插件包。Typora 可能是考虑到每个语言都来一份的话，太大了，不敢导入。

比如：https://codemirror.net/2/demo/formatting.html

**Comment by obgnail** [comment]
@ljacksonl 

这也是为什么 vscode 基本每个 language 都要手动下载 formatter、highlighter 的原因。一来硬盘、内存顶不住，二来整太多会变卡。
