### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by shitouuuuu** [obgnail/typora_plugin#351]
closed

**Comment by obgnail** [comment]
@shitouuuuu 

我给 window_tab 添加了一个配置 `RECONFIRM_WHEN_CLOES_LAST_TAB`，功能是：当关闭最后一个标签时，弹出弹窗确认是否退出 Typora。

代码在 [dev分支](https://github.com/obgnail/typora_plugin/commit/e98817a1ecfc93d6290d4316e4eec6feff535629)，预计今晚发版，你可以明天更新尝试一下。

> 升级插件步骤：常用插件 -> 自定义插件 -> 升级插件

**Comment by obgnail** [comment]
此 issue 关闭，如有其他问题，麻烦在下面留言，或者另开 issue。
