### ISSUE TITLE
在没有装插件的时候，在typora中如论是普通模式还是源代码模式，随意在任一一行插入新的东西都很方便，装上却不方便

### ISSUE THREAD

**Issue by Runnerxr** [obgnail/typora_plugin#356]
问大佬们一个问题：在没有装插件的时候，在typora中如论是普通模式还是源代码模式，随意在任一一行插入新的东西都很方便，装上却不方便？
1、没有装上这个插件的时候，两种模式下，在已经编辑好的文本中可以很轻松随意插入(很自由)
2、一旦装上这个插件，在普通模式下， **在中间很难写入新的东西**(光标会随意的跳动，除非我很刻意的在该处多双击几下，文章的末尾编辑不受影响，源代码模式下编辑也不受影响)
疑问：
1、能否在装上这个插件后(这个插件当然非常非常好用)，通过修改某些地方，仍然能保持在普通模式下在任意位置随意插入新的文本(或其他)？还是说在只要装上，只能在源代码模式下才能非常流畅的达到我说的目的
2、有极少部分的情况不受影响(是否是因为不稳定导致的，还是说因为是typora版本的原因导致的)

**Comment by obgnail** [comment]
@Runnerxr 您好，感谢反馈。

您指的是这种情况吗？
- https://github.com/obgnail/typora_plugin/issues/321
- https://github.com/obgnail/typora_plugin/issues/319

原因：

半夜打码，神志不清，错打了一行代码导致的。抱歉 😢

解决方案：

**升级到最新版本即可**。

**Comment by obgnail** [comment]
升级方法：

方法一（自动）：
右键菜单 -> 常用插件 -> 自定义插件 -> 升级插件

方法二（手动）：
到[此处](https://github.com/obgnail/typora_plugin/releases/latest)下载新版本，然后替换 plugin 目录

**Comment by obgnail** [comment]
@Runnerxr 如果有疑问或问题，麻烦在下面留言

**Comment by Runnerxr** [comment]
好滴！！

**Comment by obgnail** [comment]
@Runnerxr 

你好，请问问题解决了吗？

**Comment by Runnerxr** [comment]
昨天看到回复，更新之后当场就解决了~~~

**Comment by obgnail** [comment]
@Runnerxr 好的，感谢反馈。

此 issue 关闭，如有其他问题，麻烦另开 issue
