### ISSUE TITLE
希望增加对五线谱的支持

### ISSUE THREAD

**Issue by ntsw2001** [obgnail/typora_plugin#357]
如题，五线谱的 js 库：[abcjs](https://www.abcjs.net/)；类似 echarts、mermaid 一样，在代码块区域编写。

**Comment by obgnail** [comment]
@ntsw2001 

没有艺术细菌，完全不懂五线谱，简单做了一版，你看下行不？

## typora 编辑
![Snipaste_2023-12-19_21-36-21](https://github.com/obgnail/typora_plugin/assets/48992887/2ed22c7e-fe4f-4486-bf43-1a21f5c383c2)

## 导出为 HTML
![Snipaste_2023-12-19_21-38-05](https://github.com/obgnail/typora_plugin/assets/48992887/91060ca6-c0a5-464b-a9e6-ddca15071090)

**Comment by ntsw2001** [comment]
可以可以，感谢大佬，跑通官方的 demo 就算成功。

**Comment by obgnail** [comment]
@ntsw2001 

你好，需求已经实现，新版本已经发布。麻烦升级插件试用看看

![Snipaste_2023-12-20_00-45-55](https://github.com/obgnail/typora_plugin/assets/48992887/2474df89-e4db-4303-8971-8a637266fa70)

**Comment by ntsw2001** [comment]
目前没测出什么问题，再次感谢！

**Comment by obgnail** [comment]
好的，此 issue 关闭，如有bug或其他问题，麻烦另开issue。
