### ISSUE TITLE
ctrl + p 在新tab中开启

### ISSUE THREAD

**Issue by hwy1782** [obgnail/typora_plugin#360]
ctrl + p 快捷键支持快速打开一个新的文档，默认是在新的widows窗口中打开，请问是否能够支持在新的tab页面中打开

**Comment by obgnail** [comment]
@hwy1782 

你好，感谢反馈。

已修复。

代码在 dev 中，后续发版的时候，会在下面留言通知您，请注意查收。

需要注意的是，**只有当 待打开的文档 挂载在当前目录的时候，才能在新的 tab 页面中打开**。

比如，当前 Typora 打开的路径为 A/B/C，如果待打开的文档的路径是 A/B/C/D，可以在新的 Tab 打开。如果路径是 A/E/F，还是会在新的窗口打开。

> 这就像很多代码编辑器（如 idea），不属于本项目的文件，必须要新开窗口

**Comment by obgnail** [comment]
@hwy1782 

你好，新版本已经发布，麻烦更新试用看看。

> 更新插件：右键菜单 -> 常用插件 -> 自定义插件 -> 升级插件。

**Comment by obgnail** [comment]
@hwy1782 

此 issue 已经修复，暂时关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by hwy1782** [comment]
已经验证通过了，感谢
