### ISSUE TITLE
【Bug】中英文混排优化会扰乱代码块格式

### ISSUE THREAD

**Issue by cjcchester** [obgnail/typora_plugin#363]
如题所述，
原来的效果是
![image](https://github.com/obgnail/typora_plugin/assets/87079803/201acab9-b16b-46e1-ac94-512290651787)
点击中英文混排优化后的效果是
![image](https://github.com/obgnail/typora_plugin/assets/87079803/d65f6690-18f2-4cee-b8c7-a748e5351c57)
去掉上面三行注释也是同样的效果。
希望大佬优化，十分感谢！

**Comment by obgnail** [comment]
@cjcchester 

你好，感谢反馈，已修复。

代码在 dev 分支，预计今晚发版，届时我会在下面留言，请注意查收。

**Comment by obgnail** [comment]
复现文本：
````markdown
---
test: 1
---

```javascript
console.log(1)
```
````

**Comment by obgnail** [comment]
@cjcchester 你好，新版本已经发布，麻烦试用看看。

此 issue 暂时关闭，如有问题，麻烦在下面留言或者另开 issue。
