### ISSUE TITLE
文字风格化 功能问题

### ISSUE THREAD

**Issue by SiaYung** [obgnail/typora_plugin#367]
选中多行内容进行风格化编辑后，内容缺失，仅显示最后一行。
![231226 110139](https://github.com/obgnail/typora_plugin/assets/11502551/706bdcc2-e635-4e4b-8271-4a4cfdd67771)

**Comment by obgnail** [comment]
@SiaYung 

你好，感谢反馈。

新版本已经修复多行设置样式导致内容丢失问题。麻烦升级一下插件试用看看。

升级插件流程：右键菜单 - 常用插件 - 自定义插件 - 升级插件

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
