### ISSUE TITLE
kanban任务展示问题

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#371]
### 问题
1. 任务条数过多，看板展示不出来。具体如下图
![image](https://github.com/obgnail/typora_plugin/assets/26114336/d999706d-48b9-45b2-8048-634337dd17e2)

### 需求
1. 是否可以支持换行“-”（或者其他分隔符）代替“\n”来作为任务的分隔符？
![image](https://github.com/obgnail/typora_plugin/assets/26114336/d7c33627-5223-4bed-b2f7-a688178070cb)
2. 能否支持链接语法，支持点击任务进行跳转。
![image](https://github.com/obgnail/typora_plugin/assets/26114336/54d245b8-c365-4cb6-9c86-0d2be0358595)

### 需求场景
1. 日常记录任务时需要和公司Jira上的问题进行关联，方便跳转。

**Comment by SnowMaples** [comment]
需求2补充
![image](https://github.com/obgnail/typora_plugin/assets/26114336/4b3e8f56-e34b-4e36-b2f5-9ad9766ac695)

**Comment by obgnail** [comment]
@SnowMaples 

其他的都已经实现了：

![Snipaste_2023-12-29_13-31-26](https://github.com/obgnail/typora_plugin/assets/48992887/23bef2b9-ac83-4a0d-bb90-17bc63cd171c)

---

但是要通过下面的语法换行描述框文本，不好做。

```markdown
## TODO
* 语法说明
  - 描述1
  - 描述2
```

原因：历史包袱 😂，上面的文本已经被解析成如下，不太好换了

![Snipaste_2023-12-29_13-34-59](https://github.com/obgnail/typora_plugin/assets/48992887/6465abca-8569-4b9f-a822-5ce05429a46f)

**Comment by SnowMaples** [comment]
期待新的功能上线（我熟悉这个插件的速度都没有您更新的快=_=）

![image](https://github.com/obgnail/typora_plugin/assets/26114336/8dcc5c17-b4bc-4fab-bf8c-cd5151bdf6fa)
![image](https://github.com/obgnail/typora_plugin/assets/26114336/db9cbc48-9f8c-4a23-bf6f-f19bb83ef467)

> 是否可以支持换行“-”（或者其他分隔符）代替“\n”来作为任务的分隔符？

这个功能不是很重要（可以通过看板实时查看显示效果也误伤大雅）

**Comment by obgnail** [comment]
@SnowMaples 并不是新功能，只是文本太长自动换行罢了。目前 kanban 依旧是 **按行解析** 的。行与行之间不会互相影响。

**Comment by obgnail** [comment]
@SnowMaples 新版本已经发布，麻烦更新看看，此 issue 关闭，如有问题麻烦在下面留言，或者另开 issue。

**Comment by SnowMaples** [comment]
已更新至最新版本，使用正常，感谢您。
