### ISSUE TITLE
功能需求：MD规范检查

### ISSUE THREAD

**Issue by SiaYung** [obgnail/typora_plugin#374]
是否可以实现，点击规范检查对应的条目，进行跳转；或者增加行号显示！！3Q

**Comment by obgnail** [comment]
@SiaYung 你好，感谢反馈。

要显示行号的话，可以 ctrl+/ 进入源码模式呀。

**Comment by obgnail** [comment]
@SiaYung 

你好，目前已经添加了一键跳转所在行功能，代码在 dev，预计今晚发布，届时我会在下面留言，请注意查收。

**Comment by obgnail** [comment]
@SiaYung 你好，目前已经添加了一键跳转所在行功能，新版本已经发布，麻烦升级测试一下。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue
