### ISSUE TITLE
updater存在报毒情况

### ISSUE THREAD

**Issue by nothingandignorant** [obgnail/typora_plugin#377]
plugin\updater\updater.exe，360（版本号：15.0.2.1002）报毒类型HEUR/QVM202.0.7528.Malware.Gen
VirusTotal扫描结果
![Uploading image.png…]()

**Comment by obgnail** [comment]
@nothingandignorant 

您好，感谢反馈。

我对反病毒一窍不通。我会尝试处理，但是效果或许不理想。

如果您对安全有疑虑，可以审阅源码 plugin\updater\updater.go，并自行编译 `go build -o updater.exe`。

**Comment by obgnail** [comment]
virustotal 检测结果 4/72 😂

https://www.virustotal.com/gui/file/86f16841adcc0c3f8fa80d4283c3dbe8a8302437db701487635e15c0725d344f

**Comment by obgnail** [comment]
@nothingandignorant 

您好，感谢反馈。

我放弃了，抱歉，我没有能力让病毒检测软件不报毒。事实上，本插件系统确实是通过非正常方式实现功能的，容易报毒。

---

如果您不信任 updater.exe 文件，有两个方案：
- 本项目完全开源，您可以自行 review 同目录下的 updater.go 源码，编译得到新的 updater.exe，并替换掉旧文件。
- 根据 [报毒了怎么办.md](https://github.com/obgnail/typora_plugin/blob/master/plugin/updater/%E6%8A%A5%E6%AF%92%E4%BA%86%E6%80%8E%E4%B9%88%E5%8A%9E.md) 所载方法，删除 updater.exe 文件，之后手动安装插件。

此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
