### ISSUE TITLE
【bug】混排优化识别错误

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#381]
# 混排优化在下面的 `markdown` 语法中会出现问题

下面是使用混排后会出现 `bug` 的 `markdown` 语法：
``` markdown
>   *   **度**：一个节点含有的子树的“个数”称为该节点的“度”，而所有结点的度作为一个整数序列，在序列中取得的最大值就是整颗树的度
>   *   **根节点**：根节点没有前驱节点，一棵树有且只有一个根节点
```

## 使用混排前
>   *   **度**：一个节点含有的子树的“个数”称为该节点的“度”，而所有结点的度作为一个整数序列，在序列中取得的最大值就是整颗树的度
>   *   **根节点**：根节点没有前驱节点，一棵树有且只有一个根节点

## 使用混排后
>   *   * *度**：一个节点含有的子树的“个数”称为该节点的“度”，而所有结点的度作为一个整数序列，在序列中取得的最大值就是整颗树的度
>   *   * *根节点**：根节点没有前驱节点，一棵树有且只有一个根节点

使用的版本是 `1.7.21`

![PixPin_2024-01-06_16-38-26](https://github.com/obgnail/typora_plugin/assets/113878415/26a4a26e-271b-4662-a94a-9351d05c3ae6)

**Comment by xiaogithubooo** [comment]
顺带一提，有序列表不会出现这个问题，但是无序列表会...
![PixPin_2024-01-06_16-41-13](https://github.com/obgnail/typora_plugin/assets/113878415/94559beb-ef4f-41ea-a553-0e361d22cbab)

**Comment by xiaogithubooo** [comment]
无序列表在去除 `>` 这个语法后也不会出现问题

**Comment by obgnail** [comment]
@xiaogithubooo 你好，感谢反馈。

猜测应该是在复杂情况下，无序列表的判断有误导致的，第一和二个星号被解析斜体了。
```
> * **度**
```
这也能解释为什么有序列表没有问题，因为有序列表前缀没有星号

临时绕过方案：将无序列表前缀的 * 改成 -

**Comment by xiaogithubooo** [comment]
噢确实，改为 `-` 确实没有影响了

**Comment by obgnail** [comment]
@xiaogithubooo 

已修复，代码在 dev，影响比较大，我先测一下。没问题后再发布。

发版的时候会在下面留言，请留意。

**Comment by obgnail** [comment]
@xiaogithubooo 

已发版，麻烦更新插件测试一下。此 issue 关闭，如有问题麻烦在下面留言或者另开 issue
