### ISSUE TITLE
【小bug】中文双引号标点符号自动匹配有点问题

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#382]
中文的 `“` 和 `”` 在输入中，默认是两者使用同一个按键。

而在插件中，先输入 `“` 后会自动匹配  `”`，这本身没什么问题。

问题在于输入下一对 `“”` 的时候，永远会先打出 `”`，但是很明显我此时大概率不需要 `”`，而是需要 `“”`  （应该是因为按键默认先输出 `“` 后，再按一次按键就是输出 `”`）。

我必须先打出这个没被匹配的 `”`，然后删除它，在下一次按 `“` 才可以获得一对 `“”`。

这个也不算特别大的 `bug`，就是有时候膈应人...

> 英文的 `"` 在 `typora` 中好像没有方向区分，遇到一个 `"` 就匹配一个，就不会有这个问题。

![PixPin_2024-01-06_17-07-30](https://github.com/obgnail/typora_plugin/assets/113878415/ced6fcac-4b0d-4bf5-b3e8-a89e553e0555)

**Comment by obgnail** [comment]
@xiaogithubooo 

这是一个已知问题，如果你仔细查看 custom_plugin.default.toml 文件，里面就有我写的 NOTE

```toml
[chineseSymbolAutoPairer]
# 需要自动补全的符号（第一项为输入符号，第二项为补全符号）
# NOTE：其实有个问题我不知道要不要修复：中文的前后引号是不一样的，如果你键入的是后引号，此时便无法正常配对补全（好像搜狗输入法就没有修复此问题）
auto_pair_symbols = [
    ["（", "）"],
    ["《", "》"],
    ["‘", "’"],
    ["“", "”"],
    ["【", "】"],
    ["「", "」"],
    ["『", "』"],
]
```

我的思考如下：
1. 我参考了类似软件，大伙都偷懒没做这个功能。
2. 左右引号是输入法控制的，这个需求貌似是输入法该做的。
3. 不好处理，左右引号是相同的键位，意味这不能在 keydown 时机进行判断，只能在 input 时机处理，而此时字符已经上屏了，这就涉及字符的删除替换等等，太麻烦了。
4. 我不使用双引号，都用反引号代替。

**Comment by xiaogithubooo** [comment]
确实，代价貌似有点高，干脆就这样吧😖，反正已经打出肌肉记忆力了hhhhhh
