### ISSUE TITLE
插入kanban等片段时报错：TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by xddx123** [obgnail/typora_plugin#384]
语法解析异常，绘图失败TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
如图：
![image](https://github.com/obgnail/typora_plugin/assets/36707920/15c949b9-b9c3-4092-b8d4-40ce054ffa3c)
我的Typora版本：version 0.9.98(beta)

**Comment by obgnail** [comment]
@xddx123 你好，感谢反馈。

麻烦能给出 kanban 的内容吗？

**Comment by obgnail** [comment]
@xddx123 

你好，我这边无法复现您的情况，麻烦能像下图这样，给出 kanban 代码块里的内容吗？

![Snipaste_2024-01-09_21-13-34](https://github.com/obgnail/typora_plugin/assets/48992887/dd812ecc-462a-4ddf-9539-681a5dec4252)

**Comment by obgnail** [comment]
@xddx123 

1. 太强了，精准定位 👍
2. 已修复，代码在 dev 分支，预计这两天会发版，到时我会在下面留言，请留意。
3. 是最近一周引入的 bug，kanban 有个新特性是在描述框显示图片，所以需要获取当前文件的路径，而新建未保存的空白文档中路径为空导致的。而且此 bug 只在 beta 版本的 Typora 才能复现，我测试的时候测漏了。

**Comment by obgnail** [comment]
考虑了一下，明天没空，这个 bug 算是 p1，现在发版算了。

新版本已经发布，麻烦升级插件测试一下。

> 升级操作：右键菜单 -> 非常用插件 -> 帮助 -> 升级插件

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
