### ISSUE TITLE
功能建议，自定义最近打开的目录的个数

### ISSUE THREAD

**Issue by chuzhixing** [obgnail/typora_plugin#386]
首先，感谢作者开发出这个非常棒的插件。一直在使用它，非常棒的一款软件。

在使用中，默认情况下，“最近打开的目录”只显示6个，如下图所示。
![2024-01-08_091816](https://github.com/obgnail/typora_plugin/assets/41979923/27fa77e4-03eb-4cd6-a99e-9156b09de9f2)

通常在使用过程中，需要打开的目录不仅仅是6个，超过6个目录，再额外打开其它目录，原有的默认显示的6个目录会被覆盖一个。
能够自定义“最近打开的目录”的个数吗？

**Comment by obgnail** [comment]
@chuzhixing  你好，感谢反馈。

自定义个数不太现实。代码分析如下：

![Snipaste_2024-01-08_18-33-23 (1)](https://github.com/obgnail/typora_plugin/assets/48992887/fc5a76e6-c33d-4099-8b5c-c5b275f57cfc)

---

解决方案有两个

## 方案一：将全部文件都放在同一个目录中

这是我认为的最佳方案，如下图，我就是将全部的文件分类放在各个子目录中，然后只打开一个根目录，在跟目录里找各个子目录

![Snipaste_2024-01-08_18-37-10](https://github.com/obgnail/typora_plugin/assets/48992887/4c3a50b9-dbba-4afe-b81c-bff06ff3bc54)

## 方案二：使用 toolbar 插件

操作如下：
1. 键入 ctrl + j，弹出搜索框
2. 在搜索框键入 `his XXX YYY ZZZ` 
3. 选中目录文件/文件夹，回车（或者用鼠标操作）

> his 代表 history，表示要搜索最近的文件。XXX、YYY、ZZZ 就是目标文件的文件名的关键字，比如 `his XXX YYY ZZZ`  就能找到文件 `XXX__ZZZ---YYY.md`

![toolbar (1)](https://github.com/obgnail/typora_plugin/assets/48992887/9a2730e8-1ee0-4a1e-98fb-f471cd00ca3c)

**Comment by chuzhixing** [comment]
感谢作者的回复~~

图片中的这个数字6，可以自定义吗？
默认是6个文件夹的话，Math.min(6, Math.floor((n-r-20)/i) 结果取了前面的数字6。
n = math.max(0, 6) ==> n = 6。
把这个数字6，整个变量替换，可以配置的话，应该可以实现最近打开文件夹个数的自定义。

即不改变原有的动态计算n的逻辑的前提下，把min函数的第一个输入参数“6”自定义，即实现了文件夹数据的自定义。

![294874035-fc5a76e6-c33d-4099-8b5c-c5b275f57cfc](https://github.com/obgnail/typora_plugin/assets/41979923/6380c13d-680f-4aa5-8d21-62043e979b59)

我用vscode全局搜索了下，没有找到图片中的代码。
![2024-01-09_090659](https://github.com/obgnail/typora_plugin/assets/41979923/d9386b4b-d46d-461f-abe4-541c891443a1)

**Comment by chuzhixing** [comment]
方案一，目录树太深了，不太方便找到目录markdown文件。
方案二，可以看到历史文件，点击某个文件打开的话，它会另启动一个typora程序，不会在一个新的标签页面中打开它。

与方案二相比，从最近打开的文件夹打一个文件夹，点击两次即可以找到最近的一个文件夹。使用方案二，至少需要四次键鼠动作才能打开一个文件的文件夹，有点麻烦。

**Comment by obgnail** [comment]
@chuzhixing 

1. 你误会我的意思了。第一张图的代码是 Typora 的源码，不是我的。
2. 我说【不太现实】是指，这个 6 是硬编码在源码里面的，而且整个逻辑被闭包包裹，我暂时想不到方法去修改原有的逻辑。也就是说，**要想修改目录的个数，只能通过修改 Typora 源码实现**。
3. 【新标签页面中打开】问题，Typora 的逻辑是，如果是同属于一个根目录（就是你在侧边栏看到的根目录），就可以在标签页中打开，否则就要新开程序。也就是说，如果你采用方案一，那么你提到的方案二的缺点就会消失。
4. 如果你使用方案一，可以使用 ctrl+P 搜索文件名，ctrl+shift+P 搜索文件内容，ctrl+j 搜索历史文件等多种方式寻找目标 markdown 文件

总结：
1. 如果你采用方案一，优点多多，缺点就是需要多次键鼠操作
2. 如果你希望修改 Typora 源码，修改其中的 6，你可以定位到 frame.js，修改其中的源码（实际上我没试过，不过盲猜是可以的）
```bash
# 新版本的Typora
Typora/resources/appsrc/window/frame.js

# 老版本的Typora
Typora/resources/app/app/window/frame.js
```
![Snipaste_2024-01-09_10-57-41](https://github.com/obgnail/typora_plugin/assets/48992887/b243d7a1-c136-43a4-8c28-157f21a0fb76)

**Comment by obgnail** [comment]
@chuzhixing 

我没试过修改 frame.js，所以修改前请备份文件，如果我没说清楚，或者我的方案不太行，可以在下面留言讨论。

**Comment by chuzhixing** [comment]
> @chuzhixing
> 
> 我没试过修改 frame.js，所以修改前请备份文件，如果我没说清楚，或者我的方案不太行，可以在下面留言讨论。

感谢作者的回复~~~~
我试着修改了一下frame.js，把n=30，在typora中，最多只能展示8个文件夹。可能受限于弹出框的高度。

**Comment by obgnail** [comment]
@chuzhixing 

1. 并没有相应的 CSS 限制（当然，也有可能是你使用的 theme 有限制）
2. 我猜测是后端限制了 folder 数量。如果你有兴趣，可以升级到最新版本的插件，接着使用 ctrl + j，输入 `his `（注意有空格，参照上面的 gif 图），数一数到底有多少个 folder 
3. PS：我解包了后端的源码，你甚至可以直捣黄龙：如下代码就可以看出，历史文件的数据是存储在 AppData\Roaming\Typora\history.data 文件中，使用 lowdb 库的存储格式，有兴趣可以试试。

```js
function prepDatabase(path){
	var lowdb = require('lowdb')
	var FileSync = require('lowdb/adapters/FileSync')

	var adapter = new FileSync(path, {
		serialize: function(obj) {
			str = JSON.stringify(obj) || "{}";
			return (new Buffer.from(str)).toString("hex");
		},
		deserialize: function(str) {
			try {
				str = (new Buffer.from(str || "", "hex")).toString();
				return JSON.parse(str);
			} catch (e) {
				return {};
			}
		}
	})
	return lowdb(adapter);
}

Setting.prototype.init = function(){
      ...
      this.history = prepDatabase(app.getPath("userData") + "/history.data");
      ...
}

Setting.prototype.getRecentFolders = function(){
	var state = this.history.getState();
	var recentFolders = state['recentFolder'];
	if(!recentFolders){
		recentFolders = [];
		state['recentFolder'] = recentFolders;
	}
	return recentFolders || [];
};
```

**Comment by chuzhixing** [comment]
@obgnail 非常感谢您的回复。
