### ISSUE TITLE
文字风格化 在Cobalt主题下是否可以改变背景颜色

### ISSUE THREAD

**Issue by Q-jun** [obgnail/typora_plugin#387]
这是在Github主题下
![Snipaste_2024-01-08_11-06-26](https://github.com/obgnail/typora_plugin/assets/84129138/05c0e364-6654-4341-90ed-9830032a32d9)

这是在Night主题下
![Snipaste_2024-01-08_11-09-56](https://github.com/obgnail/typora_plugin/assets/84129138/3c79b209-e243-49b5-b207-b7a691db2936)

这是在Cobalt主题下
![Snipaste_2024-01-08_11-07-26](https://github.com/obgnail/typora_plugin/assets/84129138/f412b8d1-437c-4fae-b06a-5d8779ed9b32)

**Comment by obgnail** [comment]
@Q-jun 你好，感谢反馈。

文字风格化窗口的颜色其实是跟随主题的配色方案的。出现这个情况主要是因为 Cobalt 主题没有严格遵守 Typora 的主题 CSS 格式要求。

我在新版本中，新增了一个 MODAL_BACKGROUND_COLOR 配置，用以手动配置面板的颜色。麻烦升级到最新版本试用一下。

```toml
[text_stylize]
# 面板的背景颜色。若为""，则跟随主题的配色方案
MODAL_BACKGROUND_COLOR = ""
```

> 如何修改配置，请阅读 [请读我.md](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md)

**Comment by obgnail** [comment]
此 issue 关闭。如有问题，麻烦在下面留言，或者另开 issue。
