### ISSUE TITLE
用插件生成的思维导图能不能导出高清图

### ISSUE THREAD

**Issue by Runnerxr** [obgnail/typora_plugin#389]
这个插件可以根据目录级别生成相应的思维导图，但是这个导图只能采取截屏的方式，当标题等级很多的时候，就会发现图片有点不清晰，能否有一个功能可以导出比较清晰图片的功能

**Comment by obgnail** [comment]
@Runnerxr 

你好，感谢反馈。新版本已经支持导出 svg 文件，矢量图无限高清。麻烦升级插件试用一下。

> 升级插件：右键菜单 -> 非常用插件 -> 帮助 -> 升级插件

![Snipaste_2024-01-12_03-51-36](https://github.com/obgnail/typora_plugin/assets/48992887/b0181fb5-40af-4c92-a3a8-ba2fd5bfa29a)

**Comment by obgnail** [comment]
此 issue 暂时关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by styw1234** [comment]
你好，这个思维导图存在问题：导入PPT中会出现文字丢失的bug

思维导图保存的是svg格式
Typora中的思维导图和在edge中看到的图没问题：
![ed](https://github.com/user-attachments/assets/3bf617db-ba55-4925-901c-6250e44e8dce)

但是将这个svg图插入PPT中，就出现文字丢失的问题：
![20240902 0649 市场主体的碳分配](https://github.com/user-attachments/assets/152e4116-b1b1-444c-90fe-6c176c13fab8)

**Comment by obgnail** [comment]
@styw1234 

原因：导出的 SVG 使用了 foreignObject 标签，此标签可以在现代浏览器中解析，但是 PPT 的 SVG 解析器能力很弱，无法解析。

解决方案：选项勾选 `替换 foreignObject 标签 `。

![IMG_2024-09-03_11-28-11 (1)](https://github.com/user-attachments/assets/0306f3af-0b24-4796-9dd5-19de14344ab1)

**Comment by styw1234** [comment]
> @styw1234
> 
> 原因：导出的 SVG 使用了 foreignObject 标签，此标签可以在现代浏览器中解析，但是 PPT 的 SVG 解析器能力很弱，无法解析。
> 
> 解决方案：选项勾选 `替换 foreignObject 标签 `。
> 
> ![IMG_2024-09-03_11-28-11 (1)](https://private-user-images.githubusercontent.com/48992887/363832358-0306f3af-0b24-4796-9dd5-19de14344ab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjYyMDEsIm5iZiI6MTcyNTM2NTkwMSwicGF0aCI6Ii80ODk5Mjg4Ny8zNjM4MzIzNTgtMDMwNmYzYWYtMGIyNC00Nzk2LTlkZDUtMTlkZTE0MzQ0YWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEyMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZDhhZjc5OTY0Y2NkMmQ2OWQ4NDEwOGUyYTM2ZDhkODFhMjFlNDZlZDJiZDZhZjJiYjY5MzVkNWRkODZmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.egHkkbPPLDs3C8iI1UTTeFhpb_B-A83RslQ_i674w6Y)

针对“解决方案：选项勾选 替换 foreignObject 标签 ”
请问从Typora怎么进入去到选项 勾选替换 foreignObject 标签 ？找不到选项入口。

**Comment by obgnail** [comment]
@styw1234 

升级新版本。
