### ISSUE TITLE
多标签也功能非常实用，但在实际使用过程中，出现多次以下情况：切换标签页时，有时文档内容并不能正确切换，只能重启。

### ISSUE THREAD

**Issue by SlovinG** [obgnail/typora_plugin#391]
多标签也功能非常实用，但在实际使用过程中，出现多次以下情况：切换标签页时，有时文档内容并不能正确切换，只能重启。

**Comment by obgnail** [comment]
@SlovinG 

你好，感谢反馈。我想收集以下信息：

1. 您的平台（Linux/windows），您使用的 Typora 版本，Typora_plugin 的版本
2. 切换的标签页对应的文件是否很大？
3. 出现问题很频繁吗？
4. 切换的时候是否打开了【markdown 格式规范检测】、【高亮搜索】、【书签管理】等其他插件的弹窗？

**Comment by obgnail** [comment]
这个 BUG 我在之前做过一版修复 #313，我个人目前没有再遇到此类情况，于是先了解以下您的情况

**Comment by obgnail** [comment]
@SlovinG 

你好，请问问题解决了吗？

**Comment by WilsonVincent** [comment]
@obgnail 
在最新的版本中出现相同的问题。如图所示：
![image](https://github.com/obgnail/typora_plugin/assets/60778141/62d5ba31-b0f8-48c9-b321-187b9394adf3)
![image](https://github.com/obgnail/typora_plugin/assets/60778141/43633c3a-a604-4a0a-914d-3e113e0d1502)
![image](https://github.com/obgnail/typora_plugin/assets/60778141/d6f9f198-fea7-485e-a6cd-1ce093adba2c)


正常内容应该是：
![image](https://github.com/obgnail/typora_plugin/assets/60778141/5eda8e85-02f9-4a07-916b-52bdcc50d027)


如果强行编辑错误展示的内容将会出现致命性BUG，会将错误的内容强行替换掉正确内容，既将最后一张图的内容完全替换为第三张图的内容！！

希望可以加急修复！

**Comment by obgnail** [comment]
@SlovinG @WilsonVincent 

麻烦回复一下我上面的提问，我这边已经无法复现这个问题了。

**Comment by WilsonVincent** [comment]
@obgnail 不好意思，没注意。

您的平台（Linux/windows），您使用的 Typora 版本，Typora_plugin 的版本
Windows11，1.8.3-dev，1.7.29

切换的标签页对应的文件是否很大？
否

出现问题很频繁吗？
百分百复现，无法避免，触发条件猜测是：文件同名


切换的时候是否打开了【markdown 格式规范检测】、【高亮搜索】、【书签管理】等其他插件的弹窗？
没有、没有、没有

**Comment by obgnail** [comment]
@WilsonVincent 

盲猜是 Typora 1.8 版本和现阶段的 typora_plugin 不兼容引发竞态导致的。
- 上次出现此问题是在 1.6 升到 1.7 的时候
- 目前我在 1.7.6 版本，没有发现此问题

提问：
- 【百分百复现】是什么意思？只要文件同名，就必定出现？

**Comment by WilsonVincent** [comment]
@obgnail 

是的，在我现在的这个环境下是百分百复现成功的，没有任何意外！

**Comment by obgnail** [comment]
@WilsonVincent 

很麻烦，看了一下 [What's-New-1.8](https://support.typora.io/What's-New-1.8/)，看起来 1.8 版本和目前的 typora_plugin 有不少冲突，同时 1.8 又不是 stable 版本，我手上也没有 1.8 版本，不好整。

**Comment by WilsonVincent** [comment]
@obgnail 

https://typora.io/releases/all
