### ISSUE TITLE
混排优化问题

### ISSUE THREAD

**Issue by TimeonFly** [obgnail/typora_plugin#396]
使用**混排优化**优化文本会导致 *callout* 的`[!NOTE]` 变为`[! NOTE]` 导致 *callout* 无法正常显示

https://github.com/obgnail/typora_plugin/assets/63436694/fd88d25f-94f7-4fd9-a3b2-146f70d60fa1

**Comment by obgnail** [comment]
@TimeonFly 

感谢反馈，应该是五天前的 [1.7.23](https://github.com/obgnail/typora_plugin/releases/tag/1.7.23) 引入的 BUG，此版本修改了混排优化插件中 blockquote 的解析器。

**Comment by obgnail** [comment]
当前进展：已修复，但尚未测试，代码在 [dev 分支](https://github.com/obgnail/typora_plugin/commit/80b39469a8326c804f281df9736d4b6438979c3d)，等后续测试完毕后上线

**Comment by obgnail** [comment]
@TimeonFly 已修复，麻烦升级新版本，试用一下。如有问题，麻烦在下面留言或者另开 issue
