### ISSUE TITLE
[bug]1.8.x版本问题汇总

### ISSUE THREAD

**Issue by WilsonVincent** [obgnail/typora_plugin#404]
以下进行汇总1.8.x版本的相关问题，由于是问题反馈测试渠道的内容，不记作正式版插件的Bug。

问题一：
#391 这个问题我试了很多次，百分百的会复现，没办法避免，我暂时在1.8.x版本中禁用了tab。

问题二：
1.8.x 版本将会 额外多出来的滚动条
开启文件数量统计：将会额外多出来一个水平滚动条
![image](https://github.com/obgnail/typora_plugin/assets/60778141/87df710b-0eb0-4f8e-8223-920a74f5c055)
禁用文件数量统计后，就没有了
![image](https://github.com/obgnail/typora_plugin/assets/60778141/d27dd192-81e0-4501-8bdc-29cb3efc5676)

**Comment by xiaogithubooo** [comment]
我也有类似的问题：
1. 问题二应该是文件名字太长挤的，虽然我感觉还好无所谓，不过能消除就更棒啦~
2. 问题一的多标签，有的时候不仅是显示错误，在删除文件的时候还有些奇怪的问题（比如我切换得太快了，删除了某个文件，结果把前一个切换得文件也删除了，导致两个文件都没有了（貌似是有这个问题，因为我后面怕误删就把这个插件关闭了））

**Comment by WilsonVincent** [comment]
> 我也有类似的问题：
> 1. 问题二应该是文件名字太长挤的，虽然我感觉还好无所谓，不过能消除就更棒啦~
> 2. 问题一的多标签，有的时候不仅是显示错误，在删除文件的时候还有些奇怪的问题（比如我切换得太快了，删除了某个文件，结果把前一个切换的文件也删除了，导致两个文件都没有了（貌似是有这个问题，因为我后面怕误删就把这个插件关闭了，没怎么重现过））

问题一并不是你说的这种情况。问题二1.8版本可以用绝对到位，可以看一下我提的pr，可以消除，但是1.7我不知道会不会出现作者说的错位，1.7的typora有点。。还是继续坚持用1.8了。1.8从感觉比1.7好用一点虽然只是测试版。

**Comment by WilsonVincent** [comment]
@xiaogithubooo #409

**Comment by WilsonVincent** [comment]
@xiaogithubooo #412 如果有时间方便的话 尝试一下使用这个版本的tab还会不会出现问题一。问题二已经1.7.X和1.8.x都已经消除。
