### ISSUE TITLE
[建议] 配置文件相关建议

### ISSUE THREAD

**Issue by RiftRays** [obgnail/typora_plugin#405]
方案1. 配置文件进行隔离，避免覆盖安装的时候导致配置文件丢失。
方案2. 支持webdav进行备份。

**Comment by obgnail** [comment]
@RiftRays 

提问：
1. 如果采用方案1，那么 user.toml 应该放在哪里？而且这个位置也是必须写死的，配置文件不能配置自己呀
2. 如果采用方案2，那么我怕延迟会爆炸（加载插件的第一步操作就是 loadConfig，请求的时候，整个插件系统都 hang 住了）

**Comment by RiftRays** [comment]
@obgnail 

方案一：我电脑中其他软件的配置项大多数会放置到：C:\Users\用户名\.config文件夹下，避免软件卸载后配置文件丢失重新配置。软件原有的配置不变，但是用户config文件夹下的文件优先级更高。
方案二：不是在加载的时候读取在线配置，而是添加一个菜单按钮，点击备份后将本地的用户配置上传到云端，可以是webdav，可以是GitHub指定的仓库（强行覆盖）。

**Comment by obgnail** [comment]
@RiftRays 

已支持方案一。已经合到 master。预计明天发布。代码在这里：[update core: support home dir config](https://github.com/obgnail/typora_plugin/commit/1c5085bc545a327db434b664b17c33a6ca9143a6)

**Comment by RiftRays** [comment]
@obgnail 

试了一下，终于可以将开发环境的内容直接本地覆盖了，不用每次额外备份配置文件在替换进去了。

还有几个地方需要一起优化/建议：
1. 可以考虑添加一个按钮`配置隔离/配置迁移`等。通过按钮创建`typora_plugin`文件夹，然后将当前的user配置文件移动到文件夹中并打开移动后的文件夹。（前提是：`typora_plugin`不存在，如果存在则直接打开文件夹）
2. `修改配置` ：如果存在`typora_plugin`文件夹则应该修改的typora_plugin的配置文件而不是修改的原来安装位置的配置文件。

**Comment by RiftRays** [comment]
@obgnail 
当然还有一个小建议，每个人存放配置文件的想法可能不一样。
这个路径不一定是`C:\Users\用户名\.config`,可以像记录版本号一样，在`settings`下创建一个用于记录指定配置文件存放位置的文本或者json数据。默认可以是：`C:\Users\用户名\.config\typora_plugin`

**Comment by obgnail** [comment]
@RiftRays 

感谢建议。

1. 迁移配置：这个就不做了。有很多的非技术人员也在用这个插件，他们不能理解这种东西。他们没有 github 账号，靠邮件做用户反馈，我已经回复麻了。
2. 修改配置：已完成，合到 master 了。
3. 文件指针：暂时不做。太复杂了，目前插件系统已经有 defaultConfig，userConfig，homeConfig 三个配置文件了，还整第四优先级配置文件，都绕晕了。而且我看我电脑的 .config 目录，也没有见到其他软件这么做的。

其实最佳方案应该是做一个修改配置的页面，直接可视化操作。这也是我一直想做的，但是一想到有 400+ 个选项……

**Comment by obgnail** [comment]
@RiftRays 

已发版。

此 issue 关闭。如有建议或者问题，可以继续在下面留言。

**Comment by obgnail** [comment]
突然想到，文件指针问题，需要的话创建一个软链接或者一个快捷方式就可以了呀

**Comment by RiftRays** [comment]
> @RiftRays 
> 
> 感谢建议。
> 
> 1. 迁移配置：这个就不做了。有很多的非技术人员也在用这个插件，他们不能理解这种东西。他们没有 github 账号，靠邮件做用户反馈，我已经回复麻了。
> 2. 修改配置：已完成，合到 master 了。
> 3. 文件指针：暂时不做。太复杂了，目前插件系统已经有 defaultConfig，userConfig，homeConfig 三个配置文件了，还整第四优先级配置文件，都绕晕了。而且我看我电脑的 .config 目录，也没有见到其他软件这么做的。
> 
> 其实最佳方案应该是做一个修改配置的页面，直接可视化操作。这也是我一直想做的，但是一想到有 400+ 个选项……


哈哈哈哈。好的。.config我这边有几个软件会生成默认配置在这里。常见一点的就是cfw吧。还有一些我自己丢进去的。.config的上一层目录下有很多软件或者开发环境的配置文件的。

**Comment by RiftRays** [comment]
defaultConfig: 安装自带
userConfig: 自动检测和生成到c盘
homeConfig: 满足自动生成到c盘后，这个可以删除的。默认读取。这样你也不用判断谁优先了。

**Comment by RiftRays** [comment]
@obgnail 

有些人没有GitHub帐号这种情况。

软件发生重大更新后，我的建议是可以在合适的时候(更新后第一次打开软件，手动更新前，检测到有更新时）弹出一个框告诉用户更新了什么需要特别注意什么。

配置方面，建议默认关闭自动升级(但是可以提前下载到本地）让用户知道更新了什么后选择是不是要更新或者对配置文件就行备份之类的。

**Comment by obgnail** [comment]
@RiftRays 

更新逻辑后续会大改。

---

今晚做了一个图一乐插件：[bingSpeech](https://github.com/obgnail/typora_plugin/commit/55d7344d2b0f489d592171ec14ef452dead9fe1e)。抖音营销号看了都想要。

已经合到 master，有兴趣的话可以试试，给一下建议。

**Comment by RiftRays** [comment]
@obgnail 这个插件无法选择代码块，选择代码块会提示。

**Comment by RiftRays** [comment]
@obgnail 可以做一个必应翻译、谷歌翻译、Deeplx翻译等的插件~偶尔需要翻译专业名称。

**Comment by obgnail** [comment]
哈哈哈，要是用的多的话就不叫图一乐了。这个插件我也用不到，就是一个娱乐性质的东西。

无法选中代码块其实也没啥，毕竟代码也没有人真的把代码读出声来，读出来也听不懂。

同时，为了防止有人干坏事，我虽然做了 download 功能，但是没有暴露到产品中

```js
class bingSpeech extends BaseCustomPlugin {
    // 生成的文件是mp3格式
    // 为了防止有人干坏事，此方法并不暴露到产品中
    download = async (filepath, text) => {
        text = text || File.editor.UserOp.getSpeechText();
        const chunks = [];
        await this.crawl(text, binary => chunks.push(binary));
        await this.utils.Package.Fs.promises.writeFile(filepath, Buffer.concat(chunks));
        console.debug("done");
    }
}
```

**Comment by RiftRays** [comment]
@obgnail 翻译功能可以提上计划？平常翻译确实经常用。

**Comment by obgnail** [comment]
1. 功能倒是不难做。
2. 正常的翻译 API 都是要用户提供 token 的，没有的话只能像 bingSpeech 一样做一些偷鸡摸狗的操作了，不稳定，维护成本高。
3. 实际上，我用的是 [CopyTranslator](https://github.com/CopyTranslator/CopyTranslator)，直接常驻后台，快捷键调用，哪哪都能用。Typora 内置一个翻译插件，感觉用处不大。

**Comment by obgnail** [comment]
@RiftRays 

我花了点时间，实现了核心代码，代码在 [dev](https://github.com/obgnail/typora_plugin/commit/be71d5882a289f93b4d64a6cf5ff5ade0105cb05)

```js
class bingSpeech extends BaseCustomPlugin {
    translate = async (text, fromLang, toLang) => {
        console.debug("start translate");
        const config = (fromLang && toLang)
            ? this.utils.merge(this.config, {from_language: fromLang, to_language: toLang})
            : this.config
        const spider = new bingSpeechSpider(this);
        return await spider.translate(config, text)
    }
}
```

效果如下：

![Snipaste_2024-01-30_18-16-51](https://github.com/obgnail/typora_plugin/assets/48992887/dfc9edd5-0a3e-447f-a25d-d56610d82bdb)

**Comment by RiftRays** [comment]
@obgnail 好的。感谢。
