### ISSUE TITLE
自动添加结尾空格功能问题

### ISSUE THREAD

**Issue by 1048632280** [obgnail/typora_plugin#415]
autoTrailingWhiteSpace：自动添加结尾空格
这个功能正常吗？我在toml文件里设置了enable=ture。在回车enter换行时，还是空一行换到第三行，我检查了一下并没有添加结尾空格。还是说我对这个功能理解有误？
用的最新release版本

**Comment by obgnail** [comment]
@1048632280 

你好，感谢反馈。
1. autoTrailingWhiteSpace 这个名字其实取得有问题，auto 一词误导你了，这个插件其实并不 auto。
2. Typora 其实并不能识别结尾空格。也就是说，就算添加了结尾空格，也不会自动换行。但是在标准 Markdown 规范中，还需要在换行符前跟至少两个空格，才能起到换行效果，普通的换行会被忽略。
3. 一边是所见即所得，另一边是 Markdown 强制规范，都不能放弃。所以我并不能按你所想的那样的 在回车 enter 换行自动添加结尾空格。
4. 那么，此插件正确的使用方法是？答：**正常编辑 md 文件，等编辑结束后，点击 `右键菜单 -> 常用插件 -> 自定义插件 -> 自动添加结尾空格`，如此，就会为整篇文档添加结尾空格**。

> 注：在你反馈此 issue 后，我发现了这个插件有个 BUG，现已修复，麻烦升级到最新版本。

> 升级插件方法：`右键菜单 -> 常用插件 -> 自定义插件 -> 升级插件`。

**Comment by 1048632280** [comment]
好的，明白了

**Comment by obgnail** [comment]
好的，如果还有问题，麻烦在下面留言或者另开 issue。
