### ISSUE TITLE
1.7.31 混排优化对table中的<br />存在问题

### ISSUE THREAD

**Issue by RiftRays** [obgnail/typora_plugin#417]
![image](https://github.com/obgnail/typora_plugin/assets/60778141/cae6131f-c7e1-4713-897a-7839e4338fa1)

优化后

![image](https://github.com/obgnail/typora_plugin/assets/60778141/fdb33498-7191-46ff-b35b-71190013d9ca)

**Comment by xiaogithubooo** [comment]
欸，这个问题貌似我也遇到过，是在表格中么？我也有几个表格莫名其妙多个几个空格

> ![image](https://private-user-images.githubusercontent.com/60778141/298072836-cae6131f-c7e1-4713-897a-7839e4338fa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODk5NDEsIm5iZiI6MTcwNTg4OTY0MSwicGF0aCI6Ii82MDc3ODE0MS8yOTgwNzI4MzYtY2FlNjEzMWYtYzdlMS00NzEzLTg5N2EtNzgzOWU0MzM4ZmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MDk1NjQ4NzJiYjQxOWUzODE5MmRlN2FiMmZjMzk0ZDZiMmMyYTZhZTJiMGNjNzExMmMzNGYzNTk3NDA4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qehdFMcV-3qLMq641sDyHScL9xzPMbH7mU8DV4jgUno)
> 
> 优化后
> 
> ![image](https://private-user-images.githubusercontent.com/60778141/298072920-fdb33498-7191-46ff-b35b-71190013d9ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODk5NDEsIm5iZiI6MTcwNTg4OTY0MSwicGF0aCI6Ii82MDc3ODE0MS8yOTgwNzI5MjAtZmRiMzM0OTgtNzE5MS00NmZmLWIzNWItNzExOTAwMTNkOWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZjU5NjQwYjMyNmJhYWEzY2UxYTEyYjkwNTkxNmFkMjhiMTY5MTViZDFjMzQwMjM4MTM3NjE4NTgwMTYxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yuRNEym9ncnGdHHf2pb2X8H0GYC4JwcLsOboRAKgK7A)

**Comment by WilsonVincent** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/60778141/6e872227-7c47-47f6-9126-a9920c0d3117)

@obgnail 好像无法查看这个图片。

**Comment by obgnail** [comment]
确实有点为难。我暂时想不出有什么方法能处理。

以下文本：

```markdown
|      |                       |
| ---- | --------------------- |
|      | 123<br />456<br />789 |
```

渲染如下：

|      |                       |
| ---- | --------------------- |
|      | 123<br />456<br />789 |

造成上述 BUG 的原因是： `123<br />456<br />789` 被修改成了 `123 <br /> 456 <br /> 789`。htmlTag 的前后都加上了空格，这就是空格来源。

假如将 `<br />` 改成 `<div>` 或者其他的 htmlTag，你会发现 md_padding 的行为（给他们前后加上空格）是合理的。也就是说，处理这个问题需要处理特殊的 htmlTag。

---

最大的问题是 **md_padding 是基于词法解析的**。md_padding 实现的基本逻辑是：
1. 所有以 `<` 开头并且以 `>` 结尾的内容，统一解析成 htmlTag，
2. 然后自动在 htmlTag 和 普通 Text 中间加一个 space。

所以，你会发现，md_padding 其实是没有解析 html 的，只是原样保留罢了。也就是说，在 md_padding 看来，`<br />` 其他普通 htmlTag 没有任何区别。统一被解析成 htmlTag，而 htmlTag 的行为就是在前后加上 space。

---

要想解决这个问题，就需要把 `<br />` 作为一种新的词法去解析。

但是问题是，它没有固定的是词法规则（比如说链接就是 `[XXX](XXX)`，callout 就是 `> [!XXX]`）

---

目前 md_padding 支持的词法规则：
```typescript
export enum State {
  // markdown syntax
  LinkText,           // [
  ReferingUrl,        // [xx](
  ReferingID,         // [xx][
  ReferenceLinkUrl,   // [xx]:
  ImageText,          // ![
  ImageReferingUrl,   // ![xx](
  ImageReferingID,    // ![xx][
  ImageAttributes,    // ![xx]{
  HTMLTag,            // <
  Emphasis,           // *
  Strong,             // **
  Strikethrough,      // ~~
  InlineCode,         // `
  BlockCodeLang,      // ```
  Math,               // $, $$
  BlockCodeBody,      // ```cpp\n
  OrderedListItem,    // 1.<space>
  UnorderedListItem,  // *<space>
  BlockquoteItem,     // >
  CalloutItem,        // [!

  // natural language syntax
  Quoted,             // " in natural language
  Init,               // init state
}
```

**Comment by WilsonVincent** [comment]
@obgnail 如果换一个角度。设计呢？

![image](https://github.com/obgnail/typora_plugin/assets/60778141/4851788a-5a6d-4667-b0c0-59a02a76f2df)


将1. 也进行前面加一个空格呢？这个方式是否会轻松一些？

**Comment by WilsonVincent** [comment]
@obgnail 
如果使用这个，表格将不会序号错位了，但我我不确定会不会导致其他问题
IGNORE_WORDS = ["==","1.","2.","3.","4.","5.","6."]

**Comment by obgnail** [comment]
@WilsonVincent 

没啥意义。

这样行得通只是因为 `<br />` 后面刚好是 `1.`，`2.` 等。如果是 `123<br />456<br />789` 或者是 `<br />任意其他内容<br />任意其他内容` 也是会出现问题的。

如果你是习惯 `<br />` 后面添加 `1.` 序号，那你可以如此做。

**Comment by obgnail** [comment]
基于上述原因，此 issue 在短时间无法得到进展，此 issue 暂时关闭，抱歉，后续如有思路会重启。

**Comment by obgnail** [comment]
@RiftRays @xiaogithubooo 

上述的需求已经在新版本中支持，现在不会再自动为 `<br />` 的前后添加空格了。

新版本中，添加了一个新的配置 IGNORE_PATTERNS，后续有需求的话，你们也可以使用这个配置，绕过某些特殊的 HTML tag。

```toml
# 不希望拆分的正则词组（这些正则内部和前后禁止加空格）
IGNORE_PATTERNS = ["<br />"]
```

**Comment by obgnail** [comment]
related issue: #749
