### ISSUE TITLE
typora 1.8.3  callout样式

### ISSUE THREAD

**Issue by WilsonVincent** [obgnail/typora_plugin#423]
除了官方文档中看见支持的五种类型，其他的都会在侧边多加一个颜色。

![image](https://github.com/obgnail/typora_plugin/assets/60778141/e21877f6-37a8-4ab5-b946-1c4960ae8971)

**Comment by WilsonVincent** [comment]
@obgnail 1.8.5正式发布了。（基于1.8.3-dev版本）

**Comment by WilsonVincent** [comment]
@obgnail typora如何获取当前的版本号？

是否可以根据版本判断进行移除typora的blockquote中的`background-color`样式
![image](https://github.com/obgnail/typora_plugin/assets/60778141/b04a7737-a328-4945-bf00-52729a5f8f23)

**Comment by obgnail** [comment]
@WilsonVincent 

我也升级到了 1.8 版本，我没有出现此问题，你是用了什么主题吗？

![Snipaste_2024-01-26_00-36-30](https://github.com/obgnail/typora_plugin/assets/48992887/77046f16-699f-4ce1-b5ed-622295db8794)

**Comment by obgnail** [comment]
utils 中有一个 isBetaVersion，可以获取当前版本号，有一个 compareVersion 可以比较版本号的大小，如果确定是插件的问题，可以用此修复。

**Comment by WilsonVincent** [comment]
> @WilsonVincent
> 
> 我也升级到了 1.8 版本，我没有出现此问题，你是用了什么主题吗？
> 
> ![Snipaste_2024-01-26_00-36-30](https://private-user-images.githubusercontent.com/48992887/299740281-77046f16-699f-4ce1-b5ed-622295db8794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzI1ODEsIm5iZiI6MTcwNjI3MjI4MSwicGF0aCI6Ii80ODk5Mjg4Ny8yOTk3NDAyODEtNzcwNDZmMTYtNjk5Zi00Y2UxLWI1ZWQtNjIyMjk1ZGI4Nzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEyMzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NDUxMjYyYWFlZWZhZmVlODk4N2ZhZDMxMzZmNTRlMzdiM2U5ZDk0YjRiOTJmNzZlNmRjNTIwNmJjNDMwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5AhqKkS63VI_6c3etJQ2CtC8iS2pyQUgFpw1Px-pWPo)

好像还真的是主题导致的。
