### ISSUE TITLE
【bug?】代码块在只读模式下，有些情况依旧可以粘贴进代码

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#425]
下面是一个代码块，我已打开了 **只读模式（启动 typora 就进入只读）**，但是依旧可以复制代码粘贴进代码块。

并且这种行为只有在第一次启动 `typora` 的时候才可以，其他情况貌似都不可以。

```cpp
[这是空的代码块啦...]
```

演示 `gif`：

![20240122100623](https://github.com/obgnail/typora_plugin/assets/113878415/e08f284c-e149-46f2-9b4f-e60b1406e496)

关闭 typora 后，代码块内的内容确实被保存起来了

**Comment by obgnail** [comment]
@xiaogithubooo 

已修复，代码在 master，预计今晚发版

**Comment by obgnail** [comment]
@xiaogithubooo 

新版本已经修复，麻烦升级到新版本测试一下。

此 issue 关闭，如有问题，麻烦在下面留言或者新开 issue。
