### ISSUE TITLE
最新版本打开文件，显示空白

### ISSUE THREAD

**Issue by 596142041** [obgnail/typora_plugin#430]
更新为最新版本之后，打开文件显示空白

**Comment by 596142041** [comment]
![微信截图_20240123233503](https://github.com/obgnail/typora_plugin/assets/4958182/e31290ae-47a0-46c1-98de-9f701637bf6e)

**Comment by obgnail** [comment]
@596142041 

已紧急上线兼容版本。

https://github.com/obgnail/typora_plugin/releases/tag/1.7.35

**Comment by obgnail** [comment]
刚刚上线，可以的话麻烦试用后反馈一下。
