### ISSUE TITLE
导出增强会考虑把html的图片base64化吗

### ISSUE THREAD

**Issue by ddnrnboobaql** [obgnail/typora_plugin#431]

**Comment by obgnail** [comment]
@ddnrnboobaql 

你好，感谢反馈。

我试了一下，html 格式的图片是可以导出的呀。

源码如下：
```markdown
111

<div align="center">
  <img src="assets/1.png" width="400" />
</div>

222

![1](./assets/1.png)

333
```

导出如下：
![Snipaste_2024-01-24_12-15-25](https://github.com/obgnail/typora_plugin/assets/48992887/d1e1e721-eae4-40d9-bc7f-29f4ce1ce195)

**Comment by obgnail** [comment]
@ddnrnboobaql 

你好，问题解决了吗？还是说是我理解错你的问题了？

**Comment by obgnail** [comment]
之前的插件有个 bug：无法顺利处理绝对路径的图片，有个可能你是遇到了这个bug。

如果是这个情况，麻烦升级到最新版本。

**Comment by obgnail** [comment]
@ddnrnboobaql 

此 issue 暂时关闭，如果有问题，麻烦再下面留言，届时我会重启此 issue。
