### ISSUE TITLE
导出增强建议增加绝对路径的

### ISSUE THREAD

**Issue by wlping265** [obgnail/typora_plugin#432]
![Snipaste_2024-01-24_17-51-14](https://github.com/obgnail/typora_plugin/assets/36145406/cd817c0e-3cb0-4f03-ae62-7819483959af)
场景：我的本地图片采用的是复制到本地指定路径例如： F:/wlping/MarkDown图库/${filename}
按照绝对路径去找，则无法进行转换，建议增加如上图的判断：
如果是相对路径的图片则补全路径，否则直接使用原路径
，这样导出的html即使混用也是能都找到图片

**Comment by obgnail** [comment]
@wlping265 

已修复，代码已合到 master 中，等待发版

**Comment by obgnail** [comment]
@wlping265 

已修复，已发版。麻烦更新插件到最新版本试用。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
