### ISSUE TITLE
请问可以做个代码块自动识别的功能码

### ISSUE THREAD

**Issue by W1ndys** [obgnail/typora_plugin#439]
如题，想问一下这个想法可不可行，就是代码块自己敲完代码之后，自动识别并填入代码类型
![image](https://github.com/obgnail/typora_plugin/assets/109416673/ea2d11b1-3c2a-48a2-95a1-b31982ff395b)

**Comment by obgnail** [comment]
@W1ndys 你好，感谢反馈。

先说结论：**做不到，但是可以曲线救国**。

## 做不到的理由

类似的插件我曾经做过一版，但是效果很差。给出一段代码，推测代码的语言是很困难的，目前存在太多语法相似甚至相同的语言，比如 typescript、javascript、coffeescript 三者的代码可能完全相同。

我也找过 github 上高星的项目，但是效果都不理想。

一个最简单的例子，**强如 vscode，作为代码编辑软件，背靠软微，它在推测代码语言这点也是经常出错**。

而且有个很大的问题就是：vscode 错了就错了，用户手动调整就行。但是这个插件需要货真价实的写入文件，就很麻烦。

实际上，这个需求同样出现在 Typora 官方的 [issue](https://github.com/typora/typora-issues/issues/3661) 上，挂了 4 年同样没有任何进展。

## 曲线救国方案

你可以修改配置文件，将 ENABLE_DANGEROUS_FEATURES 功能设置为 true。

```tom
[fence_enhance]
# 在右键菜单中启用有风险的功能（此功能会消耗巨量资源并导致Typora长时间（几秒到几十秒）失去响应）
ENABLE_DANGEROUS_FEATURES = true
```

如此，就会开启风险功能，会在右键菜单中新增三个选项，其中就有两个比较适用的功能：
1. 为所有无语言代码块添加语言
2. 批量替换代码块语言

这两个功能顾名思义，你可以在编辑文件的过程中，先不手动设置语言，之后在一次性添加。

![Snipaste_2024-01-26_16-33-32](https://github.com/obgnail/typora_plugin/assets/48992887/8714cf81-2707-4345-be9e-112ab1fee5ea)

**Comment by W1ndys** [comment]
> @W1ndys 你好，感谢反馈。
> 
> 先说结论：**做不到，但是可以曲线救国**。
> 
> ## 做不到的理由
> 类似的插件我曾经做过一版，但是效果很差。给出一段代码，推测代码的语言是很困难的，目前存在太多语法相似甚至相同的语言，比如 typescript、javascript、coffeescript 三者的代码可能完全相同。
> 
> 我也找过 github 上高星的项目，但是效果都不理想。
> 
> 一个最简单的例子，**强如 vscode，作为代码编辑软件，背靠软微，它在推测代码语言这点也是经常出错**。
> 
> 而且有个很大的问题就是：vscode 错了就错了，用户手动调整就行。但是这个插件需要货真价实的写入文件，就很麻烦。
> 
> 实际上，这个需求同样出现在 Typora 官方的 [issue](https://github.com/typora/typora-issues/issues/3661) 上，挂了 4 年同样没有任何进展。
> 
> ## 曲线救国方案
> 你可以修改配置文件，将 ENABLE_DANGEROUS_FEATURES 功能设置为 true。
> 
> ```
> [fence_enhance]
> # 在右键菜单中启用有风险的功能（此功能会消耗巨量资源并导致Typora长时间（几秒到几十秒）失去响应）
> ENABLE_DANGEROUS_FEATURES = true
> ```
> 
> 如此，就会开启风险功能，会在右键菜单中新增三个选项，其中就有两个比较适用的功能：
> 
> 1. 为所有无语言代码块添加语言
> 2. 批量替换代码块语言
> 
> 这两个功能顾名思义，你可以在编辑文件的过程中，先不手动设置语言，之后在一次性添加。
> 
> [![Snipaste_2024-01-26_16-33-32](https://private-user-images.githubusercontent.com/48992887/299924196-8714cf81-2707-4345-be9e-112ab1fee5ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTkyODMsIm5iZiI6MTcwNjI1ODk4MywicGF0aCI6Ii80ODk5Mjg4Ny8yOTk5MjQxOTYtODcxNGNmODEtMjcwNy00MzQ1LWJlOWUtMTEyYWIxZmVlNWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA4NDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZmQzNThkN2NmYzlhZDI3YjVkZGE2ZTc0NWE1YTJmNTMzNWIyNzQwMmZiOTlhMDgzODkwZDM3MmVjMmVkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rzfJEXfg8IbisO7eKzePZAw8p7HV5k54zWDru-SGRIc)](javascript:void(0))

明白了，感谢回复😊😊😊，十分感谢你的插件开发，给我带来很大的便利

**Comment by obgnail** [comment]
@W1ndys 

好的。此 issue 关闭，如有其他问题，麻烦在下面留言，或者另开 issue。
