### ISSUE TITLE
【bug】有时无法在代码块中输入中文右括号 "）"

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#444]
# 有时无法在代码块中输入中文右括号 "）"

下面是一个代码块

``` cpp
int main()
{
    //（
    return 0;
}
```

![PixPin_2024-01-27_15-49-42](https://github.com/obgnail/typora_plugin/assets/113878415/f3a22a73-f791-4355-b189-88345c161582)

先在代码块中输入中文左括号后，无法立刻输入中文右括号...

在代码块中输入中文左括号后，先在其他地方输入一些其他字符才可以继续输入中文右括号，或者干脆先打中文右括号再打中文左括号，问题不大，就是有的时候怪怪的...

> 注：貌似只有在代码块中才有这个问题，英文的括号或者在其他地方输入就不会，好像没有在之前的 `issue` 里看到类似的问题？

**Comment by obgnail** [comment]
@xiaogithubooo 你好，感谢反馈。

因为就没有做这个功能：

https://github.com/obgnail/typora_plugin/blob/320af5b34e7d64f01c2185224c26b059bff27504/plugin/custom/plugins/chineseSymbolAutoPairer.js#L1

> 因为我觉得在代码块里匹配中文括号，好像有点奇怪。

---

我看一下明天有没有空，有空的话做一下这个功能

**Comment by obgnail** [comment]
额，我刚刚理解错你的问题了…… 我重新看一下

**Comment by obgnail** [comment]
@xiaogithubooo 

已修复，代码在 dev 中，明天发版。

**Comment by obgnail** [comment]
@xiaogithubooo 

已发版，麻烦升级到最新版本试用一下。

此 issue 关闭，如有其他问题，方法在下面留言或者另开 issue。
