### ISSUE TITLE
关闭最后一个标签页的时候

### ISSUE THREAD

**Issue by Godlike-long** [obgnail/typora_plugin#449]
我习惯性的会使用"ctrl+w"去关闭typora。但是当标签页只剩一个的时候，使用"ctrl+w"关闭之后还是会展示出一个空白的编辑页面，这样有点难受🙃。。而且在这个页面再使用"ctrl+w"时是关不掉typora的

求助作者大大，这个不知是bug还是特性，因为在此之前的typora我是可以直接快捷键关掉的，目前所使用的typora版本为1.8.6

**Comment by RiftRays** [comment]
@Godlike-long 

这个版本将关闭最后一个标签的后默认关闭typora操作的配置改了。

```
[window_tab]
# 当关闭最后一个标签时，弹出弹窗确认是否退出Typora
RECONFIRM_WHEN_CLOSE_LAST_TAB = false
```

**Comment by obgnail** [comment]
@RiftRays @Godlike-long 

旧版本的  RECONFIRM_WHEN_CLOSE_LAST_TAB 配置好像不太够用，于是我移除了 RECONFIRM_WHEN_CLOSE_LAST_TAB，改成了 WHEN_CLOSE_LAST_TAB。

```toml
# 当关闭最后一个标签时:
#   reconfirm: 弹出弹窗确认是否退出Typora
#   exit:      退出Typora
#   blankPage: 展示空白页（此选项仅新版本Typora可用，低版本下此选项会自动修改为reconfirm）
WHEN_CLOSE_LAST_TAB = "blankPage"
```

@Godlike-long 
对于你的情况，可以这么做：
1. 升级到最新的插件版本，
2. 然后修改配置文件，将 WHEN_CLOSE_LAST_TAB 选项改成 `exit`。

具体如何修改配置，请阅读 [这里](https://github.com/obgnail/typora_plugin/blob/master/plugin/global/settings/%E8%AF%B7%E8%AF%BB%E6%88%91.md)

**Comment by obgnail** [comment]
@Godlike-long 

此 issue 关闭，如有使用上的问题，麻烦在下面留言或者另开 issue。
