### ISSUE TITLE
reopenClosedFiles失效

### ISSUE THREAD

**Issue by aldol-reaction** [obgnail/typora_plugin#455]
系统win，plugin和typora版本均为最新版本。
配置文件中关于reopenClosedFiles和window_tab均未修改。
用typora.exe打开后，之前右上角关闭的若干标签页并未还原。

**Comment by obgnail** [comment]
@aldol-reaction 感谢反馈。

这个插件很久没动了，应该是 Typora 1.8 版本的改动导致的。

我明天处理一下。

**Comment by obgnail** [comment]
@aldol-reaction 

你好，清明节安康。不好意思，拖了这么久。

这个 BUG 出现的原因是：Typora 没有做守护线程，后端关闭的时间可能早于前端关闭的时间，导致文件没有被保存。

我在新版本中，将保存文件的时间尽量提早了，因为能解决问题了。

**Comment by obgnail** [comment]
麻烦升级到最新版本，试用一下。

此 issue 暂时关闭，如有问题，麻烦在下面留言，或者另开 issue。
