### ISSUE TITLE
右键菜单没有显示

### ISSUE THREAD

**Issue by want-u** [obgnail/typora_plugin#47]
我看默认就是开启的，不知道哪里问题[挠头]
![image](https://github.com/obgnail/typora_plugin/assets/55751244/1912e827-438e-4ecc-bc95-c84cbfad3c03)

**Comment by obgnail** [comment]
@want-u 要在正文区域右键，不能在侧边栏

**Comment by want-u** [comment]
噢噢！几乎没在正文点过右键，了解了！

**Comment by want-u** [comment]
作者大大，另外有个问题是：一体化界面的时候Typora的菜单打不开了（我试了试ctrl+,快捷键不好使），比如我想导出为pdf文档

**Comment by obgnail** [comment]
> 作者大大，另外有个问题是：一体化界面的时候 Typora 的菜单打不开了（我试了试 ctrl+, 快捷键不好使），比如我想导出为 pdf 文档

我也不知道该怎么办。

因为 window_tab 把那个按钮挡住了。而且新版本已经把那个按钮移动到 ctrl+, 面板了。

你有什么好方法么？

![Snipaste_2023-08-01_17-51-16](https://github.com/obgnail/typora_plugin/assets/48992887/40e3dd29-0f97-4b98-9003-880cf83b1de0)
![Snipaste_2023-08-01_17-52-06](https://github.com/obgnail/typora_plugin/assets/48992887/ed6e220e-9be8-4d5c-90f6-a615b08414af)

**Comment by want-u** [comment]
取消隐藏的titleBar会导致标签页显示问题，不知道是否可以调整让标签页正常显示
![image](https://github.com/obgnail/typora_plugin/assets/55751244/83e22504-fae4-4ab4-89e5-6b3fe2fa8903)

**Comment by want-u** [comment]
我试着调了一下window_tab.js文件css中的top，随便改了个1，我觉得显示ok
![image](https://github.com/obgnail/typora_plugin/assets/55751244/bfc5e353-b068-4e57-bab7-eeebafeb2d43)
![image](https://github.com/obgnail/typora_plugin/assets/55751244/1d3d82bc-bdd4-4314-97e1-3cb84200ccd7)

**Comment by obgnail** [comment]
@want-u 感谢感谢。

这样的话，标签不在顶部也很奇怪，容易出现标签点不到，点错的情况。

使用无边框窗口最大的好处就是符合直觉。我根本不用看，鼠标直接顶到顶就是标签页，不用微调，点击就能跳转。

导出算是一个低频操作，而且这个问题只出现在低版本中，这样的修改可能得不偿失。

不过，这也是开源的意义，不必纵容万恶的产品经理，所有人都能根据自己的喜好设置。
