### ISSUE TITLE
【bug】在只读模式下，依旧可以删除图片

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#473]
在只读模式下，依旧可以删除图片，如下操作：

![PixPin_2024-02-17_18-04-01](https://github.com/obgnail/typora_plugin/assets/113878415/d10051b6-959b-4a03-9fca-ab23aa3143b6)

偶然发现的，虽然这么操作的可能性不大hhh

**Comment by obgnail** [comment]
@xiaogithubooo 

你好，感谢反馈。

这个 BUG，有 10% 算是 Typora 本身的锅：在 Locked 状态时，没有处理 context 事件。

但是 context 事件又怎么多，要一个个处理，处理不过来。于是我一不做二不休整了个 DISABLE_CONTEXT_MENU_WHEN_READ_ONLY 选项，**只读时直接禁用大部分的右键菜单**。

有兴趣可以升级试用一下。此 issue 关闭，如有问题或者改进方案，麻烦在下面留言，或者另开 issue。
