### ISSUE TITLE
【咨询】typora软件升级后插件除了重新安装还有其他办法保留不动吗？

### ISSUE THREAD

**Issue by BrazilAmando** [obgnail/typora_plugin#477]
最近typora升级了几次，每次升级完都要重新安装插件，比较麻烦，请问有什么方案可以在typora升级的情况下保留插件吗？谢谢！

**Comment by obgnail** [comment]
@BrazilAmando 

你好，感谢反馈。

1. typora 升级，势必会修改 window.html，导致插件系统失去入口，进而整个插件系统无法被调用。

2. 要想在 typora 升级时保留插件，必须要 hook 插件的升级流程。

3. 我看了一下后端源码，其升级逻辑是：在程序退出前，检测升级的安装包是否已经下载到本地，接着执行升级流程。

   ```js
   app.on('will-quit', function() {
       ...
   	if(isWin) {
   		app.updater && app.updater.installIfNeeded();
   	}
       ...
   });
   
   updater.installIfNeeded = function(){
     if(updater.installPathOnQuit) {
       updater.install(updater.installPathOnQuit);
     }
   }
   
   updater.install = function(fullPath){
     var cproc = require('child_process');
     cproc.spawn(fullPath, ['/SILENT'], {
       detached: true,
       stdio: ['ignore', 'ignore', 'ignore']
     }).unref()
   }
   ```

4. 现在的问题就是：

   1. 升级流程是纯后端操作，并不是前端通过 ipc 发送 install 信号控制后端实现的。hook 不住升级流程。
   2. 所以只能通过一些更绿皮的手段 hook，而且就算能 hook 住，这也是比较危险的操作。


---


PS：我不清楚升级操作会不会删除整个 plugin 文件，导致用户配置文件丢失。如果出现这种情况，你可以创建目录 `homeDir/.config/typora_plugin/` ，并在里面存放配置文件，而且这里的配置文件 **优先级最高**。

```bash
dir /b C:\Users\用户名\.config\typora_plugin

custom_plugin.user.toml
hotkey.user.toml
settings.user.toml
```

> 此方法适用于 Linux、Windows 平台。

**Comment by obgnail** [comment]
@BrazilAmando 

暂时想不到有更好的方法解决这个问题。后续找到了再重启此 issue。

总之，**升级完 Typora，重新双击运行一下 updater.exe 即可完成插件的重装**。
