### ISSUE TITLE
右上角markdown语法检查：1、没有关闭按钮；2、不能基于更新内容重新检查语法

### ISSUE THREAD

**Issue by CCT-maker** [obgnail/typora_plugin#478]

**Comment by obgnail** [comment]
@CCT-maker 

你好，感谢反馈。

1. 点击右上角的小方块，即可弹出弹窗；再次点击小方块，即可隐藏弹窗。
2. 插件支持实时更新检测的，需要你前往 Typora 的配置，开启自动保存功能。或者在编辑完毕后，手动 ctrl+S 保存文件。

有问题可以在下面留言。

**Comment by CCT-maker** [comment]
看着是点击语法错误序号自动进入源代码模式，修改再退出源代码模式会刷新语法错误列表，不影响使用，目前找到诀窍了






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obgnail/typora_plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 凌晨0:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obgnail/typora_plugin] 右上角markdown语法检查：1、没有关闭按钮；2、不能基于更新内容重新检查语法 (Issue #478)





 
@CCT-maker
 
你好，感谢反馈。
  
点击右上角的小方块，即可弹出弹窗；再次点击小方块，即可隐藏弹窗。
 
插件支持实时更新检测的，需要你前往 Typora 的配置，开启自动保存功能。或者在编辑完毕后，手动 ctrl+S 保存文件。
  
有问题可以在下面留言。

**Comment by obgnail** [comment]
@CCT-maker 

此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue
