### ISSUE TITLE
I completely follow the tutorial to the author, but the right-click does not appear after the plugin logo

### ISSUE THREAD

**Issue by Coinsi** [obgnail/typora_plugin#495]
I am a Windows system.New Typora, What Should I Do?

**Comment by obgnail** [comment]
@Coinsi  

hi. is there a button group in the bottom right corner of Typora? if there is, it seems like you clicked in the wrong spot - you should be right-clicking in the writing area instead.

![Snipaste_2024-02-29_20-05-40](https://github.com/obgnail/typora_plugin/assets/48992887/fed82a15-4ae6-4b2b-a9df-c9a0e8fe5d55)

**Comment by obgnail** [comment]
@Coinsi 

close this issue. if you have any questions, feel free to leave a message below or open a new issue
