### ISSUE TITLE
只读的小问题

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#497]
很抱歉，由于我经常害怕自己的文件被意外修改，导致我使用只读模式进行 文本复制 和 文本查找 的次数比较多，因此经常发现一些可能有点刁钻的 `bug`？：只读模式下可以通过 `替换` 来修改文本。

![PixPin_2024-02-29_14-20-32](https://github.com/obgnail/typora_plugin/assets/113878415/3fa7d87a-7d7f-48f6-9952-13390b2ec22f)

不过像我这么操作导致文本意外修改的概率貌似也不大...

另，使用插件很久了，很喜欢这些插件，非常感谢您。

**Comment by obgnail** [comment]
@xiaogithubooo 

您好，感谢反馈。用的很深入 👍 

已经修复，预计明天发版。

---
Q：为什么【只读模式】狡兔三窟？
A：Windows 本身并没有文件写入权限相关的 API，并没有一劳永逸的解决方法。也就是说：**由于操作系统限制，【只读模式】无法做到从根本上的只读，只是想尽一切方法去阻止 Typora 修改文件罢了**。条条大路通罗马，在无法给罗马加盖的前提下，如何阻止人们前往罗马？答：堵路，出现一条堵一条。这也是为什么需要像您一样的用户反馈的原因 —— 我无法找出所有 Typora 修改文件的事件。

**Comment by obgnail** [comment]
@xiaogithubooo 

新版本已经发布。此版本对 read_only 做了小重构，提升了性能。

此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。

**Comment by obgnail** [comment]
PS：如果遇到 BUG，请尽量反馈，不必有心理负担。
