### ISSUE TITLE
关于导出和查找的几点小优化和一个疑惑

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#500]
## 1.导出时代码块内容不完整
在代码块插件中，可以设置折叠，但是导出文件时会出现一些问题（例如导出为 `PDF`、`HTML`），代码块只包含折叠后的内容，如下視頻：

https://github.com/obgnail/typora_plugin/assets/113878415/56243782-6b2f-4f5d-8eda-fe37e4244fd3

能否先将代码块全部展开，再进行文件导出？（这里的导出是指 `Typora` 内置的导出，不是指第三方导出工具）

## 2. 只读模式下查找有点小问题
如果以只读模式首次打开一个 `.md` 文件，无法使用查找（这里的查找指 “多关键字查找” 和 “多关键字高亮”），如下視頻：

https://github.com/obgnail/typora_plugin/assets/113878415/f5232f97-62b2-42ad-af0b-317dcb1bc83e

但是手动解开只读模式再关闭又可以使用插件进行查找了。官方自带的查找倒是无论是否只读模式都可以进行查找。

## 3. 一点疑惑
我没有关闭 `pluginUpdater` 插件，也没有关闭 `commander` 插件，但是我右键菜单里确实没有 `右键菜单 -> 常用插件 -> 自定义插件 -> 升级插件` 这个选项，这是为什么呢？是我哪里误操作了吗？（虽然没有太大影响，单纯比较好奇）

![aaa2bbe2e81517fb8b70f88a2630f11](https://github.com/obgnail/typora_plugin/assets/113878415/ca220eca-01b1-4547-a6b9-39968b2662b9)

![189af289e3a2a3792d6b5795eb30e88](https://github.com/obgnail/typora_plugin/assets/113878415/05c7c33e-6811-46f5-bae4-3c81f8e789b0)

**Comment by obgnail** [comment]
@xiaogithubooo 

你好，感谢反馈。

问题 1、2 已经解决。预计今晚发版。

---

问题 3，提问：

是否存在这个文件：.\plugin\updater\updater.exe

> 你可以使用 everything 找一下关键字 `plugin\updater\updater.exe`

## 若不存在

大概率是被杀毒软件干掉了。进入[这个页面](https://github.com/obgnail/typora_plugin/blob/master/plugin/updater/updater.exe)下载文件并放回原位即可。

## 若存在

麻烦回答下面问题：

1. typora_plugin 的版本？
2. 此 BUG 是什么时候出现的？还是说一直都是这样？
3. 是否存在这个选项：`右键菜单 -> 非常用插件 -> 帮助 -> 升级插件`

---

# PS 
如果存在上述 updater.exe 文件，你可以以管理员身份打开终端，执行下面命令完成插件升级：
```bash
# 注意updater.exe改成你的路径
# proxy参数：你的代理URL。如果你所在地区能直连GitHub，可以删除此参数
D:/software/typora/resources/plugin/updater/updater.exe --action=update --proxy=http://127.0.0.1:7890
```

**Comment by xiaogithubooo** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/113878415/ffb3aa07-a9e2-4e4d-88d9-0919233ba588)

确实没有，重新下载回来了，现在右键菜单可以看见了

![image](https://github.com/obgnail/typora_plugin/assets/113878415/f16115ed-4da8-4a0f-a190-315abd605470)

![image](https://github.com/obgnail/typora_plugin/assets/113878415/4d43bb52-06c0-4c3d-b74a-ce648ca8ec2a)

不过我的电脑只有一个 Windows 安全中心 🫢

**Comment by obgnail** [comment]
@xiaogithubooo 

所有问题已经解决，新版本已经发布。麻烦升级到最新版本。

> 如何升级请查看：[如何升级插件？](https://github.com/obgnail/typora_plugin?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E5%8D%87%E7%BA%A7%E6%8F%92%E4%BB%B6)

此 issue 关闭，如果有问题，麻烦在下面留言或者另开 issue。
