### ISSUE TITLE
请问callouts插件可以应用在hexo博客中吗, 如果可以该怎么使用?

### ISSUE THREAD

**Issue by fzt1106** [obgnail/typora_plugin#503]

**Comment by obgnail** [comment]
@fzt1106 你好，感谢反馈。

typora_plugin 和 hexo 没有任何关系。如果你希望 hexo 支持 callouts 语法，可以搜索安装 hexo 的 callouts 插件

> chatGPT：要让 Hexo 支持 Markdown 的 callouts 语法，您可以使用 Hexo 的插件系统来实现。一种常见的方法是使用 Hexo 的自定义标签插件，在 Markdown 中添加自定义标签来实现 callouts 效果。您可以编写一个自定义标签插件，通过在 Markdown 中插入特定的标签来生成 callouts 样式的内容。另一种方法是使用 Hexo 的渲染器插件，例如 hexo-renderer-marked，在 Markdown 解析过程中添加对 callouts 语法的支持。您可以查找现有的 Markdown 插件或编写自己的插件来扩展 Hexo 的 Markdown 解析功能，实现对 callouts 语法的支持。无论您选择哪种方法，确保插件与 Hexo 的版本兼容，并遵循 Hexo 的插件开发规范。在实现完支持后，您可以在 Markdown 中使用 callouts 语法来突出显示特定内容，从而增强文章的可读性和可视性。

**Comment by obgnail** [comment]
@fzt1106 

此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
