### ISSUE TITLE
是否可加入同步数据功能

### ISSUE THREAD

**Issue by fu9809** [obgnail/typora_plugin#506]
Typora 没有自带数据同步功能，使用git同步老是会忘记，而且不方便。
各种支持Markdown语法的云笔记，都有云服务的功能，但是用起来不如Typora。

是否可以实现一个同步数据的功能？

我的思路是，可以选定一个文件夹，做为工作区，然后可以挂载webdav，实现文件的同步。
各大云盘和各种笔记软件是怎么实现云同步的，不太清楚，不知道插件能不能实现这个功能？

看了几个issues ，大佬说选用 dropbox，但是我不太想使用其他的软件。
#405  #335

**Comment by xiaogithubooo** [comment]
直接定时使用 `git` 进行同步怎么样？直接编写一个定时的自动脚本每天同步到 `github`。

**Comment by obgnail** [comment]
1. 同步必须要有服务器，不是别人的就是自己的，你说不想用其他的软件，那么就必须自己提供服务器。
2. 自动同步到自己的服务器，自己写通讯协议不太现实，大概率采用现成的协议（webdav 或者其他成熟的协议）。
3. 同时，文件同步要采用增量备份，自己写 diff 算法也不现实，大概率还是找现成的轮子。
4. 这么一来，基本上就是采用现成的轮子拼起来一个玩具，稳定性堪忧。
5. 而且有个致命问题，typora_plugin 是依附于 typora 的，也就是说，只有 typora 启用时，同步服务才能运行，关闭就没了。

---

如果你不想采用商用的软件，其实可以找一个现成的开源的同步应用。

我推荐 rsync + inotify：
- inotify：负责文件监控。
- rsync ：负责同步，Linux 发行版都自带它。如果是 windows 平台就用 rsync for windows（或者直接用 WSL）。完全开源，体积小巧，增量备份，方便快捷。

上面绝对可行，实际上我的 githubPage 就是采用上述方案实现自动更新的。有兴趣可以参考下面的 AutoHexo 项目。

参考网址：
- [我的 AutoHexo 项目](https://github.com/obgnail/AutoHexo)
- [阮一峰的 rsync 用法教程](https://www.ruanyifeng.com/blog/2020/08/rsync.html)

**Comment by fu9809** [comment]
感谢大佬😘



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月13日 01:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [obgnail/typora_plugin] 是否可加入同步数据功能 (Issue #506) |

同步必须要有服务器，不是别人的就是自己的，你说不想用其他的软件，那么就必须自己提供服务器。
自动同步到自己的服务器，自己写通讯协议不太现实，大概率采用现成的协议（webdav 或者其他成熟的协议）。
同时，文件同步要采用增量备份，自己写 diff 算法也不现实，大概率还是找现成的轮子。
这么一来，基本上就是采用现成的轮子拼起来一个玩具，稳定性堪忧。
而且有个致命问题，typora_plugin 是依附于 typora 的，也就是说，只有 typora 启用时，同步服务才能运行，关闭就没了。

如果你不想采用商用的软件，其实可以找一个现成的开源的同步应用。

我推荐 rsync + inotify：

inotify：负责文件监控。
rsync ：负责同步，Linux 发行版都自带它。如果是 windows 平台就用 rsync for windows（或者直接用 WSL）。完全开源，体积小巧，增量备份，方便快捷。

上面绝对可行，实际上我的 githubPage 就是采用上述方案实现自动更新的。有兴趣可以参考下面的 AutoHexo 项目。

参考网址：

我的 AutoHexo 项目
阮一峰的 rsync 用法教程
