### ISSUE TITLE
导出为HTML。代码块的没有复制按钮。

### ISSUE THREAD

**Issue by TKsatty** [obgnail/typora_plugin#507]
开启了代码块复制按钮，但是导出为HTML。代码块没有复制按钮。是我使用的操作有问题吗？还是没有这个功能呢？

**Comment by obgnail** [comment]
@TKsatty 

你好，感谢反馈。

1. 导出时是不会有复制按钮的。
2. 和其他多数产品一样，导出的文件是【看的】，而不是【用的】。所以 **导出的文件会移除所有交互，只剩下显示功能**。
3. 导出 HTML 文件，尚且可以通过添加 JS 代码实现一键复制功能，如果导出的是 图片，PDF 这类完全不支持交互的文件，从原理上就无法实现。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
