### ISSUE TITLE
混排优化问题

### ISSUE THREAD

**Issue by lxb9764** [obgnail/typora_plugin#510]
对于正文中127.0.0.1:8082这样的字符串，优化之后会变成127.0.0.1: 8082

**Comment by obgnail** [comment]
@lxb9764 

你好，感谢反馈。

我认为这样是合理的，因为：
1. 在 markdown 语法中，裸 url 推荐使用尖括号 <> 包裹
2. md_padding 不应该验证文本是否为 url

也就是说，正文中 127.0.0.1:8082 应该写成 
```markdown
<127.0.0.1:8082>
```

---

参考网址： [url语法](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses)。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
