### ISSUE TITLE
使用中英文混排之后会导致网址之类的url错误

### ISSUE THREAD

**Issue by mikuBaymax** [obgnail/typora_plugin#516]
如图所示
![miku_2024-03-16_10-33-18](https://github.com/obgnail/typora_plugin/assets/100461237/9d698afb-e5bf-4651-a080-2f4cd7912f3e)

**Comment by obgnail** [comment]
@mikuBaymax 

你好，感谢反馈。

解决方案参考 #510

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
