### ISSUE TITLE
在typora中用ctrl+p方式打开不同MD文件，两个标签的内容变成一样的了，如下截图

### ISSUE THREAD

**Issue by freemagnet** [obgnail/typora_plugin#517]
![11](https://github.com/obgnail/typora_plugin/assets/19940462/6c1b4eda-dba9-45d3-981d-3bd9d4563e9f)
![22](https://github.com/obgnail/typora_plugin/assets/19940462/9983fe22-6c82-4e81-aebd-2c7c1ab28222)
![33](https://github.com/obgnail/typora_plugin/assets/19940462/bdaf1d26-1b9b-41d7-8fe0-01aac29fdf0c)
![55](https://github.com/obgnail/typora_plugin/assets/19940462/2a4d82e2-a287-463e-81c9-a3ee814f3014)

**Comment by freemagnet** [comment]
两个标签的内容是不同的，但打第二个标签后，第一个标签的内容变成了第二个标签的内容

**Comment by obgnail** [comment]
@freemagnet 

你好，清明节安康。

不好意思，拖了这么久。

新版本已经修复，麻烦升级到最新版本试用一下。

**Comment by freemagnet** [comment]
收到谢谢！我后面更新试试
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年04月04日 17:58 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [obgnail/typora_plugin] 在typora中用ctrl+p方式打开不同MD文件，两个标签的内容变成一样的了，如下截图 (Issue #517) 
Closed #517 as completed.
