### ISSUE TITLE
笔记加密功能

### ISSUE THREAD

**Issue by constwill22** [obgnail/typora_plugin#518]
如题, 可否增加一个笔记或markdown文件加密功能?

**Comment by obgnail** [comment]
@constwill22 

你好，感谢反馈。新版本已经添加插件【cipher】，麻烦升级到新版本试用。

> 使用方式：右键菜单 -> 非常用插件 -> 加密文件

此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
