### ISSUE TITLE
右键面板优化问题

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#527]
## 右键面板的优化

有时快捷键太多记不清，迫不得已需要用鼠标直接操作，但有时我让 `typora` 占据的屏幕空间较小，右键鼠标时弹出的窗口会互相重叠（`typora` 本自带的功能窗口倒是不会出现这种情况），以下是演示例子：

### typora 本身的功能弹窗（不会重叠）

![recording](https://github.com/obgnail/typora_plugin/assets/113878415/3ce047c0-cd5c-4964-b3a1-b7a577215ca4)

### 插件的功能弹窗（窗口重叠）

![recording](https://github.com/obgnail/typora_plugin/assets/113878415/205dd237-9442-47b3-8dfa-efbafb62db99)

> 这种可以自己在插件设置内调整么？

**Comment by obgnail** [comment]
@xiaogithubooo 

你好，已经处理，预计今晚发版。

对于第三级菜单超出窗口的情况，我采取了和 jetbrains 相同的策略：折回去。

![img_2024-03-24_13-31-33](https://github.com/obgnail/typora_plugin/assets/48992887/6cadc336-03af-42b7-ba91-f3134fbb5143)

**Comment by obgnail** [comment]
@xiaogithubooo 

新版本已发布。

此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
