### ISSUE TITLE
md_paddin 中英文混排优化  相关问题

### ISSUE THREAD

**Issue by wlping265** [obgnail/typora_plugin#538]
![image](https://github.com/obgnail/typora_plugin/assets/36145406/9f01383e-1ad2-4bc7-b6a6-a603a31a435e)
![image](https://github.com/obgnail/typora_plugin/assets/36145406/e091cf62-e6eb-4828-8934-35869b5b00c9)

**Comment by wlping265** [comment]
再加一个问题， 标注3 的注释部分感觉前面被分割也不合理

**Comment by obgnail** [comment]
@wlping265 

你好，感谢反馈。
## 问题 4

在 markdown 语法中，裸 url 需要使用尖括号 <> 包裹。参考网址： [url 语法](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses)



## 问题 3

 **`:X:` 并不是 markdown 的原生语法**。

对于形如 `:X:` 的字符串：

- `:happy:` 要翻译为 emoji，所以不能加空格；

- `:meanlessWord:` 没有对应的 emoji，所以需要加空格。

也就是说，要实现此功能就需要维护 emoji 的单词表。

你可以通过修改配置文件实现需求：打开 `\plugin\global\settings\settings.user.toml`，添加如下内容

```toml
[md_padding]
# 不希望拆分的词组：
# Typora\resources\appsrc\editor\EmojiSearchMap.js 里面有全部的emoji
IGNORE_WORDS = [":happy:", ":cactus:"]
```

> 我并不推荐使用这个 emoji 语法，这个是 Typora 的自定义语法，换到其他的 markdown 编辑器是无法显示的。
> 
> 这种翻译语法其实是旧时代的产物，目前 Unicode 已经支持 emoji 了，如果你希望使用 emoji，我建议使用 emoji 本体。参考网址：[unicode-full-emoji-list](https://unicode.org/emoji/charts/full-emoji-list.html)
>
> unicode 的通用性完全不必担心。实际上，我甚至代码中都使用了 emoji，比如https://github.com/obgnail/typora_plugin/blob/a632495d67cfb039b6bc74fcd31f846d87055cf9/plugin/preferences.js#L47



## 问题 1、2

- 问题 1 是 HTML 语法解析问题；
- 问题 2 是 HTML 语义解析问题。

目前 md_padding 不含 HTML 语法/语义解析器，暂时无法解决。

完整的 HTML 语法解析器体积很大，语义解析器更大。让 md_padding 理解 `<br />` 表示换行，所以不要加空格；`<select />` 表示选择，所以不加空格 并不是件容易的事情。



---



对于不希望拆分的词组，目前绕过方式有三：

- 修改配置文件，将词组加入 `IGNORE_WORDS`
- 使用单引号包裹
- 使用尖括号包裹
