### ISSUE TITLE
禁用图片自动编号和代码自动编号，重启typora之后又打开了

### ISSUE THREAD

**Issue by MuZzzlen** [obgnail/typora_plugin#541]

**Comment by MuZzzlen** [comment]
没有永久关闭

**Comment by MuZzzlen** [comment]
大佬，菜菜，救救呜呜呜呜

**Comment by MuZzzlen** [comment]
看到了大佬的设置了 image和fence设为false！！

**Comment by obgnail** [comment]
@MuZzzlen 

打开文件 `\plugin\global\settings\settings.user.toml`，添加如下内容

```toml
[auto_number]
# 启用表格自动编号
ENABLE_TABLE = false
# 启用图片自动编号
ENABLE_IMAGE = false
# 启用代码块自动编号
ENABLE_FENCE = false
```

**Comment by MuZzzlen** [comment]
TOC设为true之后，仍然没有自动开启

**Comment by MuZzzlen** [comment]
展开大纲目录TOC是true 但是没有自动开启

**Comment by obgnail** [comment]
@MuZzzlen 

我猜你理解错 toc 了。

参考：[typora_support](https://support.typora.io/TOC/)

![img_2024-04-01_18-34-43](https://github.com/obgnail/typora_plugin/assets/48992887/efeef38f-53d3-4e08-ae25-5ac96e781e80)

**Comment by MuZzzlen** [comment]
> @MuZzzlen
> 
> 我猜你理解错 toc 了。
> 
> 参考：[typora_support](https://support.typora.io/TOC/)
> 
> ![img_2024-04-01_18-34-43](https://private-user-images.githubusercontent.com/48992887/318410373-efeef38f-53d3-4e08-ae25-5ac96e781e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjgzMzYsIm5iZiI6MTcxMTk2ODAzNiwicGF0aCI6Ii80ODk5Mjg4Ny8zMTg0MTAzNzMtZWZlZWYzOGYtNTNkMy00ZTA4LWFlMjUtNWFjOTZlNzgxZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNjYyNDBkOTFlMzUwOGQ0NmQwZTU5NzRhMmViZGQ3ZGIzMGMxMTU4MWU1NjY3MDc4ZmRmOGE0ZTA5NzBiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKkfXKJPhCu7dd-HJ3Ry3T-I5BS4NeYa120hqmGhpec)

大佬，那右侧大纲目录打开应该设置哪个啊，我看你的说明里是toc

**Comment by MuZzzlen** [comment]
> @MuZzzlen
> 
> 我猜你理解错 toc 了。
> 
> 参考：[typora_support](https://support.typora.io/TOC/)
> 
> ![img_2024-04-01_18-34-43](https://private-user-images.githubusercontent.com/48992887/318410373-efeef38f-53d3-4e08-ae25-5ac96e781e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjgzMzYsIm5iZiI6MTcxMTk2ODAzNiwicGF0aCI6Ii80ODk5Mjg4Ny8zMTg0MTAzNzMtZWZlZWYzOGYtNTNkMy00ZTA4LWFlMjUtNWFjOTZlNzgxZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNjYyNDBkOTFlMzUwOGQ0NmQwZTU5NzRhMmViZGQ3ZGIzMGMxMTU4MWU1NjY3MDc4ZmRmOGE0ZTA5NzBiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKkfXKJPhCu7dd-HJ3Ry3T-I5BS4NeYa120hqmGhpec)

![image](https://github.com/obgnail/typora_plugin/assets/100769574/79f3fa49-7c7c-447a-b0aa-c61c3ddc8ab2)

**Comment by obgnail** [comment]
那个指的是 toc 插件。同名而已

![img_2024-04-01_18-43-13](https://github.com/obgnail/typora_plugin/assets/48992887/3a75d883-36fb-4cc2-88b6-94434bed4677)

**Comment by MuZzzlen** [comment]
> 那个指的是 toc 插件。同名而已
> 
> ![img_2024-04-01_18-43-13](https://private-user-images.githubusercontent.com/48992887/318412005-3a75d883-36fb-4cc2-88b6-94434bed4677.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Njg2NzksIm5iZiI6MTcxMTk2ODM3OSwicGF0aCI6Ii80ODk5Mjg4Ny8zMTg0MTIwMDUtM2E3NWQ4ODMtMzZmYi00Y2MyLTg4YjYtOTQ0MzRiZWQ0Njc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwNDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNzNkNmRlZWIwNGIwNTA3YmE2OGRkYThkZGE2ZjIyNDk4YWQ1MzY1ODFlNWY4ZmRmMTgyY2JlYmMwNWViMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R8cNx4CDrzgWLR4mXUGrOiUOYsZPUT0CNf08H9WYgHk)

这里我知道 但是每次都是手动开启 无法实现自动吗
![image](https://github.com/obgnail/typora_plugin/assets/100769574/720f26f0-e854-41d5-8d13-d6e6c56bad34)

**Comment by obgnail** [comment]
你是需要每次打开 Typora 时自动弹出右侧的大纲目录吗？

**Comment by MuZzzlen** [comment]
> 你是需要每次打开 Typora 时自动弹出右侧的大纲目录吗？

是的！！

**Comment by obgnail** [comment]
> 展开大纲目录 TOC 是 true 但是没有自动开启

哦哦哦，我理解错你的意思了，之前都在说 auto_number，我以为你说的是 auto_number 的 ENABLE_TOC 选项。结果你说的 toc 这个插件……

答：没做。主要是我从来不关闭 Typora，没有默认打开的需求，要不你给他设置个快捷键？
```toml
[toc]
[toc.config]
# 快捷键
hotkey = ""
```

不过要加个默认打开的配置选项也不难，你要么？

**Comment by MuZzzlen** [comment]
> > 展开大纲目录 TOC 是 true 但是没有自动开启
> 
> 哦哦哦，我理解错你的意思了，之前都在说 auto_number，我以为你说的是 auto_number 的 ENABLE_TOC 选项。结果你说的 toc 这个插件……
> 
> 答：没做。主要是我从来不关闭 Typora，没有默认打开的需求，要不你给他设置个快捷键？
> 
> ```toml
> [toc]
> [toc.config]
> # 快捷键
> hotkey = ""
> ```
> 
> 不过要加个默认打开的配置选项也不难，你要么？

需要需要 ！！对我很有用的这个！ 如果大佬有空的时候能写一下我真是感谢！！！

**Comment by obgnail** [comment]
@MuZzzlen 

需求完成了，添加了配置选项 default_show_toc，加了三行代码。commit 在[这里](https://github.com/obgnail/typora_plugin/commit/45a23926f52ef3a33f4f64dd3f710f325508e0a3)

今晚发版，你明天升级一下插件，default_show_toc 选项默认是 false，到时记得修改为 true

**Comment by MuZzzlen** [comment]
> @MuZzzlen
> 
> 需求完成了，添加了配置选项 default_show_toc，加了三行代码。commit 在[这里](https://github.com/obgnail/typora_plugin/commit/45a23926f52ef3a33f4f64dd3f710f325508e0a3)
> 
> 今晚发版，你明天升级一下插件，default_show_toc 选项默认是 false，到时记得修改为 true

谢大佬！！！！！！！

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。

**Comment by obgnail** [comment]
@MuZzzlen 

新版本已发布，麻烦升级到最新版本试用一下。

**Comment by MuZzzlen** [comment]
> @MuZzzlen
> 
> 新版本已发布，麻烦升级到最新版本试用一下。

很好用，拜谢大佬！！
