### ISSUE TITLE
开发者提问：各位觉得【插件升级】功能需要脚本化吗？

### ISSUE THREAD

**Issue by obgnail** [obgnail/typora_plugin#548]
最近 XZ 投毒的事影响挺大的（我也中毒了，但是因为本地运行所以不受影响）。有不少用户觉得 updater.exe 报毒的事需要解决。

---

我当初设计的时候，主要是考虑到浏览器环境的 fetch 函数无法设置代理，非常受限（跨域什么的很麻烦），node 的 HTTPS 库用起来究极折磨，所以一拍脑门就决定使用 go 实现了。

目前已知的问题：

1. 因为编译生成的 updater.exe 在更新时需要删除文件，Windows 可能会报毒。
2. 如果 Typora 安装在 Program Files 目录下有可能因为权限问题导致无法执行。
3. Linux 环境无法执行 exe。
4. 还有一点就是我的洁癖，整个插件系统 10M+，其中这个 exe 文件占了 6.7M。

---

开发者提问：
1. 您使用过升级插件功能吗？
2. 是否由于上述原因导致无法升级？
3. 您觉得是否需要使用 node 重写？
4. 如果重写，需要保留 updater.exe 吗？

**Comment by xiaogithubooo** [comment]
1. 使用过升级插件，每次版本更新都会使用
2. Windows 下都可以顺畅进行升级，但是我曾经给我另外一台 Ubuntu 电脑安装过插件，由于没啥时间鼓捣，基本都是手动 clone 然后替换插件相关文件的
3. 我不清楚
4. 都可以
