### ISSUE TITLE
关于插件 json_rpc 的一些疑惑

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#549]
# 关于插件 json_rpc 使用的疑惑

这几天我需要对我的文件做一些批量化的操作，所以希望使用 `json_rpc` 插件来实现，但是遇到了一些问题。

## 1. 说明文档里的 python 代码？

[说明文档](https://github.com/obgnail/typora_plugin/blob/master/plugin/json_rpc/%E8%AF%B7%E8%AF%BB%E6%88%91.md) 里有下面这段 `python` 代码如下：

``` python
from jsonrpc import JSONRPCClient

client = JSONRPCClient('http://localhost:5080')

print(client.call('ping'))
client.call('callPluginFunction', ["search_multi", "call"])
client.call('eval', ["console.log(this, File)"])
```

这个 `JSONRPCClient` 是哪来的？我下载了 `jsonrpc` 的相关模块，包括查阅了相关资源，好像并没有这个类？

或许是我安装错模块了？始终无法找到这个 `JSONRPCClient`。

于是我重写了另外一份类似的代码：

``` python
import requests

# 定义 JSON-RPC 请求的基本信息
url = 'http://localhost:5080'
headers = {'content-type': 'application/json'}

# 发送 JSON-RPC 请求
def send_json_rpc_request(method, params=None):
    payload = {
        "jsonrpc": "2.0",
        "method": method,
        "id": 1
    }
    if params is not None:
        payload["params"] = params
    
    response = requests.post(url, json=payload, headers=headers)
    return response.json()

# 发送 callPluginFunction 请求
call_plugin_response = send_json_rpc_request('callPluginFunction', ["search_multi", "call"])
``` 

通过这份代码的话，就确实可以在 `typora` 外部操作插件了。

## 2.如何传递参数？

我只使用过一点点 `JS` 代码，不算特别了解（正在学习中，所以看不太懂插件的具体实现方式），我应该如何传递一些关键的参数呢？

例如：

- 能否使用 `search_multi` 插件的同时，传递我需要查找的关键字？
- 能否选取不同的文件进行查询而不是 `typora` 当前打开的文件里查询？
- ...

如果可以，能否给出更多关于 `json_rpc` 插件的使用例子，真的非常感谢~

> 另外，恭喜 `1k Star`，真的非常感谢您~

**Comment by obgnail** [comment]
忘记说了一点，之前的代码有问题，你要先升级插件

**Comment by xiaogithubooo** [comment]
非常感谢，我有时间再试一试！

**Comment by obgnail** [comment]
此 issue 暂时关闭，如有问题，麻烦在下面留言，或者另开 issue。
