### ISSUE TITLE
[优化] 章节折叠在大文件下，会直接导致软件崩溃无反应。

### ISSUE THREAD

**Issue by RiftRays** [obgnail/typora_plugin#553]
版本号：1.8.10
插件版本号：1.8.20

1. 【章节折叠】 在大文件下，会直接导致软件崩溃无反应
2. 【章节折叠】 STRICT_MODE = true 似乎并未生效。如图1。好像全部折叠显示到了排序上。
3. 【章节折叠】 折叠按钮有时候显示出来很突兀的感觉。如图2。
4. 【启停插件】 操作后，弹出重启typora，点击确认后无反应。
5. 【其他问题】 升级1.8.20后软件打开大文件会变得很卡顿。（在关闭了章节折叠）

图1：
![image](https://github.com/obgnail/typora_plugin/assets/60778141/6c043392-46ce-40f8-b964-2cd596201924)
图2：
![image](https://github.com/obgnail/typora_plugin/assets/60778141/0af16685-9543-43f0-9406-a430eaf9af2e)

**Comment by RiftRays** [comment]
@obgnail 感觉现在的版本好像会让软件变得很卡。应该不是软件原因吧。感觉没有之前的版本湿滑。

**Comment by obgnail** [comment]
@RiftRays 

你好，感谢反馈。



## 【启停插件】 操作后，弹出重启 typora，点击确认后无反应

没做重启功能，弹窗只是一个提示而已。点击确定就重启我怕被打。



## 【章节折叠】 折叠按钮有时候显示出来很突兀的感觉。

我后续想想怎么搞。



## 【章节折叠】 STRICT_MODE = true 似乎并未生效。好像全部折叠显示到了排序上。

没有理解什么意思。麻烦具体解释一下。

1. collapse_paragraph 的 STRICT_MODE 选项
   1. 若为 false：若没有点击到 h1-h6，会自动向上寻找最近的 h1-h6，并触发折叠/展开。
   2. 若为 true：必须严格点击到 h1-h6。
2. collapse_paragraph 的 STRICT_MODE 选项默认就是为 true。为 true 的话就是不会自动向上寻找的。
3. 【章节折叠】和 【列表折叠】的触发事件不一样，两者互不干预。
   1. 章节折叠是 ctrl+click h1~h6；
   2. 列表折叠是 click 右上角的三角图标



## 【其他问题】 升级 1.8.20 后软件打开大文件会变得很卡顿。（在关闭了章节折叠）

我这阵子的更新都基本不吃资源，能具体解释一下吗？

- 是 1.8.19 升级到 1.8.20 后变卡吗？理论上不太可能，因为 [1.8.20 的更新](https://github.com/obgnail/typora_plugin/compare/1.8.19...1.8.20) 很小，相反应该更快才对。
- 还是关闭了章节折叠插件后变卡，不关闭插件反而更丝滑？
- 你的上一个插件版本是多少？
- 卡顿具体是指刚打开的时候很卡吗？还是在编辑的时候很卡？

可以的话，麻烦提供一下你的配置文件，我看在本地能否复现。在【右键菜单 -> 非常用插件 -> 帮助 -> 备份配置文件】即可生成一份新的配置文件目录。



## 【章节折叠】 在大文件下，会直接导致软件崩溃无反应

我在 300K 的文件试了一下，没问题。麻烦具体描述一下。

如果可以的话，麻烦提供脱敏后的文件，我看能不能复现。

**Comment by obgnail** [comment]
右小角的小三角形是新的插件【列表折叠】的功能，并不是【章节折叠】的新功能。可能你是搞错这点了？

![collapse (1)](https://github.com/obgnail/typora_plugin/assets/48992887/fc7d8542-8a5b-4b7e-850b-bcf9d7942753)

**Comment by RiftRays** [comment]
@obgnail 

> 没做重启功能，弹窗只是一个提示而已。点击确定就重启我怕被打。

求生欲满满啊，哈哈

>  STRICT_MODE = true

这个好像是我搞混淆了，一下子跨了好多版本有点陌生了。

> 版本号

具体的我不记得了，我的应该还是2月中旬的版本，3月至今没写过内容就没升级过。忙其他事情了。感觉很卡。关了插件（整个）后是湿滑的。我有空回退到2月中旬左右的再试试看。（好像我有备份在本地一个）

> 卡顿具体是指刚打开的时候很卡吗？还是在编辑的时候很卡？

刚打开的时候非常非常非常非常卡顿！非常！在编辑的时候还好，但是在大文件的时候直接崩了。我非常确定2月份的那个版本没有崩。我2月还对那个大文件进行编辑过。

> 我在 300K 的文件试了一下，没问题。麻烦具体描述一下。

字数大概在35W，内容：代码、图片、文字，大纲很长。很多h1-h6。

**Comment by RiftRays** [comment]
> 列表左上角的小三角形是新的插件【列表折叠】的功能，并不是【章节折叠】的新功能。可能你是搞错这点了？
> 
> ![collapse (1)](https://private-user-images.githubusercontent.com/48992887/320793362-fc7d8542-8a5b-4b7e-850b-bcf9d7942753.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzUxODAsIm5iZiI6MTcxMjczNDg4MCwicGF0aCI6Ii80ODk5Mjg4Ny8zMjA3OTMzNjItZmM3ZDg1NDItOGE1Yi00YjdlLTg1MGItYmNmOWQ3OTQyNzUzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OWRhOTQwMzBiZmRjMWVjNjcwZWRiNTA0MTIxY2I3OWNjYmJlOTdmNzdkOTFhOGRiYTEwNTRkZjk4M2ZlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8VuQ-mD9Hz8o3dlWJ6lyJu_oy6OfTSMUYBZjI6mEpNE) [ ![collapse (1)](https://private-user-images.githubusercontent.com/48992887/320793362-fc7d8542-8a5b-4b7e-850b-bcf9d7942753.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzUxODAsIm5iZiI6MTcxMjczNDg4MCwicGF0aCI6Ii80ODk5Mjg4Ny8zMjA3OTMzNjItZmM3ZDg1NDItOGE1Yi00YjdlLTg1MGItYmNmOWQ3OTQyNzUzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OWRhOTQwMzBiZmRjMWVjNjcwZWRiNTA0MTIxY2I3OWNjYmJlOTdmNzdkOTFhOGRiYTEwNTRkZjk4M2ZlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8VuQ-mD9Hz8o3dlWJ6lyJu_oy6OfTSMUYBZjI6mEpNE) ](https://private-user-images.githubusercontent.com/48992887/320793362-fc7d8542-8a5b-4b7e-850b-bcf9d7942753.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzUxODAsIm5iZiI6MTcxMjczNDg4MCwicGF0aCI6Ii80ODk5Mjg4Ny8zMjA3OTMzNjItZmM3ZDg1NDItOGE1Yi00YjdlLTg1MGItYmNmOWQ3OTQyNzUzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OWRhOTQwMzBiZmRjMWVjNjcwZWRiNTA0MTIxY2I3OWNjYmJlOTdmNzdkOTFhOGRiYTEwNTRkZjk4M2ZlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8VuQ-mD9Hz8o3dlWJ6lyJu_oy6OfTSMUYBZjI6mEpNE) [ ](https://private-user-images.githubusercontent.com/48992887/320793362-fc7d8542-8a5b-4b7e-850b-bcf9d7942753.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzUxODAsIm5iZiI6MTcxMjczNDg4MCwicGF0aCI6Ii80ODk5Mjg4Ny8zMjA3OTMzNjItZmM3ZDg1NDItOGE1Yi00YjdlLTg1MGItYmNmOWQ3OTQyNzUzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OWRhOTQwMzBiZmRjMWVjNjcwZWRiNTA0MTIxY2I3OWNjYmJlOTdmNzdkOTFhOGRiYTEwNTRkZjk4M2ZlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8VuQ-mD9Hz8o3dlWJ6lyJu_oy6OfTSMUYBZjI6mEpNE)

是的！我昨天熟悉的时候发现我好像混了。（sorry）但是卡顿是真的。关了开了这两个折叠都卡顿，开了直接卒，关了还能活一下。

**Comment by obgnail** [comment]
此 issue 关闭，如有进展，麻烦在下面留言。
