### ISSUE TITLE
window_tab 需求-单文件多标签页编辑

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#555]
**需求痛点：**
单文件跨页太大（超过显示器显示范围）的时候不好查看，需要来回切换编辑（不方便），能不能做到想`Idea`一样实现单文件双窗口编辑，具体效果如下

![image](https://github.com/obgnail/typora_plugin/assets/26114336/237f9d72-a7e0-4240-9d1e-42a8a5f3d4fb)

**Comment by obgnail** [comment]
@SnowMaples 

你好，感谢反馈。

---

做不了。

1. **原理上很难实现**：由于 Typora 的限制（只有一个 electron.BrowserWindow），window_tab 并不是真正意义的多标签，只是在同一个标签里不断切换内容罢了。没有真正的多标签，就很难实现这个功能。

   > 以新瓶装旧酒为例：idea 是有 N个瓶，每个瓶装着不同的酒，想喝什么酒就换什么瓶就行；而 Typora 只有一个瓶，每次切换标签都需要将旧酒倒出来，换上新酒

2. **性能弱**：Typora 的性能本身就非常羸弱，md 文件字数一多就卡的不行，多一个窗口直接导致性能砍半（我怀疑官方就是由于这点才不做多标签的）

---

## 绕过

### 方法一：多窗口

标签页处鼠标右键 -> 新窗口打开
![img_2024-04-12_11-31-39](https://github.com/obgnail/typora_plugin/assets/48992887/162ce161-c62a-4072-a12b-eec799840dfe)

### 方法二：使用书签插件

![bookmarker](https://github.com/obgnail/typora_plugin/assets/48992887/3943739d-2f76-4beb-b078-eae887cf3df2)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。

**Comment by SnowMaples** [comment]
@obgnail 
原来是这个原因，那我采取您给的折中办法吧。

随着我md文件越来越多了,整体加载的速度的确越来越慢了，原来是typora自身的问题。
好奇您是怎么整理文件的， 我之前都是直接根目录一个Readme.md文件，然后三到四层目录。

**Comment by obgnail** [comment]
@SnowMaples 

## Typora 的性能为什么羸弱？

1. Typora 的性能和侧边栏的文件数量关系不大，和 Typora 打开的文件的体积关系很大。一个 400K 的文件，Typora 就很难顶了。
2. 为什么众多的 markdown 编辑器都使用双栏式？答：【所见即所得】对于性能的影响超出你的想象。（盲猜这也是 Typora 采用 JQuery，而不是更加现代的 Vue、react 的原因）

我之前的 md 文件超过了 5000，使用 Typora 也没有遇到性能问题，你可以描述一下你的使用场景吗？


## 如何绕过 Typora 的性能问题？

当我编辑大文件（>200K）时，我总是使用【章节折叠】插件，将不需要编辑的标题全部折叠起来，减少需要计算的元素。当需要看被折叠的内容时，可以点击侧边栏的大纲目录，相应内容会自动展开。
> 原理：通过设置 DOM 元素的 display 样式为 none 来隐藏元素，让元素不占用渲染树中的位置，对隐藏的元素操作不会引发其他元素的重排。

实际上，我开发这个插件就不是为了折叠标题，单纯就是为了绕过 Typora 的性能问题。

![img_2024-04-12_17-08-57](https://github.com/obgnail/typora_plugin/assets/48992887/4f56cf5e-a3f9-4b8d-bee6-81c72148c614)


## 我是怎么整理文件的？

和你一样，没啥区别。

1. 一般只打开一个 Typora 窗口，默认打开根目录。
2. 三到四层目录整理好文件位置。
3. 查找文件的时候直接【ctrl+shift+p】查找文件内容关键字

> PS：我觉得给 md 文件的 front-matter 写 tag，然后搜索 tag 的操作特傻逼。纯文本文件就应该使用全文搜索。

![img_2024-04-12_16-42-22 (1)](https://github.com/obgnail/typora_plugin/assets/48992887/4aee491b-29ce-40de-ac27-cdde0010580c)

**Comment by SnowMaples** [comment]
@obgnail 

感谢您的详细回复，性能问题我描述有误，其实是之前多tab页切换存在切换后有一瞬间还是显示切换前页面的内容，文本大的时候切换这个卡顿比较明显。
我怀疑是我自己这台笔记本的性能问题（i5-8250U 16G内存），之前打开文件管理器页存在几秒钟加载文件的白屏情况。

原来折叠章节菜单可以提高性能呀，我尝试一下。
如果单md文件中存在很多图片截图，是否也会比较影响性能。（因为我是做技术笔记的，会加入一些自己画的流程图，单文件可能会有很多图片）

**Comment by obgnail** [comment]
@SnowMaples 

1. 三天前发布的最新版本 1.8.21 做了性能优化，可以尝试更新，切换时卡顿应该会有所好转。
2. 大文本切换的长时间卡顿并不是插件造成的，Typora 本身如此。
3. 只要是需要渲染大量 HTML 标签的，都会影响性能。盲猜对性能的影响： 代码块 ≫ 表格 > 图片 > 引用 > 有序列表、无序列表、任务列表。
4. 和 obsidian 一样，代码块的解决方案采用的是开源的 codeMirror，优点是功能强，缺点是吃资源，所以 Typora 采用了惰性加载代码块（比如说你打开一个很大的文件后，将进度条直接快速拉到最底下，中间的代码块是不会渲染的，对性能的影响就很小，如果你缓慢的拉动进度条，系统一遇到代码块就会触发惰性加载，导致占用内存增长，系统就卡的不行）

你可以对比一下渲染前后的 HTML（这还不包括每个代码块内部的 JS）

![img_2024-04-13_15-15-42 (1)](https://github.com/obgnail/typora_plugin/assets/48992887/89b3be69-3fd3-40f2-9b40-9fd0f5412cc3)
![img_2024-04-13_15-17-25 (1)](https://github.com/obgnail/typora_plugin/assets/48992887/cdef9eb1-3b67-4cb1-b9fb-355ce0e7add6)

---

总结：

除了代码块，其他的元素都是全量加载的，图片吃多少资源 其实都无所谓——因为我们根本无法避免。

所以比较好的绕过方案就是上述的使用折叠章节 —— 虽然我做不到不让系统渲染图片，但是我可以在渲染完毕后手动将其从渲染树中踢出去

**Comment by SnowMaples** [comment]
@obgnail 

前几天升级过一次，刚想升级发现升级插件选项没有了，启停插件中 升级插件的功能是勾选上的。
![image](https://github.com/obgnail/typora_plugin/assets/26114336/9d235166-3b03-4408-9c93-610ce877750c)

**Comment by obgnail** [comment]
@SnowMaples 

解决方案：将 update1.8.19.exe 改名为 update.exe，然后重启 Typora 就可以看到选项了

出现这种情况应该是手动删除 update.exe 导致的（或者被杀毒软件干掉了）

**Comment by obgnail** [comment]
形成原因，以 1.8.18 升级为  1.8.19 为例：

1. 1.8.18 版本本身就有一个 updater.exe 文件，1.8.19 版本也有自己的 updater.exe
2. 18 升级 19 版本的时候，此时 18 版本的 updater.exe 还在运行中，无法删除。为了避免重名，此时 19 版本的 updater.exe 文件就会被重命名为 updater1.8.19.exe
3. 所以，当你在升级到 1.8.19 版本后，就会存在两个文件：updater.exe 和 updater1.8.19.exe。前者来自 1.8.18，后者来自 1.8.19
4. 当你在升级到 1.8.19 版本后，重启 Typora，插件系统就会自动删除 updater.exe，然后将 updater1.8.19 重命名为 updater.exe 
5. 如此就完成了 updater.exe 文件的自更新（selfupdate）

你的情况是只有 updater1.8.19.exe，而之前的 updater.exe 文件被手动删除掉了，导致自更新失效。

所以：将 updater1.8.19.exe 改名为 updater.exe，然后重启 Typora 就可以看到选项了
