### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by zhouxinghong** [obgnail/typora_plugin#557]
需求：
1. 右键 标签页增加固定、取消固定功能，类似 黑曜石 的编辑器标签。
2. 右键 标签页增加重命名当前文件名称。
3. 右键 标签页增加只读模式、取消只读模式。

**Comment by zhouxinghong** [comment]
以上两个看似简单的功能但是更加符合人们的使用习惯。😜希望可以加入它们。非常感谢！🏆🎉👍

**Comment by obgnail** [comment]
@zhouxinghong 

没用过 obsidian，固定标签页的效果是什么？

**Comment by zhouxinghong** [comment]
固定标签，效果就是当你退出编辑器后，下次再打开编辑器，标签会一直出现在那个位置并打开
![image](https://github.com/obgnail/typora_plugin/assets/54253524/a97058cf-2968-4f89-b9ff-8f474d8c6d5e)
取消固定，效果就是当你退出编辑器后，下次再打开编辑器，标签不再出现
![image](https://github.com/obgnail/typora_plugin/assets/54253524/15a0d645-de1e-476d-a043-8205f215a6fa)

**Comment by lidonggui** [comment]
能不能添加tag功能？（也是类似obsidian）把tag信息用"#tag1 #tag2"这种存储在文件头，其实单纯在文章内容中自己也可以实现，用于搜索和标注，但是插件要是能把tag渲染的显眼一点、能够帮助快速添加已有tag就好了。但是可能会需要遍历所有文件解析tag不知道对使用性能影响如何
