### ISSUE TITLE
大文件多标签切换功能 bug

### ISSUE THREAD

**Issue by chuzhixing** [obgnail/typora_plugin#575]
作者您好，感谢您开源这个非常实用的插件。

我这边在使用过程中遇到一个问题，具体描述如下：
1 我先打开一个大文件a.md，它的行数在6905行以上。
2 我再在左侧文件夹中，打开另一个小的文件：b.md。
3 从b.md，在多标签标签栏，切回到a.md，typora会重新打开一个新的窗口来打开a.md，并不是在标签栏中切回到a.md。
4 对于a.md b.md，已经存在于标签栏的情况下 打开c.md d.md，并在b.md c.md d.md之间来回切换tab页面，能够正常切换，前提是c.md b.md不能过大（总行数比较少）。

总结下就是，标签栏中存在打开的大文件（行数），在tab页面中，切换回大文件对应文件，typora会重新打开文件。

我查看过其它的issue:  
[1] https://github.com/obgnail/typora_plugin/issues/391 (多标签也功能非常实用，但在实际使用过程中，出现多次以下情况：切换标签页时，有时文档内容并不能正确切换，只能重启。 · Issue #391 · obgnail/typora_plugin)    
[2] https://github.com/obgnail/typora_plugin/issues/313  

上面的issue，跟我的情况不太一样，所以重开一个issue。

软件运行环境描述：
平台：windows 10
Typora 版本：version 0.9.96(beta)
Typora_plugin 的版本:1.8.30  （已经升级最新版）
切换的标签页对应的文件是否很大：是
出现问题很频繁吗：是的。上述场景下每次都能复现。
插件打开情况：即插件下载下来后的默认打开状态，没有打开【markdown 格式规范检测】、【高亮搜索】、【书签管理】等其他插件的弹窗。

**Comment by obgnail** [comment]
@chuzhixing 

你好，感谢反馈。

我在最后一个免费版本的 Typora（0.9.98）没有复现。你看一下我的操作有没有问题。

![bug_resp](https://github.com/obgnail/typora_plugin/assets/48992887/fe74265d-f494-4e6f-8234-722c25657b2e)

**Comment by obgnail** [comment]
打开操作的逻辑很简单，使用 `isUnderMountFolder` 判断待打开文件是否是 当前挂载目录 的子文件，如果不是就新建窗口打开。

```js
isUnderMountFolder = path => {
    const mountFolder = File.getMountFolder();
    return path && mountFolder && path.startsWith(mountFolder);
}

openFile = filepath => {
    if (this.isUnderMountFolder(filepath)) {    // 判断待打开文件是否是 当前挂载目录 的子文件
        File.editor.focusAndRestorePos();
        File.editor.library.openFile(filepath);    // 新标签页打开
    } else {
        File.editor.library.openFileInNewWindow(filepath, false);   // 新窗口打开
    }
}
```

我只在 0.9.98 版本测试过，有可能是低版本的 Typora 本身的 BUG，方便的话麻烦录个屏看看。

**Comment by chuzhixing** [comment]
https://github.com/obgnail/typora_plugin/assets/41979923/55eea670-2e2e-4279-b01f-40f8f95d67c8

**Comment by chuzhixing** [comment]
Uploading Video_2024-04-30_153415.mp4

**Comment by chuzhixing** [comment]
在github上，上传视频有点问题。放到网盘中了。
链接：https://pan.baidu.com/s/1GqKUF48lcNa1euUyJeDyZg?pwd=mh2l 
提取码：mh2l

**Comment by obgnail** [comment]
@chuzhixing 

不用下载新版本了，我懂了，稍等五分钟，我打一下字

**Comment by obgnail** [comment]
## 现象解释

先说结论，不是 BUG，算是 feather。

1. 和文件大小没有关系，和文件路径很有关系。
2. 目前插件的逻辑是：打开文件时，会 **判断文件路径是否为 【当前挂载目录】 的直接或间接子文件，如果不是就新建窗口打开**。
3. 【当前挂载目录】的意思是：侧边栏左上角的根目录。如下图【当前挂载目录】就是 experience。
4. 也就是说，假设 experience 的路径为 `D:/test/experience`，那么只有文件路径以  `D:/test/experience` 开头的文件才可以在新标签页中打开。

![img_2024-04-30_15-56-33](https://github.com/obgnail/typora_plugin/assets/48992887/8d4f0753-ff44-4b7d-9a87-8be38fffd714)

看文件内容，似乎您是做开发的，结合下面的 JS 代码，应该比较好理解。

```js
isUnderMountFolder = path => {
    const mountFolder = File.getMountFolder();
    return path && mountFolder && path.startsWith(mountFolder);
}

openFile = filepath => {
    if (this.isUnderMountFolder(filepath)) {    // 判断待打开文件是否是 当前挂载目录 的子文件
        File.editor.focusAndRestorePos();
        File.editor.library.openFile(filepath);    // 新标签页打开
    } else {
        File.editor.library.openFileInNewWindow(filepath, false);   // 新窗口打开
    }
}
```
---


## 为什么会这么做？

参考 jetbrain 家族软件，把挂载目录视为一个项目。不属于这个项目的，就新创一个窗口打开。

实际上，除了 vscode，似乎还没有编辑软件是支持在同一个窗口打开两个完全不同路径的文件。

## 我是怎么做的？

我把所有的文件都放在同一个目录下，Typora 也只会打开这个目录。

如此所有的文件都是当前挂载目录下的子文件。

![img_2024-04-30_16-07-58](https://github.com/obgnail/typora_plugin/assets/48992887/e9312a22-d2ce-42ef-b167-166e7f14fb1b)

## 额外的话

实践上，这个插件系统和文件有关的设计，都是基于上面的思想的。

比如说【多关键字搜索】插件，它只会搜索当前挂载目录下的所有直接/间接子文件。

这个插件在你的操作方式下是会水土不服的。也就是说，你在 【experience】的当前挂载目录下搜索，是不会搜索到位于【讲义】目录下的【C++提高编程】的。

## feat request

之前好像也有人希望支持像你一样的操作，你觉得这个功能要不要做？

**Comment by chuzhixing** [comment]
感谢您的解释。

typora插件，typora，与notepad++类似，我这边把它当成一个轻量级文本编辑、阅读的工具使用。
在一个轻量级的文本编辑、阅读软件内部，跟jetbrain不一样，应该没有"项目"的概念。

如果没有"项目"的概念，一个轻量级的文件编译、阅读软件，在它内部，受限于“项目”、挂载目录，直观感觉上不太合理。这样在使用这个多标签页切换功能时，有使用前提，有限制。不能充分发挥这个插件的强大之处。

从普通用户角度出发，当然希望这个插件可以支持跨"当前挂载目录"的多标签切换功能，希望这个插件能更通用，使用场景更多。

祝好~~~~~~

**Comment by obgnail** [comment]
感谢反馈。我后续有时间会评估一下能不能支持这个特性，以及带来的影响。

此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
