### ISSUE TITLE
点击二级标题文字会消失

### ISSUE THREAD

**Issue by shaw-Lee** [obgnail/typora_plugin#585]
![recording](https://github.com/obgnail/typora_plugin/assets/78359360/d4b507c9-f0b6-47e9-a067-0bccf4f3a100)
这是特性还是Bug

**Comment by obgnail** [comment]
@shaw-Lee 

你好。

不是特性，也不是 BUG。是和你使用 Theme 冲突了，你可以试试切换回 默认的 github theme，问题就消失了。

1. 这点我在 readme 里有写：`注意：通过注入 CSS 实现此功能，有可能会与你使用的 theme 冲突。`
2. 具体来说是你使用的 theme 的 CSS，强制取消了 `::before` 选择器导致的
3. 如果不想使用正文的标题编号。 `右键菜单 -> 不常用插件 -> 自动编号 -> 禁用/启用正文编号`
4. 如果不想使用自动标号插件。`右键菜单 -> 不常用插件 -> 启停插件 -> 取消勾选【自动编号】插件`

**Comment by shaw-Lee** [comment]
好的，非常感谢您的解答

**Comment by obgnail** [comment]
简单来说，就是因为：本插件系统不是官方的，主题作者在实现的时候不会主动兼容这个项目。
