### ISSUE TITLE
功能建议-表格隐藏功能

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#589]
**提问：**
![image](https://github.com/obgnail/typora_plugin/assets/26114336/db712020-788c-4739-8d99-57b143737ac9)
1. 上图中的功能是否为`typora_plugin`插件提供？
2. 如果是的话，希望能做成类似下图所示的样式？
  
![image](https://github.com/obgnail/typora_plugin/assets/26114336/fa5b2979-8a81-4e8f-a7ec-ec8b53f961ba)

使用痛点：
1. 表格过长的时候会占据页面空间，希望能做到类似代码块折叠一样的功能

**Comment by obgnail** [comment]
@SnowMaples 

你好，感谢反馈。

需求已实现，参考新增插件【collapse_table】

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
