### ISSUE TITLE
不从typora打开的文件还是单独窗口

### ISSUE THREAD

**Issue by aiqyqy** [obgnail/typora_plugin#59]
软件很不错，但有点小问题，不从typora打开的文件还是单独窗口，并没有受到标签页管理，我习惯与使用everyting检索文件直接打开，能做下优化吗。

**Comment by aiqyqy** [comment]
还有标签页切换的快捷键能优化为ctr+pgup/pgdn 吗。

**Comment by obgnail** [comment]
@aiqyqy 感谢反馈。

1. 这个 [issue](https://github.com/obgnail/typora_plugin/issues/25) 之前已经有不少人提出来了。从原理上来说就是做不到的（除非你用的是低版本）。typora_plugin 本质是一个前端项目，Typora 并不支持插件功能。本项目的做法是通过各种黑魔法强行实现功能。使用命令行直接和后端交互，就绕开了 typora_plugin。**要想实现这个功能，要么等待 Typora 官方支持，或者 Typora 官方提供插件系统**。
2. 可以做，你可以明天再来。

**Comment by obgnail** [comment]
你这种情况或许可以绕过：写一个脚本对接 commander.js 插件。然后让 commander.js 打开文件。

**Comment by obgnail** [comment]
@aiqyqy 你好。

1.1.1 版本已经发布，添加了快捷键 ctr+pgup/pgdn 切换标签。
因为移动了 window_tab.js 的位置，更新时需要替换整个 plugin 目录。
