### ISSUE TITLE
替换功能仅支持单次替换

### ISSUE THREAD

**Issue by nothingandignorant** [obgnail/typora_plugin#596]
我将空格替换掉后，再次使用替换功能（此时替换的内容是Ignorant），但是没有反应
（详细信息见GIF录屏）
![仅支持单次替换](https://github.com/obgnail/typora_plugin/assets/131669301/20042ce2-4240-459b-86d8-e6de3e1e1316)

**Comment by obgnail** [comment]
@nothingandignorant 

你好。

替换并不是 Typora_Plugin 的功能，而是 Typora 本身自带的，这是 Typora 本身的问题。如果有 BUG，我推荐向 [Typora官方](https://github.com/typora/typora-issues) 反馈。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
