### ISSUE TITLE
开启多标签后重新打开之存在question

### ISSUE THREAD

**Issue by li-W-2025** [obgnail/typora_plugin#604]
前置条件typora中偏好设置->文件->启动选项->重新打开上次使用的文件和目录
1.启用window_tab 打开上次关闭的所有文件窗口
2.关闭window_tab 打开上次最后关闭的最后一个文件
ps:使用4个typora窗口来使用
插件版本1.8.46

**Comment by obgnail** [comment]
@li-W-2025 

你好，感谢反馈。我不太理解你的文字，麻烦能详细说明吗？

**Comment by obgnail** [comment]
此 issue 长时间没有进展，暂时关闭，如有新信息麻烦在下面留言。
