### ISSUE TITLE
window_tab补充配置

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#605]
根据现有的`window_tab`插件中 `ctrl+鼠标点击` 会打开新窗口，希望可以增加一个操作可以支持打开新的tab页，而不是新窗口。

目前想到的方式
1. ctrl+鼠标点击快捷键重新定义行为
2. 使用新的快捷键支持。

![image](https://github.com/obgnail/typora_plugin/assets/26114336/0cf02fe4-f281-4b3a-b93d-3b9b9fb093bd)

**Comment by obgnail** [comment]
@SnowMaples 

Typora_Plugin 新版本支持：ctrl+click 带有锚点的本地文件链接（如下），在新的 tab 页打开

> 严格来说是很久之前就已经支持了，但是不知道什么时候被我改出 BUG 导致失效了。新版本修复了。

```
[thisIsMessage](ThisIsFile.md#ThisIsID) 
```

官网参考：
- https://support.typora.io/zh/What's-New-1.1/#文件链接
- https://support.typora.io/Links/#internal-links

---

对于不带锚点的本地文件链接，**暂时没有实现**。原因：影响面太大，可能引发大范围 BUG。

**Comment by SnowMaples** [comment]
@obgnail 
您好，我用的是0.9.98(beta)版本，刚更新`Typora_Plugins`是1.8.51版本，ctrl+click带有锚点的本地连接还是没有打开tab页，而是新开了一个`Typora`窗口。具体情况如下图

![Video_2024-06-04_120959](https://github.com/obgnail/typora_plugin/assets/26114336/bee4bb85-3c01-48db-a118-37974d35487a)

**Comment by obgnail** [comment]
@obgnail 

你好。

上述的网址：https://support.typora.io/zh/What's-New-1.1/#文件链接

文件链接是 Typora 1.1 的 What's-New，说明是 1.1 版本以后才支持的

**Comment by SnowMaples** [comment]
@obgnail 
看样子我得升级了，感谢您的回复
