### ISSUE TITLE
deepin上安装不起来

### ISSUE THREAD

**Issue by fengking2022** [obgnail/typora_plugin#608]
都按照你的步骤实行了。
从typora官方网站下载的1.6.6、1.7.6、1.8.10三个版本，全部安装失败。
![截图_20240602143101](https://github.com/obgnail/typora_plugin/assets/99980084/dd35a64a-0712-4511-8105-57fdacb2c86a)

**Comment by obgnail** [comment]
@fengking2022 

你好，感谢反馈。麻烦看一下 devtools 的 console 报啥错。

**Comment by fengking2022** [comment]
写不下。
[询问.md](https://github.com/user-attachments/files/15524942/default.md)
![截图_选择区域_20240602174456](https://github.com/obgnail/typora_plugin/assets/99980084/8cea33f1-b31e-4ab6-94ed-bfce2da5d792)
微信：fengking1986
两个大陆人跑到国外对话，逗
贼拉胯的网速

**Comment by obgnail** [comment]
问题已解决。

这里做一下记录，以便后来人：**是一个简单的权限问题**。

不同 Linux 发行版的权限默认设置可能不同，如果遇到安装失败问题，大概率是权限问题。执行 `chmod 777 your_typora_path/resources/plugin` 即可。
