### ISSUE TITLE
关闭标签不提示保存

### ISSUE THREAD

**Issue by 87zrjojo** [obgnail/typora_plugin#611]
用了插件，修改文件之后，关闭标签但不提示保存，只有点关闭窗口按钮才会提示“是否保存”。这样容易丢失修改的信息，这应该是bug吧，希望优化一下呢。

**Comment by obgnail** [comment]
@87zrjojo 

你好，感谢反馈。

解决方案：

1. 键入【ctrl + 逗号】，打开 Typora 的偏好设置
2. 选中【文件】选项卡
3. 勾选【自动保存】

![img_2024-06-03_20-37-03](https://github.com/obgnail/typora_plugin/assets/48992887/2e25ae30-6714-4df5-a069-c85f24b1fea5)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
