### ISSUE TITLE
选中文字后，按住鼠标左键可以随意拖动文字换位置

### ISSUE THREAD

**Issue by styw1234** [obgnail/typora_plugin#613]

**Comment by obgnail** [comment]
@styw1234 

你好，感谢反馈。我决定不实现此功能，抱歉。

之前有个 [同样的 issue](https://github.com/obgnail/typora_plugin/issues/325)，我在这里转述一下我的理由：

1. `成本高`：需要将全部的文本标签添加 draggable 属性，十分影响性能
2. `实现难度较大`：不同于 vscode 这种简单文本，md 同时支持普通文字、html 标签、latex 代码、代码块、math 等等特性，每个都要单独实现
3. `影响文字框选`：选中文字然后拖动，太容易误触
4. `不太实用`

如果有其他需求，麻烦另开 issue。
