### ISSUE TITLE
是否可添加一个跟vitepress一样的code代码块里面某些行代码进行突出显示？

### ISSUE THREAD

**Issue by wskaudh** [obgnail/typora_plugin#615]
参考链接是vitepress官方说明https://vitepress.dev/guide/markdown#line-highlighting-in-code-blocks
代码块中的行高亮功能
```js{4}
export default {
  data () {
    return {
      msg: 'Highlighted!'
    }
  }
}
```
使用js{4}来高亮第4行代码

**Comment by obgnail** [comment]
@wskaudh 

你好，感谢反馈。

首先，功能肯定是能做的。

但是现在有一个很尴尬的点，Typora 在解析 language 的时候，会自动过滤掉 `{}`。导致 `js{2}` 变成 `js2`

所以这个需求可能需要改变高亮行的约定，比如 `js{2}` 改成 `js(2)` 之类的。

![img_2024-06-07_02-00-45](https://github.com/obgnail/typora_plugin/assets/48992887/fbd68ae5-2892-49be-8a10-8eb80406245e)

**Comment by obgnail** [comment]
@wskaudh 

你好，功能已经实现。麻烦升级到最新版本试用一下。

1. 新增了 HIGHLIGHT_BY_LANGUAGE 选项（此功能默认关闭，需要手动修改配置文件，将其置为 true）
2. 如上述所言，我修改了高亮行的约定，将 `js{2}` 改成 `js(2)`

**Comment by obgnail** [comment]
此 issue 关闭，如有问题麻烦在下面留言或另开 issue。

**Comment by wskaudh** [comment]
好的，非常感謝，我嘗試一下這個功能。
