### ISSUE TITLE
文本折叠的小优化

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#616]
我超喜欢这个带有三角符号的折叠的，但是我没有想到这个特性被加在了列表中🤨...

![image](https://github.com/obgnail/typora_plugin/assets/113878415/2c8f6d6c-188c-4978-95fa-f324cc7b69d8)

这个特性加到文本缩折叠中不是更好么（我经常忘记文本折叠的快捷键，右键又有点麻烦，导致我不怎么使用这个功能）

类似语雀这种

![image](https://github.com/obgnail/typora_plugin/assets/113878415/b2702992-122f-4f0e-b037-ae43eefa15fa)

而且折叠图标最好是和已有的列表折叠区分开，这样这个功能将会更加易用不是么，非常感谢💕~

**Comment by obgnail** [comment]
@xiaogithubooo 

你好，感谢反馈。

为了提高性能，列表折叠的实现采用了极端的、非正常的方式。

1. 你可以打开 devTools 看一下，上面的三角符号其实是一个 ::before 伪元素。由于是 ::before 伪元素，导致有一定概率与用户的 theme 冲突。
3. 如果标题折叠也采用上述方案，势必会和很多 theme 冲突（同时也和 auto_number 插件冲突），导致三角符号显示不出来。
4. 列表折叠比标题折叠的优势在于，很多 theme 并不会为 列表添加 ::before 伪元素，导致冲突概率降低。

---

还有一种解决方案，就是放弃 ::before 伪元素，采用真实的元素显示三角符号。

难题是由于 Typora 的前端代码写的比较暴力，除非修改 Typora 源代码，目前插件系统无法捕获 【插入标题】这一事件。

没有准确的事件捕获，只能退而求其次，就需要监听整颗 DOM 树的变化，每次发生改变就执行一次，进而导致性能下降 N 倍。

Typora 的所见即所得特性，每次修改都需要重新渲染， 导致 DOM 树时时刻刻都在发生变化，这加剧性能的损失。

在此情况下，我选择放弃此特性。抱歉。

---

总结：由于 Typora 并没有提供官方的插件系统，**Typora Plugin 本质还是带着脚镣起舞**。

**Comment by obgnail** [comment]
此 issue 关闭，如果有问题或者 **你有其他比较好的方法，麻烦在下面留言**。

**Comment by xiaogithubooo** [comment]
> @xiaogithubooo
> 
> 你好，感谢反馈。
> 
> 为了提高性能，列表折叠的实现采用了极端的、非正常的方式。
> 
> 1. 你可以打开 devTools 看一下，上面的三角符号其实是一个 ::before 伪元素。由于是 ::before 伪元素，导致有一定概率与用户的 theme 冲突。
> 2. 如果标题折叠也采用上述方案，势必会和很多 theme 冲突（同时也和 auto_number 插件冲突），导致三角符号显示不出来。
> 3. 列表折叠比标题折叠的优势在于，很多 theme 并不会为 列表添加 ::before 伪元素，导致冲突概率降低。
> 
> 还有一种解决方案，就是放弃 ::before 伪元素，采用真实的元素显示三角符号。
> 
> 难题是由于 Typora 的前端代码写的比较暴力，除非修改 Typora 源代码，目前插件系统无法捕获 【插入标题】这一事件。
> 
> 没有准确的事件捕获，只能退而求其次，就需要监听整颗 DOM 树的变化，每次发生改变就执行一次，进而导致性能下降 N 倍。
> 
> Typora 的所见即所得特性，每次修改都需要重新渲染， 导致 DOM 树时时刻刻都在发生变化，这加剧性能的损失。
> 
> 在此情况下，我选择放弃此特性。抱歉。
> 
> 总结：由于 Typora 并没有提供官方的插件系统，**Typora Plugin 本质还是带着脚镣起舞**。

我还以为仅是普通的矢量图标的插入😰不过这个特性其实有无都无所谓，毕竟就现存的文本折叠以及够用了hhhh非常感谢~

**Comment by xiaogithubooo** [comment]
那能不能在章节折叠的时候适当做一些提示呢？不然容易忘记曾在哪里折叠过...下面的 `{...}` 的标识能不能保留？

![recording](https://github.com/obgnail/typora_plugin/assets/113878415/61c40b8b-f502-408f-b5d8-06d89e27bcc4)

**Comment by xiaogithubooo** [comment]
我之前希望加入一个折叠按钮的另外一个目的其实是方便察觉这个章节的文本有被折叠，这种的话容易实现么，毕竟这个 `{...}` 其实已经有提示的效果了，但是光标移动到别处的时候这个 `{...}` 又消失了...😣

**Comment by obgnail** [comment]
> 我之前希望加入一个折叠按钮的另外一个目的其实是方便察觉这个章节的文本有被折叠，这种的话容易实现么，毕竟这个 `{...}` 其实已经有提示的效果了，但是光标移动到别处的时候这个 `{...}` 又消失了...😣

这个应该就是上面我说的：和你使用主题冲突了。你试试切换回原始的主题试试？

![img_2024-06-08_22-19-11](https://github.com/obgnail/typora_plugin/assets/48992887/8dee44bc-0a02-4b05-a234-2fcfc4252fb6)

**Comment by xiaogithubooo** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/113878415/3067e86e-b6b1-4ed3-bca6-f1be8bd2d114)
吐血，还真是...我用的是一个黑暗主题😵

**Comment by xiaogithubooo** [comment]
欸不对啊，我换了之后，好像还是不行...

**Comment by xiaogithubooo** [comment]
![recording](https://github.com/obgnail/typora_plugin/assets/113878415/9d26bc29-e0e3-43d9-a233-ae03ed5a0939)

换了很多个ba白色主题，依旧有这个问题，点一下就不见了

**Comment by obgnail** [comment]
@xiaogithubooo 

为啥你这个 theme 字体忽大忽小的，试试 github 这个初始 theme 呗？

![img_2024-06-08_22-27-49](https://github.com/obgnail/typora_plugin/assets/48992887/e63d6a03-97d1-47ab-a408-68a0eef7e2c3)

**Comment by xiaogithubooo** [comment]
https://github.com/obgnail/typora_plugin/assets/113878415/be69dcc1-ce37-4df8-99d0-b86ede295e6c

依旧存在

**Comment by obgnail** [comment]
@xiaogithubooo 

很奇怪，为啥不管你用什么 theme，字体总是忽大忽小的，你是引入了什么 CSS 文件吗？我强烈怀疑就是这个原因导致。

**Comment by obgnail** [comment]
我这边没有复现你的情况 😂

![t](https://github.com/obgnail/typora_plugin/assets/48992887/29b93952-5201-4636-892f-8ec84e0b5475)

**Comment by xiaogithubooo** [comment]
欸？难道typora不是设置标题的时候经常会有这种放大放小的现象么？

https://github.com/obgnail/typora_plugin/assets/113878415/3ad69e24-5266-4276-90e4-3f90843232ed

我还去看了看别人的typora，也是一样的现象呀？

**Comment by obgnail** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/48992887/25319021-cd00-4813-bbb2-b04ee5011d85)

编辑标题时，会出现 `##` 的等级提示，在原版中是没有这个功能的呀

**Comment by xiaogithubooo** [comment]
啊？？？非常奇怪，找个时间我重新安装一下typora再试试把...或许真的是某些第三方的主题文件影响了...😵

https://github.com/obgnail/typora_plugin/assets/113878415/079154f7-45ea-47be-aa56-db65280d0476

**Comment by obgnail** [comment]
我复现你的情况了。是 Typora 本身的特性导致的。

![img_2024-06-08_23-04-51](https://github.com/obgnail/typora_plugin/assets/48992887/b1eb91dc-b692-47fa-97a0-37e0ab1e111b)

麻烦试试临时绕过方案，把下面这个配置取消勾选，应该就可以了

![img_2024-06-08_23-06-05](https://github.com/obgnail/typora_plugin/assets/48992887/d1a03645-10f4-404c-bb34-1414d92adfe4)

**Comment by obgnail** [comment]
这是个 BUG，因为我一直没开上面的选项，一直没发现。

我后续有时间的时候看一下怎么处理

**Comment by xiaogithubooo** [comment]
![recording](https://github.com/obgnail/typora_plugin/assets/113878415/4c921063-b395-4473-91aa-f5a113d00640)

的确消失了，非常感谢您~
