### ISSUE TITLE
【fence_enhance】 建议：能否支持代码块添加输入代码块名称

### ISSUE THREAD

**Issue by DoubleW2w** [obgnail/typora_plugin#620]
不知道官方以后对代码块是否做一些信息补充，比如代码块名称。

在语雀中，代码块是支持输入代码块名称的。

也不知道用的人多不多。

![image](https://github.com/obgnail/typora_plugin/assets/73921620/703457d5-38db-40d8-ad1b-92858e74ad60)

**Comment by obgnail** [comment]
@DoubleW2w 

你好，感谢反馈。

不太行。

要为代码块取名，那么就必须将信息持久化到 md 文件中，而目前 md 格式是不支持 fence-title 这种功能的。

也就是说，**要想实现此功能，就必须自定义语法，势必会绑架用户**。本项目及其看重兼容性和可迁移，希望用户可以毫无心里负担的安装和卸载本项目。

很明显，文章在语雀的储存形式不是普通的 md 文件，而是数据库。所以它能轻易的拓展功能。

**Comment by obgnail** [comment]
此 issue 暂时关闭，如果有问题，麻烦在下面留言或者另开 issue。

**Comment by DoubleW2w** [comment]
> 此 issue 暂时关闭，如果有问题，麻烦在下面留言或者另开 issue。

好的 ，谢谢您的及时反馈。
