### ISSUE TITLE
Typora右键未显示插件

### ISSUE THREAD

**Issue by unquire** [obgnail/typora_plugin#621]
开发者您好，我在安装完插件之后，右键菜单并未显示常用插件这么个选项，但是Typora确实有所变化，是我的Typora版本太低了吗，我的版本是0.9.77，期待您的回答。谢谢

**Comment by unquire** [comment]
ctrl+j是可以查询到插件的，应该是加载进去了，但是右键还是没有常见插件这个选项，您知道可能是哪里的问题吗，期待您的回复

**Comment by obgnail** [comment]
@unquire 

你好，感谢反馈。

我只在 0.9.98 版本（最后一个免费版本）和最新版本测试过。

Typora 在 0.9.98 版本以后功能才稳定下来。**0.9.98 版本以下，可能会因为缺少某些功能导致失败**。

要不您去互联网上 下载 0.9.98 版本试用一下？

**Comment by unquire** [comment]
好的好的，感谢您的回复，插件能用，就是右键显示不了。插件很好用，感谢您的开发

**Comment by obgnail** [comment]
好的。

如果不嫌麻烦，可以尝试升级到 0.9.98 版本。

0.9.98 版本以下有些功能缺失，兼容这些版本极其折磨，我放弃了，抱歉。

本 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
@unquire 

我刚刚发布了新版本 [1.9.4](https://github.com/obgnail/typora_plugin/releases/tag/1.9.4) 。有兴趣的话可以装 1.9.4 版本，这个版本对远古版本的 Typora 做了兼容，应该可以在你的机器里正常运行。
