### ISSUE TITLE
aur包 `PKGBUILD` 未添加 `backup` 属性会导致更新后覆盖 `*.user.toml` 配置

### ISSUE THREAD

**Issue by XDwanj** [obgnail/typora_plugin#624]
首先感谢作者对该包做出的一切付出！

你好，我阅读了 PKGBUILD 文件，发现打包脚本中并没有对 `/usr/share/typora/resources/plugin/global/settings/*.user.toml` 进行备份操作，出处在 [ArchWiki该章节](https://wiki.archlinuxcn.org/wiki/PKGBUILD#backup) 中，这将致使每次包更新的时候覆盖用户对 `*.user.toml` 的修改。

麻烦可以添加 backup 属性以修正该部分吗？

**Comment by obgnail** [comment]
@XDwanj 

你好，感谢反馈。

包主不是我，是 @jeffrey4l 大佬。我没有编辑的权限。（大佬看到这条消息的话麻烦有空的时候处理一下）

## 绕过方案：将 *.user.toml 迁移到家目录下

你可以在家目录下创建 `.config/typora_plugin/` ，并在里面存放配置文件，而且这里的配置文件 **优先级最高**。

```bash
dir /b C:\Users\用户名\.config\typora_plugin

custom_plugin.user.toml
hotkey.user.toml
settings.user.toml
```

> 此方法适用于 Linux、Windows 平台。

**Comment by jeffrey4l** [comment]
the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/diff/PKGBUILD?h=typora-plugin) is fixed, please check . thanks a lot.

**Comment by XDwanj** [comment]
@jeffrey4l 

Thank you for your response. I have updated the package, and it functions splendidly!

**Comment by XDwanj** [comment]
I have meticulously re-evaluated the package and I apologize for my prior hasty conclusion.

The `backups` entry in the `PKGBUILD` file should be `backup`, and its path should not commence with a `/`.

Below is the revised reference:

```
1,4d0
< 
< 
< # typora-plugin
< 
24,28c20,24
< backups=(
<     '/usr/share/typora/resources/plugin/global/settings/custom_plugin.user.toml'
<     '/usr/share/typora/resources/plugin/global/settings/hotkey.user.toml'
<     '/usr/share/typora/resources/plugin/global/settings/settings.user.toml'
<     )
---
> backup=(
>     'usr/share/typora/resources/plugin/global/settings/custom_plugin.user.toml'
>     'usr/share/typora/resources/plugin/global/settings/hotkey.user.toml'
>     'usr/share/typora/resources/plugin/global/settings/settings.user.toml'
> )
```

**Comment by jeffrey4l** [comment]
@XDwanj updated, please check

**Comment by XDwanj** [comment]
@jeffrey4l Thank you for the correction; the backup functionality is now operating flawlessly.

**Comment by obgnail** [comment]
close issue as completed.
