### ISSUE TITLE
[bug]: 初始界面中 `CTRL+P` 后无法进入任一文件

### ISSUE THREAD

**Issue by ProjektMing** [obgnail/typora_plugin#625]
<img width="315" alt="Typora 快速打开最近文件" src="https://github.com/obgnail/typora_plugin/assets/73031259/73b7bba3-44a1-43d2-bc2e-83bcb50d520f">
如图会出现无法弹出新界面的问题
这个 bug 仅会出现在初始界面，其他时候都能正常弹出新窗口。
确认过最新版本，均存在该问题。

**Comment by obgnail** [comment]
@ProjektMing 

你好，感谢反馈。

已修复，代码在 [dev](https://github.com/obgnail/typora_plugin/commit/95371185d40111ed7f5ce9020616641c5eef5aa7)，等待发版

**Comment by obgnail** [comment]
@ProjektMing 

代码已经上线，麻烦升级到最新版本试用一下。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
