### ISSUE TITLE
只读模式的bug

### ISSUE THREAD

**Issue by BloodlineL** [obgnail/typora_plugin#627]
开启只读模式再关闭后，typora原生的文本替换功能依然不能使用

**Comment by obgnail** [comment]
@BloodlineL 

你好，感谢反馈。

这个 BUG 是之前重构 read_only 插件的时候引入的（多加了一行错误的剪枝代码），目前新版本已经修复。麻烦升级到最新版本试用一下。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
