### ISSUE TITLE
启停插件问题

### ISSUE THREAD

**Issue by somniahub** [obgnail/typora_plugin#629]
启停插件勾选后点击确定，实际上并没有保存这些设定

**Comment by obgnail** [comment]
@somniahub 

你好，感谢反馈。

我在本地测试了一下，并没有问题呀。

正常情况下，勾选，点击确定以后会弹出一个弹窗提示【当你重启 Typora 才会生效】

![img_2024-06-13_10-18-48](https://github.com/obgnail/typora_plugin/assets/48992887/e57541fd-5714-48ff-9b71-db1858ea8ae0)

---

你可以测试一下：
1. 勾选最后一个一级插件【测试专用（test）】，点击确定
2. 重启 Typora
3. 正常情况下，当你打开 Typora 后，会自动弹出调试工具

---

如果上述方式出现问题：
1. 麻烦描述一下情况
2. 麻烦给一下您使用的 Typora 和 Typora_plugin 版本

**Comment by somniahub** [comment]
我的Typora版本是0.9.98，plugin版本是昨天在这里下载的 应该是最新版。
具体情况就是点击启停插件，勾选列表折叠，取消自动编号，点击确定，但没有设置成功的提示，没有配置将于重启后生效的提示。
另外一个问题是：我在少用插件—自动编号里禁用了全部选项的自动编号，但重启typora后依然是全部启用，似乎重启typora后就刷新了。

**Comment by obgnail** [comment]
您是 Linux 系统吗？可能是没有给权限导致的

**Comment by somniahub** [comment]
我是window11 专业版系统，还真是没有权限，感谢解答！

**Comment by obgnail** [comment]
好的。

顺带一提，上面两个操作其实都是在编辑 `/plugin/global/settings/` 目录下的文件，您也可以手动编辑文件达到同样的效果。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
