### ISSUE TITLE
正文区域点击鼠标右键，不显示右键菜单栏；但是插件的功能却能使用

### ISSUE THREAD

**Issue by run-cao** [obgnail/typora_plugin#631]
我的typora版本是0.0.92

**Comment by obgnail** [comment]
@run-cao 

你好，感谢反馈。

你的问题和 [这个 issue](https://github.com/obgnail/typora_plugin/issues/621) 一样。

我简单说明一下：

1. 我只在 0.9.98 版本（最后一个免费版本）和最新版本测试过。
2. Typora 在 0.9.98 版本以后功能才稳定下来。0.9.98 版本以下，可能会因为缺少某些功能导致一些插件失效。
3. 兼容这些远古版本究极折磨，我放弃了，抱歉。
4. 您可以去互联网上下载 0.9.98 版本试用一下

**Comment by run-cao** [comment]
好的，谢谢开发者大大的回复；
之前用插件1.7.59可以正常显示右键菜单，所以我尝试降级插件版本；

**Comment by run-cao** [comment]
请问作者大大，降级是再执行方法二（手动）吗？

**Comment by obgnail** [comment]
@run-cao 

直接替换 plugin 目录即可。

**Comment by obgnail** [comment]
@run-cao 

如果您采用插件降级的方式，麻烦在降级完成后，按照如下步骤关闭插件的自动升级功能。

    1. 打开文件./plugin/global/settings/custom_plugin.user.toml
    2. 添加如下内容，并保存:
         [pluginUpdater]
         [pluginUpdater.config]
         auto_update = false

**Comment by run-cao** [comment]
好的 谢谢

**Comment by obgnail** [comment]
@run-cao 

我刚刚在虚拟机装了 0.9.86 版本并做了代码兼容。然后发布了新版本 [1.9.4](https://github.com/obgnail/typora_plugin/releases/tag/1.9.4) 。有兴趣的话可以装 1.9.4 版本，应该可以在你的机器里正常运行。

**Comment by run-cao** [comment]
谢谢大佬，等下就安装

**Comment by obgnail** [comment]
@run-cao 

如果遇到问题可以在下面留言，我尽力兼容。

**Comment by run-cao** [comment]
1.9.4 版本兼容效果很好，解决了Typora 0.9.92右键菜单不显示的问题。
辛苦作者大大了
