### ISSUE TITLE
【文件模版】：模板预览固定，不发生变化。

### ISSUE THREAD

**Issue by DoubleW2w** [obgnail/typora_plugin#641]
![image](https://github.com/obgnail/typora_plugin/assets/73921620/888bddc4-c094-4bad-9a42-d780b63ba7c2)

![image](https://github.com/obgnail/typora_plugin/assets/73921620/7a92e369-a7a3-48a1-a723-58b504e5dafd)

![image](https://github.com/obgnail/typora_plugin/assets/73921620/5b60d330-eb34-4b9b-9acf-92516d6ce09a)

**Comment by DoubleW2w** [comment]
当前 typora 版本为 1.9.3。

版本更新日志如下：https://typora.io/releases/all

**Comment by obgnail** [comment]
@DoubleW2w 

已修复，代码在 [dev](https://github.com/obgnail/typora_plugin/commit/24dba7e1e87ed4f82559a33a6c9a670646a2ed6c)

[1.9.9](https://github.com/obgnail/typora_plugin/releases/tag/1.9.9)版本修改了 dialog 引入的。

**Comment by DoubleW2w** [comment]
@obgnail 

好的，感谢你的及时反馈。

**Comment by obgnail** [comment]
@DoubleW2w 

已修复。麻烦在新版本试用一下。
