### ISSUE TITLE
callouts渲染异常

### ISSUE THREAD

**Issue by locusyuri** [obgnail/typora_plugin#642]
callout渲染异常，需要对其中内容进行删改才能正常显示。typora版本1.8.10
<img width="588" alt="Snipaste_2024-06-23_16-15-49" src="https://github.com/obgnail/typora_plugin/assets/98383764/288ba437-dcc8-454a-a8a1-b39a1fbf4146">

<img width="701" alt="Snipaste_2024-06-23_16-15-58" src="https://github.com/obgnail/typora_plugin/assets/98383764/dd3a4d28-6b31-4f4a-98a9-e2ac73d26ff6">

**Comment by obgnail** [comment]
@locusyuri 

你好，感谢反馈。麻烦能给一下复现路径吗？

**Comment by locusyuri** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by obgnail** [comment]
你好，感谢反馈。

先说结论：不算 BUG。

造成此现象的原因：官方的 Callouts 功能对于语法要求严格，不允许错误语法。

1. Callouts 插件诞生得很早。半年以前官方在 Typora 1.8.3 版本支持了 Callouts 功能，你可以看一下 [官方说明](https://support.typora.io/What's-New-1.8/)

2. 既然官方支持 Callouts 了，为什么不删除 Callouts 插件？

   答：拥有官方 Callouts 没有的功能：
   1. 官方其仅支持五种类型的 callouts（NOTE、TIP、IMPORTANT、WARNING、CAUTION），插件支持任意类型，并且能配置任意颜色、icon 等样式。
   2. 官方不支持 fold callouts（如： `> [!NOTE]-`），插件支持
   3. 插件兼容官方 Callouts 功能

   这就能解释为什么你的第一张图两个 Callouts 样式不同：前者为官方，后者为插件

3. 你的问题：根据 Callouts 基本语法，第一行不应该有 `> [!Type]` 以外的任何内容（具体到你的情况，应该删除 test ）。实际上，如果你关闭插件，用官方的，它甚至都无法正确显示：

    ![image](https://github.com/obgnail/typora_plugin/assets/48992887/8f3ede33-2a4d-4a9c-9fbf-b86b43536d75)


4. 解决方案：

   1. 方法一：遵循 Callouts 语法规则，第一行不添加额外内容
   1. 方法二：关闭官方的 Callouts 功能，使用 Callouts 插件，这样就允许你在第一行添加其他内容（插件对于语法的检查比较宽松，允许你怎么做）（关闭流程：【ctrl+逗号】 打开配置选项 -- Markdown -- Github 风格警报框）

**Comment by locusyuri** [comment]
好的，谢谢大佬
