### ISSUE TITLE
如何默认开启调试模式

### ISSUE THREAD

**Issue by magiceses** [obgnail/typora_plugin#644]
占个楼，请教个问题，请问如何在开关 typora 的时候，默认开启 debug 模式？
<img width="221" alt="image" src="https://github.com/obgnail/typora_plugin/assets/50326171/64eb00e4-b165-4080-bbc2-1145779a7c4c">

**Comment by obgnail** [comment]
你是希望打开 typora 的时候自动弹出 devtools 吗？

可以如下操作:

右键菜单 -- 少用插件 -- 启停插件 -- 启用 test 插件
