### ISSUE TITLE
文件规范性检查的小方块不见了

### ISSUE THREAD

**Issue by 87zrjojo** [obgnail/typora_plugin#651]
最新版插件中“文件规范性检查”怎么看不到右上角的小方块了呢，是要怎么才启用吗？我用的win7 typora1.5.22

**Comment by obgnail** [comment]
@87zrjojo 

你好，感谢反馈。

检查：`右键菜单 -> 少用插件 -> 启停插件` ，看看 `md格式规范检测（markdownLint）` 插件是否启用。

**Comment by 87zrjojo** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/31100329/7cb19240-b99a-4d8c-b3dc-d118e9b0a284)
我这里`md格式规范检测（markdownLint）`是打开的，但小方块就是没出现

**Comment by 87zrjojo** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/31100329/8a233caa-37b9-42df-9a90-fcaacb20f167)
我没有修改过，这是控制台输出情况，不懂编程，给大佬看看是否有问题。

**Comment by obgnail** [comment]
@87zrjojo 

很奇怪，看截图没有报错。

1. 有可能是你使用的主题和插件不兼容导致的，你先试试将 theme 改回默认 github 主题，看看能不能恢复。
2. 如果不能恢复，尝试：右键菜单 -> 常用插件 -> 二级插件 ->  md格式规范检测，应该可以弹出窗口。

**Comment by 87zrjojo** [comment]
确实，换个主题就出来了，看来是跟主题不关系。谢谢

**Comment by obgnail** [comment]
@87zrjojo 

和主题冲突确实没啥好办法处理。

这个项目不是官方的，其他人在制作主题的时候不会主动兼容插件，而 Typora 主题这么多，我也不能挨个去兼容他们。

**Comment by 87zrjojo** [comment]
谢谢，知道了。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
