### ISSUE TITLE
自动编号功能问题

### ISSUE THREAD

**Issue by 87zrjojo** [obgnail/typora_plugin#652]
自动编号时，图表、代码块等都是从0-1……开始编号的吗？不太符合逻辑呢，可否提供从图1、图2……表1、表2这样的编排方式自动编号，不然在文章标题下的图片等都会从0开始编号。

**Comment by obgnail** [comment]
你情况应该是文件中有多个 h1 导致的。

根据 [Markdown 最佳实践](https://learn.microsoft.com/en-us/powershell/scripting/community/contributing/general-markdown?view=powershell-7.3)，一篇文档应该有且仅有 一个 h1，故此插件从 h2 开始编号。

因为功能是通过 CSS 实现的，很难复用代码。每个编排方式都要写一堆代码，有点麻烦。我这边只能给出一个相对标准的实现方式。

**Comment by 87zrjojo** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/31100329/7cfcd04e-850b-41ce-8a6d-3cb13440d6e6)
因为有的文章可能需要在引方部分就插入图片或表格，所以想编排方式有多一种选择。当然也不是什么大问题，如果有空的话，大佬支持一下也许更完美。

**Comment by 87zrjojo** [comment]
感谢大佬回复，如有时间可计划完善下。

**Comment by obgnail** [comment]
@87zrjojo 

你好，感谢反馈。此需求已完成，麻烦升级到最近版本试用。

此 issue 关闭，如有问题，麻烦在下面留言。
