### ISSUE TITLE
timeline 问题反馈

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#653]
今天尝试了一下timeline插件，发现有点问题，是不是用的人太少了。~_~

问题：使用时间线插件存在三级标题未对齐问题。
优化：希望内部的markdown语法支持复选框按钮。

![image](https://github.com/obgnail/typora_plugin/assets/26114336/030e00e4-5de5-41e9-bc1c-b7281b104e79)

**Comment by obgnail** [comment]
@SnowMaples 

感谢反馈，最近确实没时间处理。这个插件应该只有我一个人在用 😂

新版本已经支持 tasklist 和修复。麻烦升级到新版本试用一下。

此 issue 关闭，如有问题麻烦在下面留言或另开 issue。

**Comment by SnowMaples** [comment]
@obgnail 
你好，希望可以支持复选框渲染，主要想作为每日任务版来记录任务完成情况。

另外希望可以对timeline、kanban等上面源代码下面为显示效果的排版模式进行优化。

原因是如果timeline作为一个月的日报时，长编辑内容后，无法直接显示效果,如下图

![image](https://github.com/user-attachments/assets/a59e8114-a29a-4555-bed4-95d16522f953)

可以考虑左右排版的方式进行优化，如下图
![image](https://github.com/user-attachments/assets/f181cc07-67ba-42ee-8eff-427faa405701)

ps：这里就提一下个人建议哈，如果你比较忙，或者不好处理，可以忽略，不着急。目前这个插件已经相当完美了，非常感谢你的无私付出。

**Comment by obgnail** [comment]
@SnowMaples 

趁着晚上有空连夜做了，麻烦升级到新版本试用一下。

1. 功能在插件 【blockSideBySide】插件上，默认此插件关闭，需要开启（嵌套编辑页面是大工程，我选择讨巧的方式，将预览图移动到右边）。
2. 暂时强制所有的图表都会并排显示（我没精力去做单独的开关了）。
3. 如果开启此插件，当进入 Typora 就会强制开启此功能。但是支持热插拔：【右键菜单 -> 常用插件 -> 二级插件 -> 并排显示活动块】即可临时关闭，再次点击则重新启用。
4. 你说的【复选框渲染】是 tasklist 吗，如下图
5. 累了，睡了，有什么问题请下面反馈。

![IMG_2024-07-14_00-59-27](https://github.com/user-attachments/assets/f6a8d634-b28c-426c-bf16-14645fbb9d75)

**Comment by SnowMaples** [comment]
@obgnail 大可不必如此之卷（捂脸笑哭），保重身体，升级后可以了，不过tasklist这个功能在我1.6.7的版本没有生效，不知道是不是我的主题引起的，具体效果如下图。
![image](https://github.com/user-attachments/assets/3647fde3-0f67-47b8-afdd-748422689f7c)

早睡早起，注意身体。^_^

**Comment by obgnail** [comment]
@SnowMaples 

麻烦试试换成 Typora 自带的主题，先排除主题的问题

**Comment by SnowMaples** [comment]
@obgnail  自带的github主题可以显示，但是不可以勾选，需要手动修改成`- [X]`，Drake主题都不行。

![image](https://github.com/user-attachments/assets/2a3c4878-b137-4466-af00-bac4047ec9d2)

**Comment by SnowMaples** [comment]
@obgnail 非常感谢你的详细回复，不处理就不处理哈，已经很好了。（下次别熬夜改了，真的，你这样熬夜，我作为白嫖的都不好意思提Issue了）
