### ISSUE TITLE
按要求修改了快捷键配置文件，快捷键无效

### ISSUE THREAD

**Issue by ccasg** [obgnail/typora_plugin#658]
在快捷键中心有出现，但是实际按下无效
![image](https://github.com/obgnail/typora_plugin/assets/76237050/19b5aea1-b818-4625-89f4-e7f621614a12)

**Comment by obgnail** [comment]
@ccasg 

你好，感谢反馈。

麻烦说明一下修改的插件，给一下修改的配置文件，我看看本地能不能复现

**Comment by ccasg** [comment]
修改的配置文件是custom_plugin.user.toml
修改内容为
```
[toc]
enable = true
hotkey = "ctrl+shift+p"
default_show_toc = true
```
有可能是快捷键冲突的问题，昨天把命令行的快捷键ctrl+g改成其他功能成功了

**Comment by obgnail** [comment]
`ctrl+shift+p` 被【search_multi】插件占用了，建议使用 `ctrl+alt` 系列快捷键。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
> 修改的配置文件是 custom_plugin.user.toml 修改内容为
> 
> ```
> [toc]
> enable = true
> hotkey = "ctrl+shift+p"
> default_show_toc = true
> ```
> 
> 有可能是快捷键冲突的问题，昨天把命令行的快捷键 ctrl+g 改成其他功能成功了

刚刚仔细看了一下，你的配置文件少了个 `[toc.config]`

正确的方式：
```toml
[toc]
enable = true
[toc.config]
hotkey = "ctrl+shift+p"
default_show_toc = true
```
