### ISSUE TITLE
请问，能否让命令行环境功能打开后就是位于typora当前工作文件夹

### ISSUE THREAD

**Issue by sword4869** [obgnail/typora_plugin#662]

**Comment by obgnail** [comment]
@sword4869 

你好，感谢反馈。

提供如下环境变量:
- `$f`：当前文件路径
- `$d`：当前文件所属目录
- `$m`：当前挂载目录

默认命令行环境的路径就是当前的文件夹

![IMG_2024-07-05_22-45-17](https://github.com/obgnail/typora_plugin/assets/48992887/ff9ee01d-3231-4672-aa68-17fb432fecb9)
![IMG_2024-07-05_22-47-29](https://github.com/obgnail/typora_plugin/assets/48992887/25b52467-d1bb-4bf9-b199-1fdaa6061927)

**Comment by sword4869** [comment]
非常好的设计，感谢作者大大的介绍👌
