### ISSUE TITLE
上传文章到CSDN，提示开始上传后就没动静了，实际上未上传成功

### ISSUE THREAD

**Issue by bearmeetu** [obgnail/typora_plugin#664]
如题

**Comment by obgnail** [comment]
你好，感谢反馈。

article_uploader 这个插件并不是我写的，我来 at 一下原作者。@AZCodingAccount 帮忙看看？

同时麻烦您看一下 devtools 里控制台的报错。

**Comment by bearmeetu** [comment]
> 你好，感谢反馈。
> 
> article_uploader 这个插件并不是我写的，我来 at 一下原作者。@AZCodingAccount 帮忙看看？
> 
> 同时麻烦您看一下 devtools 里控制台的报错。

控制台里没报错信息，就是typora软件里，弹出开始上传，请不要关闭软件提示后，就没后文了。我是chrome dev 128版本

**Comment by AZCodingAccount** [comment]
> > 你好，感谢反馈。
> > article_uploader 这个插件并不是我写的，我来 at 一下原作者。@AZCodingAccount 帮忙看看？
> > 同时麻烦您看一下 devtools 里控制台的报错。
> 
> 控制台里没报错信息，就是typora软件里，弹出开始上传，请不要关闭软件提示后，就没后文了。我是chrome dev 128版本

是突然不能用了还是刚开始就上传不了呢，如果突然不能用可以试着覆盖一下cookie

**Comment by bearmeetu** [comment]
> > > 你好，感谢反馈。
> > > article_uploader 这个插件并不是我写的，我来 at 一下原作者。@AZCodingAccount 帮忙看看？
> > > 同时麻烦您看一下 devtools 里控制台的报错。
> > 
> > 
> > 控制台里没报错信息，就是typora软件里，弹出开始上传，请不要关闭软件提示后，就没后文了。我是chrome dev 128版本
> 
> 是突然不能用了还是刚开始就上传不了呢，如果突然不能用可以试着覆盖一下cookie

解决了，复制cookie格式错了，双击复制下来格式不对，只能鼠标拖选再复制，麻烦你了，不好意思

**Comment by AZCodingAccount** [comment]
okok，过段时间暑假闲下来时候会对这个插件加点新功能，到时候会更好用，敬请期待

**Comment by obgnail** [comment]
感谢 @AZCodingAccount 回复。

此 issue 关闭，如有问题麻烦在下面留言或另开 issue。
