### ISSUE TITLE
希望添加一款大纲目录插件

### ISSUE THREAD

**Issue by 87zrjojo** [obgnail/typora_plugin#666]
大神你好，我想导出的html有一个好看的大纲目录。今天终于找到一款非常合适的插件https://github.com/cayxc/Mdtht，请问您能将它集成到插件库中吗？

**Comment by obgnail** [comment]
那个项目自带导出的 [说明文档](https://github.com/cayxc/Mdtht/blob/master/readme.zh.md#%E5%9C%A8typora%E4%B8%AD%E4%BD%BF%E7%94%A8) ，你跟着操作就行了呀。

我试了一下，没啥问题，可以正常导出。

自定义导出是 Typora 自带的功能，而且是一劳永逸的。

**Comment by obgnail** [comment]
自定义导出方案是 Typora 自带的功能，直接使用就可以了。而且这种操作是一劳永逸的，所以没有必要做成一个插件。

此 issue 关闭，如果您不知道怎么配置自定义导出方案，麻烦在下面留言。

**Comment by 87zrjojo** [comment]
我是觉得<https://github.com/cayxc/Mdtht>这个项目的大纲和简洁主题很漂亮，但我不太喜欢他那样的自定义导出方案，希望直接能在Typora中就显示他那样的大纲，同时导出html时也保持那样的效果。如果能跟您的Typora_plugin插件融合的话，那看起来就非常棒了。只是一点小小建议罢，实在不好移植也没什么，感谢您的回复。

**Comment by obgnail** [comment]
你是希望 TOC 插件的样式 改成他那样吗？

> 导出的样式我是不能改的，这个应该交给用户。

**Comment by 87zrjojo** [comment]
![image](https://github.com/obgnail/typora_plugin/assets/31100329/60180e7e-a5b2-4f90-882c-614d8c72ba92)我是希望typora这里的大纲显示成Mdthd导出html之后左侧显示的大纲样子。可折叠、分层显示标题（显示+-等图标）、有搜索元素，可开关自动编号等功能。
