### ISSUE TITLE
callouts问题

### ISSUE THREAD

**Issue by gebts** [obgnail/typora_plugin#673]
1.新建文档，新增一个callouts，比如选择QUESTION类型，不会正常显示，需要关闭再打开才行
2.导出显示不正常：html能正常显示，但pdf、图片都不可正常显示
![1](https://github.com/user-attachments/assets/2d54d0f8-5223-4732-8795-90d93fc2e840)
![2](https://github.com/user-attachments/assets/1e17483f-5979-47c5-b8f5-da36e48349c9)

**Comment by obgnail** [comment]
@gebts 

你好，感谢反馈。

关于第一点能详细说明一下复现情况和复现路径吗？

**Comment by gebts** [comment]
@obgnail 

第一点的问题，我今天试了一下，又可以了，很奇怪。

**Comment by insomniaU** [comment]
我也遇到这个问题了，info和tip等都有这个问题

**Comment by obgnail** [comment]
@gebts @insomniaU 

你好，感谢反馈。

已经修复，麻烦升级到新版本试用一下。

**Comment by obgnail** [comment]
已经修复。此 issue 关闭，如果问题，麻烦在下面留言，或者另开 issue。
