### ISSUE TITLE
window_tab 问题-切换tab页时内容没有切换

### ISSUE THREAD

**Issue by SnowMaples** [obgnail/typora_plugin#675]
![tab页切换](https://github.com/user-attachments/assets/f7060994-d9ee-424d-be9d-a881e420ee28)

tab1 共16456个字，tab2-780个字，均纯文本，没有图片

此时选择关闭两个tab后重新打开，均显示白屏，**留意下图左上角显示tab1**的文件好像没有保存成功（期间按过ctrl+s，关闭时弹出是否保存确认框，也点击确认了）

![Video_2024-07-18_104425](https://github.com/user-attachments/assets/9c8884e5-3dad-4963-bd35-3b3a92c9548c)

目前已重启Typora，未复现此问题。（之前遇到过几次这个问题）

**Comment by xiaogithubooo** [comment]
我其实也经常遇到过这个问题，有些时候甚至会造成文件数据对视...尤其是在大文本的时候

**Comment by xiaogithubooo** [comment]
我其实也经常遇到过这个问题，有些时候甚至会造成文件数据对视...尤其是在大文本的时候

**Comment by SnowMaples** [comment]
@obgnail 稳定复现路径没有留意，下次我注意一下，感觉大文本的时候概率高一点。文件内容丢失的情况，之前出现过一次。
有一次使用`ctrl+s`保存后，点击×符号的时候还是会弹出是否需要保存的弹出框，点确定以后再次关闭还是会有这个是否保存的提示。

**Comment by obgnail** [comment]
@SnowMaples  @xiaogithubooo 

做了一版修复。麻烦升级到最新版本测试一下。

**Comment by obgnail** [comment]
此 issue 关闭，如果还有问题麻烦在下面留言。

**Comment by obgnail** [comment]
NOTE：我这边也没有找到稳定复现的方案，我是通过分析代码，猜测出现的原因，然后进行尝试性的修复。

也就是说，这并不是一次严谨的修复，不能 100% 的保证以后不再出现。目前我在本地试了几天，没有再复现了。

**Comment by obgnail** [comment]
@SnowMaples @limou3434 

此问题的解决方案请参考：

- #1130
