### ISSUE TITLE
可否开发一个微信公众号文章一键复制功能插件

### ISSUE THREAD

**Issue by sumruler** [obgnail/typora_plugin#676]
复制的时候可以携带主题内的样式，因为typora导出的html是携带样式的，不知道是否有相应的接口能够实现复制有样式的内容，然后一键粘贴到微信公众号后台。

**Comment by obgnail** [comment]
@sumruler 

你好，感谢反馈。

理论上应该是能做的，我查看了一下，有几个类似的项目，您可以参考一下。
- [markdown转微信公众号编辑器的项目](https://github.com/cnych/markdown-weixin)
- https://github.com/sunbooshi/note-to-mp

这个需求最重要的应该是 clickboard.js，负责将样式写入到剪切板中。我看第一个项目用的是 [https://zenorocha.github.io/clipboard.js](https://zenorocha.github.io/clipboard.js)，您可以试试。

---

我这边应该就不做了，抱歉。原因如下：
1. 市面上有非常多成熟的微信公众号文章排版工具
2. 需求比较小众并且实现成本比较高，需要处理微信各种奇葩要求，图片上传要和微信 API 交互等等。
3. 我没有公众号


此 issue 关闭，如有问题，麻烦在下面留言。
