### ISSUE TITLE
能否支持wavedrom

### ISSUE THREAD

**Issue by narutozxp** [obgnail/typora_plugin#680]
您好，wavedrom可以很方便得在md中绘制时序图。当前我已经对自己的hexo的模板进行了修改，从而使得hexo能够将标记为wavedrom的代码块渲染为波形。
由于实现的原理就只是将```wavedrom替换成<script>，然后导入js文件就行。不知道typora插件能否实现类似功能呢

**Comment by narutozxp** [comment]
看了一下那个custom，感觉跟hexo的差不多，我有时间去试试。

**Comment by obgnail** [comment]
@narutozxp 

简单看了一下 wavedrom，应该可以在 100 行内实现。

我抽象出了一个 `this.utils.thirdPartyDiagramParser` 方法，用于注册第三方的图表，你可以借鉴一下我写的第三方图表的实现 [echarts](https://github.com/obgnail/typora_plugin/blob/master/plugin/custom/plugins/echarts/index.js)，[chartjs](https://github.com/obgnail/typora_plugin/blob/master/plugin/custom/plugins/chart/index.js)，[abcjs](https://github.com/obgnail/typora_plugin/blob/master/plugin/custom/plugins/abc/index.js)，[marp](https://github.com/obgnail/typora_plugin/blob/master/plugin/custom/plugins/marp/index.js)

**Comment by narutozxp** [comment]
@obgnail 好的，多谢

**Comment by obgnail** [comment]
@narutozxp 

新版本已经支持了，麻烦在新版本试用一下。

> 吐槽：不得不说，wavedrom 的坑实在是太多了，还没有文档 😳

![wavedrom](https://github.com/user-attachments/assets/e2b5d3f7-497a-4de7-b0ed-729732f3de54)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言。

**Comment by RyanLei-icer** [comment]
> 此 issue 关闭，如有问题，麻烦在下面留言。

你好，我现在刚刚使用这个功能，发现一些问题：
在输入相同的绘图代码时能否自动输出调整好的hight*width，并且对于不同的主题，其以图片形式显示的格式也不一样，导致有时候更换主题后显示不全，最好hight要能够自动调整，显示全，对于width貌似也与直接使用软件不太一样，不过无伤大雅。
此外对于drawio也是类似的问题，而且不知道是不是版本不一样的原因，typora绘制出的和直接使用drawio的图片不太一样：
drawio：
![图片](https://github.com/user-attachments/assets/d760d0bd-d8bb-4002-860b-a012d4a1b8cc)
typora插件：
![图片](https://github.com/user-attachments/assets/30dcd634-ffd8-4e88-96d4-f8aa6795751f)

**Comment by obgnail** [comment]
@RyanLei-icer 

你好，感谢反馈。

wavedrom 代码块自动高度调整的需求已经实现。代码在 master 中，等待发版。

至于您说的绘制图不太一样，麻烦新开 issue 详细说明。
