### ISSUE TITLE
标题序号问题

### ISSUE THREAD

**Issue by JerryMeeet** [obgnail/typora_plugin#681]
![微信图片_20240726154937](https://github.com/user-attachments/assets/dc625495-e1ee-42c5-9d93-d29cbcd9d4e0)

我右键->4级标题，自动给我生成这个序号，然后下面一个，也是生成同一个0.0.01，没有增序啊！！有时候我不需要自动帮我0.0.01，我自己写了1、2、3,直接变成四级标题就行了

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言。
