### ISSUE TITLE
折叠代码是否能有记忆功能？

### ISSUE THREAD

**Issue by Nianwenxin** [obgnail/typora_plugin#683]
代码折叠之后下次打开文件是展开状态，是否有记忆功能，使下次打开时还是折叠的代码

**Comment by obgnail** [comment]
@Nianwenxin 

你好，感谢反馈。目前我找不到实现这一需求的方法。

要想有记忆功能，就要找到代码块的唯一标识，目前标题标签的唯一标识是标题标签在 DOM 树的序号。然而，Typora 的代码块是使用 intersectionObserver 延迟加载的，这导致序号不起作用，进而无法实现这个需求。

此 issue 暂时关闭，如果我找到其他的方法实现，再开启。
