### ISSUE TITLE
[features request]图片标题显示（类似word中的题注功能）

### ISSUE THREAD

**Issue by BrazilAmando** [obgnail/typora_plugin#685]
一直在默默使用该插件，最近因为电脑恢复系统重装该插件，发现作者终于多了个打赏功能，必须要感谢、鼓励！

再提一个常用的需求，能否实现类似word中的题注功能，即通过CSS选择器获取图片标题（可在typora中编辑），在图片编号后展示，如图所示
![image](https://github.com/user-attachments/assets/952b49d0-9875-44ca-a06e-465dcf9ce2f9)

**Comment by obgnail** [comment]
@BrazilAmando 

你好，感谢支持。

这该怎么做呢？

`img` 是单标签，不允许有 `::after` 伪元素。所以 `::after` 只能加在 `img` 的父标签上。

CSS 有什么好方法能将子标签的 alt 属性传递给其父标签呢？

**Comment by BrazilAmando** [comment]
在AI的帮助下，copy了typora中的代码到vscode测试成功，供您参考：

添加CSS样式如下
 ```
<style>
        .md-image {
            display: inline-block;
            position: relative;
        }

        .md-image::after {
            content: attr(data-alt);
            display: block;
            margin-top: 5px;
            text-align: center;
            font-weight: bold;
            font-size: 14px;
            color: #333;
        }
    </style>
```

然后通过脚本动态插入
 
```
<script>
        document.addEventListener("DOMContentLoaded", function () {
            var images = document.querySelectorAll(".md-image img");
            console.log(images)
            images.forEach(function (img, index) {
                var altText = img.getAttribute("alt");
                var wrapper = img.parentElement;
                wrapper.setAttribute("data-alt", "图" + (index + 1) + " " + altText);
            });
        });
    </script>
```
 
![image](https://github.com/user-attachments/assets/22efb367-56bd-4cae-86a2-8cd4310ccd3f)

**Comment by obgnail** [comment]
@BrazilAmando 

你好，新版本已经支持此功能了，新增了配置选项 SHOW_IMAGE_NAME（默认为 false，需要手动开启），commit 在 [这里](https://github.com/obgnail/typora_plugin/commit/53604a45cc987a0edc076e419eb11a1e4b082a22)

说明一下几点：
1. Typora 和普通网页有一个很大区别，那就是 **Typora 是可编辑的，这导致 DOM 树总是会改变**。
2. 所以您上面的代码是行不通的 —— DOMContentLoaded 事件是不够的，一旦开始编辑，图片标注就会出现异常。此时必须使用 MutationObserver。
3. Typora 性能羸弱的最重要原因就是【所见即所得】带来了 N 倍的性能下降（我猜这就是为什么 Typora 宁愿选择 JQuery 而不使用 react、vue 之类的第三方框架）。而 MutationObserver 会导致性能继续下降。因为 V8 总是要时不时抽空遍历整个 DOM 树，而大文件形成的 DOM 树及其庞大。
4. 更糟糕的是，国内输入法是非常流氓的，为了抢占资源，每次键入都会触发 DOM 树改变。解决方法就是防抖。
5. 所以，虽然我做了此功能，但是我很怀疑此功能在大文件下的性能问题。为了提高性能，最好的方法还是将逻辑迁移到 CSS 上。但是目前我也想不到什么有效方法能用纯 CSS 实现。
6. 进而：**我建议您先试用此功能，看在大文件下是否会出现性能问题**。

**Comment by obgnail** [comment]
此需求已经实现，此 issue 关闭，后续请在下面留言。

**Comment by BrazilAmando** [comment]
测试成功，非常感谢！
