### ISSUE TITLE
如何关闭` \ ` 自动出现标题提示 

### ISSUE THREAD

**Issue by hwy1782** [obgnail/typora_plugin#688]
在中文输入模式下，使用 `\` 输入顿号的时候，会自动浮现如下提示，请问该如何关闭
![image](https://github.com/user-attachments/assets/6c609290-4226-44ae-8747-050876cc50fb)

**Comment by obgnail** [comment]
@hwy1782 

你好，感谢反馈。

关闭【斜杆命令】插件即可。

关闭方法：右键菜单 - 少用插件 - 启停插件 - 取消勾选【斜杆命令】

**Comment by obgnail** [comment]
此 issue 关闭，如有问题麻烦在下面留言。

**Comment by hwy1782** [comment]
感谢
