### ISSUE TITLE
问题反馈：出现无法正常键入中文但是英文键入的情况。

### ISSUE THREAD

**Issue by wczhan** [obgnail/typora_plugin#693]
大神您好，感谢你如此无私地奉献这么好用的插件！

在此要向你反馈一个问题：就是我现在打开了自己的typora文档后，经常出现无法正常键入中文但是英文输入法正常运作的情形，这种情况下我一般会关闭掉文档，然后重新打开文档。但是没过多久中文输入法又再次失效了...

我尝试安装其他的中文输入法，都会出现这个现象，这种现象在我使用插件之前没有出现过，不知道你是否有什么好的解决办法？

**Comment by obgnail** [comment]
@wczhan 

你好，感谢反馈。

不应该吧，第一次听说这个情况。本插件系统不会对输入法做任何调整。实际上，**从原理上说，基于 Web 技术的本项目是无法影响到系统的**。

我猜大概率是 Windows 自己的 BUG，输入法是 Windows BUG 的重灾区。我自己也总是遇到输入法的相关 BUG。

你先做如下尝试：
1. 重启电脑，试试还有没有问题。
2. 如果还有问题，尝试【在 Typora 右键菜单 -> 少用插件 -> 帮助 -> 卸载插件】。卸载完毕后看看还有没有问题。

**Comment by wczhan** [comment]
谢谢大神，明白了，我试试！

**Comment by obgnail** [comment]
这个 BUG 只在 Typora 里能复现吗？其他软件里输入有没有问题？重启电脑后，建议到其他软件测试一下，也许是你的操作有问题，不小心点到了切换导致的。

**Comment by wczhan** [comment]
明白你的意思啦，我会留意一下这个BUG出现的场景并做好记录，确实很奇怪...之前没有遇到过这个问题

**Comment by wczhan** [comment]
> @wczhan
> 
> 你好，感谢反馈。
> 
> 不应该吧，第一次听说这个情况。本插件系统不会对输入法做任何调整。实际上，**从原理上说，基于 Web 技术的本项目是无法影响到系统的**。
> 
> 我猜大概率是 Windows 自己的 BUG，输入法是 Windows BUG 的重灾区。我自己也总是遇到输入法的相关 BUG。
> 
> 你先做如下尝试：
> 
> 1. 重启电脑，试试还有没有问题。
> 2. 如果还有问题，尝试【在 Typora 右键菜单 -> 少用插件 -> 帮助 -> 卸载插件】。卸载完毕后看看还有没有问题。

这个帖子[Typora输入卡顿解决办法\_typora卡顿解决方法-CSDN博客](https://blog.csdn.net/m0_58699417/article/details/125744005)提到的解决方案和你说的一样，是输入法的问题，我刚才关闭了自带输入法的兼容性，且现在使用搜狗输入法，我看看还会不会出现这个问题。

**Comment by wczhan** [comment]
刚才我的电脑又出现了这个问题，我突然想到可能是因为我笔记本扩展了两块显示器的原因，因为输入法的输入状态是正常的，但是无法在当前的 `TYPORA` 页面中键入中文，于是我按照以下方法在自己笔记本上进行了设置：

`语言设置` - `键盘` - `切换输入法` - 勾选 `允许我为每个应用窗口使用不同的输入法` 

神奇地发现没什么问题了，我看看接下来还会不会出现这个问题，谢谢大神啦

**Comment by obgnail** [comment]
@wczhan 

好的，这玩意可能需要您自己的去探索了。

我只能向您传达：**插件系统只影响了 Typora 软件本体，不会调整包含输入法在内的任何系统配置**。

如果真的出现奇奇怪怪的 BUG，您可以按照上述方式卸载插件系统。

---

此 issue 暂时关闭，如有问题，麻烦在下面留言或者另开 issue。（另：如需留言，您可以向其他人一样，叫我【作者】就行）
