### ISSUE TITLE
是否可以在插件自动增加的图片序号中编辑相应的图片标题？

### ISSUE THREAD

**Issue by wczhan** [obgnail/typora_plugin#694]
![image](https://github.com/user-attachments/assets/bc06578b-481d-4452-96b6-3789ec8d1eaa)

如图所示，`Figure 0-2` 是插件所生成的图片编号，我想给上述图片重命名为：

```markdown
Figure 0-2: Typora Logo
```

我现在使用的方法是通过 `内嵌html` 所实现的：

```html
<center style="color:#C0C0C0;text-decoration:underline">Figure 0-2: Typora Logo</center>
```

可否直接编辑插件所自动生成的 `Figure 0-2` 呢？

**Comment by wczhan** [comment]
是否可以查询当前的插件版本的
`版本号`以及`是否是最新版本`？

**Comment by obgnail** [comment]
@wczhan 

## 当前版本号

一开始是没有的，**在成功升级一次后开始记录**。如果你之前升级过，你可以看一下【右键菜单 -> 少用插件 -> 帮助 -> 升级插件】

![IMG_2024-08-07_02-38-54](https://github.com/user-attachments/assets/2e96ce26-e658-4209-8201-c5f771cc9eb9)

## 是否为最新版本

需要访问：https://api.github.com/repos/obgnail/typora_plugin/releases/latest

## 用户无需考虑

实际上，用户都不需要考虑这些，上面的全部逻辑都集成在【pluginUpdater】插件上了，用户可以一键更新。

**Comment by obgnail** [comment]
我睡了，有问题麻烦在下面留言，我明天回复。

**Comment by wczhan** [comment]
好的，大神晚安哈！

目前的问题是：我的插件没办法显示`升级插件`

![3db8e3cab6c75e878c36fddd65ccc79](https://github.com/user-attachments/assets/07dc1801-f076-49e6-98e5-41c55bb50898)

然后我去了插件配置中查看，如下所示：

![image](https://github.com/user-attachments/assets/6f1f2396-d4ac-4139-ac03-37ce6741a96a)

显示 `pluginUpdater` 是打开的。

会不会是因为我的 `TYPORA` 装在了 C盘 Promgram 文件夹内，从而必须将这个插件也装在C盘路径下的缘故？

**Comment by obgnail** [comment]
@wczhan 

麻烦看一下 1247 行，看看是否为此情况。可能是被杀毒软件干掉了。

> 1.10.0 重构了插件升级功能，解决了一系列无法升级的问题。此后的版本应该不会再出现无法升级的情况。

所以，你也可以手动升级一次：
1. 到 https://github.com/obgnail/typora_plugin/releases/tag/1.10.7 下载新版本
2. 右键菜单 -> 少用插件 -> 帮助 -> 备份配置，得到三个备份的配置文件
3. 将新版本的 plugin 目录 覆盖到 Typora/plugin 目录（为了保证不会出问题，先删除 Typora/plugin 目录下的文件，然后再粘贴进去，不要直接覆盖）
4. 将备份的配置文件覆盖回 Typora/plugin/global/settings

**Comment by wczhan** [comment]
谢谢大佬，我按照你手动升级的方式，更新好了，现在已经出现了 `升级插件` 的选项了，不过，当我点击`升级插件`的时候，会弹出如下提示，这是因为目前的版本已经是最新了的吧？

![image](https://github.com/user-attachments/assets/bba3fbc7-b10c-44a4-a63c-bdd4d4ecd162)

**Comment by wczhan** [comment]
在最新的版本中，我已经可以在插件自动增加的图片序号中编辑相应的图片标题！谢谢大神

**Comment by obgnail** [comment]
> 这是因为目前的版本已经是最新了的吧？

并不是，如果是最新版，那么会提示无需更新。

你的情况是 Typora 安装在了 Promgram Files 目录导致的，此目录的权限管理会比其他目录更加严格。

解决方式：手动给 Typora/plugin 目录授权。你可以按照 https://www.cnblogs.com/loaferwp/p/16693991.html 步骤做。

> 我不是很懂 Windows 的权限管理，麻烦尝试之后反馈一下是否能成功执行。

**Comment by wczhan** [comment]
您好

> > 这是因为目前的版本已经是最新了的吧？
> 
> 并不是，如果是最新版，那么会提示无需更新。
> 
> 你的情况是 Typora 安装在了 Promgram Files 目录导致的，此目录的权限管理会比其他目录更加严格。
> 
> 解决方式：手动给 Typora/plugin 目录授权。你可以按照 https://www.cnblogs.com/loaferwp/p/16693991.html 步骤做。
> 
> > 我不是很懂 Windows 的权限管理，麻烦尝试之后反馈一下是否能成功执行。

大神你好，这个[[Windows文件夹权限设置 - loaferWP - 博客园](https://www.cnblogs.com/loaferwp/p/16693991.html)](https://www.cnblogs.com/loaferwp/p/16693991.html)方法非常好！我现在可以直接在`Promgram Files` 目录下直接编辑 `settings.user.toml` 这个文件了，之前都会提醒我说要我 `使用管理员权限修改`，现在不会提醒了，谢谢大神！

**Comment by obgnail** [comment]
能正常升级吗？

**Comment by wczhan** [comment]
> 能正常升级吗？

没问题，刚才试了！

**Comment by obgnail** [comment]
好的，此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
