### ISSUE TITLE
为啥导出增强插件偶尔不见了？

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#695]
为啥导出增强插件偶尔不见了？

![image](https://github.com/user-attachments/assets/f5c01e50-aa3f-4c50-97b9-e4ce6bb9b08c)

**Comment by obgnail** [comment]
@xiaogithubooo 

你好，感谢反馈。

四天前的 [1.10.6](https://github.com/obgnail/typora_plugin/releases/tag/1.10.6) 版本已经修复了此问题。

**Comment by obgnail** [comment]
此 issue 关闭，如果还有问题，麻烦在下面留言。

**Comment by xiaogithubooo** [comment]
hhhh非常感谢~
