### ISSUE TITLE
找不到修改markdown格式警报的地方（软件内）

### ISSUE THREAD

**Issue by ZAerBeiGa** [obgnail/typora_plugin#698]
先疯狂保命
* 只用了1周typora
* 装上插件的时候没注意有没有报错功能，可能是typora自己的报错
* 找这个功能也只是在软件里找了半小时）
正题：这是报错
![1723096520415](https://github.com/user-attachments/assets/fc4a8fcf-a001-49ae-8006-8938872e7866)
这本身没什么问题，但我在文档中看到了这个
![1723098345302](https://github.com/user-attachments/assets/46bd56a6-dcb7-44c2-901d-bfa2fe30aef1)
这里提到**允许嵌套重复**，我并没有找到这个选项
或者说重复本身会出现什么问题（或者说不优雅）

**Comment by obgnail** [comment]
@ZAerBeiGa 

你好，感谢反馈。

1. markdownLint 是一个插件，不是原生的功能。
2. 目前插件系统的配置是基于文件的，没有提供 UI 层面的配置。所以若你想修改配置，暂时只能到配置文件中修改。（主要原因：我也想做成 UI 呀，但是目前整个插件系统有 600+ 项配置，其数据结构也很复杂，做成 UI 要被累死）
3. 回到正题，这是一个 BUG，目前已经修复，麻烦升级到最新版本试用。

PS：siblings_only 这个配置暂时是写死在代码中的，没有暴露到配置文件中。

> 修改配置文件的方式，升级插件的方式请阅读 readme。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。
