### ISSUE TITLE
能否提供typora代码块方案切换功能。

### ISSUE THREAD

**Issue by fyxsky** [obgnail/typora_plugin#703]
Typora 默认使用 codeMirror 作为代码块，是否可以切换为 Prism 作为代码块方案。
CodeMirror 支持的语言有点少，对于一些小众语言不支持。
例如 Excel 和 Power BI 中用到的的 DAX 语言等等。

**Comment by obgnail** [comment]
@fyxsky 

你好，感谢反馈。

做不了，没有这么大的自由度。目前 Typora 代码块的所有功能都是强依赖 CodeMirror 的。这种组件替换级别的需求只能等 Typora 官方提供支持。

typora_plugin 本质是黑魔法，利用装饰器 hook 住 Typora 内置函数，在函数执行前后注入逻辑。

我怀疑 Typora 永远无法支持这个需求。一方面是此需求需要重构才能实现，另一方面 Typora 目前已经存在数目众多的 Theme，一旦支持此需求，全部的 Theme 都会失效。

---

你的需求是支持小众语言的高亮，其实完全不必有如此大的改动，你可以去给 Typora 官方提一个 issue，让他支持此功能。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言。
