### ISSUE TITLE
能否为插件状态增加提示

### ISSUE THREAD

**Issue by Ethan-Chase** [obgnail/typora_plugin#707]
像是这种禁用/启用的非插入类或单次生效的按钮在生效后不会切换显示状态，不能直观的看出是否生效

![image](https://github.com/user-attachments/assets/ec0acff3-d744-46d8-84b1-6fa6c8b14ab3)

是否可以在
启用/禁用之间切换
或是变成启用之后在后方加一个√，例如
启用按钮：折叠 √  即表示启用
启用按钮：折叠   即表示未启用

**Comment by obgnail** [comment]
@Ethan-Chase

需求已实现。麻烦升级到新版本试用。

![IMG_2024-09-11_21-00-02](https://github.com/user-attachments/assets/7f691bc2-db53-41e2-9434-4c80dee8e5a6)
![IMG_2024-09-11_21-00-06](https://github.com/user-attachments/assets/868cafb9-acff-4e50-a736-53c404dfe62f)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
注意：此功能仅在高于 0.9.98 版本的 Typora 可用
