### ISSUE TITLE
0.9.98版本 安装包

### ISSUE THREAD

**Issue by flying-lby** [obgnail/typora_plugin#719]
请问能提供一个0.9.98版本的typora安装包吗，之前那个版本用不了这个插件

**Comment by obgnail** [comment]
@flying-lby 

github 随便搜一下就有了，比如这是我刚刚找的：https://github.com/tobyqin/Typora-Portable/releases

**Comment by obgnail** [comment]
0.11.18 好像会被远程施法，建议安装 0.9.98 版本

**Comment by flying-lby** [comment]
好的好的，感谢感谢，感觉被秒回了
