### ISSUE TITLE
大纲目录无法折叠，高亮语法无法使用

### ISSUE THREAD

**Issue by flying-lby** [obgnail/typora_plugin#720]
你好，使用插件后遇到了几个小问题，原本markdown语法==内容高亮显示无法使用，另外大纲目录也全部展开了，无法像之前那样将同级目录折叠
![image](https://github.com/user-attachments/assets/8353ddf4-82aa-4ccd-a24b-72955cde3aa8)

**Comment by obgnail** [comment]
@flying-lby 

我试了，没问题的。应该是你没有打开相关配置，键入快捷键【ctrl+逗号】检查一下。

1. 高亮语法在 Markdown -> Markdown 拓展语法 -> 高亮
2. 目录折叠在 文件 -> 大纲 -> 允许折叠和展开侧边栏的大纲视图


![IMG_2024-08-23_22-58-56](https://github.com/user-attachments/assets/911115e4-d208-4ce5-8199-83a71fba6916)
![IMG_2024-08-23_23-00-13 (1)](https://github.com/user-attachments/assets/365e83a2-f2cd-48f3-a831-39bc2929c9c0)

**Comment by obgnail** [comment]
设置完记得重启 Typora

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
