### ISSUE TITLE
使用增强导出时提示没有这个文件或者路径

### ISSUE THREAD

**Issue by lyidle** [obgnail/typora_plugin#721]
![Clip_2024-08-24_18-49-35](https://github.com/user-attachments/assets/827a7d87-8323-4a40-9f24-772b8dcfa4b2)
使用增强导出时提示没有这个文件或者路径
环境：
版本Windows11专业工作站版
版本号23H2
安装日期2024/8/10
操作系统版本22631.3880
体验Windows Feature Experience Pack 1000.22700.1020.0
Typora for Windows (x64)     version1. 9. 5

**Comment by obgnail** [comment]
@lyidle 

你好，感谢反馈。

感谢提供报错图，报错原因是：export_enhance 没有处理转义的图片 URL，导致找不到路径。已经修复，commit 在 [这里](https://github.com/obgnail/typora_plugin/pull/722/commits/866fc72ca25cd3f9fc325b49803bbc8661208074)。

目前新版本已经修复，麻烦升级到最新版本试用一下。

**Comment by obgnail** [comment]
已经修复。此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
