### ISSUE TITLE
[求助]插件主题与hexo主题同步问题

### ISSUE THREAD

**Issue by lshcx** [obgnail/typora_plugin#726]
首先非常感谢作者开发这个插件，对我帮助很大。
然后想请教一下有没有方法实现插件的主题和hexo主题的同步？

如插件中的提示块是”> [!Note]“,
而hexo主题butterfly中的是
```
{% note info simple %}
info 提示塊標籤
{% endnote %}
```
互相无法解析

**Comment by obgnail** [comment]
@lshcx 

你好，感谢反馈。

这个需求应该是做不了。抱歉。

1. 从标准上说，callouts 的事实语法是 `> [!Note]`，而大括号的语法是 Hexo 的插件自定义语法。插件应该使用标准（事实）语法，而不是自定义语法。
2. 从技术上说，我暂时想不到该如何实现。Typora 本质还是插件，自由度没那么大，受到 Typora 的限制。要想实现上述语法，需要修改语法解析器，改不了。

此 issue 暂时关闭，如果你有问题或者有实现思路，麻烦在下面留言或者另开 issue。

**Comment by lshcx** [comment]
感谢您的回复，hexo对花括号的渲染是基于Nunjucks实现的。
回去之后研究了一下，思路是先正则匹配，根据匹配的类型、参数和内容，替换为自定义的样式，前端小白没能成功不知道是否可行。
看了您的回复后，决定放弃修改typora了，修改hexo也许更容易实现。

**Comment by obgnail** [comment]
@lshcx 

解释下为什么说在技术上实现不了。

根本原因：Typora 的语法解析和语义解释是一遍完成的，目前我没有办法修改这个过程。在无法修改语法解析器的前提下，只能通过伪装的方式实现。

---

callouts 组件是一个鸭子类型：
1. callouts `> [!Note]` 和 blockquote `> ` 语法结构高度相近
2. callouts 和 blockquote 都为 block 组件，都支持嵌套其他组件（比如说无序列表）

实际上，callouts 这个插件的实现过程中，`> [!Note]` 并没有被解释为 callouts 组件，依旧解释为 `blockquote`，我做的不过是修改这个 blockquote 对应的样式罢了。

也就是说，**callouts 这个插件其实是一个黑魔法，是把鹅视为鸭子的过程**，伪装过程完全仰赖于一个特点： callouts 和 blockquote 语法结构和行为特性高度一致。

---

下面的 markdown 代码，会被直接解释为三行 plain。现在的问题就是：语法结构和行为特性都不一致，我无法将多行 plain 通过修改样式，伪装为 callouts。

鹅经过一顿修饰能视为鸭子，狗再怎么修饰都无法视为鸭子。

```markdown
{% note info simple %}
info 提示塊標籤
{% endnote %}
```
