### ISSUE TITLE
怎么引用公式、图、表

### ISSUE THREAD

**Issue by styw1234** [obgnail/typora_plugin#728]
公式、图、表自动编号后，请问如何引用这些编号？

当插入新的公式、图、表后，原来引用的编号依然有效，无需再进行手动调整。

**Comment by obgnail** [comment]
@styw1234 

你好，感谢反馈。

1. 引用的编号是使用 CSS 的 counter 属性实现的，仅有显示功能，没有引用功能。
2. 引用公式、图、表的功能不属于 [CommonMark](https://commonmark.org/)，需要自定义语法才能实现。本插件系统不希望污染标准语法，因此，此需求实现不了。抱歉。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
