### ISSUE TITLE
直达顶部和直达底部按钮无效

### ISSUE THREAD

**Issue by Ignorant12321** [obgnail/typora_plugin#729]
具体情况如下：
![recording](https://github.com/user-attachments/assets/06335eb3-261f-44b4-bef6-cd7e934756e7)

**Comment by obgnail** [comment]
@Ignorant12321 

你好，感谢反馈。很奇怪，这个插件很久没修改了。

麻烦尝试以下：

1. 其他按钮有效吗？
2. 切换其他文件，尝试一下。
3. 切换回默认的主题（github.css），尝试一下。（如果切换回默认主题后问题消失，麻烦反馈一下您使用的主题）
4. 【右键菜单 -> 少用插件 -> 启停插件】，查看【一键到顶（go_top）】插件是否开启。
5. 如果可以，帮忙打开调试控制台，查看一下报错。

**Comment by Ignorant12321** [comment]
![recording](https://github.com/user-attachments/assets/3cf539d9-61aa-4099-a39e-15f8938e167f)
1. 其他按钮均有效
2. 用github.css主题，
3. 切换其他文件依然存在此情况
4. 插件已用
5. 未打开任何文档时，console的情况
![image](https://github.com/user-attachments/assets/5744b55e-850e-4943-a4a0-100e67129740)
打开目标文档，console的情况
![image](https://github.com/user-attachments/assets/293b6d77-f638-4da5-819f-d91736596f79)

**Comment by obgnail** [comment]
@Ignorant12321 

好奇怪呀。

麻烦尝试以下：
1. 保持 Console 打开，点击按钮，查看是否报错
2. 重启 Typora 再试一下（有可能你遇到万分之一的情况导致 ID 重复了）

麻烦回答以下：
1. Typora 的版本是多少？是升级 Typora 后出现的吗？
2. 大概什么时候出现这个情况的？昨天/上周 有出现此问题吗？是升级插件后出现的吗？
3. 升级过插件吗？当前插件版本是多少？（如果升级过插件，可以在【右键菜单 -> 少用插件 -> 帮助】中看到）

**Comment by Ignorant12321** [comment]
已重启，上版本和最新版仍出现此情况，上周偶然使用该按钮，突然发现出现此情况。
![recording](https://github.com/user-attachments/assets/6900c840-ffc0-4737-807a-b4dc5ffc213e)

**Comment by obgnail** [comment]
@Ignorant12321 

你好，感谢反馈。

我在虚拟机里安装了最新版本的 Typora 测试了一下，没有发现异常（忽略右边的未激活报错）

这个插件不到 20 行代码，已经半年没更新过了，所以我猜测应该是环境问题

不嫌麻烦的话，可以将整个 plugin 目录打包发给我，我来排查排查。

![ttt (1)](https://github.com/user-attachments/assets/c3c0b006-5a00-4f0c-8b25-0c31fcf795a3)

**Comment by Ignorant12321** [comment]
感谢，已找到原因。打字机模式无法兼容跳转功能。（跳转功能仅在普通视图和专注视图模式下适用）
![recording](https://github.com/user-attachments/assets/9731c912-c433-4e67-a80b-38386a6cb5f7)
