### ISSUE TITLE
升级失败问题

### ISSUE THREAD

**Issue by styw1234** [obgnail/typora_plugin#733]
你好，自动升级失败问题：鼠标右键选择自动升级，提示升级失败

![PixPin 20240903 200620](https://github.com/user-attachments/assets/675ce5a6-885c-40c1-a085-f42eae16ca4a)
![PixPin 20240903 200606](https://github.com/user-attachments/assets/6841b0f7-1546-4937-a977-a2a269a00675)

**Comment by styw1234** [comment]
我的电脑只有一个C盘，没有D盘

**Comment by obgnail** [comment]
@styw1234 

你好，感谢反馈。

大概率是网络问题，导致下载失败。

我也经常遇到网络问题导致升级失败的情况，建议再试一两次。我一般重试 2-3 次就能成功。

> PS：你的插件版本很老了，1.10.0 版本已经完全重构升级逻辑了，相关文件在新版本中已经被删除了，因此就算是 BUG，也没有修复的必要了。

---

如果总是失败，可以手动升级：

1. **备份用户配置**：前往目录 `Typora\plugin\global\settings\`，将三个后缀为 `user.toml` 的文件移到到其他地方
2. **下载最新版本**：[最新版本](https://github.com/obgnail/typora_plugin/releases/tag/1.10.25) 
3. **覆盖 plugin 目录**：将 新版本的 plugin 文件夹覆盖到原来的 `Typora/plugin` 文件夹中
4. **还原用户配置**：将第一步得到的三个配置文件覆盖回 `Typora\plugin\global\settings\` 中

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by styw1234** [comment]
你好，按照提示操作后，鼠标右键插件功能完全消失了。
如图所示：

![PixPin 20240904 081633](https://github.com/user-attachments/assets/430c16c3-8e52-4c2c-8135-8862d0379e8d)

**Comment by obgnail** [comment]
@styw1234 

麻烦看一下控制台，如果没有报错，可能是你的配置文件放错位置了。

**Comment by styw1234** [comment]
请问怎么看控制台呢？plugin文件夹的位置：
![PixPin 20240904 152804](https://github.com/user-attachments/assets/8ded3038-6bdf-4be6-8f7e-3a34667e9b11)
3个配置文件的位置：
![PixPin 20240904 152902](https://github.com/user-attachments/assets/d27de29c-c15c-40b3-8a56-06f2dff89290)

**Comment by obgnail** [comment]
@styw1234 

可能是你装在 C 盘的原因。C 盘下权限管理会比其他目录更加严格。

解决方式：手动给 plugin 目录授权。你可以按照 https://www.cnblogs.com/loaferwp/p/16693991.html 步骤做。

**Comment by styw1234** [comment]
授权了，但好像依然不起作用。

![PixPin 20240905 092517](https://github.com/user-attachments/assets/87c133f7-f05f-4031-b2f4-11dbcfca035b)
![PixPin 20240905 092435](https://github.com/user-attachments/assets/b7920897-f057-4e90-96a7-0078e5a1ade7)

**Comment by obgnail** [comment]
你的现象确实比较奇怪，第一次遇到 之前能安装成功，现在安装不成功的情况。

麻烦尝试重新安装一下：
1. 备份 `C:\MyProgram\typora_v1.7.0_x64_cracked\resources\plugin\global\settings\` 下三个 `user.toml` （注意不要备份 `default.toml` 文件）
2. 删除 `C:\MyProgram\typora_v1.7.0_x64_cracked\resources\plugin` 目录 和 `C:\MyProgram\typora_v1.7.0_x64_cracked\resources\plugin\window.html.bak`
3. 按 [下面步骤](https://github.com/obgnail/typora_plugin?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95%E4%B8%80%E8%87%AA%E5%8A%A8) 重新安装插件
4. 双击打开 `C:\MyProgram\typora_v1.7.0_x64_cracked\Typora.exe`，验证是否成功
5. 如果成功，将 三个备份的 user.toml 文件还原回原来的位置， 双击打开 `C:\MyProgram\typora_v1.7.0_x64_cracked\Typora.exe`，验证是否成功

---
如果上述步骤还是不行，尝试如下：

1. 【ctrl+逗号】打开偏好设置 -> 通用 -> 高级设置 -> 勾选【开启调试模式】
6. 回到正文区域，右键菜单，会发现多了一个【检查元素】选项，点击它
7. 点击第二个选项卡【控制台/Console】，正常情况下应该会出现如下，
8. 如果不出现下图，麻烦截图发给我

![IMG_2024-09-05_11-39-08 (1)](https://github.com/user-attachments/assets/af78af5e-997f-45fd-b1bc-058ba1262740)

**Comment by styw1234** [comment]
感谢大佬，删除了C:\MyProgram\typora_v1.7.0_x64_cracked\resources\plugin\window.html.bak
按照提示要求重装插件后插件恢复正常，非常感谢！
![PixPin 20240906 100218](https://github.com/user-attachments/assets/63f0dcba-827c-4ff2-82ac-921260a1a663)
svg格式的图片能够顺利正常导出，粘贴到ppt中也没问题
![PixPin 20240906 100713](https://github.com/user-attachments/assets/9d5e811c-d6b2-4030-a328-af89d43f9090)

**Comment by obgnail** [comment]
@styw1234 

PPT 的 SVG 解析器不支持 CSS 变量，导致节点的颜色变黑。新版本中我已经添加了新的配置 `尽力解决样式兼容性问题`，感兴趣的话可以升级到最新版本试用。
