### ISSUE TITLE
希望 图片管理 功能，可以过滤掉非图片文件链接

### ISSUE THREAD

**Issue by at2008** [obgnail/typora_plugin#734]
因为obsidian支持拖入、插入附件，所以用obsidian编辑的md文档可能包含一些非图片类的链接，[typora_plugin](https://github.com/obgnail/typora_plugin)插件的图片管理功能，会把所有有后缀的本地链接都列出来；

建议图片管理功能，是否可以过滤图片后缀名，否则zip、js之类的文件也会显示；

最好浏览图片界面下面加个图片列表预览；

**Comment by obgnail** [comment]
@at2008 

两个需求皆已实现，麻烦升级到最新版本试用。

> 升级插件方法：右键菜单 -> 常用插件 -> 二级插件 -> 升级插件

此 issue 关闭，如有问题，请在下面留言或者另开 issue。

**Comment by at2008** [comment]
感谢及时更新和回复 ❤，就是 使用 升级插件 功能升级，和手动下载 1.1.026 版本，更新后，前面提到的需求没有变化，我用干净虚拟机重新装了typora 和 插件，同样没生效。是不是没有更新代码未生效？ 😂

**Comment by at2008** [comment]
> @at2008
> 
> 两个需求皆已实现，麻烦升级到最新版本试用。
> 
> > 升级插件方法：右键菜单 -> 常用插件 -> 二级插件 -> 升级插件
> 
> 此 issue 关闭，如有问题，请在下面留言或者另开 issue。

感谢及时更新和回复 ❤， 如果插入的文件链接是wikilink格式的 `[[测试.json]]`，插件过滤掉了；markdown 格式的文件链接 `[测试](测试.json)`，没有过滤掉。

**Comment by obgnail** [comment]
@at2008 

请看下图：
1. 我在 assets 目录创建了一个 test.png，此图片文件没有被任何 md 文件引用；创建了一个 测试.json 文件，在 md 文件以 link（`[测试](./assets/测试.json)`） 和 image（`![测试](./assets/测试.json)`） 两种方式引用
2. 无论是 `[测试](./assets/测试.json)` 还是 `![测试](./assets/测试.json)` 都没有被视为 图片
3. 点击右上角的眼睛，即可预览。

md 原文件为：
```markdown
[测试](./assets/测试.json)

![测试](./assets/测试.json)
```

![ttt (1)](https://github.com/user-attachments/assets/c463fa23-d84d-4d78-98ad-c0ae344dd04b)

---

是我理解错了吗？

麻烦能详细说明你那边的 BUG 吗？

**Comment by at2008** [comment]
@obgnail 

我提这个 issues 的起因是 图片管理 功能，您是不是演示的 资源管理 ？ 是不是我理解有误？ 😊

![image](https://github.com/user-attachments/assets/4f042fa0-f215-452b-8657-f2308c6aac2c)

点击 图片管理 ，embed 状态文件链接会显示 

![image](https://github.com/user-attachments/assets/516412a7-be43-44b3-b1a5-37950d5d351f)

**Comment by obgnail** [comment]
@at2008 

尴尬了，搞错插件了 😂

我下个版本搞这个需求

**Comment by at2008** [comment]
> @at2008
> 
> 尴尬了，搞错插件了 😂
> 
> 我下个版本搞这个需求

哈哈哈哈 我以为我理解错了 😂

**Comment by obgnail** [comment]
我发现【资源管理】也没有过滤 .json 等非图片格式的文件，就以为你讲的是这个插件。

**Comment by at2008** [comment]
为避免误解，再明确一下需求

1. 建议插件的 **图片管理** 功能过滤掉 embed 状态非图片格式的文件链接，浏览图片界面下方最好加个图片列表预览；

2. 如果可以的话，能优化一下非图片格式的文件链接 embed 状态在typora中的显示样式，目前 typora 是这样显示的

![image](https://github.com/user-attachments/assets/fd47c98d-a8f9-4872-88e3-df5da7cba184)

obsidian 是这样显示的

![image](https://github.com/user-attachments/assets/b2bb6dc6-5691-4cce-8367-4948d40c7b6d)

**Comment by obgnail** [comment]
@at2008 

功能点比较多，会分多版本迭代，汇报一下新版本进度。

1. 新版本的图片管理插件，新增配置选项 filter_error_image，支持过滤没有 embed 的图片。
2. 列表预览功能应该会在下个版本做。

**Comment by at2008** [comment]
辛苦了 🤝，已更新 1.10.27 版本，经测试 **图片管理** 已经正常过滤非图片文件，感谢更新！👏

**Comment by obgnail** [comment]
@at2008 

图片列表预览功能已经实现，麻烦升级到最新版试用一下。

**Comment by at2008** [comment]
@obgnail 浏览过程中，操作图片定位，无法准确跳转到文档中图片的位置。

**Comment by obgnail** [comment]
@at2008 

我测试没有问题呀，麻烦详细说明

![ttt2 (1)](https://github.com/user-attachments/assets/ab911fc7-2835-4d8b-a545-8c5d4428ae91)

**Comment by at2008** [comment]
@obgnail 

![动画](https://github.com/user-attachments/assets/a87d51fd-1a12-4cd1-aa76-4c2f2406b3c3)

**Comment by obgnail** [comment]
@at2008 

感谢反馈。

1. 已修复。预计明天发版。
2. BUG 原因：上次支持了你的需求：非图片格式 `![测试.json](<./assets/test/测试.json>)` 。导致图片定位逻辑出现了 BUG，进而导致定位的时候总是定位到上一个 img。
3. 临时绕过：删除  `![测试.json](<./assets/test/测试.json>)`  即可正常

**Comment by obgnail** [comment]
感谢反馈，此需求已完成，如有问题，麻烦另开 issue。
