### ISSUE TITLE
不是哥们

### ISSUE THREAD

**Issue by Faye-DW** [obgnail/typora_plugin#740]
哥们你plugin目录里面根本没有updater文件夹

**Comment by obgnail** [comment]
@Faye-DW 

1. 1.10.0 版本重构了升级逻辑，删除了 updater 目录，updater.exe 也没有了。
2. 现在安装和卸载的操作放在了 bin 目录下。
3. 升级逻辑使用 node.js 重构了，因此如果你想升级，可以在 Typora 里操作：【右键菜单 -> 常用插件 -> 二级插件 -> 升级插件】

**Comment by obgnail** [comment]
总之，你用的插件版本很老了，目前已经换方案了。老方案对应目录已经删除了。请参考新版本的 [安装方法](https://github.com/obgnail/typora_plugin?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95%E4%B8%80%E8%87%AA%E5%8A%A8)
和 [升级方法](https://github.com/obgnail/typora_plugin?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E5%8D%87%E7%BA%A7%E6%8F%92%E4%BB%B6)

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
