### ISSUE TITLE
安装插件后，可否保持标题与原生一样

### ISSUE THREAD

**Issue by Fengjun-sh** [obgnail/typora_plugin#744]
鼠标点击标题，不再显示markdown语法标记。比如：鼠标点击标题，会显示`## 标题`。如何设置，恢复原生状态。

**Comment by obgnail** [comment]
@Fengjun-sh 

你好，感谢反馈。

此功能和插件【章节折叠】冲突了。可以通过关闭此插件恢复。

> 关闭方法：右键菜单 -> 少用插件 -> 启停插件 -> 取消勾选【章节折叠（collapse_paragraph）】 -> 确定

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
感谢支持，思维导图应该是我花费最多时间的插件了，希望你喜欢。
