### ISSUE TITLE
目前插件适合的 typora 最新版本是哪一个

### ISSUE THREAD

**Issue by xiaogithubooo** [obgnail/typora_plugin#746]
更新完最新版本的插件后，我一拍脑袋就给自己的 `typora` 手动更新了...

然后插件就都不见了(￣﹃￣)...

想知道目前插件支持的 `typora` 的最新版本是哪一个，我需要回退 `typora` 到哪一个版本？

![image](https://github.com/user-attachments/assets/0c3a05e4-93c1-4653-a857-022ea926131f)

![image](https://github.com/user-attachments/assets/e9855a08-e964-416d-ad27-d15c1cca96c8)

拜托了，我已经脱离不开您的插件了o(TヘTo)

**Comment by obgnail** [comment]
我目前在 1.9.4。你的 1.9.5 版本不能用吗？我之前测试某个 BUG 的时候用的就是 1.9.5 呀。

---

理论上升级 Typora 并不会删除 plugin 目录，只是删除了插件的入口而已。

也就是说，每次升级完 Typora，需要重新注册入口。具体做法就是：双击 `\plugin\bin\install_windows_amd_x64.exe`

**Comment by obgnail** [comment]
目前来说，typora_plugin 应该是支持任何版本的

**Comment by xiaogithubooo** [comment]
这下有了，非常感谢！
