### ISSUE TITLE
中英文混排优化处理`<br />`

### ISSUE THREAD

**Issue by wjwj14** [obgnail/typora_plugin#749]
中英文混排优化会自动给typora列表里`<br />`的前后，分别加上空格，导致列表各段无法对齐，该如何避免这个特性呢。

![image](https://github.com/user-attachments/assets/a4407438-a87c-4d54-b1db-5c34e5d0ed7a)

**Comment by obgnail** [comment]
@wjwj14 

你好，感谢反馈。

遇到希望保持原状的片段，可以在前后添加 `<!--md-padding-ignore-begin-->` 和 `<!--md-padding-ignore-end-->` 标签包裹起来。


```markdown
下面是一段不需要格式化的文本
<!--md-padding-ignore-begin-->
a*b=c, b>1 => a<c
<!--md-padding-ignore-end-->
现在开始又可以格式化了。
```

具体到你的情况：

```markdown
<!--md-padding-ignore-begin-->

|                             |      |      |
| --------------------------- | ---- | ---- |
| 123<br />456<br />789<br /> |      |      |

<!--md-padding-ignore-end-->

```

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
@wjwj14 

你好，我在新版本中支持了这个需求，现在可以自动处理 `<br />` 了，麻烦升级到新版本试用。
