### ISSUE TITLE
使用文件模板时只能点击确定创建文件，按回车会直接关闭typora

### ISSUE THREAD

**Issue by kongshan4219** [obgnail/typora_plugin#750]
typora：1.9.5
typora_plugin-1.10.31
能不能按回车时创建文件或者屏蔽回车
![image](https://github.com/user-attachments/assets/0f22c6f8-51c2-45aa-a808-32b0acd99595)

**Comment by obgnail** [comment]
@kongshan4219 

感谢反馈，已修复。麻烦升级到最新版本试用一下。

目前的逻辑是：`键入回车 = 点击确定 = 提交`

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
