### ISSUE TITLE
希望资源管理可以支持尖括号包裹的地址链接

### ISSUE THREAD

**Issue by at2008** [obgnail/typora_plugin#759]
这个插件非常棒，感谢作者的持续更新！

资源管理 功能目前似乎不支持 `![text](<./assets/filename>)` ，这种方式是markdown规范支持的格式，兼容性更好。

另外，codeblock 里面的文件链接是不是可以过滤掉，只是代码例子，不算资源。

**Comment by obgnail** [comment]
@at2008 

已修复，commit 在 [这里](https://github.com/obgnail/typora_plugin/pull/760/commits/67a704033b5bcd553cb6f99e746ba33acad81718)

已发版，麻烦升级到新版本试用。

另外，blockcode 是支持文件链接的，不能过滤。

![IMG_2024-09-22_12-25-04 (1)](https://github.com/user-attachments/assets/9f049aa3-f3bd-42fc-82ed-3bb63bbc3f64)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
