### ISSUE TITLE
切换标签页大纲会全部折叠

### ISSUE THREAD

**Issue by FriedShrimps** [obgnail/typora_plugin#761]
切换标签页原文件大纲会全部折叠, 非常影响体验, 希望能够改善, 非常棒的插件

**Comment by obgnail** [comment]
@FriedShrimps 

感谢反馈，没听太懂。是侧边栏的【文件】还是【大纲】？

麻烦能详细说明一下复现路径吗？或者录个屏

**Comment by FriedShrimps** [comment]
![PixPin_2024-09-22_14-18-59](https://github.com/user-attachments/assets/27617598-9c0c-424a-b7fc-f51d86150773)

**Comment by FriedShrimps** [comment]
就是切换文件大纲会叠起来,需要手动再次展开

**Comment by obgnail** [comment]
@FriedShrimps 

应该是 Typora 本身的 BUG 导致的。

如下，我删除了 plugin 目录，使用原生功能。结果轻易就复现了，一次能展开一次不能展开。

![bug_report (1)](https://github.com/user-attachments/assets/036d22e1-cfab-4464-afc9-2f1768f56978)

**Comment by obgnail** [comment]
我现在的版本是 1.9.4，实际上我很久之前就是因为这个 BUG 才停用了这个功能。

你那边使用原生功能能复现这个情况吗？

**Comment by FriedShrimps** [comment]
我也不行,应该是typora自身问题

**Comment by obgnail** [comment]
好的，感谢反馈。

此 issue 暂时关闭，如果后续有问题麻烦在下面留言或者另开 issue。
