### ISSUE TITLE
resize_image使用的快捷键ctrl+滚轮

### ISSUE THREAD

**Issue by George1825** [obgnail/typora_plugin#766]
你好，resize_image使用的快捷键ctrl+滚轮好像和typora的视图缩放快捷键冲突了，无法使用，能否调整快捷键？谢谢！

**Comment by obgnail** [comment]
@George1825 

感谢反馈。已修复，代码在 [dev](https://github.com/obgnail/typora_plugin/commit/0bbc22aede30276d48279cd56f46504c511e720f)，今晚发版。

1. 目前的解决方案是改成 `alt+滚轮`（修饰键改为 alt）。
2. 其实这件事挺难搞的。这个插件很早了，当初 Typora 官方并没有使用这个快捷键。现在改成 alt，会有很多用户感到疑惑，以为是插件出 BUG 了。
3. 我现在加了一个 MODIFIER_KEY 配置，让用户自己去修改修饰键。

**Comment by George1825** [comment]
谢谢！已经更新代码。
1.我发现这样缩放，重启typora之后，缩放效果就重置了，另外如果是导出pdf的话，图片也是原大小。
2.另外发现右键还有一个缩放图片的功能，这个功能会把md的图片语法变成html的语法，这样是可以保持缩放效果的。但没有快捷键。
能否增加一个滚轮调整图片大小的功能，并且可以永久维持固化效果？

**Comment by obgnail** [comment]
@George1825 

已实现，代码在 [dev](https://github.com/obgnail/typora_plugin/commit/e2759cf86e2556907417e222c3f7b80fb5b7652b)。

此功能默认关闭，需手动开启：

你可以将 PERSISTENT 置为 `shift+alt` 什么的，如果用不到临时变化，也可以置 `MODIFIER_KEY = { TEMPORARY = "", PERSISTENT = "alt" }`

```toml
# 各个功能对应的修饰键（为空则不使用对应的功能）
#   - TEMPORARY  : 临时修改图片大小
#   - PERSISTENT : 将图片转为HTML格式，永久修改图片大小
# 举例：【TEMPORARY = "alt"】：当鼠标悬停于图片，并且【alt+滚轮】后，就会临时修改图片大小
MODIFIER_KEY = { TEMPORARY = "alt", PERSISTENT = "" }
```

**Comment by George1825** [comment]
已测试，很好用，谢谢！

**Comment by obgnail** [comment]
已发版，此 issue 关闭，如有问题，麻烦另开 issue。
