### ISSUE TITLE
快捷鍵衝突，md-padding 的快捷鍵和軟件本身的代碼塊快捷鍵衝突了

### ISSUE THREAD

**Issue by SiaYung** [obgnail/typora_plugin#77]
如題。

**Comment by obgnail** [comment]
感谢反馈。

我开发 md-padding 的时候，用的是低版本的 Typora，当时 ctrl+shift+K 还没有被占用。
后续我应该会提供个配置页面给用户修改快捷键。

如果你比较急，可以通过右键菜单调用。或者直接修改代码：

![Snipaste_2023-08-13_21-33-15](https://github.com/obgnail/typora_plugin/assets/48992887/687ef700-962a-4e7f-ab1f-8e48e40e721b)
![Snipaste_2023-08-13_21-36-37](https://github.com/obgnail/typora_plugin/assets/48992887/20171bcd-4869-4dd2-a522-a1bd072b8c82)

**Comment by obgnail** [comment]
@SiaYung 你好

1.1.15 版本：

1. 加了 ctrl+shift+B 快捷键
2. 所有的配置都集成到 settings.toml 文件中，如果不喜欢这个快捷键，修改 settings.toml 文件，打开方式：鼠标在正文区域右键 -> 【右键菜单】 -> 【打开配置文件夹】
