### ISSUE TITLE
相见恨晚！感谢作者！

### ISSUE THREAD

**Issue by holwell** [obgnail/typora_plugin#771]
没想到还有这么好用的插件，我也不知道开这个 issue 合不合适，我想请教下可能和插件本身没关的问题，请教下见多识广的作者。

我想用一个本地文件夹来存放所有的 md 文件，把这个文件夹当本地日记本或博客使用，但是有个致命问题，没有博客那种时间线排序，假如我想在本地对自己写的 md 文件能够按时间排序，又能按主题排序，类似于 oneNote 那种，有什么好的方案吗。谢谢

**Comment by obgnail** [comment]
@holwell 

您好，感谢反馈。

不好意思，我倾向于有了进展再反馈。没想到您关掉了 issue。

这个需求我还在考虑，目前的初步结论是：**理论上不是不能做，但是很不适合**。

我解释一下。

1. 目前本插件从设计上就是无状态的，不会储存任何信息（甚至都不写日志）。如果要想按主题排序，必须记录每个文件的 front Matter 中的 tag。这导致 Typora 每次打开 Typora 都要扫描大量文件，影响性能。毕竟不像 Obsidian 一样有一个 vault。
2. 要想按时间排序，鉴于 Linux 的文件系统不含有文件的创建时间信息，因此只能按更改时间排序，类似于【最近修改的文件】的概念。或者就是像第一步那样，存储每个文件的创建时间和更新时间。
3. 最麻烦的是：侧边栏的文件排序是按时间排序的，这是写死在代码中的，而且是写死在 electron 后端的。如果要修改后端，那么就涉及解包文件什么的，如果只是修改前端，那么有不少代码需要兼容。

> 总之，由于 Typora 没有官方插件系统，typora_plugin 只能以一种入侵的方式修改程序逻辑。它不是一个真正的系统，比起程序，更像是一个木马。所以很多系统能简单实现的功能，插件需要花费大量精力去魔改，去兼容。

**Comment by obgnail** [comment]
正如上述所言，【按时间排序】、【按主题排序】这类功能，适用于那些拥有一个固定的 vault 的笔记系统（比如 oneNote）他们能了解并随时掌控 vault 里面的所有文件。这样就能建立数据库，然后在合适的时间获取这些信息。而 Typora 本质只是一个文本编辑器，没有管理文件的能力。

也就是说，这类功能和 Typora 的设计哲学是冲突的，强硬实现此功能的效果也不会很好。我这边还是建议您使用其他软件实现这个功能。

**Comment by holwell** [comment]
> @holwell
> 
> 您好，感谢反馈。
> 
> 不好意思，我倾向于有了进展再反馈。没想到您关掉了 issue。
> 
> 这个需求我还在考虑，目前的初步结论是：**理论上不是不能做，但是很不适合**。
> 
> 我解释一下。
> 
> 1. 目前本插件从设计上就是无状态的，不会储存任何信息（甚至都不写日志）。如果要想按主题排序，必须记录每个文件的 front Matter 中的 tag。这导致 Typora 每次打开 Typora 都要扫描大量文件，影响性能。毕竟不像 Obsidian 一样有一个 vault。
> 2. 要想按时间排序，鉴于 Linux 的文件系统不含有文件的创建时间信息，因此只能按更改时间排序，类似于【最近修改的文件】的概念。或者就是像第一步那样，存储每个文件的创建时间和更新时间。
> 3. 最麻烦的是：侧边栏的文件排序是按时间排序的，这是写死在代码中的，而且是写死在 electron 后端的。如果要修改后端，那么就涉及解包文件什么的，如果只是修改前端，那么有不少代码需要兼容。
> 
> > 总之，由于 Typora 没有官方插件系统，typora_plugin 只能以一种入侵的方式修改程序逻辑。它不是一个真正的系统，比起程序，更像是一个木马。所以很多系统能简单实现的功能，插件需要花费大量精力去魔改，去兼容。

对不起，作者大佬！我关闭 issue 没有一点点其他意思，只是觉得这个 issue 的提法可能和本插件的关联性不大，说的太空泛，可能更多的是 typora 自身该思考的设计问题，有点乱提 issue 了，所以就关了:) 
 不礼貌的开了 issue，又不礼貌的关了，作为一个没接触太多开源知识的人，其实我对 issue 的正确提法和礼貌习惯都不太懂，希望能原谅下我的奇葩操作-.-

**Comment by obgnail** [comment]
@holwell 

你太拘谨了，你的操作没啥问题。提 issue 也没有什么不成文规定，正常聊就行了。

有兴趣可以看看其他关掉的 issue，大伙都是普通对话。也不需要叫大佬什么的，叫作者，开发者就行。

**Comment by holwell** [comment]
好的！谢谢作者😎



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 中午12:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [obgnail/typora_plugin] 相见恨晚！感谢作者！ (Issue #771)




 
@holwell
 
你太拘谨了，你的操作没啥问题。提 issue 也没有什么不成文规定，正常聊就行了。
 
有兴趣可以看看其他关掉的 issue，大伙都是普通对话。也不需要叫大佬什么的，叫作者，开发者就行。

**Comment by obgnail** [comment]
好的，就这样。后续有问题麻烦另开 issue。
