### ISSUE TITLE
思维导图显示怪异请求优化

### ISSUE THREAD

**Issue by zhonglixun** [obgnail/typora_plugin#777]
在标题里添加脚注时生成的思维导图里的文字怪怪的能给它忽略掉或者图形化吗？
![PixPin_2024-10-02_20-43-36](https://github.com/user-attachments/assets/6ed64873-9866-4960-b359-2b404db58857)

**Comment by obgnail** [comment]
@zhonglixun 

已实现。麻烦升级到新版本试用。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
