### ISSUE TITLE
斜杠命令出现提示后,tab没有补全

### ISSUE THREAD

**Issue by 1571312541** [obgnail/typora_plugin#779]
![Snipaste_2024-10-03_23-48-15](https://github.com/user-attachments/assets/9446548e-f328-46c3-a945-4269b044eeb9)

![image](https://github.com/user-attachments/assets/d7ac8e5d-186b-4f9e-9dd4-16d5160a56e2)

输入 /ta 出现提示后, 按tab没起作用, 直接缩进了, 不知道什么问题, 请问有什么解决方法吗

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。

**Comment by 1571312541** [comment]
@obgnail 感谢回复,请问我可以自己修改成tab键吗?如果可以的话需要修改哪里呢

**Comment by obgnail** [comment]
莫得，此功能是依赖于 emoji 功能的，会和 emoji 的行为保持一致。
