### ISSUE TITLE
Typora无法在当前窗口打开文件

### ISSUE THREAD

**Issue by MisakaSakura** [obgnail/typora_plugin#780]
Typora首次启动空白文档情况下"打开"或者“打开文件夹”后不会直接在当前窗口填入打开文章内容，而是新建了一个窗口打开新文件，原来的窗口保持空白。我在设置选项中没看到类似的相关设置，看了朋友电脑上没装插件的版本是打开文件正常在当前窗口打开的，不确定是否是插件的原因，该项目没有discussion，只能占用一下iusse请教了，非常抱歉

**Comment by obgnail** [comment]
@MisakaSakura 

感谢反馈。

确实是插件的 BUG，已修复，麻烦升级到新版本试用。

**Comment by obgnail** [comment]
已修复，此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
