### ISSUE TITLE
在某些主题下代码块内图标显示不清晰基本不可见

### ISSUE THREAD

**Issue by zhonglixun** [obgnail/typora_plugin#783]
我发现在有些主题下，（不是全部，比如默认github主题就没这问题）你额外添加的例如```abc 这些的代码块应该是有更改过图标的一些颜色的，就刚好和我代码块设置的背景色高度相似，就导致在我的主题下就基本看不见了。如图，背景是黑的而光标也是黑的可以说完全看不见光标了，右上角的编辑按钮可以说直接隐身了。我还是截图放大放大才隐约发现是有那么个图案。你能告诉我这些图标具体到哪修改颜色吗？这样我改下也能看清楚。
![PixPin_2024-10-05_23-22-12](https://github.com/user-attachments/assets/8e5bf3ee-3126-4559-858a-db6c0ceef050)

**Comment by obgnail** [comment]
@zhonglixun 

你好，感谢反馈。

## 问题反馈

fence_enhance 在新版本中新增了  BUTTON_COLOR 选项，可以自行决定按钮的颜色。

```toml
[fence_enhance]
# 按钮的颜色
BUTTON_COLOR = "currentColor"
```

光标看不见的情况我这边复现不了，麻烦给一下对应主题，如果是自定义的，麻烦给一下对应的主题文件。

## 附加说明

主题适配问题是硬伤，没用一劳永逸的解决方法，因为主题的作者不会主动兼容此项目，我也无法主动兼容茫茫多的主题。

很多主题作者不遵守 Typora 的主题实现规范，所以有些主题是无法全部兼容的，兼容了主题 A 就会导致主题 B 有问题。

如果您懂 CSS，遇到主题兼容问题，可以考虑在 [user_styles](https://github.com/obgnail/typora_plugin/tree/master/plugin/global/user_styles) 目录下创建 `customize.css` 文件，并在里面写兼容代码。

**Comment by obgnail** [comment]
@zhonglixun 

双引号。

```toml
[fence_enhance]
BUTTON_COLOR = "black"
```

**Comment by obgnail** [comment]
@zhonglixun 

光标问题，是这个主题本身设计不完善导致的。我这边兼容不了。

如下图，能正常显示光标：

![IMG_2024-10-06_14-30-41](https://github.com/user-attachments/assets/60ec5f82-91db-4e0a-ac6c-5b1ad62b28bb)


原因：主题设置了 `.CodeMirror { padding: 1rem; }`，具体行的盒子尺寸很小，你只有点到下图高亮区域才能显示光标，很容易点错。

![IMG_2024-10-06_14-18-25](https://github.com/user-attachments/assets/d8a48525-3c05-4beb-a02a-a32891f46851)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言，或者另开 issue。

**Comment by obgnail** [comment]
@zhonglixun 

你好，感谢反馈。

确实是插件的锅，原因是：当内容为空时我直接 return 了，没有执行后续的渲染任务。现在我仿照 mermaid，加了个 whenEmptyContent 的默认渲染样式。

修复代码在 [dev](https://github.com/obgnail/typora_plugin/commit/f890091855081507ce86537255cacf61f1f997c8)，麻烦试用一下，看看还没有问题。

![IMG_2024-10-06_20-47-01](https://github.com/user-attachments/assets/5771e471-f498-474b-b424-67b478e5d501)

**Comment by obgnail** [comment]
@zhonglixun 

这种情况其实是我主动选择的。

所有的代码块插件都有一个 INTERACTIVE_MODE 选项，此选项为 true 时，只能通过点击那个【铅笔 icon】才能展开代码块的输入区。

设计这个选项的原因是：echarts、chart、calendar 可以运行 Node.js 代码，是可以监听 click 事件的，如果关闭这个选项，那么当 click 事件触发时将自动展开代码块的输入区，起不到交互的效果。

这也是为什么 mermaid 没有这个问题 —— mermaid 不会响应 click 事件。至于 kanban、abc 等不能响应 click 的插件，也只是出于统一目的设置为 false。

也就是说，**如果你确定你的代码块不需要和鼠标进行 click 交互，可以将这些插件的 INTERACTIVE_MODE 全部置为 false，这样就和 mermaid 保持一致了**。

```toml
[kanban]
# 默认处于交互模式（处于交互模式下，鼠标点击图表并不会展开代码块）
INTERACTIVE_MODE = true
```

---

所有的代码块插件都有一个 TEMPLATE 选项，用于编辑示例。

通过 【右键菜单 -> 常用插件 -> 二级插件 -> kanban】就可以自动插入 TEMPLATE 的内容。
