### ISSUE TITLE
为什么折叠章节的快捷键用不了？并且快捷键中心并没有绑定ctrl+click快捷键。

### ISSUE THREAD

**Issue by Polaris-zmy** [obgnail/typora_plugin#789]
![image](https://github.com/user-attachments/assets/ad8a22f8-35a9-4afd-8dae-121e060c14fa)

**Comment by obgnail** [comment]
@Polaris-zmy 

你好，感谢反馈

1. click 属于点击事件，ctrl 属于点击事件的修饰按键。我认为点击事件不应该放在 `快捷键中心`。
2. 【章节折叠】插件默认关闭，需要您手动开启。开启方式：【右键菜单 -> 少用插件 -> 启停插件 -> 勾选 [章节折叠] 插件】。
3. 您可以在开启【章节折叠】插件后可以试试 ctrl 点击正文的标题，就可以折叠章节了。
