### ISSUE TITLE
功能建议：格式规范检测

### ISSUE THREAD

**Issue by holwell** [obgnail/typora_plugin#791]
这个功能对于 markdown 初学者养成良好习惯真是太好了，但是，目前这个插件的修复功能让我感觉很不好用。

* 问题描述
我的习惯是先点定位按钮，然后看下具体哪里不规范，比如说 1000 行的位置，再手动改改，刷新规范检测看看消除没有，不行就点下自动修复按钮，这时候第一个问题就来了，**自动修复它不是在原位置做一些修复操作，而是会修复完自动跳到文档开头**，这种割裂体验很不好，甚至说让人产生不安全感，我还得重新拉回 1000 行的位置看它到底做了什么操作。然后，我又没看出到底是改了什么，比如说可能是多了一个空行或者缩进啥的，我又想 Ctrl+Z 和 Ctrl+Shift+Z 撤回并反撤回对比看看到底改了啥，这时候又会回到文档开头。

* 问题总结
格式规范检测器的自动修复功能会自动定位到文档开头，我猜测这不是一个简单的定位问题，可能的机制类似于将整个文本做了一个处理后，再把结果覆盖整个文本，而不是进行局部修改。

* 功能建议
  1. 只进行局部的修改，最好是不让当前编辑位置发生变动。
  2. 点击修复按钮后，产生局部修改后，不是简单的刷新检测器状态，而是把保留刚才的那条规范提示，使其标灰或者用删除线标记，并将 OP 这列的定位和修复按钮变成撤回按钮。这种标记无需保持多个，只需保持最新的那条即可，当然也可以添加其他消除逻辑，例如离开修复行多远就消除。

虽然不知道这些建议靠不靠谱，仅作参考。

**Comment by obgnail** [comment]
@holwell 

你好，感谢反馈。

已修复，麻烦升级到新版本试用。

1. 你说的很对，确实是由于全量替换导致在 reloadContent 时 scrollTop 被置为 0
2. 我选择了最简单的修复方案：替换前记录 scrollTop，然后在替换后恢复。具体修复代码在 [这里](https://github.com/obgnail/typora_plugin/commit/ab0cdc14732f6e79649a6ae0a9b30cfc9704f64e)
3. 引入删除标记确实能提高用户体验，但这需要引入新的状态。我希望在 hotfix 时减少引入。毕竟状态太多了难管。
4. `删除标记` 是个很好的 feature，我先考虑考虑。

**Comment by obgnail** [comment]
需求完成，此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
