### ISSUE TITLE
只读模式点击图片不要抖动

### ISSUE THREAD

**Issue by zhouxinghong** [obgnail/typora_plugin#796]
您好！请改进只读模式，只读模式点击图片不要抖动。非常🙏！
[1.11.5](https://github.com/obgnail/typora_plugin/releases/tag/1.11.5)
Windows 10

**Comment by obgnail** [comment]
@zhouxinghong 

不要抖动是啥意思？是指不要展开语法块？麻烦仔细说明

**Comment by zhouxinghong** [comment]
对，不要显示图片路径，这样就不会抖动了。。。

**Comment by obgnail** [comment]
@zhouxinghong 

已实现。等待发版。代码见上述  referenced commit。

**Comment by zhouxinghong** [comment]
非常🙏

**Comment by zhouxinghong** [comment]
**只读模式应该具备记忆状态：**

_解释:_
如果我在只读模式下关闭或者退出应用程序，那么下次启动应用程序后依然对某个文件保持只读模式打开。

**Comment by obgnail** [comment]
@zhouxinghong 

已发版，麻烦升级到新版本试用。

---

只读功能的记忆功能应该不做了，抱歉。我的想法如下：

理由一：

Typora  的设计哲学是一个 **增强版的文本编辑器**，并不是一个笔记系统。obsidian、oneNote、notion 都有一个 vault 的概念，每次打开软件都会固定打开同一个 vault，而 Typora 可以在任何地方打开任何单个文件。

vault 的存在决定了软件能全盘掌握所有的文件，可以建立数据库进行管理。而 Typora 不行，Typora 的设计基本都是无状态的，不存在一个专门的文件去记录各个文档的运行信息。否则，由于 Typora 可以随时随地打开任意文档的特点，这个存储文件就会无限膨胀。

比如说，Typora 的专注模式、打字机模式等等都是存储在 Typora 本身的，不会说打开某个文档进入专注模式，打开另一个文档进入打字机模式。

也就是说，【只读模式】是刻意去贴合 Typora 原生设计的，这样能和专注模式等各种模式保持统一，减少用户疑虑。

理由二：

插件应该做到：让用户建立对插件的信任，其中需要做到一点就是：`结果可预测`。**没有人能记得上次退出时，某个文档的所处状态**。也就是说：实现这个功能后，用户打开某个文档，此文档是否可编辑都是不可预测的，会增大用户的心智负担。

我的想法就是：提供一个 READ_ONLY_DEFAULT 选项，打开 Typora 就默认进入只读模式。在混乱中建立秩序。

```toml
[read_only]
# 默认使用只读模式（打开Typora就进入只读模式）
READ_ONLY_DEFAULT = false
```

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by zhouxinghong** [comment]
点击图片还是会抖动，会显示图片路径。。。

**Comment by obgnail** [comment]
@zhouxinghong 

额，不用了，我复现了。这个 BUG 只会在低版本的 Typora 出现，我明天再仔细看看。

**Comment by obgnail** [comment]
@zhouxinghong 

给一下录屏吧，我这边无法复现。

**Comment by zhouxinghong** [comment]
我使用的是 Ty 1.9.5
Windows 10

**Comment by zhouxinghong** [comment]
https://github.com/user-attachments/assets/5bf001fb-ac23-41cf-a074-492c25ad41f7

**Comment by obgnail** [comment]
@zhouxinghong 

好奇怪呀。我这边都复现不出来你的情况。

你是怎么升级插件的？如果升级插件的流程没有问题，盲猜应该是 Typora 本身的配置会影响到插件的运行。

**Comment by zhouxinghong** [comment]
我是直接替换 plugin 目录所有文件

**Comment by obgnail** [comment]
@zhouxinghong 

我这边复现不了，我怀疑是 Typora 本身的配置影响到了插件的运行。

麻烦按如下操作，我来排查排查：

1. 按如下图片，下载 master 的代码
2. 删除本地的 `Typora\resources\plugin` 目录，然后将第一步得到的 plugin 目录粘贴回去（不要直接覆盖，而是先删除原来的，后粘贴）
3. 测试一下是否会复现问题，如果还是复现，【右键菜单 -> 少用插件 -> 帮助 -> 环境信息】，它会生成当前包括配置在内的环境信息，把他发给我（如果里面有敏感信息，请先脱敏）

![IMG_2024-10-16_12-59-59](https://github.com/user-attachments/assets/4bad76ae-5bdb-4f30-9ffd-e7d95ef41e9a)

![IMG_2024-10-16_13-01-08 (1)](https://github.com/user-attachments/assets/271ea0d5-5a01-4933-994e-2e9954d7ac65)

**Comment by zhouxinghong** [comment]
麻烦按如下操作，我来排查排查：

按如下图片，下载 master 的代码
删除本地的 Typora\resources\plugin 目录，然后将第一步得到的 plugin 目录粘贴回去（不要直接覆盖，而是先删除原来的，后粘贴）

安装上述操作后，在只读模式下点击图片不再显示路径且不会抖动了。
问题出在：global 目录下的某个配置文件

**Comment by zhouxinghong** [comment]
你的原始配置：
![image](https://github.com/user-attachments/assets/34d56d37-c054-40ce-bee0-bedbc9933849)

我的自定义配置：
![image](https://github.com/user-attachments/assets/17ccb03c-b542-40b5-a522-a6581b654711)

**Comment by obgnail** [comment]
> 问题出在：global 目录下的某个配置文件。

有可能。我预设的情况是用户使用【右键菜单 -> 常用插件 -> 二级插件 -> 升级插件】进行一键升级。像您这样手动覆盖目录的情况确实有可能在某次升级时出 BUG。

不过问题解决了就行。又不是不能用.jpg

---

吐槽：你的按钮分布好奇怪啊，为什么要设置成中空的布局？ 😂

**Comment by zhouxinghong** [comment]
`吐槽：你的按钮分布好奇怪啊，为什么要设置成中空的布局？ 😂`
不要我特意要设置成中空布局，我仅仅是禁用了一些插件而已。还记得我上次有给你提过，当用户禁用某些插件后，布局应该能够自动排版，但是您当时拒绝了这个自动排版的功能需求。😂

**Comment by zhouxinghong** [comment]
问题出在：`global\settings` 目录下的某个配置文件。

**Comment by obgnail** [comment]
我看你手动添加了一个【混排优化】的按钮，为什么不通过手动修改配置中的 coordinate 选项手动指定按钮的位置？

---

关于自动排版的需求，我当时的想法是：
1. 没有必要 😂，手动指定按钮的坐标就行了，又不要频繁变动。
2. 而且自动排版和 coordinate 选项冲突了：一方面 coordinate 选项手动指定按钮的坐标，另一方面，自动排版又会自动修改坐标。

**Comment by zhouxinghong** [comment]
`我看你手动添加了一个【混排优化】的按钮，为什么不通过手动修改配置中的 coordinate 选项手动指定按钮的位置？`
感觉太麻烦了，就这样将就用了。。。

`而且自动排版和 coordinate 选项冲突了：一方面 coordinate 选项手动指定按钮的坐标，另一方面，自动排版又会自动修改坐标。`
对啊！

**Comment by obgnail** [comment]
这也就 30 秒的事，我帮你改好了。

```toml
[quickButton]
# 添加的按钮：
#   disable:      禁用此按钮
#   coordinate:   按钮坐标。往上为x轴正方向，往左为y轴正方向，从零开始计数
buttons = [
    { disable = false, coordinate = [0, 0], hint = "直达底部", size = "24px", icon = "fa fa-caret-down", callback = "go_top.goBottom" },
    { disable = false, coordinate = [1, 0], hint = "直达顶部", size = "24px", icon = "fa fa-caret-up", callback = "go_top.goTop" },
    { disable = false, coordinate = [0, 1], hint = "图片管理", size = "17px", icon = "fa fa-image", callback = "imageReviewer.callback" },
    { disable = false, coordinate = [1, 1], hint = "高亮搜索", size = "17px", icon = "fa fa-search", callback = "search_multi.call" },
    { disable = false, coordinate = [2, 0], hint = "混排优化", size = "17px", icon = "fa fa-book", callback = "md_padding.call" },
]
```

![IMG_2024-10-16_22-53-42](https://github.com/user-attachments/assets/ca5402d0-0948-49aa-a909-7766d0dc8da7)

**Comment by zhouxinghong** [comment]
非常感谢！兄台。

**Comment by zhouxinghong** [comment]
兄台之前是开发者吧！

**Comment by obgnail** [comment]
不是搞这个方向的，JS、CSS 是现学现卖的

**Comment by zhouxinghong** [comment]
那你也是个天才了。
