### ISSUE TITLE
混排优化时导致:joy:等emoji显示失效

### ISSUE THREAD

**Issue by Yester03** [obgnail/typora_plugin#799]
发现一个小碧油鸡(bug)
- 举个栗子 :chestnut:(: chestnut :)
- :joy:(: joy :)
混排优化之后会变成 : joy :

从而编辑器无法识别, 希望大佬在以后的版本中可以优化一下这个,谢谢啦 ❤️

**Comment by obgnail** [comment]
@Yester03 

[最新版本](https://github.com/obgnail/typora_plugin/releases/tag/1.11.6) 已修复，升级即可。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
referenced commit：https://github.com/obgnail/typora_plugin/commit/606f9cd73b5209d842c1bafa7fe3b8bad3bf7c58

**Comment by Yester03** [comment]
大佬,太感谢你啦,我昨天才的发现这个插件,没想到更新这么快! 👍 👍 👍
