### ISSUE TITLE
[feature request] 图片交叉引用功能

### ISSUE THREAD

**Issue by owenstake** [obgnail/typora_plugin#80]
pandoc 有个图片交叉引用功能，图定义格式:    `![xx](./xx.png){#fig:1}` , `#fig:1` 是图片id

引用图片 : `{@fig:1}`  , 这里根据图片id 引用

会自动渲染为 对应的图片编号。

参考 [tomduck/pandoc-fignos: A pandoc filter for numbering figures and figure references.](https://github.com/tomduck/pandoc-fignos )

**Comment by owenstake** [comment]
这个功能 可能涉及typora底层 markdown解析

**Comment by obgnail** [comment]
@owenstake 

解析这个难度也还行，我担心的是**插件污染了语法**。这样用户就被插件绑架了
（虽然 kanban 插件已经有前科了，不过我是把它作为临时使用的）

还有一点担心的是：添加引用，势必要修改 Typora 的正文页面 #write 的直接子节点，引入新标签。
兼容难度不小，而且我担心会造成软件不稳定，容易崩溃。

我明天再仔细看看。

**Comment by obgnail** [comment]
BTW，1.3.0 版本添加了一键更新插件功能。因为这个项目也没啥人用，能拜托老哥帮忙测一下吗？

**Comment by obgnail** [comment]
typora 内置平替的 link 语法，就不新增新的语法了。

https://support.typora.io/Links/#internal-links

如有其他问题，麻烦另开 issue
