### ISSUE TITLE
typora更新完似乎失效了

### ISSUE THREAD

**Issue by zhonglixun** [obgnail/typora_plugin#800]
今天typora更新是应用内是死活更新不了，无奈去官网下了setup重装。然后打开插件就用不了了。在那个bin里重新运行文件打开typora仍然没效果。不知道是不是我的问题。

**Comment by obgnail** [comment]
@zhonglixun 

你好，感谢反馈。

1. 我现在就在用 Typora 1.9.5，所以应该不会不兼容。
2. 更新完 Typora，需要重新执行 bin/install_windows_amd_x64.exe 文件。麻烦您再次运行一次，看其输出结果是否包含 `plugin install successfully`字样。例如：[install_windows.png](https://github.com/obgnail/typora_plugin/blob/master/assets/install_windows.png)
3. 我猜测您要么是 plugin 目录犯错位置了，要么是安装出了问题。

您可以把执行 install_windows_amd_x64.exe 结果的图片贴上来，我帮您看看。

**Comment by obgnail** [comment]
@zhonglixun 

没有关系，你可以看看上面的 issue，他就是带插件更新的。
