### ISSUE TITLE
已经移除的插件仍然出现在“启停插件”列表中

### ISSUE THREAD

**Issue by PDxtXHd** [obgnail/typora_plugin#807]
在列表中看见几个名字叫undefined的插件，查看更新日志发现都是废弃的插件，是否可以在废弃插件后自动将其移除？
![image](https://github.com/user-attachments/assets/e5ae5a2f-52ea-4cf2-96b6-e73196ca7180)

**Comment by obgnail** [comment]
@PDxtXHd 

你好，感谢反馈。已修复，麻烦升级到新版本试用。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
