### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by hyyed** [obgnail/typora_plugin#811]
反馈：很好用，很喜欢目录树，结构一目了然。不过当我复制网站上的表格、有序无序列表时，会对他们的格式有很大干扰

**Comment by obgnail** [comment]
@hyyed 

你好，感谢反馈。

我这边没有看懂，麻烦能详细说明吗？

**Comment by obgnail** [comment]
@hyyed 

hi，麻烦能详细说明一下情况吗？

**Comment by obgnail** [comment]
长时间未有进展，此 issue 暂时关闭，您后续看到此消息麻烦在下面补充留言，我再重启此 issue。
