### ISSUE TITLE
插件安装一切顺利，但右键不显示“常用插件”菜单

### ISSUE THREAD

**Issue by chentonny** [obgnail/typora_plugin#813]
按照readme步骤安装一切正常，但最后右键不显示“常用插件”菜单。我的typora=1.4.8, window10
![Clip_20241026_030358](https://github.com/user-attachments/assets/a9e2eeb5-62af-4363-8798-6581a9bdbb56)
![Clip_20241026_030545](https://github.com/user-attachments/assets/8132ba9f-3298-4df6-ad5a-3c6ce8ac8e45)
![Clip_20241026_030641](https://github.com/user-attachments/assets/cefd5c5e-b7cc-49ac-a6fe-d42c6a35460d)
请问是哪里操作错误呢

**Comment by obgnail** [comment]
@chentonny 

您好，感谢您细致的说明。

我看您的 Typora 安装位置在 `C:\Program Files\`，那么最大的可能就是权限问题。

## 解决方案

麻烦根据 [这篇文章](https://www.cnblogs.com/loaferwp/p/16693991.html) 给 `C:\Program Files\Typora\resources\plugin` 目录授权。

## 验证

执行完上述操作后，重启 Typora。打开调试工具。应该能看到打印 Typora Plugin 的 logo。

![IMG_2024-10-26_08-21-40](https://github.com/user-attachments/assets/a0f589ca-c192-475d-9640-521eb23b1bcd)

**Comment by chentonny** [comment]
感谢您的解答。按照您的方法，给plugin进行了授权，但问题依然存在，右键菜单还是没有“常用插件”
![Clip_20241026_092732](https://github.com/user-attachments/assets/25ffc696-da3a-42d4-b7c8-bfc8a482e273)
![Clip_20241026_092912](https://github.com/user-attachments/assets/1183a094-f5a6-4b0b-8a58-12f8b6e84374)
查看控制台，提示css和js没有引入。但我不知道要如何修改配置。
![Clip_20241026_093346](https://github.com/user-attachments/assets/65ef5641-98f9-4228-80ee-23e19a16c864)

**Comment by obgnail** [comment]
1. 【查看控制台，提示 css 和 js 没有引入】这两个报错是正常的。
2. 麻烦定位到全部消息，看是否有打印 logo。如果没有打印 logo，说明插件入口文件没有被正常引入。

![IMG_2024-10-26_09-38-22](https://github.com/user-attachments/assets/ab74f2d1-0973-48e4-81be-5a5b7e384d71)

**Comment by chentonny** [comment]
没有打印logo
![Clip_20241026_095259](https://github.com/user-attachments/assets/1f6eeecd-cad9-402f-b885-d5f15b751460)
怎么办？

**Comment by obgnail** [comment]
@chentonny 

现在能确定的是：这是代码外的问题。因为此时代码还没有引入呢。

---

会不会是您安装了多个版本的 Typora，然后打开错了？你试试双击打开 `C:\Program Files\Typora\Typora.exe`

**Comment by obgnail** [comment]
执行完 install_windows_amd_x64.exe，应该会为 `window.html` 生成一个备份的 `window.html.bak` 文件。

你的第一张图是有的，第二张图就没有了，你是手动删除了吗？还是说你升级了 Typora？

如果升级了 Typora，需要重新执行一次 `install_windows_amd_x64.exe`。**谨慎起见，建议你还是再执行一次，不用担心，这个操作是幂等的，可以执行多次**。

**Comment by chentonny** [comment]
您好，感谢您的耐心解答。我昨晚先安装1.4.8，因为没有常用插件菜单，后面就升级到最新版本，还是不行。早上又退回，1.4.8

好的，我重新执行一下install_windows_amd_x64.exe
重新执行后，问题照旧，仍然没有右键菜单-常用插件
![Clip_20241026_100738](https://github.com/user-attachments/assets/d79306fb-a369-46a7-8697-4d1879f4108a)
![Clip_20241026_101324](https://github.com/user-attachments/assets/0c775a24-1ae6-421f-9c05-a983d4219e8d)

**Comment by obgnail** [comment]
@chentonny 

我看您的图片显示的是 `plugin install successfully` 而不是 `plugin has already been installed`。也就是之前的排查都是在未安装的情况下进行的，现在回到起跑线。

麻烦按照如下步骤排查：

1. 首先确保插件已经成功安装：右键文件 `bin/install_windows.ps1`，点击【使用PowerShell运行】，应该会显示 `plugin has already been installed`
2. 检查 plugin 目录是否授权
3. 双击打开 `C:\Program Files\Typora\Typora.exe`，调出调试工具，查看全部消息中是否打印 logo

**Comment by chentonny** [comment]
非常感谢您的耐心解答。
1. powershell显示插件成功安装了（图1）
2. plugin已经授权（图2）
3. 控制台没有输入logo，一堆报错（图3）
![Clip_20241026_104435](https://github.com/user-attachments/assets/a1ec072e-d911-4d31-bf30-4480158eabed)
![Clip_20241026_104513](https://github.com/user-attachments/assets/ebf199ae-d9a3-4c16-8b4b-8316d05b9785)
![Clip_20241026_104701](https://github.com/user-attachments/assets/edc243af-906e-42a2-8f2b-1a93cbe3c299)
谢谢

**Comment by obgnail** [comment]
@chentonny 

感谢反馈。

有报错是好事，说明 **有进展了**，入口文件已经被成功引入了。

---

报错内容是业务代码文件无法成功导入。

麻烦按如下步骤排查：
1. 确保 plugin 目录是完整的：下载 [最新版本压缩包](https://github.com/obgnail/typora_plugin/archive/refs/tags/1.11.11.zip)，替换掉原先的 plugin 目录（注意要先删除 plugin 目录，再粘贴进去。不要直接覆盖）
2. 打开 Typora，如果控制台还是报错，可能还是权限问题导致业务代码文件无法读取，给 `plugin\global\core\utils\common\toml\`  目录授权

**Comment by chentonny** [comment]
非常感谢您的指导。下载最新版本压缩包，并替换原先的plugin就好了，右键出现少用插件和常用插件了。
![Clip_20241026_215118](https://github.com/user-attachments/assets/2e9aa2f2-042f-4e2d-90b0-8e2a1a54cb49)
至此，问题完美解决。感谢您不厌其烦的指导！！！

**Comment by obgnail** [comment]
好的。此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
