### ISSUE TITLE
markmap可否直接导出成图片

### ISSUE THREAD

**Issue by 87zrjojo** [obgnail/typora_plugin#815]
想做个思维导图，试了下写markmap，不知道怎么能导出成图片，能否在markmap可否直接导出成图片代码段加个右键菜单。

**Comment by obgnail** [comment]
思维导图本身就能导出图片呀

![IMG_2024-10-26_12-33-39](https://github.com/user-attachments/assets/39755fef-f393-45f4-bd5b-a815cc0bac4a)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或另开 issue。
