### ISSUE TITLE
导出为HTML后，代码块的复制按钮没有导出

### ISSUE THREAD

**Issue by chentonny** [obgnail/typora_plugin#817]
在TYPORA中，代码块的复制按钮可以正常使用，这非常棒
但导出为HTML后，复制按钮没有跟着导出，如果能一起导出就更好啦
![Clip_20241027_010041](https://github.com/user-attachments/assets/b1f2abc1-63a0-4516-95c4-187651739cef)
![Clip_20241027_010147](https://github.com/user-attachments/assets/797a547c-8aa8-49cc-8c7a-4cf116f21454)

**Comment by obgnail** [comment]
@chentonny 

你好，感谢反馈。

这功能做不了，抱歉。

理由如下：
1. 此功能是通过添加标签和 JS 实现的。**Typora 支持自定义导出，可以随意修改导出的 html**。这两者发生冲突了，插件是不能修改用户自定义内容的。如果添加此功能大概率会影响自定义导出功能。

2. 导出 HTML、image、pdf 其实共用一套代码 —— image 和 pdf 是先将文档转为 html，再转为图片或 pdf 的。图片、pdf 是无法交互的，因此如果添加此功能，就会影响图片和 pdf 的导出功能。

3. Typora 本身就提供了实现这一需求的能力。**实现此功能的最佳实践是：自定义一套导出规则，在导出的文件中引入 JavaScript，动态的为代码添加交互**。如下图，在 `<body />` 中引入 `<script>` 标签

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

![IMG_2024-10-27_01-16-56](https://github.com/user-attachments/assets/90a92add-d9a7-46b6-9605-5e4587c6ffda)
