### ISSUE TITLE
1.10.26及之后版本的资源管理插件无法正常使用

### ISSUE THREAD

**Issue by MrRen-sdhm** [obgnail/typora_plugin#818]
使用的typora版本是0.9.98，默认安装在C:\Program Files\Typora，我是以管理员身份运行的typora。简单创建一个新的md文件，插入一张图片，使用资源管理插件时一直显示：

![image](https://github.com/user-attachments/assets/35302e83-d97f-4fb2-ab60-333a81a8d0a9)

经排查问题是[1.10.26](https://github.com/obgnail/typora_plugin/releases/tag/1.10.26)版本引入的，1.10.25是正常的，1.10.26及之后的版本都无法正常使用，麻烦大佬帮忙看一下 @obgnail

**Comment by obgnail** [comment]
@MrRen-sdhm 

你好，感谢反馈。感谢提供细致说明，帮助我快速排查问题。

确实是 BUG，原因是用了一个高版本的特性，0.9.98 的 Typora 不支持。

现已经修复，麻烦升级到 [新版本](https://github.com/obgnail/typora_plugin/releases/tag/1.11.12) 试用。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
