### ISSUE TITLE
可以把这个typora插件github项目里的代码块折叠功能整合上吗

### ISSUE THREAD

**Issue by 1654061616** [obgnail/typora_plugin#820]
https://github.com/typora-community-plugin/typora-plugin-code-folding

**Comment by obgnail** [comment]
1.10.42 版本就已经实现了。

https://github.com/obgnail/typora_plugin/releases/tag/1.10.42

此 issue 关闭。如有问题，麻烦在下面留言或者另开issue。

**Comment by obgnail** [comment]
@1654061616 

启用方法：右键菜单 -> 少用插件 -> 代码块增强 -> 勾选【启用侧边折叠按钮】

如果找不到此选项，说明插件版本比较低，需要升级到新版本

![IMG_2024-11-01_11-50-09](https://github.com/user-attachments/assets/e19cb7f6-48ee-4913-acd4-1faa654330fe)
