### ISSUE TITLE
【启停插件】插件名称有中划线样式

### ISSUE THREAD

**Issue by zhouxinghong** [obgnail/typora_plugin#826]
插件标题中间加一横线是什么意思？可否消除它。。。

**Comment by obgnail** [comment]
@zhouxinghong 

你好，感谢反馈。

具体是哪里?能截图看看吗

**Comment by zhouxinghong** [comment]
启停插件中，我的git账户，无法上传图片，使用鼠标悬停GitHub账户头像显示⌛️是什么意思？

**Comment by zhouxinghong** [comment]
![2024-10-31_183629](https://github.com/user-attachments/assets/c5860541-f13b-4bba-8184-b2f70b4778b7)

**Comment by zhouxinghong** [comment]
1.9.5
1.1.33

**Comment by obgnail** [comment]
我没有这个问题。大概率是你使用的主题导致的，切换到默认的 github 主题，应该就恢复正常了。

你可以将出现问题的主题发给我，我看能不能兼容

![IMG_2024-10-31_21-49-44](https://github.com/user-attachments/assets/8e1c8add-0e7f-4f4a-8623-e2254cc686c0)

**Comment by zhouxinghong** [comment]
https://theme.typora.io/theme/DogsChoice/

**Comment by obgnail** [comment]
@zhouxinghong 

你魔改过主题文件了吗？或者你使用了 user.css 文件？

我装了 DogsChoice，没问题的。

你先切到默认的 github 主题看看能不能复现。如果切到 github 后发现没问题，基本就能确定是主题不兼容导致的。

**Comment by zhouxinghong** [comment]
是主题的问题。
