### ISSUE TITLE
我要写插件->请读我.md文件->1.2如何使用，第一步添加配置给出的路径错误

### ISSUE THREAD

**Issue by KatanaNeko** [obgnail/typora_plugin#829]
原文为

> 仅需两步：
>
> 1. 在 `./plugin/custom/custom_plugin.user.toml` 添加配置。
> 2. 在 `./plugin/custom/plugins` 目录下，创建和插件同名的 js 文件，在此文件中创建一个 class 继承自 BaseCustomPlugin，并导出为 `plugin`。

实际操作过程中发现第一步路径应该为`./plugin/global/settings/custom_plugin.user.toml`

**Comment by obgnail** [comment]
@KatanaNeko 

你好，感谢反馈。

你是对的。我手滑打错了。
