### ISSUE TITLE
加载报错 “plugin err: TypeError: Cannot read properties of undefined (reading 'library')”

### ISSUE THREAD

**Issue by owenstake** [obgnail/typora_plugin#83]
plugin err: TypeError: Cannot read properties of undefined (reading 'library')

![image](https://github.com/obgnail/typora_plugin/assets/45960823/72930a09-5682-4459-a273-a9733e60783b)

**Comment by obgnail** [comment]
@owenstake 收到，我看看

**Comment by obgnail** [comment]
@owenstake 这个BUG是偶现的还是必现的？

**Comment by owenstake** [comment]
> @owenstake 这个BUG是偶现的还是必现的？如果是必现的，可以讲一下如何复现吗？
@obgnail 没特殊操作，就是安装插件后 就报错，重装过typora
版本如下
![image](https://github.com/obgnail/typora_plugin/assets/45960823/82a6c524-7ef9-4ae5-a77f-c42fc4e8d6d2)

**Comment by obgnail** [comment]
@owenstake 
应该是 Typora 新版本采用了延迟加载导致的，我码的时候偷懒了。

修复代码已经更新到 master，麻烦更新一下代码。应该能解决问题。

如果还是不行，麻烦告知一下。

**Comment by owenstake** [comment]
@obgnail  好了

**Comment by obgnail** [comment]
@owenstake 

好的，感谢反馈。此 issue 我先留两天，如有问题，麻烦在此告知一下。
