### ISSUE TITLE
【markmap】并列的两个 markmap 代码块会导致渲染异常

### ISSUE THREAD

**Issue by zhonglixun** [obgnail/typora_plugin#836]
![PixPin_2024-11-06_23-30-23](https://github.com/user-attachments/assets/a669c393-e993-4533-bd5c-804642c1c949)
![PixPin_2024-11-06_23-29-55](https://github.com/user-attachments/assets/83f35731-d318-4674-ac8f-b534a5cf7413)
具体来说就是连续两个markmap当他们之间没有间隔时，比如右键连续插入两模板，这个时候关闭文件再次打开，下面那个就不能正常显示了，中间有间隔比如回车再次打开上面那个markmap就有问题了。不知道什么情况。

**Comment by obgnail** [comment]
@zhonglixun 

你好，感谢反馈。

我这边无法复现【连续两个 markmap 导致无法正常显示】的 BUG。我猜测有可能是大文件情况下加载触发此 BUG 的。

麻烦说明一下 Typora 版本，麻烦给一下你那边能复现的 md 文件

![IMG_2024-11-07_00-09-48 (1)](https://github.com/user-attachments/assets/fcced803-2890-42c6-97ed-16bc15cb91a2)

**Comment by obgnail** [comment]
@zhonglixun 

参数没法实时刷新问题已经修复，等待发版，详情见上面 reference commit

**Comment by obgnail** [comment]
@zhonglixun 

新版本中我做了一些修复，在我这边已经不再复现了，麻烦升级试用一下。

此 issue 关闭，如有问题，麻烦在下面留言。
