### ISSUE TITLE
没有在安装路径下找到window.html

### ISSUE THREAD

**Issue by BelovedChunh** [obgnail/typora_plugin#837]
按照提示，但是并未找到windows.html
![EcoPaste_240](https://github.com/user-attachments/assets/3e4ab08a-3a02-40e8-941e-278c65d1dc57)

**Comment by obgnail** [comment]
@BelovedChunh 

你好，感谢反馈。根据截图，应该是你放错位置了。

- 如果你的 Typora 是正式版，window.html 出现在：`E:\系统软件\笔记\Typora\resources\`
- 如果你的 Typora 是免费版，window.html 出现在：`E:\系统软件\笔记\Typora\resources\app\`

**Comment by obgnail** [comment]
具体看一下 [说明文档](https://github.com/obgnail/typora_plugin?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95%E4%B8%80%E8%87%AA%E5%8A%A8) 中截图的文件路径
