### ISSUE TITLE
Swiper JS Support

### ISSUE THREAD

**Issue by CatOnly** [obgnail/typora_plugin#841]
Please support it:
https://swiperjs.com/

**Comment by obgnail** [comment]
@CatOnly 

Thanks for your feedback! 

How would you like to introduce SwiperJS into typora_plugin? As a code block language, or something else?

**Comment by CatOnly** [comment]
Let's make it simply. Just leave it as pure html and make it as a button to create a template code to quick insert it.

**Comment by obgnail** [comment]
Due to Typora's security policy, any script tags within the text will be filtered out, making it impossible to implement this feature using pure HTML.

**Comment by obgnail** [comment]
I'm closing this issue for now due to inactivity. If you have any new ideas or updates, feel free to drop a comment below.
