### ISSUE TITLE
插件以成功安装，但未能使用

### ISSUE THREAD

**Issue by BelovedChunh** [obgnail/typora_plugin#845]
按照提示，安装了插件，但是并未正常使用，以下是截图
![EcoPaste_718](https://github.com/user-attachments/assets/207b7548-091c-4d24-be1e-e876d71a1aa4)

![EcoPaste_719](https://github.com/user-attachments/assets/f1eb6a3c-2e0f-4a60-b725-fb5632653f09)

**Comment by BelovedChunh** [comment]
谢谢您的解答，已成功解决😘

**Comment by obgnail** [comment]
好的。

此 issue 关闭，如有问题，麻烦另开 issue。
