### ISSUE TITLE
添加drawio的支持

### ISSUE THREAD

**Issue by lizelin2243** [obgnail/typora_plugin#850]
能添加一个对 drawio的支持么，直接打开弹窗画图，保存后直接以图片形式添加到文档中

**Comment by obgnail** [comment]
@lizelin2243 

你好，感谢反馈。

新版本已经支持 drawIO，麻烦升级到新版本试用。

![drawIO](https://github.com/user-attachments/assets/17f3e7c2-f4e6-4575-90a7-926bc081aae9)

**Comment by RyanLei-icer** [comment]
> @lizelin2243
> 
> 你好，感谢反馈。
> 
> 新版本已经支持 drawIO，麻烦升级到新版本试用。
> 
> ![drawIO](https://private-user-images.githubusercontent.com/48992887/390730201-17f3e7c2-f4e6-4575-90a7-926bc081aae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MDcxODYsIm5iZiI6MTczNjQwNjg4NiwicGF0aCI6Ii80ODk5Mjg4Ny8zOTA3MzAyMDEtMTdmM2U3YzItZjRlNi00NTc1LTkwYTctOTI2YmMwODFhYWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDA3MTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYmYwYTdhNDBhMTFiNTRkZjc0ZjdjMTFkYmE4MTU3MzA5NDUzNmNhMjU0NmZiMjlmN2UzOWRkYjFhYzQwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kmM2AuzXlfzw23oHxoNz6Deew7lEAEE_d_JuQ58ppLk)

你好，对于这种插件能否调整显示的尺寸，适应宽度之类的

**Comment by obgnail** [comment]
@RyanLei-icer 

您好，感谢反馈。

我发现您分别在两个 issue 里提供发了两个 comment。

为了方便管理，麻烦新开一个 issue，详细描述两个 comment 的情况，最好能提供一个可复现的文件。

**Comment by obgnail** [comment]
@RyanLei-icer 

所有的代码块都是可以通过添加 `// {height: "800px", width: ""}` 注释调整高度和宽度。

不过 drowIO 代码块的高宽度是自适应的，应该没有必要调整。

**Comment by RyanLei-icer** [comment]
> @RyanLei-icer
> 
> 所有的代码块都是可以通过添加 `// {height: "800px", width: ""}` 注释调整高度和宽度。
> 
> 不过 drowIO 代码块的高宽度是自适应的，应该没有必要调整。

关于drawio的问题可参考[#915](https://github.com/obgnail/typora_plugin/issues/915)
