### ISSUE TITLE
记住章节折叠状态不起作用

### ISSUE THREAD

**Issue by wudixiaoguaishouaa** [obgnail/typora_plugin#852]
章节折叠记忆功能已经启用，但是关闭软件再打开后还是章节全部打开的状态，不起作用

**Comment by obgnail** [comment]
@wudixiaoguaishouaa 

你好，感谢反馈。

设计如此。目前章节的折叠信息仅存储在内存中，没有持久化到硬盘里，重启软件会全部丢失。

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue
