### ISSUE TITLE
支持代码块里面自动识别语言/设置默认语言

### ISSUE THREAD

**Issue by zhainanshidai** [obgnail/typora_plugin#855]
支持代码块里面自动识别语言/设置默认语言，现在每次需要重新设置，有些费时间

**Comment by obgnail** [comment]
@zhainanshidai 

你好，感谢反馈。

1. 【自动识别语言】：这个需求之前也有人提过。目前没有什么好的解决方法。原因：存在太多语言的语法相似甚至相同，比如 `alert(123)` 可以是 typescript，javascript，coffeescript。我尝试过 Github 一些库，其识别能力很差。这里有一个最简单例子：强大如 vscode，在识别代码语言的能力上也是一塌糊涂。代码编辑器尚且如此，Typora 这种简单的文本编辑确实很难做到。
2. 【设置默认语言】：新版本的 Typora 已经原生支持此功能。

此 issue 关闭，如有问题，麻烦在下面留言。
