### ISSUE TITLE
想问一下你们插件升级是否平滑呢？有没有什么备份机制呀

### ISSUE THREAD

**Issue by zhainanshidai** [obgnail/typora_plugin#857]
想问一下你们插件升级是否平滑呢？有没有什么备份机制呀

**Comment by obgnail** [comment]
@zhainanshidai 

你好，感谢反馈。

1. 支持一键升级：【右键菜单 -> 少用插件 -> 升级插件】
2. 一键备份：目前唯一需要备份就是配置文件。可以通过【右键菜单 -> 帮助 -> 备份配置】实现。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
