### ISSUE TITLE
代码块添加对k8s的风格支持

### ISSUE THREAD

**Issue by zhainanshidai** [obgnail/typora_plugin#858]

**Comment by obgnail** [comment]
@zhainanshidai 

k8s 风格是什么意思？

- 如果指的是配置文件，那就是普通的 yaml 语言
- 如果指的是 kubectl，那就是普通的 bash

**Comment by obgnail** [comment]
@zhainanshidai 

你好，麻烦详细说明一下此问题。

**Comment by obgnail** [comment]
此暂时 issue 关闭。如果您看到这条消息，麻烦在下面回复，我再重启此 issue。

**Comment by zhainanshidai** [comment]
kubectl、kubelet、kubeadm 不会变色

**Comment by obgnail** [comment]
您指的应该是 bash 的语法高亮能力吧。这受 codeMirror 的 bash 语法高亮能力所限。要想实现此功能就必须 让 grammar parser 专门针对 k8s 做适配。暂时无法处理。
