### ISSUE TITLE
【中英文混排优化】希望加粗语法前后不加空格

### ISSUE THREAD

**Issue by woaiwulima** [obgnail/typora_plugin#868]
上次提问见[issue#865](https://github.com/obgnail/typora_plugin/issues/865)

我希望可以正常使用加粗标记，即 abc`**`ABC`**`abc 中ABC加粗但前后不会产生空格
而 `IGNORE_PATTERNS =["<br\\s*?/>", "<u>.+?</u>"]` 并不能使粗体前后不产生空格，于是我使用
`IGNORE_PATTERNS = [
  "<u>.+?</u>",
  ".\*\*."
  ]`
但此时若出现下划线样式的文本则会影响之后的加粗正则表达式 `".\*\*."` 无法成功识别

测试样本为 `测试**测试**测试
<u>测试</u>
测试**测试**测试`

开启 md_padding 功能前
![image](https://github.com/user-attachments/assets/e49bc143-13f0-4b15-89fc-8a45f7618587)      
md_padding 后  ![image](https://github.com/user-attachments/assets/95495559-3c66-49d4-96dc-56d98ced26da)

**Comment by obgnail** [comment]
@woaiwulima 

感谢反馈和详细的说明。

你的正则写得有问题。`.\*\*.` 并不能匹配加粗标记。

试试如下：

`IGNORE_PATTERNS = ["<br\\s*?/>", "<u>.+?</u>", "\\*\\*.+?\\*\\*"]`

**Comment by woaiwulima** [comment]
不使用`"\\*\\*.+?\\*\\*"`的原因是加粗符号不像下划线，前后有差别`<u>`和`</u>`，我担心发生导致跨段的匹配。即使按您这种改法，还是不能解决测试样本`测试**测试**测试 <u>测试</u> 测试**测试**测试`的问题

**Comment by obgnail** [comment]
@woaiwulima 

1. 【发生跨段落的匹配】：JavaScript 中点号不匹配换行符，因此没有问题。
2. 【后一个加粗周围出现空格】：是 BUG，已修复。目前代码在 dev 分支中，等待发版。

**Comment by obgnail** [comment]
@woaiwulima 

新版本已经修复，麻烦升级到新版本。此 issue 关闭，如有问题，麻烦在下面留言。
