### ISSUE TITLE
插件是否支持在macos上使用？

### ISSUE THREAD

**Issue by hal0n0sec** [obgnail/typora_plugin#869]
按照作者的方式，没有找到相对应的插件存放路径，请问在macos上如果想要使用该如何安装插件？

**Comment by obgnail** [comment]
你好，感谢反馈。

暂时不支持 Mac。抱歉。

一来是我没有 Mac，没有环境进行测试。二来是 Typora for Mac 好像不基于 Electron，需要专门改造。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
