### ISSUE TITLE
[feature request] 导出html文件，内嵌图片数据，参考data uri scheme

### ISSUE THREAD

**Issue by owenstake** [obgnail/typora_plugin#88]
期望导出html文件内嵌图片数据，而不是本地文件链接。即<img>src不再是文件路径，而是base64编码过的图片数据。

原本格式：`<img src="xxx">`
期望格式： `<img src="data:image/png;base64,xxxxxxxxxxxxxxxxxxxxx"> `

参考 [data URI scheme - Wikipedia](https://en.wikipedia.org/wiki/Data_URI_scheme )

**Comment by owenstake** [comment]
基于你global/util.js的decorator方法，我试过 decoMixin.afterExport，来获取 exportToHTML的输出，但是js异步处理的方式 很难同步最终result。
```js
        global._pluginUtils.decorate(
            () => (File && File.editor && File.editor.export && File.editor.export.exportToHTML),
            File.editor.export,
            "exportToHTML",
            decoMixin.beforeExport,
            decoMixin.afterExport,
            true
        );

```

搞不定。js的异步编程 太难受了。

**Comment by obgnail** [comment]
@owenstake 

js 的异步确实恶心。
1.1.15 版本已经添加 export_enhance 插件。麻烦测试反馈一下。

**Comment by owenstake** [comment]
> @owenstake
> 
> js 的异步确实恶心。 1.1.15 版本已经添加 export_enhance 插件。麻烦测试反馈一下。

没发现问题。高产似母猪。让我看看观摩代码
