### ISSUE TITLE
不支持mac电脑

### ISSUE THREAD

**Issue by lignpeng** [obgnail/typora_plugin#883]
我使用的是mac m2Pro，typora1.6.7。
在mac电脑中，typora没有window.html，而是index.html，引入：
```
<script src="file:///Users/dde_1/Library/Application%20Support/abnerworks.Typora/plugins/index.js"
			 defer="defer" type="module"></script>

--------

我又下载了插件：**typora-community-plugin**，同样的方式导入，可以正常使用。证明这个方式是行得通的。

------

```

1. 重启typora提示找不到global。
2. 尝试修改index.js文件，把global注释掉，直接指定core的路径，依然报错，提示：例如没有reqnode之类的报错。尝试修改了很多都依然不行。

能否优化支持一下mac呀。

**Comment by obgnail** [comment]
你好，感谢反馈。

我也想支持 Mac。然而我并没有 Mac，没有环境，做不了测试。

猜测 typora for Mac 不同于 Windows，不是基于 electron 的，而是使用某种技术嵌入了 webview，甚至后端不是使用 node，因此兼容 Mac 需要大量改造甚至重写。

也就是说，您上面做的简单尝试大概率是跑不通的。

**Comment by obgnail** [comment]
目前来说，在几个版本内应该做不到支持 Mac。抱歉。

此 issue 关闭，如果您有问题 麻烦在下面留言或者另开 issue。
