### ISSUE TITLE
Typora 无法打开文件夹中的子文件，也无法显示文件中的文件的数量

### ISSUE THREAD

**Issue by luopeis** [obgnail/typora_plugin#885]
您好！
我的typora版本为1.9.5 
当我打开一个文件夹的时候，能够显示该文件夹中的子文件，但是无法打开子文件，（子文件中是有文件的）在我的typora中文件左侧没有折叠小三角，并且无法显示该文件中的文件数量。
第一张图是我的typora ，第二张图是其他人正常的typora。
请问这是什么原因，谢谢您！
![1](https://github.com/user-attachments/assets/5ba8262b-706a-413a-98b0-6537eeb9a325)
![image](https://github.com/user-attachments/assets/3481f5a0-5a36-4a29-8f88-d2ab8aba4f2a)

**Comment by obgnail** [comment]
@luopeis 

这是 Typora 的特性。只有目录下包含以下后缀的文件时，左侧才有折叠小三角，才能显示文件的数量（也就是说，它其实计算的是后缀为以下情况的文件的数量）

```
"", "md", "markdown", "mdown", "mmd", "text", "txt", "rmarkdown", "mkd", "mdwn", "mdtxt", "rmd", "mdtext", "apib"
```

举例：

![IMG_2024-12-06_22-37-46](https://github.com/user-attachments/assets/48775695-4c03-4247-8c96-8dafcae1c151)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
