### ISSUE TITLE
建议增加分屏功能

### ISSUE THREAD

**Issue by Sepsdf** [obgnail/typora_plugin#895]
建议增加分屏功能

有时候需要对照修改代码或者文档，来回切换页面或者上下滚动页面不太方便。

分屏好像已经成了所有编辑器的标配了

**Comment by obgnail** [comment]
@Sepsdf 

你好，感谢反馈。

此需求做不了。抱歉。

实现此需求需要使用 electron.BrowserWindow 派生出一个窗口，然而 Typora 只有一个 BrowserWindow 用于显示主页面。typora_plugin 本质是通过逆向工程整出来的，只能在现有的框架内折腾。

也就是说，**目前 Typora 缺少实现此需求的能力**，要想实现这个功能，要么等待 Typora 官方支持，要么 Typora 官方提供插件系统。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
