### ISSUE TITLE
能不能支持针对mermaid出的图片导出高清矢量图出来

### ISSUE THREAD

**Issue by Runnerxr** [obgnail/typora_plugin#898]
能不能支持针对mermaid出的图片导出高清矢量图出来？

**Comment by obgnail** [comment]
@Runnerxr 

你好，感谢反馈。

Typora 自身就支持将 mermaid 导出为 SVG。

此 issue 关闭。如有问题，麻烦在下面留言。

![IMG_2024-12-24_12-22-38 (1)](https://github.com/user-attachments/assets/10a70d91-8b97-4daa-901c-cae5c1901042)

**Comment by Runnerxr** [comment]
谢谢，我刚刚通过网站(https://www.mermaidchart.com/app/projects/f3181587-07d3-465b-b86a-9756ec1f56d9/diagrams/dd44540a-001c-4ba5-8c69-73c0cc50cc3e/version/v0.1/whiteboard)试了一下可以，不过在typora中没有找到入口(我的typora的版本是：1.0.3)

**Comment by obgnail** [comment]
@Runnerxr 

查了一下，在 Typora 1.3.6 支持此特性：[Typora-What's-New-1.3](https://support.typora.io/What's-New-1.3/#save-resources-as)

您将 Typora 升级到新版本即可。

**Comment by Runnerxr** [comment]
谢谢~~
