### ISSUE TITLE
[😀] 希望增加个本地图片文件路径自动URLEncoder功能

### ISSUE THREAD

**Issue by xpko** [obgnail/typora_plugin#901]
首先感谢作者大大开发出这么好用得工具，大大得扩展了typora了功能，非常好用！

typora的自动识别文件转本地资源很好用，但我在长久使用中发现一个小问题，若是图片名本身有空格或其它特殊字符，粘贴后，typora虽然自己能识别，但上传到其它平台，比如github，就不支持了，但通过URLEncoder编码后就正常了

原始：  
![image](https://github.com/user-attachments/assets/d9dc7a8f-0edf-4ef0-a4b2-1bf6975339ce)  

编码后：  
![image](https://github.com/user-attachments/assets/69ee1420-466c-417a-b7ea-ebda6258e4a3)

**Comment by obgnail** [comment]
你好，感谢反馈。

Typora 自带此功能。详情请参考：[preferred-image-syntax](https://support.typora.io/Images/#preferred-image-syntax)

![IMG_2024-12-27_11-28-40 (1)](https://github.com/user-attachments/assets/e78152d2-f208-412d-946e-42f690a7e6ff)

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue

**Comment by xpko** [comment]
噢噢，原来已经有了，谢谢作者大大！
