### ISSUE TITLE
可以参考增加下这个Typora项目下的一些功能吗

### ISSUE THREAD

**Issue by 1654061616** [obgnail/typora_plugin#907]
https://gitee.com/madmaxchow/VLOOK
例如这个
![image](https://github.com/user-attachments/assets/54f3ff6c-f907-41b4-aec4-7c3d51b2d19b)

**Comment by obgnail** [comment]
@1654061616 

您好，感谢反馈。

1. 如果有某些具体的需求可以在 issue 提及，我会进行评估。我看了一下 VLOOK，功能不少，我不清楚你具体对哪些特性感兴趣。
2. 如果您观察地比较仔细，您会发现当前所有插件都是符合 [CommonMark](https://commonmark.org/) 规范的。我追求通用和零成本迁移，不希望插件绑架用户，所以我一般不会做需要自定义语法的插件。
3. 因为【表格题注】不是 CommonMark 规范的一部分，需要通过自定义语法实现，所以我暂时不打算实现此需求，抱歉。
4. typora_plugin 是支持自定义插件的，如果有想法，您也可以按照 [教程](https://github.com/obgnail/typora_plugin/blob/master/plugin/custom/%E8%AF%B7%E8%AF%BB%E6%88%91.md) 自行实现插件。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
