### ISSUE TITLE
一键生成mindmap思维导图有问题 无法生成

### ISSUE THREAD

**Issue by styw1234** [obgnail/typora_plugin#91]
[test.md](https://github.com/obgnail/typora_plugin/files/12369930/test.md)
[test.pdf](https://github.com/obgnail/typora_plugin/files/12369931/test.pdf)
在进行一键生成mindmap思维导图有问题，无法生成

**Comment by obgnail** [comment]
如果我理解没错的话，你说的情况是：
对于 test.md 文件，生成 graph 形式的思维导图没有问题，生成 mindmap 形式的思维导图有问题。是吗？

这是由于 mermaid 本身有个很搞笑的 BUG，他把 `mindmap` 作为关键字了，不允许出现在标题中。
我看能不能兼容这个 BUG。

**Comment by styw1234** [comment]
> 如果我理解没错的话，你说的情况是： 对于 test.md 文件，生成 graph 形式的思维导图没有问题，生成 mindmap 形式的思维导图有问题。是吗？
> 
> 这是由于 mermaid 本身有个很搞笑的 BUG，他把 `mindmap` 作为关键字了，不允许出现在标题中。 我看能不能兼容这个 BUG。

对的，就是这个 `mindmap` 作为关键字问题，去掉这个关键词，就可以正常显示mindmap图片。

另外mindmap有不同风格的样式可以选择么

**Comment by obgnail** [comment]
1. 已修复，已合到 master 中。麻烦更新一下。
2. 当然可以，mermaid 本身就支持样式美化。这也是为什么有 mermaid_replace 这个插件。此插件可以更换和美化 mermaid 组件。不过我还没来得及开发美化功能。

**Comment by obgnail** [comment]
mermaid_replace 这个插件默认是关闭的，请暂时不要去开启，它还是处于起步阶段。
