### ISSUE TITLE
[feature request] 右键编辑图片

### ISSUE THREAD

**Issue by owenstake** [obgnail/typora_plugin#95]
markdown我是通过drawio来画流程图，然后保存为图片，名为xxx.drawio.svg。但是编辑该流程图的时候很麻烦，要先打开图片所在文件夹，然后右键打开方式，选择drawio编辑。
[期望行为] ： 在typora右键增加一个 "drawio编辑图片" 的选项

**Comment by obgnail** [comment]
@owenstake 你好。

1. 这个需求太小众了，我电脑也没有 drawio，就不写入项目里了。
2. 今天整了个 custom 插件，支持用户自定义插件。你可以使用它自己整一个。这个需求能在 10 行代码内实现。
3. 我给一下具体的实现思路：
   1. selector 使用 `#write .md-image`，表示当鼠标在图片右键时，触发插件菜单
   2. 回调函数有两个参数: anchorNode 和 utils。anchorNode 参数表示鼠标右键时的标签，可以使用 `anchorNode .querySelector('img").src` 获取到图片的路径。使用 `utils.getPlugin("commander").silentExec(your-cmd， "cmd/bash")` 即可调用 cmd 命令打开 drawio 了。

可能的代码：
```toml
[[custom.OPTIONS]]
name = "在drawio打开"
selector = "#write .md-image"
callback = "openInDrawio"
```

```js
class callback {
    openInDrawio = (anchorNode, utils) => {
        const imagePath = decodeURI(anchorNode.querySelector("img").src.replace("file:///", "").split("?")[0]);
        const cmd = `ls -la ${imagePath}`;
        utils.getPlugin("commander").silentExec(cmd, "gitbash");
    }
}
```

如果有任何问题，请在此 issue 里 at 我

**Comment by owenstake** [comment]
@obgnail 基于您的提示，已经实现了这个功能。还有个问题，想要右键新建一个drawio文件，路径在xxx.assets/目录下，如何跳出一个对话框来输入新建drawio文件名?

**Comment by obgnail** [comment]
> 

@owenstake 

答：更新 1.2.6 版本。此版本添加更多的生命周期函数。可以支持你的需求实现。

不过此版本修改了 custom 的接口定义，需要你把 openInDrawio 花三分钟重新写一遍。具体看 readme。

> 注：我把 settings.toml 中的 OPTIONS 改成了 PLUGINS。有什么问题可以继续问。

**Comment by obgnail** [comment]
我把用户自定义的插件单独成一个文件了，这样以后更新 typora-plugin 也不需要每次都重新复制一遍过去。

**Comment by obgnail** [comment]
或者你也可以等我更新，后续我会把 custom 的配置也单独成一个文件 toml 文件。

不过因为还在考虑接口该怎么定义比较好，你现在整好了，后续可能又要去适配新的接口定义。

**Comment by obgnail** [comment]
@owenstake 

你好，custom 插件的接口定义已经完成了，后续也不会改变了。

本次提供了 modal 函数，快速的无痛的创建模态框。这样，你的需求也只需二三十行代码就可以完成了。

这次我提供了一个 extracRangeToNewFile 作为例子，还有一个 modalExample 可以参考。

更新此次版本后，之前的 openInDrawio 需要花三分钟重新写一遍。
有问题希望在这 at 我。

**Comment by obgnail** [comment]
@owenstake 

本次的接口定义修改，比起之前，简单来说就是：
0. 将之前的静态函数 openInDrawio 变成了 openInDrawio 文件里class 的 callback 函数。把每个插件都独立成一个文件，方便隔离，也方便升级的时候不被替换掉。
1. 将之前的 selector 属性，变成了 selector 方法，更加灵活
2. 添加了 utils，modal，info，config 等属性和 其他生命周期函数，从面向过程变成了面向对象。

**Comment by obgnail** [comment]
@owenstake 

您好，如果您对于 custom 怎么写有些疑惑。可以看一下 openInTotalCommander 和 templater 两个插件。和您的需求几乎是一致的。
- openInTotalCommander 是直接调用命令行。
- templater 是弹出交互窗口
