### ISSUE TITLE
[feature request] 显示图片名称

### ISSUE THREAD

**Issue by owenstake** [obgnail/typora_plugin#96]
[预期]：图片下方显示图片名称。图片名称来自 `![图片名](xx.png)`

**Comment by obgnail** [comment]
@owenstake 

你好。

考虑了一下，决定不支持此需求了。不好意思。

原因：
1. 我没有此类需求，在我的情况，图片名称都是一些随机的字符组合，显示意义不大
2. 最重要的是：我暂时想不到该如何低成本的实现此需求。

我搜了一下，网上确实有这个需求的实现方案，但是都是需要修改 frame.js 的。
如果您有需要，可以参考：
https://github.com/muggledy/typora-dyzj-theme/blob/master/demo.md
