### ISSUE TITLE
新功能需求：多标签切换时记忆切换前的文档位置

### ISSUE THREAD

**Issue by chuzhixing** [obgnail/typora_plugin#98]
作者好，首先非常感谢作者创建出这个非常好用、便利的插件。

软件运行环境描述： OS为：windows 10。typora版本为：0.9.96。插件版本是：typora_plugin-1.0.4。

下面，是我在使用过程中的一些新的需求。
1 能不能在多标签切换时记忆切换前的文档位置？
举个例子。目前打开的文档，有a.md  b.md。在阅读a.md时，阅读到了第100行的位置。通过多标签切换，阅读b.md，阅读完b.md，再重新切换到a.md时，a.md文档能仍然停留在第100行的位置。同理，由a.md再切回到b.md，标签页打开 b.md时，希望能够停留在b.md刚才阅读的位置。

2 在左侧大纲标题下，能不能整一个类似于visual studio code的复制路径的功能。这里是想描述复制标题的路径。比如在三级标题下，右键，有一个复制标题路径的菜单功能，点击它会把该标题及父标题都复制到剪贴板上。复制到的文本类似于"xxx.md/xxx一级标题/xxx二级标题/xxx三级标题"

3 在文档中，增加跳到指定行的功能。这个功能在typora中没有找到。

已经star过了，再次感谢作者~~

**Comment by obgnail** [comment]
@chuzhixing 你好

1. 你的版本太老了，这个功能很久之前就支持了，甚至还支持持久化了 :)
2. 今天（1.2.1 版本）整了个 custom 插件，支持用户自定义插件，正好用这个需求作为例子，所以已经支持了。（不过不是在大纲里右键，而是在正文的标题处右键，具体可以看 readme 的 custom 插件使用说明部分）
3. Typora 本身没有显示所在行数，提供这个功能有点奇怪。如果你愿意的话可以试用一下【类别大纲】插件，它可以快速定位到某个表格、代码块、图片、标题。用于定位我想应该是够用了。

> 注：1.2.0 版本重构了，可能有些许 BUG，如果你发现了，麻烦提醒我。

**Comment by chuzhixing** [comment]
@obgnail 谢谢作者的回复。
已经更新插件版本为1.2.1。本issue提到的需求1与需求2，都已经测试了一下，功能都是正常的。没有发现bug。

关于"复制标题路径"功能，探索了一下，才知道怎么用。下面是使用的总结，在下面列出来，给其它有类似需要的小伙伴一个参考。

复制标题路径，使用说明：
1 光标移动到正文标题末尾，点击鼠标右键盘，会弹出的下拉列表中。
2 在一级下拉列表中，选择"启动插件"，会弹出二级下拉列表。
3 在二级下拉列表中，选择"自定义插件"，会弹出三级下拉列表。
4 在三级下拉列表中，选择"复制标题路径"，则当前光标所在的标题路径，会被复制到剪贴板。
5 在目标文档区域，粘贴（鼠标右键，粘贴；或者 Ctrl + V），即可把标题路径复制到相应文档区域。

**Comment by obgnail** [comment]
@chuzhixing 

售后来了 😂

半夜打码，都傻掉了，不知道为什么被我删掉了一行配置。

麻烦修改一下 settings.toml。在 28行添加一行配置。

```toml
LOOP_DETECT_INTERVAL = 35
```

或者直接拉取最新代码替换。

![Snipaste_2023-08-20_14-52-32](https://github.com/obgnail/typora_plugin/assets/48992887/f0013ca2-2972-4606-ad6b-a0bb7992ca9b)

**Comment by chuzhixing** [comment]
@obgnail 
刚想反馈：在windows 10的机器上，插件升级到1.2.1，发现多标签功能失效了，而且点开启用插件的二级下拉列表中的内容，跟windows7电脑相比不是很全。

重新拉代码，升级到1.2.3，这个想反馈的问题，就消失了。谢谢作者，辛苦啦~~
